/** Cursor-agent Myanmar for N3–N1 (part 02) */
module.exports = {
  "to console": "နှစ်သိမ့်သည်",
  moving: "ရွေ့လျားခြင်း",
  "to be caught in": "မိသွားသည်",
  "to overturn": "မှောက်သည်",
  "to upset": "မငြိမ်မသက်ဖြစ်သည်",
  "changing residence": "ပြောင်းရွှေ့နေထိုင်ခြင်း",
  "to undertake": "တာဝန်ယူသည်",
  "to take up": "စတင်လုပ်သည်",
  "a draw (in competition)": "သရေ (ပြိုင်ပွဲ)",
  "tie game": "သရေဂိမ်း",
  "to send back": "ပြန်ပို့သည်",
  gravity: "ဆွဲငင်အား",
  "to be prolonged": "ရှည်ကြာသည်",
  extension: "တိုးချဲ့ခြင်း",
  smoky: "မီးခိုးထူသော",
  "coming and going": "သွားလာခြင်း",
  receiving: "လက်ခံခြင်း",
  favor: "ကျေးဇူး",
  benefit: "အကျိုး",
  alighting: "ဆင်းခြင်း",
  drainage: "ရေဆင်း",
  gutter: "ရေမြောင်း",
  meanness: "ယုတ်မာမှု",
  assumption: "ယူဆချက်",
  scald: "ပူလောင်ဒဏ်ရာ",
  cargo: "ကုန်တင်",
  process: "လုပ်ငန်းစဉ်",
  mosquito: "ခြင်",
  release: "လွှတ်ပေးခြင်း",
  detour: "လမ်းလွှဲ",
  lump: "အလုံး",
  clod: "မြေစိုင်",
  suspicious: "သံသယဖြစ်ဖွယ်",
  regrettable: "နှမြောဖွယ်",
  grey: "မီးခိုးရောင်",
  gray: "မီးခိုးရောင်",
  lid: "အဖုံး",
  expansion: "ချဲ့ထွင်ခြင်း",
  husk: "အခွံ",
  "grade in school": "ကျောင်းအတန်း",
  relatively: "အတော်အတန်",
  rebate: "ပြန်အမ်းငွေ",
  "division (math)": "စားခြင်း (သင်္ချာ)",
  kettle: "ရေနွေးအိုး",
  battery: "ဘက်ထရီ",
  "tin can": "သံဘူး",
  notion: "အယူအဆ",
  conception: "အသိဉာဏ်အယူ",
  "to include": "ပါဝင်သည်",
  instrument: "တူရိယာ",
  "to be careful": "သတိထားသည်",
  "market trend": "စျေးကွက်လမ်းကြောင်း",
  ritual: "ထုံးတမ်း",
  "on the contrary": "ဆန့်ကျင်ဘက်အားဖြင့်",
  inversion: "ပြောင်းပြန်ခြင်း",
  "to scoop": "ဝက်သည်",
  grant: "ထောက်ပံ့ငွေ",
  curve: "ကွေးမျဉ်း",
  nearness: "နီးကပ်မှု",
  "to draw near": "နီးကပ်လာသည်",
  zone: "ဇုန်",
  "to be furnished with": "တပ်ဆင်ထားသည်",
  vision: "အမြင်",
  "even number": "စုံဂဏန်း",
  waste: "အလဟဿ",
  "to affect": "သက်ရောက်သည်",
  longitude: "လောင်ဂျီတွဒ်",
  crack: "အက်ကြောင်း",
  gap: "ကွာဟချက်",
  beam: "ရောင်ခြည်/တန်း",
  masterpiece: "လက်ရာမြောက်",
  "to serve": "ဝန်ဆောင်သည်",
  honorable: "လေးစားဖွယ်",
  index: "အညွှန်း",
  "inaccessible place": "မရောက်နိုင်သောနေရာ",
  originally: "မူလက",
  "raw materials": "ကုန်ကြမ်းများ",
  stubborn: "ခေါင်းမာသော",
  "to harden": "မာကျောသည်",
  amusement: "ဖျော်ဖြေမှု",
  "treating (someone)": "ဧည့်ခံခြင်း",
  "not writing or contacting for a while": "အဆက်အသွယ်ပြတ်ခြင်း",
  dismissal: "ထုတ်ပယ်ခြင်း",
  "to mingle with": "ရောနှောသည်",
  "meritorious deed": "ကောင်းမှုကုသိုလ်",
  extensive: "ကျယ်ပြန့်သော",
  "to spread": "ပျံ့နှံ့သည်",
  mineral: "သတ္တုဓာတ်",
  item: "ပစ္စည်း/အချက်",
  "high class": "အဆင့်မြင့်",
  "high grade": "အရည်အသွေးမြင့်",
  "to carve": "ထွင်းသည်",
  "to engrave": "ထွင်းထုသည်",
  mixture: "ရောနှောမှု",
  "deep blue": "ပြာနက်ရောင်",
  calamity: "ဘေးအန္တရာယ်",
  "national holiday": "အမျိုးသားနေ့",
  cancellation: "ပယ်ဖျက်ခြင်း",
  "to print": "ပုံနှိပ်သည်",
  "to rub": "ပွတ်သည်",
  "to file": "ဖိုင်တင်သည်",
  "rust (colour)": "သံချေးရောင်",
  "new moon": "လဆန်း",
  "crescent moon": "လခြမ်း",
  "to distribute": "ဖြန့်ဝေသည်",
  "to pierce": "ထိုးဖောက်သည်",
  "sliced raw fish": "ငါးစိမ်းလှီး",
  crossroads: "လမ်းဆုံ",
  "from beginning to end": "အစမှအဆုံး",
  descendants: "သားစဉ်မြေးဆက်",
  offspring: "သားသမီးများ",
  casual: "ပေါ့ပေါ့ပါးပါး",
  assignment: "တာဝန်ပေးချက်",
  "full name": "အမည်အပြည့်",
  "paper money": "စက္ကူငွေ",
  violet: "ခရမ်းရောင်",
  dentifrice: "သွားတိုက်ဆေး",
  toothpaste: "သွားတိုက်ဆေး",
  magnet: "သံလိုက်",
  "self-defense": "ကိုယ်ခံပညာ",
  autonomy: "ကိုယ်ပိုင်အုပ်ချုပ်ရေး",
  "unrequited love": "တစ်ဘက်သတ်ချစ်ခြင်း",
  "to be damp": "စိုစွတ်သည်",
  moisture: "အစိုဓာတ်",
  dampness: "စိုထိုင်းမှု",
  "to bear fruit": "အသီးသီးသည်",
  procedure: "လုပ်ထုံးလုပ်နည်း",
  bar: "ဘား/တန်း",
  director: "ဒါရိုက်တာ",
  "to be contracted": "ကျုံ့သည်",
  "income and expenditure": "ဝင်ငွေနှင့်အသုံးစရိတ်",
  "exit and entrance": "ဝင်ပေါက်ထွက်ပေါက်",
  naivete: "နုံအမှု",
  "in turn": "အလှည့်ကျ",
  dictation: "စာချရေး",
  "Japanese chess": "ရှောဂိ (ဂျပန်စစ်တုရင်)",
  passive: "ခံနေရသော",
  exhaustion: "ပင်ပန်းမှု",
  omission: "ချန်လှပ်ခြင်း",
  "high and low": "အမြင့်အနိမ့်",
  "up and down": "အတက်အဆင်း",
  "unloading and loading": "တင်ချခြင်း",
  "praising and blaming": "ချီးမွမ်းခြင်းနှင့်ကဲ့ရဲ့ခြင်း",
  sultry: "ပူအိုက်စွတ်သော",
  artisan: "လက်မှုပညာသည်",
  penetration: "ထိုးဖောက်မှု",
  invasion: "ကျူးကျော်မှု",
  aggression: "ရန်လိုမှု",
  lips: "နှုတ်ခမ်း",
  "sleep-wear": "အိပ်ရာဝတ်",
  nightclothes: "ညဝတ်စုံ",
  nightgown: "ညအိပ်ရာဝတ်",
  "to deepen": "နက်ရှိုင်းသည်",
  "to heighten": "မြင့်တက်သည်",
  "to intensify": "ပြင်းထန်လာသည်",
  "late at night": "ညဥ့်နက်",
  "to imitate": "တုပသည်",
  legend: "ဒဏ္ဍာရီ",
  diagnosis: "ရောဂါရှာဖွေခြင်း",
  "tissue paper": "တစ်ရှူးစက္ကူ",
  extreme: "အစွန်းရောက်",
  graph: "ဂရပ်",
  cooking: "ချက်ပြုတ်ခြင်း",
  drunkard: "အရက်သမား",
  china: "ကြွေထည်",
  "to be in order": "စနစ်တကျရှိသည်",
  consolidation: "စုစည်းခိုင်မာခြင်း",
  lively: "စည်ကားသော",
  "to calm down": "ငြိမ်သက်သည်",
  "to subside": "ကျဆင်းသက်သည်",
  "month before last": "ယခင်လမတိုင်မီလ",
  despotism: "အာဏာရှင်စနစ်",
  "folding fan": "အခေါက်ပန်ကာ",
  cork: "ဖော့",
  "to pass through": "ဖြတ်သန်းသည်",
  "to fry": "ကြော်သည်",
  "to aim at": "ပစ်မှတ်ထားသည်",
  coarse: "ကြမ်းတမ်းသော",
  amateur: "အပျော်တမ်း",
  godown: "ဂိုဒေါင်",
  "to scratch": "ခြစ်သည်",
  "to dispute": "ငြင်းခုံသည်",
  funeral: "ဈာပန",
  carriage: "ရထားတွဲ/လှည်း",
  abominable: "မုန်းစရာ",
  "poor-looking": "ညံ့ဖျင်းပုံ",
  measurement: "တိုင်းတာခြင်း",
  candour: "ဖြောင့်မတ်မှု",
  openheartedness: "ပွင့်လင်းရိုးသားမှု",
  "to contradict": "ဆန့်ကျင်ပြောသည်",
  "business meeting": "စီးပွားရေးအစည်းအဝေး",
  "previous arrangement": "ကြိုတင်စီစဉ်မှု",
  capacity: "စွမ်းရည်/ထုထည်",
  "waiting room": "စောင့်ဆိုင်းခန်း",
  "to take away": "ယူသွားသည်",
  "to relieve": "သက်သာစေသည်",
  "(not) very": "အလွန်မဟုတ်",
  carpenter: "လက်သမား",
  exaggerated: "ချဲ့ကားသော",
  title: "ခေါင်းစဉ်",
  waterfall: "ရေတံခွန်",
  "to carry on shoulder": "ပခုံးထမ်းသည်",
  site: "နေရာ/ဆိုက်",
  bamboo: "ဝါး",
  "middle finger": "လက်ခလယ်",
  filling: "ဖြည့်ခြင်း",
  indifference: "လျစ်လျူရှုမှု",
  tuning: "ချိန်ညှိခြင်း",
  seasoning: "ဟင်းခတ်အမွှေး",
  diameter: "အချင်း",
  addition: "ပေါင်းခြင်း",
  appendix: "နောက်ဆက်တွဲ",
  "to happen to pass by": "ဖြတ်သွားမိသည်",
  "to waste": "ဖြုန်းတီးသည်",
  "to shave": "ရိတ်သည်",
  precise: "တိကျသော",
  "Emperor of Japan": "ဂျပန်ဘုရင်",
  "to collect": "စုဆောင်းသည်",
  "to roll": "လှိမ့်သည်",
  score: "ရမှတ်",
  runs: "အမှတ်/ပြေးမှတ်",
  contagion: "ကူးစက်ရောဂါ",
  "(1) to serve": "အမှုထမ်းသည် (၁)",
  "to fill a post": "ရာထူးယူသည်",
  "to serve under": "လက်အောက်တွင်အမှုထမ်းသည်",
  "to work (for)": "အလုပ်လုပ်သည်",
  "appointed day": "သတ်မှတ်နေ့",
  uniformity: "ညီညွတ်မှု",
  scattering: "ပြန့်ကျဲခြင်း",
  dispersion: "ကွဲပြားပျံ့ခြင်း",
  scratch: "ခြစ်ရာ",
  "to let loose": "လွှတ်လိုက်သည်",
  "to set free": "လွတ်မြောက်စေသည်",
  "to let escape": "လွတ်ထွက်စေသည်",
  equality: "တန်းတူညီမျှမှု",
  "pupil (of eye)": "မျက်ဆံ",
  "to plunge into": "ခုန်ဝင်သည်",
  "to smell": "နံ့ရှူသည်",
  rainbow: "သက်တံ",
  sunset: "နေဝင်ချိန်",
  agenda: "အစီအစဉ်ဇယား",
  "sunny place": "နေသာသောနေရာ",
  fragment: "အပိုင်းအစ",
  splinter: "စုတ်ပြတ်",
  "to be burdened with": "ဝန်ထုပ်ခံရသည်",
  "to carry on back or shoulder": "ကျော/ပခုံးထမ်းသည်",
  sales: "ရောင်းအား",
  proceeds: "ရောင်းရငွေ",
  "to warp": "ကွေးညွတ်သည်",
  cowardice: "ကြောက်ရွံ့မှု",
  essential: "မရှိမဖြစ်",
  copying: "ကူးယူခြင်း",
  "bad luck": "ကံဆိုးခြင်း",
  irregularity: "မမှန်ကန်မှု",
  "to keep company with": "အပေါင်းအသင်းလုပ်သည်",
  "to get on with": "လိုက်ဖက်သည်",
  diffusion: "ပျံ့နှံ့မှု",
  spread: "ပြန့်ပွားမှု",
  "to become loose": "လျော့ရဲသည်",
  "to rise to surface": "မျက်နှာပြင်ပေါ်တက်သည်",
  "to come to mind": "စိတ်ထဲပေါ်လာသည်",
  attached: "တွဲဖက်ထားသော",
  belonging: "ပိုင်ဆိုင်မှု",
  parts: "အစိတ်အပိုင်းများ",
  stationery: "စာရေးကိရိယာ",
  "(going) side by side": "ဘေးချင်းကပ်သွားခြင်း",
  abreast: "တန်းတူအတူ",
  "at the same time": "တစ်ချိန်တည်း",
  closure: "ပိတ်သိမ်းခြင်း",
  "to be one-sided": "တစ်ဘက်သတ်ဖြစ်သည်",
  "to incline": "ညွတ်သည်",
  "to be partial": "ဘက်လိုက်သည်",
  compilation: "စုစည်းပြုစုခြင်း",
  "health preservation": "ကျန်းမာရေးထိန်းသိမ်းမှု",
  packing: "ထုပ်ပိုးခြင်း",
  "to destroy": "ဖျက်ဆီးသည်",
  "Buddhist priest": "ဗုဒ္ဓဘာသာရဟန်း",
  "son (of others)": "သား (သူများ၏)",
  "to struggle": "ရုန်းကန်သည်",
  "to swell (out)": "ဖောင်းကားသည်",
  essentially: "အနှစ်သာရအားဖြင့်",
  chafe: "ပွတ်တိုက်နာ",
  "special product": "ဒေသထွက်ကုန်",
  "to appoint": "ခန့်အပ်သည်",
  pelt: "သားရေ",
  "walking around at night": "ညလှည့်လည်ခြင်း",
  "night train": "ညရထား",
  "night travel": "ညခရီး",
  unpreparedness: "ပြင်ဆင်မှုမရှိခြင်း",
  toll: "လမ်းကြေး",
  "to take charge of": "တာဝန်ယူသည်",
  infancy: "နို့စို့အရွယ်",
  vessel: "သင်္ဘော/အိုး",
  "to melt": "အရည်ပျော်သည်",
  "to dissolve": "ပျော်ဝင်သည်",
  covetousness: "လိုချင်မှု",
  greed: "လိုဘ",
  "to be popular": "လူကြိုက်များသည်",
  hostel: "အဆောင်",
  dormitory: "အိပ်ဆောင်",
  reassuring: "စိတ်ချရသော",
  exception: "ခြွင်းချက်",
  "cold storage": "အအေးခန်းသိုလှောင်ခြင်း",
  refrigeration: "ရေခဲသေတ္တာအအေးခံခြင်း",
  "to murmur": "ညည်းညူသည်",
  cunning: "လှည့်စားတတ်သော",
  elegant: "ကျက်သရေရှိသော",
  errand: "အမှု/စေခိုင်းချက်",
  compliment: "ချီးမွမ်းစကား",
  guidebook: "လမ်းညွှန်စာအုပ်",
  cheat: "လိမ်လည်သူ",
  crane: "ငှက်ကုလားအုတ်/ကရိန်း",
  tenacious: "ဇွဲရှိသော",
  straw: "ကောက်ရိုး",
  baggy: "လျော့တွဲသော",
  vat: "စည်",
  "to be exhausted": "ပင်ပန်းနွမ်းနယ်သည်",
  hunger: "ဆာလောင်မှု",
  virus: "ဗိုင်းရပ်စ်",
  hint: "အရိပ်အမြွက်",
  boom: "တိုးတက်မှု/အသံ",
  buzzer: "ဘဇာ",
  abundant: "ပေါများသော",
  bolt: "တံကျင်",
  message: "စာတို",
  uniform: "ယူနီဖောင်း",
  liver: "အသည်း",
  range: "အကွာအဝေး/အကွက်",
  courtesy: "ယဉ်ကျေးမှု",
  deterioration: "ယိုယွင်းမှု",
  degeneration: "ပျက်စီးကျဆင်းမှု",
  reed: "ကျူပင်",
  oppression: "ဖိနှိပ်မှု",
  "that one": "အဲဒါ",
  Italy: "အီတလီ",
  jailer: "ထောင်မှူး",
  rank: "အဆင့်",
  customs: "ဓလေ့/အကောက်ခွန်",
  protest: "ကန့်ကွက်ခြင်း",
  "different opinion": "မတူသောအမြင်",
  immigration: "လူဝင်မှုကြီးကြပ်ရေး",
  "to fade": "မှေးမှိန်သည်",
  breeding: "မွေးမြူခြင်း",
  "a while": "ခဏတာ",
  "front page": "မျက်နှာဖုံးစာမျက်နှာ",
  monotony: "တသမတ်တည်းငြီးငွေ့ဖွယ်",
  "marine transportation": "ရေကြောင်းပို့ဆောင်ရေး",
  transport: "ပို့ဆောင်ရေး",
  smoothness: "ချောမွေ့မှု",
  stretching: "ဆန့်ခြင်း",
  "feeling awkward": "အဆင်မပြေခံစားရခြင်း",
  disgrace: "အရှက်ရခြင်း",
  livestock: "မွေးမြူရေးတိရစ္ဆာန်",
  baggage: "ခရီးဆောင်အိတ်",
  magnificent: "ခမ်းနားသော",
  gorgeous: "လှပထည်ဝါသော",
  pomp: "အလှအပခမ်းနားမှု",
  crowded: "စည်ကားသော",
  elegance: "ကျက်သရေ",
  intervention: "ဝင်ရောက်စွက်ဖက်မှု",
  innovation: "ဆန်းသစ်တီထွင်မှု",
  channel: "လမ်းကြောင်း/ချန်နယ်",
  "puckery juice": "ဖန်ရည်/ခါးရည်",
  pioneer: "ရှေ့ဆောင်",
  imported: "တင်သွင်းသော",
  cliff: "ချောက်ကမ်းပါး",
  highway: "အဝေးပြေးလမ်း",
  kernel: "အူတိုင်",
  guarantee: "အာမခံ",
  credit: "ယုံကြည်မှု/ခရက်ဒစ်",
  allotment: "ခွဲဝေပေးခြင်း",
  heaven: "ကောင်းကင်/နတ်ဘုံ",
  emperor: "ဧကရာဇ်",
  issue: "ပြဿနာ/ထုတ်ဝေမှု",
  forgiveness: "ခွင့်လွှတ်ခြင်း",
  forbearance: "သည်းခံခြင်း",
  bureaucrat: "ဗျူရိုကရက်",
  generosity: "ရက်ရောမှု",
  cheer: "အားပေးခြင်း",
  "quasi-": "တစ်ဝက်တစ်ပျက်-",
  brevity: "တိုတောင်းမှု",
  "to slacken": "လျော့ရဲသည်",
  "to loosen": "ဖြေလျှော့သည်",
  "point of view": "ရှုထောင့်",
  eyeball: "မျက်လုံး",
  counterfeit: "အတု",
  forgery: "အတုပြုလုပ်ခြင်း",
  sham: "အယောင်ဆောင်",
  "fixed date": "သတ်မှတ်ရက်",
  fickle: "စိတ်မတည်ငြိမ်သော",
  cheerful: "ရွှင်လန်းသော",
  "to write down": "ရေးမှတ်သည်",
  priceless: "တန်ဖိုးမဖြတ်နိုင်သော",
  sacrifice: "စွန့်လွှတ်ခြင်း",
  poverty: "ဆင်းရဲမှု",
  "old friend": "မိတ်ဟောင်း",
  residence: "နေအိမ်",
  coexistence: "အတူတကွနေထိုင်ခြင်း",
  shout: "အော်ဟစ်ခြင်း",
  scream: "အော်မြည်ခြင်း",
  enforcement: "အတည်ပြုကျင့်သုံးခြင်း",
  mediation: "ကြားဝင်ညှိနှိုင်းခြင်း",
  wonder: "အံ့ဩဖွယ်",
  tune: "သံစဉ်/တေး",
  paradise: "ပရဒိသု",
  "to suppress": "နှိမ်နင်းသည်",
  "to torment": "ညှဉ်းပန်းသည်",
  "to harass": "နှောင့်ယှက်သည်",
  hollow: "အခေါင်းပေါက်",
  ruler: "အုပ်ချုပ်သူ/ပေတံ",
  crowd: "လူစု",
  warship: "စစ်သင်္ဘော",
  lean: "ပိန်သော/မှီသည်",
  incline: "ညွတ်သည်",
  formation: "ဖွဲ့စည်းခြင်း",
  particulars: "အသေးစိတ်အချက်များ",
  "personal history": "ကိုယ်ရေးရာဇဝင်",
  scorn: "မထီမဲ့မြင်ပြုခြင်း",
  rash: "ပေါ့ဆသော",
  "to join together": "ပေါင်းစည်းသည်",
  "to combine": "ပေါင်းစပ်သည်",
  crystal: "ပုံဆောင်ခဲ",
  "to miss": "လွဲသည်/လွမ်းသည်",
  mission: "မစ်ရှင်/တာဝန်",
  "to complete": "ပြီးစီးသည်",
  atom: "အက်တမ်",
  local: "ဒေသခံ",
  antiquity: "ရှေးဟောင်းခေတ်",
  "ancient times": "ရှေးခေတ်",
  "to challenge": "စိန်ခေါ်သည်",
  inherent: "မွေးရာပါ",
  orphan: "မိဘမဲ့",
  loneliness: "အထီးကျန်မှု",
  "counter for houses": "အိမ်ရေတွက်",
  thigh: "ပေါင်",
  hire: "ငှားရမ်းခြင်း",
  retreat: "ဆုတ်ခွာခြင်း",
  words: "စကားလုံးများ",
  "to avoid": "ရှောင်ကြဉ်သည်",
  favourable: "အဆင်ပြေသော",
  farming: "စိုက်ပျိုးရေး",
  "to invade": "ကျူးကျော်သည်",
  disagreement: "သဘောကွဲလွဲမှု",
  administration: "အုပ်ချုပ်ရေး",
  precipitation: "မိုးရွာသွန်းမှု",
  surrender: "လက်နက်ချခြင်း",
  confession: "ဝန်ခံခြင်း",
  acknowledgement: "အသိအမှတ်ပြုခြင်း",
  "to hinder": "ဟန့်တားသည်",
  reconstruction: "ပြန်လည်တည်ဆောက်ခြင်း",
  resuscitation: "ပြန်လည်အသက်သွင်းခြင်း",
  "question mark": "မေးခွန်းအမှတ်",
  friendly: "ရင်းနှီးသော",
  tactics: "နည်းဗျူဟာ",
  "counter for books": "စာအုပ်ရေတွက်",
  crude: "ကြမ်းတမ်းသော",
  adoration: "ကိုးကွယ်ချစ်ခင်မှု",
  cruelty: "ရက်စက်မှု",
  employee: "ဝန်ထမ်း",
  thorn: "ဆူး",
  ambition: "ရည်မှန်းချက်",
  directions: "လမ်းညွှန်ချက်များ",
  "carrying out": "ဆောင်ရွက်ခြင်း",
  "personal use": "ကိုယ်ပိုင်အသုံး",
  rearing: "မွေးမြူခြင်း",
  spin: "လှည့်ခြင်း",
  axis: "ဝင်ရိုး",
  attachment: "တွဲဖက်မှု",
  turf: "မြက်ခင်း",
  "to be emaciated": "ပိန်ချုံးသည်",
  preparations: "ပြင်ဆင်မှုများ",
  variety: "မျိုးစုံ",
  earnings: "ဝင်ငွေ",
  circuit: "ပတ်လမ်း",
  flexible: "ပြောင်းလွယ်သော",
  beast: "သားရဲ",
  brute: "ရက်စက်သူ",
  "to respect": "လေးစားသည်",
  "to honor": "ဂုဏ်ပြုသည်",
  "to esteem": "တန်ဖိုးထားသည်",
  "to prize": "ချီးမြှောက်သည်",
  convenience: "အဆင်ပြေမှု",
  congratulations: "ဂုဏ်ပြုစကား",
  display: "ပြသခြင်း",
  wink: "မျက်တောင်ခတ်ခြင်း",
  "to conform to": "လိုက်နာသည်",
  escutcheon: "တံဆိပ်/အမှတ်အသား",
  pretext: "အကြောင်းပြချက်",
  masses: "ပြည်သူလူထု",
  particle: "အမှုန်",
  exclusion: "ချန်လှပ်ခြင်း",
  "to be impatient": "စိတ်မရှည်ဖြစ်သည်",
  crash: "ပျက်ကျခြင်း",
  landing: "ဆင်းသက်ခြင်း",
  passion: "စိတ်အားထက်သန်မှု",
  "tender-hearted": "နှလုံးနူးညံ့သော",
  weave: "ရက်လုပ်ခြင်း",
  textile: "အထည်အလိပ်",
  fabric: "အထည်",
  deliberation: "ဆွေးနွေးစဉ်းစားခြင်း",
  "to suggest": "အကြံပြုသည်",
  pearl: "ပုလဲ",
  mystery: "လျှို့ဝှက်ဆန်းကြယ်မှု",
  "to befriend": "မိတ်ဖွဲ့သည်",
  prisoner: "အကျဉ်းသား",
  conjecture: "ခန့်မှန်းချက်",
  vapor: "အငွေ့",
  chick: "ကြက်ကလေး",
  doll: "အရုပ်",
  innocence: "အပြစ်ကင်းမှု",
  raw: "စိမ်းသော/မချက်ရသေး",
  "to blush": "မျက်နှာနီသည်",
  "to die out": "မျိုးတုန်သည်",
  hermit: "ရသေ့",
  wizard: "မှော်ဆရာ",
  specialization: "အထူးပြုခြင်း",
  "to dye": "ဆိုးသည်",
  "to stir up": "နှိုးဆော်သည်",
  previously: "ယခင်က",
  goodness: "ကောင်းမြတ်မှု",
  virtue: "ဂုဏ်သိက္ခာ",
  carelessness: "ပေါ့ဆမှု",
  lawsuit: "တရားစွဲမှု",
  investigation: "စုံစမ်းစစ်ဆေးခြင်း",
  synthesis: "ပေါင်းစပ်ခြင်း",
  integration: "ပေါင်းစည်းခြင်း",
  ornament: "အလှဆင်ပစ္စည်း",
  riot: "အဓိကရုဏ်း",
  malice: "မကောင်းမှုစိတ်",
  negative: "အနုတ်လက္ခဏာ",
  "to bear": "ခံသည်",
  "to endure": "သည်းခံသည်",
  languid: "အားအင်ကုန်သော",
  podium: "စင်မြင့်",
  rostrum: "မိန့်ခွန်းစင်",
  topography: "မြေမျက်နှာသွင်ပြင်",
  "counter for suits of clothing": "အဝတ်စုံရေတွက်",
  "arriving at ..": "ရောက်ရှိခြင်း",
  coloring: "အရောင်တင်ခြင်း",
  relay: "ဆက်လက်ပို့ခြင်း",
  pivot: "ဗဟိုချက်",
  neutralize: "ချေဖျက်သည်",
  "go-between": "ကြားခံသူ",
  fidelity: "သစ္စာရှိမှု",
  faithfulness: "ယုံကြည်သစ္စာ",
  lottery: "ထီ",
  signs: "လက္ခဏာများ",
  omen: "နိမိတ်",
  symptoms: "ရောဂါလက္ခဏာများ",
  levy: "အခွန်ကောက်ခြင်း",
  challenge: "စိန်ခေါ်မှု",
  guts: "သတ္တိ",
  butterfly: "လိပ်ပြာ",
  "super-": "စူပါ-",
  "ultra-": "အလွန်-",
  reticence: "စကားနည်းမှု",
  exile: "ပြည်နှင်ဒဏ်",
  consistency: "ညီညွတ်မှု",
  fishing: "ငါးဖမ်းခြင်း",
  consolation: "နှစ်သိမ့်မှု",
  divert: "လွှဲပြောင်း/ဖျော်ဖြေ",
  walking: "လမ်းလျှောက်ခြင်း",
  throw: "ပစ်ခြင်း",
  command: "အမိန့်",
  pottery: "မြေအိုး",
  comrade: "ရဲဘော်",
  longing: "တောင့်တမှု",
  aspiration: "ရည်မှန်းချက်",
  specialty: "အထူးကျွမ်းကျင်မှု",
  bathe: "ရေချိုးသည်",
  urine: "ဆီး",
  burning: "လောင်ကျွမ်းခြင်း",
  fuel: "လောင်စာ",
  "to speak ill of": "ကဲ့ရဲ့ပြောသည်",
  defeat: "ရှုံးနိမ့်ခြင်း",
  background: "နောက်ခံ",
  indemnity: "လျော်ကြေး",
  "to tear off": "ဆုတ်ခွာသည်",
  "to strip off": "ချွတ်သည်",
  bomb: "ဗုံး",
  excavation: "တူးဖော်ခြင်း",
  curse: "ကျိန်စာ",
  retribution: "အပြစ်ဒဏ်ပြန်ပေးခြင်း",
  judgment: "စီရင်ချက်",
  arch: "ခုံးတံတား",
  oppose: "ဆန့်ကျင်သည်",
  edition: "ထုတ်ဝေမှု",
  thriving: "စည်ပင်သော",
  flourishing: "ရှင်သန်ထွန်းကားသော",
  manure: "မြေဩဇာ",
  fertilizer: "မြေသြဇာ",
  "to be endowed with": "ပါရှိသည်",
  eyebrow: "မျက်ခုံး",
  slump: "ကျဆင်းမှု",
  ordinance: "အမိန့်/ဥပဒေ",
  decay: "ပုပ်သိုးခြင်း",
  contempt: "မထီမဲ့မြင်",
  "to overthrow": "ဖြုတ်ချသည်",
  veil: "မျက်နှာဖုံး",
  disguise: "အယောင်ဆောင်ခြင်း",
  sharing: "မျှဝေခြင်း",
  division: "ခွဲခြမ်းခြင်း",
  closing: "ပိတ်ခြင်း",
  advantage: "အကျိုးကျေးဇူး",
  charge: "တာဝန်/စရိတ်",
  custody: "ထိန်းသိမ်းစောင့်ရှောက်မှု",
  shelter: "ခိုလှုံရာ",
  replenishment: "ဖြည့်တင်းခြင်း",
  recompense: "လျော်ကြေးပေးခြင်း",
  "leave as is": "အတိုင်းထားခြင်း",
  honey: "ပျားရည်",
  revelation: "ဖော်ထုတ်ခြင်း",
  spinning: "ချည်ငင်ခြင်း",
  flax: "ပိုက်ဆံလျှော်",
  membrane: "အမြှေးပါး",
  "son-in-law": "သားမက်",
  network: "ကွန်ရက်",
  scale: "စကေး/အတိုင်းအတာ",
  arrow: "မြှား",
  suppression: "နှိမ်နင်းခြင်း",
  "interest (bank)": "အတိုး (ဘဏ်)",
  sink: "နစ်သည်/ရေဆင်း",
  arrears: "ကြွေးကျန်",
  favorable: "အဆင်ပြေသော",
  dew: "နှင်းရည်",
  instant: "ခဏတာ",
  bacteria: "ဘက်တီးရီးယား",
  confront: "ရင်ဆိုင်သည်",
  braid: "ကျစ်သည်",
  plait: "ကျစ်ရက်",
  hit: "ထိသည်",
  attach: "တွဲသည်",
  "refer to": "ရည်ညွှန်းသည်",
  append: "ပေါင်းထည့်သည်",
  excel: "ကျွမ်းကျင်သည်",
  surpass: "သာလွန်သည်",
  admonish: "သတိပေးသည်",
  commandment: "ပညတ်တော်",
  "drive away": "မောင်းထုတ်သည်",
  pursue: "လိုက်လံသည်",
  transit: "ဖြတ်သန်းခြင်း",
  ford: "ရေတိမ်ကူး",
  harbor: "ဆိပ်ကမ်း",
  invite: "ဖိတ်ခေါ်သည်",
  stab: "ထိုးသည်",
  scatter: "ဖြန့်ကြဲသည်",
  exclude: "ချန်လှပ်သည်",
  remove: "ဖယ်ရှားသည်",
  abolish: "ဖျက်သိမ်းသည်",
  censure: "ကဲ့ရဲ့သည်",
  perish: "ပျက်စီးသည်",
  approve: "အတည်ပြုသည်",
  extract: "ထုတ်ယူသည်",
  pilfer: "ခိုးယူသည်",
  "take pleasure in": "ပျော်မွေ့သည်",
  discontinue: "ရပ်ဆိုင်းသည်",
  serve: "ဝန်ဆောင်သည်",
  search: "ရှာဖွေသည်",
  evade: "ရှောင်သည်",
  reach: "ရောက်ရှိသည်",
  attain: "ရရှိသည်",
  rob: "လုယူသည်",
  manipulate: "ကိုင်တွယ်သည်",
  wash: "ဆေးကြောသည်",
  district: "ခရိုင်",
  "govt office": "အစိုးရရုံး",
  "entrust to": "အပ်နှံသည်",
  state: "ပြည်နယ်/ဖော်ပြသည်",
  "semi-": "တစ်ဝက်-",
  conform: "လိုက်နာသည်",
  "counter for articles": "ပစ္စည်းရေတွက်",
  cure: "ကုသသည်",
  pretend: "ဟန်ဆောင်သည်",
  "long time": "ကြာရှည်စွာ",
  oppress: "ဖိနှိပ်သည်",
  "police station": "ရဲစခန်း",
  waves: "လှိုင်းများ",
  billows: "လှိုင်းကြီးများ",
  clot: "သွေးခဲ",
  boulder: "ကျောက်တုံးကြီး",
  mix: "ရောသည်",
  confuse: "ရှုပ်ထွေးသည်",
  flourish: "ထွန်းကားသည်",
  blaze: "လောင်ကျွမ်းသည်",
  bury: "မြှုပ်သည်",
  celebrate: "ဆင်နွှဲသည်",
  congratulate: "ဂုဏ်ပြုသည်",
  "throw away": "ပစ်ပယ်သည်",
  resign: "နုတ်ထွက်သည်",
  congeal: "ခဲသည်",
  "yearn for": "တောင့်တသည်",
  miss: "လွမ်းသည်",
  recede: "ဆုတ်သည်",
  melt: "အရည်ပျော်သည်",
  dissolve: "ပျော်ဝင်သည်",
  tears: "မျက်ရည်များ",
  yell: "အော်သည်",
  freeze: "အေးခဲသည်",
  wet: "စိုသော",
  cultivate: "စိုက်ပျိုးသည်",
  "adhere to": "ကပ်ငြိသည်",
  poetry: "ကဗျာ",
  seethe: "ပွက်ပွက်ဆူသည်",
  ferment: "အချဉ်ဖောက်သည်",
  "dry up": "ခြောက်သွေ့သည်",
  pinch: "ညှစ်သည်",
  clan: "မျိုးနွယ်စု",
  swamp: "စမ်းချောင်းညွန်",
  expand: "ချဲ့သည်",
  stretch: "ဆန့်သည်",
  sue: "တရားစွဲသည်",
  promontory: "ကျွန်းစွန်း",
  cape: "စွန်",
  confer: "ချီးမြှင့်သည်",
  wag: "ခါသည်",
  uncovered: "ဖုံးမထားသော",
  creek: "ချောင်းငယ်",
  delusion: "အထင်မှားခြင်း",
  minuteness: "အသေးစိတ်မှု",
  suspend: "ဆိုင်းငံ့သည်",
  "what?": "ဘာလဲ?",
  flip: "လှန်သည်",
  refuse: "ငြင်းသည်",
  decline: "ကျဆင်း/ငြင်းသည်",
  mound: "တောင်ကုန်း",
  tub: "စည်",
  accompany: "လိုက်ပါသည်",
  hang: "ချိတ်သည်",
  relax: "အနားယူသည်",
  shoot: "ပစ်သည်",
  finance: "ဘဏ္ဍာရေး",
  divide: "ခွဲသည်",
  press: "ဖိသည်",
  discreet: "သတိရှိသော",
  "tie up": "ချည်နှောင်သည်",
  constrict: "ကျပ်သည်",
  disturb: "နှောင့်ယှက်သည်",
  cedar: "ဆာရာသစ်ပင်",
  seduce: "သွေးဆောင်သည်",
  willow: "ဝါးယားပင်",
  overgrown: "ပေါက်ရောက်သော",
  "be luxuriant": "စည်ပင်သည်",
  graceful: "ကျက်သရေရှိသော",
  refined: "သန့်စင်သော",
  gleam: "လင်းလက်သည်",
  "go around": "ပတ်လည်သွားသည်",
  twinkle: "တောက်ပသည်",
  prevent: "ကာကွယ်သည်",
  swell: "ဖောင်းသည်",
  "get fat": "ဆူဖြိုးသည်",
  balmy: "နူးညံ့နွေးထွေးသော",
  sword: "ဓားရှည်",
  blade: "ဓားသွား",
  relate: "ဆက်စပ်သည်",
  "consult with": "တိုင်ပင်သည်",
  furnace: "မီးဖို",
  kiln: "အိုးဖို",
  cave: "ဂူ",
  mellow: "နူးညံ့ရင့်ကျက်သည်",
  ripen: "မှည့်သည်",
  mature: "ရင့်ကျက်သည်",
  accomplish: "ပြီးမြောက်သည်",
  rub: "ပွတ်သည်",
  planting: "စိုက်ပျိုးခြင်း",
  quietly: "တိတ်ဆိတ်စွာ",
  mount: "တက်သည်",
  cook: "ချက်သည်",
  grieve: "ဝမ်းနည်းသည်",
  beat: "ရိုက်သည်",
  enclosure: "ခြံဝင်း",
  gauze: "ပိတ်စပါး",
  slave: "ကျွန်",
  "long for": "တောင့်တသည်",
  "spindle tree": "စပင်ဒယ်ပင်",
  jasmine: "ဇာမင်း",
  "ice cream": "ရေခဲမုန့်",
  "(electric) iron": "မီးပူ",
  out: "အပြင်/ထွက်",
  "(2) remains": "အကြွင်းအကျန် (၂)",
  ruins: "အပျက်အစီး",
  "(conj": "ဆက်သွယ်ပုဒ်",
  exp: "အသုံးအနှုန်း",
  "int) Thank you": "ကျေးဇူးတင်ပါသည်",
  album: "အယ်လ်ဘမ်",
  "TODO same as いいえ?": "မဟုတ်နှင့်တူ?",
  whisky: "ဝီစကီ",
  "(n) energy (de: Energie)": "စွမ်းအင်",
  "(1) overcoat": "အပေါ်ကုတ်",
  "(2) over": "အပေါ်/ကျော်",
  "(fam) you (sing)": "မင်း (ရင်းနှီး)",
  "presence (of a high personage)": "မြင့်မြတ်သူရှေ့မှောက်",
  "Congratulations!": "ဂုဏ်ယူပါတယ်!",
  "each other": "အချင်းချင်း",
  "feel disappointed": "စိတ်ပျက်သည်",
  "be dejected": "စိတ်ဓာတ်ကျသည်",
  "lose heart": "စိတ်အားလျော့သည်",
  accurately: "တိကျစွာ",
  captain: "ကပ္ပတိန်",
  "sound asleep": "အိပ်ပျော်နေသော",
  "fast asleep": "အိပ်မောကျသော",
  "classic(s)": "ဂန္ထဝင်",
  "(1) glass": "မှန်/ဖန် (၁)",
  "(2) grass": "မြက် (၂)",
  gland: "ဂလင်း",
  "(electrical) ground": "မြေစိုက်ကြိုး",
  cream: "ခရင်မ်",
  Christmas: "ခရစ္စမတ်",
  "(1) a (photo)copy": "မိတ္တူ (၁)",
  "(2) blurb on a book jacket": "စာအုပ်အဖုံးမိတ်ဆက် (၂)",
  "(1) service": "ဝန်ဆောင်မှု (၁)",
  "support system": "ပံ့ပိုးစနစ်",
  "(2) goods or services without charge": "အခမဲ့ပစ္စည်း/ဝန်ဆောင်မှု (၂)",
  "(1) autograph": "လက်မှတ် (၁)",
  "(2) sign": "ဆိုင်းဘုတ်/လက္ခဏာ (၂)",
  "(3) sine": "ဆိုင်း (သင်္ချာ)",
  "in round numbers": "အကြမ်းဖျင်း",
  "feeling refreshed": "လန်းဆန်းခံစားရခြင်း",
  "feeling relieved": "စိတ်ပေါ့ပါးခံစားရခြင်း",
  neat: "သပ်ရပ်သော",
  trimmed: "ညှိထားသော",
  jeans: "ဂျင်းဘောင်းဘီ",
  "jet aeroplane": "ဂျက်လေယာဉ်",
  "soft drink": "အချိုရည်",
  deuce: "ဒူးစ်",
  switch: "ခလုတ်",
  "(Western) soup": "ဟင်းချို (အနောက်တိုင်း)",
  skiing: "နှင်းလျှောစီးခြင်း",
  "skate(s)": "စကိတ်",
  skating: "စကိတ်စီးခြင်း",
  consecutively: "ဆက်တိုက်",
  "a lot": "များစွာ",
  thereupon: "ထိုအခါ",
  hereupon: "ဤအခါ",
  "face of the earth": "ကမ္ဘာမြေမျက်နှာပြင်",
  sofa: "ဆိုဖာ",
  couch: "ကော်ချ",
  typewriter: "စာရိုက်စက်",
  "(1) dyer": "ဆိုးဆေးသမား (၁)",
  "(2) diagram": "ပုံကြမ်း (၂)",
  "(3) (railway) schedule": "ရထားအချိန်ဇယား (၃)",
  "(4) diamond": "စိန် (၄)",
  simile: "ဥပမာပုံ",
  metaphor: "ဥပစာ",
  allegory: "ဥပမာပြော",
  cheese: "ချိစ်",
  outflow: "ထွက်စီးခြင်း",
  "coming (going) out": "ထွက်ခြင်း/လာခြင်း",
  "graduate (of)": "ဘွဲ့ရ",
  "go on a date": "ချိန်းတွေ့သည်",
  "chance of going out": "ထွက်ခွင့်အခွင့်အရေး",
  "opportunity (to succeed)": "အောင်မြင်ခွင့်",
  "moment of departure": "ထွက်ခွာချိန်",
  "beginning of work": "အလုပ်စတင်ခြင်း",
  "(abbr) demo": "ဒီမို (အတိုကောက်)",
  tent: "တဲ",
  "copper coin": "ကြေးပြား",
  "at any cost": "ဘယ်လိုပဲဖြစ်ဖြစ်",
  drive: "မောင်းနှင်ခြင်း",
  "trip by car": "ကားခရီး",
  "(1) truck": "ထရပ်ကား (၁)",
  "(2) (running) track": "ပြေးလမ်း (၂)",
  drama: "ဒရာမာ",
  "playing cards (lit: trump)": "ဖဲချပ်",
  offensive: "ထိုးစစ်/စော်ကားသော",
  "What a thing to say!": "ဘာပြောတာလဲ!",
  "No way!": "မဖြစ်နိုင်ဘူး!",
  tunnel: "ဥမင်",
  "(1) knock": "ခေါက်ခြင်း (၁)",
  "(2) fungo (baseball)": "ဖန်ဂို (ဘေ့စ်ဘော) (၂)",
  "at leisure": "အားလပ်စွာ",
  wear: "ဝတ်သည်",
  "put on (sword)": "ဓားစွဲသည်",
  violin: "ဗိုင်အိုလင်",
  hiking: "တောင်တက်လမ်းလျှောက်",
  "(1) pipe": "ပိုက် (၁)",
  "(2) channels": "လမ်းကြောင်းများ (၂)",
  "official or otherwise": "တရားဝင်ဖြစ်စေမဖြစ်စေ",
  pilot: "လေယာဉ်မှူး",
  path: "လမ်းကြောင်း",
  "pass (in games)": "ပေးပို့ခြင်း (ဂိမ်း)",
  "with a clash (thud)": "တုံးတိုးနှင့်",
  "with a bang": "ပေါက်ကွဲသံနှင့်",
  flop: "ပျက်ကျခြင်း",
  bun: "ပေါင်မုန့်လုံး",
  "van (caravan)": "ဗင်ကား",
  "VAN (value-added network)": "တန်ဖိုးမြှင့်ကွန်ရက်",
  picnic: "ပိတ်နစ်",
  video: "ဗီဒီယို",
  plus: "ပေါင်း/အပေါင်း",
  "a brake": "ဘရိတ်",
  "Belt for western clothes": "အနောက်တိုင်းခါးပတ်",
  "(n) paint (nl: pek)": "ဆေးသုတ်",
  bench: "ခုံတန်းလျား",
  "rowing boat": "လှေလှော်",
  "(1) platform": "ပလက်ဖောင်း (၁)",
  "(2) home": "အိမ်/ပလက်ဖောင်း (၂)",
  almost: "နီးပါး",
  "absent-minded": "စိတ်လွင့်သော",
  "block-head": "ထုံထိုင်းသူ",
  dim: "မှိန်သော",
  faint: "အားနည်းသော",
  "(female) you might say": "မင်း (မိန်းကလေးသုံး)",
  mike: "မိုက်ခ်",
  "by no means": "မည်သို့မျှမ",
  proprietor: "ပိုင်ရှင်",
  manager: "မန်နေဂျာ",
  barowner: "ဘားပိုင်ရှင်",
  "master (e.g. arts": "ဆရာ/ကျွမ်းကျင်သူ",
  Mama: "မာမာ",
  memorandum: "မှတ်စုစာ",
  humor: "ဟာသဉာဏ်",
  yacht: "ယော့",
  twist: "လိမ်ခြင်း",
  ply: "ချည်လွှာ",
  "according to": "အရ",
  lighter: "မီးခြစ်/ပေါ့ပါးသူ",
  rider: "စီးသူ",
  paddle: "လှော်တက်",
  racket: "ရက်ကက်",
  locket: "လော်ကက်",
  rocket: "ဒုံးပျံ",
  greeting: "နှုတ်ဆက်ခြင်း",
  salutation: "နှုတ်ဆက်စကား",
  handshake: "လက်ဆွဲနှုတ်ဆက်ခြင်း",
  "to deal with": "ကိုင်တွယ်သည်",
  stability: "တည်ငြိမ်မှု",
  memorization: "အလွတ်ကျက်မှတ်ခြင်း",
  "learning by heart": "နှလုံးသားထဲမှတ်ခြင်း",
  "to surround": "ဝန်းရံသည်",
  "to encircle": "ပတ်ရစ်သည်",
  "committee member": "ကော်မတီအဖွဲ့ဝင်",
  surprising: "အံ့အားသင့်ဖွယ်",
  consciousness: "သိစိတ်",
  senses: "အာရုံများ",
  strangeness: "ထူးဆန်းမှု",
  abnormality: "ပုံမှန်မဟုတ်မှု",
  "to transfer": "လွှဲပြောင်းသည်",
  "to infect": "ကူးစက်သည်",
  "(phrase) sure": "သေချာသည်",
  "no mistaking it": "မှားမည်မဟုတ်",
  "for certain": "သေချာပေါက်",
  "violation (of law)": "ဥပဒေချိုးဖောက်မှု",
  transgression: "ကျူးလွန်မှု",
  infringement: "ထိပါးမှု",
  breach: "ချိုးဖောက်မှု",
  "to raise (child)": "မွေးမြူပြုစုသည်",
  "to be brought up": "ပြုစုခံရသည်",
  "to grow (up)": "ကြီးပြင်းသည်",
  "a moment": "ခဏတာ",
  "an instant": "တစ်ခဏ",
  "one at a time": "တစ်ခုချင်း",
  "whole life": "တစ်သက်တာ",
  "a lifetime": "တစ်သက်",
  "all through life": "တစ်သက်လုံး",
  "much more": "ပို၍ပင်",
  "(1) one object": "တစ်ခု/တစ်ကိုယ် (၁)",
  "one body": "တစ်ကိုယ်",
  "(2) what on earth?": "ဘာလို့လဲ? (၂)",
  "really?": "တကယ်လား?",
  "rice-plant": "စပါးပင်",
  "(1) mark": "အမှတ် (၁)",
  "(2) symbol": "သင်္ကေတ (၂)",
  "(3) evidence": "သက်သေ (၃)",
  "(1) to pull": "ဆွဲသည် (၁)",
  "to draw": "ဆွဲသည်",
  "to drag": "ဆွဲယူသည်",
  "to conceal": "ဖုံးကွယ်သည်",
  "counter for birds": "ငှက်ရေတွက်",
  "counter for rabbits": "ယုန်ရေတွက်",
  operation: "စစ်ဆင်ရေး/လည်ပတ်မှု",
  exercise: "လေ့ကျင့်ခန်း",
  bait: "เหား",
  nutrition: "အာဟာရ",
  permanence: "ထာဝရတည်မြဲမှု",
  satellite: "ဂြိုဟ်တု",
  pointed: "ချွန်သော",
  sharp: "ထက်သော",
  "to go over (e.g. with audience)": "ရှင်းပြဆွေးနွေးသည်",
  postponement: "ရွှေ့ဆိုင်းခြင်း",
  adjournment: "ရပ်ဆိုင်းခြင်း",
  acting: "သရုပ်ဆောင်ခြင်း",
  "musical performance": "ဂီတဖျော်ဖြေမှု",
  fumes: "မီးခိုးငွေ့",
  "a means": "နည်းလမ်း",
  "e.g. of living": "ဥပမာ နေထိုင်နည်း",
  contamination: "ညစ်ညမ်းမှု",
  "inner part": "အတွင်းပိုင်း",
  "to respond": "တုံ့ပြန်သည်",
  "to accept": "လက်ခံသည်",
  "to cross (e.g. arms)": "ကူးသည် (လက်တို့)",
  "to traverse": "ဖြတ်သန်းသည်",
  crossing: "ဖြတ်ကူးခြင်း",
  prince: "မင်းသား",
  roof: "ခေါင်မိုး",
  favour: "ကျေးဇူး",
  "debt of gratitude": "ကျေးဇူးတန်ဖိုး",
  "(hon) to give": "ပေးသည် (လေးစား)",
  "to lower": "နှိမ့်သည်",
  "to let go down": "ချသည်",
  "down-train (going away from Tokyo)": "တိုကျိုမှထွက်ရထား",
  chemistry: "ဓာတုဗေဒ",
  "make-up (cosmetic)": "မိတ်ကပ်",
  something: "တစ်ခုခု",
  "Why?": "ဘာကြောင့်?",
  "What for?": "ဘာအတွက်?",
  "to sum up": "စုစုပေါင်းတွက်သည်",
  "to add (up)": "ပေါင်းသည်",
  "addition and subtraction": "ပေါင်းခြင်းနှင့်နုတ်ခြင်း",
  "allowance for": "အတွက်ခွင့်ပြုချက်",
  passable: "သင့်တင့်သော",
  "daughter-in-law": "ချွေးမ",
  furniture: "ပရိဘောဂ",
  housework: "အိမ်မှုအလုပ်",
  "domestic chores": "အိမ်တွင်းအလုပ်များ",
  "(school) subject": "ဘာသာရပ်",
  singer: "အဆိုတော်",
  "(abbr) Tuesday": "အင်္ဂါနေ့ (အတို)",
  "to earn income": "ဝင်ငွေရှာသည်",
  "to labor": "အလုပ်လုပ်သည်",
  pastry: "မုန့်ပျား",
  "counter for chapters (of a book)": "အခန်းရေတွက်",
  painter: "ပန်းချီဆရာ",
  "to come untied": "ကြိုးလွတ်သည်",
  "to come apart": "ကွဲထွက်သည်",
  solution: "ဖြေရှင်းချက်",
  "recovery (from illness)": "နာမကျန်းမှပြန်ကောင်းခြင်း",
  "injury (to animate object)": "ဒဏ်ရာ (သက်ရှိ)",
  betterment: "တိုးတက်ကောင်းမွန်ခြင်း",
  abroad: "နိုင်ငံရပ်ခြား",
  overseas: "ပြည်ပ",
  ash: "ပြာ",
  diplomacy: "သံတမန်ရေး",
  outing: "အပြင်ထွက်ခြင်း",
  cough: "ချောင်းဆိုး",
  "evil influence": "ဆိုးကျိုးသက်ရောက်မှု",
  "to ascertain": "သေချာစုံစမ်းသည်",
  certainty: "သေချာမှု",
  reliability: "ယုံကြည်စိတ်ချရမှု",
  soundness: "ခိုင်မာမှု",
  confirmation: "အတည်ပြုခြင်း",
  "to awaken": "နိုးသည်",
  readiness: "အသင့်ရှိမှု",
  preparedness: "ပြင်ဆင်ထားမှု",
  horn: "ဦးချို",
  "term (school)": "စာသင်နှစ်ကာလ",
  comfort: "သက်တောင့်သက်သာ",
  ease: "လွယ်ကူမှု",
  forehead: "နဖူး",
  brow: "မျက်ခုံး",
  liveliness: "စည်ကားမှု",
  conjugation: "ကြိယာပုံစံပြောင်းခြင်း",
  share: "ဝေစု",
  "stump (of tree)": "တုံးတိုင်",
  "to cut (hair)": "ဆံပင်ညှပ်သည်",
  "to mow (grass)": "မြက်ရိတ်သည်",
  "the sixth sense": "ဆဋ္ဌမအာရုံ",
  counting: "ရေတွက်ခြင်း",
  "to recommend": "အကြံပေးသည်",
  "to advise": "အကြံပြုသည်",
  "to offer (wine)": "ကမ်းလှမ်းသည် (ဝိုင်)",
  "(1) complete": "ပြည့်စုံသော (၁)",
  "(2) perfection": "ပြည့်စုံမှု (၂)",
  accomplishment: "ပြီးမြောက်မှု",
  "a patient": "လူနာ",
  "emotion(s)": "စိတ်ခံစားမှုများ",
  "feeling(s)": "ခံစားချက်များ",
  sentiment: "စိတ်သဘော",
  "Well done!": "ကောင်းလိုက်တာ!",
  "being deeply moved": "စိတ်လှုပ်ရှားခံစားခြင်း",
  perspiration: "ချွေး",
  "spectator(s)": "ပရိသတ်များ",
  "to concern": "သက်ဆိုင်သည်",
  "to be related": "ဆက်စပ်သည်",
  "to hold in the mouth": "ပါးစပ်ထဲကိုင်သည်",
  enterprise: "လုပ်ငန်း",
  undertaking: "လုပ်ဆောင်ချက်",
  "(a) joy": "ဝမ်းသာမှု",
  "to be grounded on": "အခြေခံသည်",
  "to be due to": "ကြောင့်ဖြစ်သည်",
  "to originate from": "မှအစပြုသည်",
  facility: "အဆောက်အအုံ/အဆင်အပြေ",
  function: "လုပ်ဆောင်ချက်",
  faculty: "စွမ်းရည်",
  "returning home": "အိမ်ပြန်ခြင်း",
  "to be pleased with": "ကျေနပ်သည်",
  "a pity": "နှမြောစရာ",
  "to become aware of": "သတိပြုမိသည်",
  "-looking": "-ပုံရသော",
  "-looked": "-ပုံပေါက်သော",
  reporter: "သတင်းထောက်",
  "filling in of forms": "ပုံစံဖြည့်ခြင်း",
  "to occur": "ဖြစ်ပေါ်သည်",
  "to happen": "ဖြစ်သည်",
  ogre: "ဘီလူး",
  "it (i.e.": "သူ (ဆိုလိုသည်မှာ",
  "in a game of tag)": "ဖမ်းရမည့်သူ (ဂိမ်း)",
  technician: "နည်းပညာရှင်",
  "member of the Diet": "ပါလီမန်အမတ်",
  "congress or parliament": "ကွန်ဂရက် သို့မဟုတ် ပါလီမန်",
  Diet: "ပါလီမန်",
  chairman: "ဥက္ကဋ္ဌ",
  "to pack": "ထုပ်သည်",
  "to work out (details)": "အသေးစိတ်စီစဉ်သည်",
  "to defy": "ဆန့်ကျင်သည်",
  absorption: "စုပ်ယူမှု",
  suction: "စုပ်ခြင်း",
  attraction: "ဆွဲဆောင်မှု",
  "rapid (e.g. progress)": "လျင်မြန်သော",
  "to rescue from": "ကယ်တင်သည်",
  "to help out of": "ကူညီထုတ်သည်",
  "ex-": "အရင်-",
  "living room (western style)": "ဧည့်ခန်း",
  dozing: "ငိုက်မျဉ်းခြင်း",
  "nodding off": "ခေါင်းညိတ်အိပ်ခြင်း",
  gigantic: "ဧရာမ",
  "to permit": "ခွင့်ပြုသည်",
  "to allow": "ခွင့်ပေးသည်",
  provision: "ထောက်ပံ့မှု",
  "sharing with": "မျှဝေခြင်း",
  "participate in": "ပါဝင်သည်",
  commonness: "ဘုံဖြစ်မှု",
  community: "အသိုင်းအဝိုင်း",
  joint: "ပူးတွဲ",
  "mental state": "စိတ်အခြေအနေ",
  "stressed point": "အရေးကြီးချက်",
  burglary: "အိမ်ဖောက်မှု",
  "herculean strength": "အင်အားကြီးမားမှု",
  "mountain carrier-guide": "တောင်ပေါ်လမ်းပြ",
  "be afraid": "ကြောက်သည်",
  dread: "ကြောက်ရွံ့ခြင်း",
  dismay: "ထိတ်လန့်မှု",
  terror: "အကြောက်တရား",
  "teacher (classroom)": "ဆရာ",
  teaching: "သင်ကြားခြင်း",
  professor: "ပါမောက္ခ",
  "to go mad": "ရူးသည်",
  "to get out of order": "ပျက်စီးသည်",
  breast: "ရင်သား",
  chest: "ရင်ဘတ်",
  "court lady": "နန်းတွင်းအမျိုးသမီး",
  "lady in waiting": "နန်းတွင်းသူ",
  "No Smoking!": "ဆေးလိပ်မသောက်ရ!",
  muscle: "ကြွက်သား",
  sinew: "ရွတ်",
  tension: "တင်းမာမှု",
  "mental strain": "စိတ်ဖိစီးမှု",
  nervousness: "အာရုံကြောတင်းမာမှု",
  "present day": "ယနေ့ခေတ်",
  "(1) gold": "ရွှေ (၁)",
  "(2) gold general (shogi) (abbr)": "ရွှေဗိုလ် (ရှောဂိ)",
  "amount of money": "ငွေပမာဏ",
  metal: "သတ္တု",
  "monetary circulation": "ငွေကြေးလည်ပတ်မှု",
  "credit situation": "ခရက်ဒစ်အခြေအနေ",
  "(abbr) Friday": "သောကြာနေ့ (အတို)",
  "(1) silver": "ငွေ (၁)",
  "silver coin": "ငွေဒင်္ဂါး",
  "silver paint": "ငွေရောင်ဆေး",
  "poor (at)": "ညံ့သော",
  "weak (in)": "အားနည်းသော",
  "dislike (of)": "မကြိုက်သော",
  tangible: "ထိတွေ့နိုင်သော",
  casually: "ပေါ့ပေါ့ပါးပါး",
  "by chance": "မထင်မှတ်ဘဲ",
  "to do something over again": "ပြန်လုပ်သည်",
  "native Japanese reading of a Chinese character": "ဂျပန်အသံဖတ်ခြင်း",
  inclination: "ညွတ်မှု",
  "criminal case": "ရာဇဝတ်မှုမှုခင်း",
  "(police) detective": "ရဲစုံထောက်",
  bulletin: "သတင်းလွှာ",
  "go by the way": "လမ်းမှဖြတ်သည်",
  via: "မှတစ်ဆင့်",
  reckoning: "တွက်ချက်ခြင်း",
  "(fine) art": "အနုပညာ",
  "the arts": "အနုပညာများ",
  theatre: "ပြဇာတ်ရုံ",
  playhouse: "ပြဇာတ်အိမ်",
  intense: "ပြင်းထန်သော",
  "to be lacking": "ချို့တဲ့သည်",
  determination: "ဆုံးဖြတ်ချက်",
  "seeing one off": "ပို့ဆောင်ခြင်း",
  "be found": "တွေ့ရှိသည်",
  clever: "ထက်မြက်သော",
  "(1) to appear": "ပေါ်လာသည် (၁)",
  "to come in sight": "မြင်ရသည်",
  "to become visible": "မြင်သာသည်",
  "(2) to express oneself": "ကိုယ်ကိုဖော်ပြသည် (၂)",
  cash: "ငွေသား",
  "ready money": "အသင့်ငွေ",
  mercenary: "ငှားရမ်းစစ်သည်",
  "self-interested": "ကိုယ်ကျိုးကြည့်သော",
  "present condition": "လက်ရှိအခြေအနေ",
  "existing state": "ရှိရင်းစွဲအခြေအနေ",
  proverb: "စကားပုံ",
  maxim: "ဆိုရိုးစကား",
  "to restrict": "ကန့်သတ်သည်",
  "to limit": "ကန့်သတ်သည်",
  "to confine": "ချုပ်နှောင်သည်",
  respiration: "အသက်ရှူခြင်း",
  "old village": "ရွာဟောင်း",
};
