module.exports = {
  'brazen': 'ရဲရင့်',
  'lipstick': 'နှုတ်ခမ်းနီ',
  '(v5u) to face': 'မျက်နှာမူ',
  'to go towards': 'ဆီသို့သွား',
  'matter of taste': 'အရသာကိစ္စ',
  'filial piety': 'မိဘကျိုးကျင့်',
  'factory worker': 'စက်ရုံအလုပ်သမား',
  'industrial arts': 'စက်မှုလက်မှု',
  'construction work': 'ဆောက်လုပ်ရေး',
  'labourer': 'အလုပ်သမား',
  'spacious': 'ကျယ်ဝန်း',
  'to enlarge': 'ချဲ့',
  'to broaden': 'ကျယ်အောင်လုပ်',
  'to propagate': 'ပြန့်ပွား',
  'plaza': 'ရင်ပြင်',
  'to get late': 'နောက်ကျ',
  'to wear on': 'ဝတ်',
  'school building': 'ကျောင်းအဆောက်အအုံ',
  '(1) (Japanese) maple': 'မေပယ်ပင်',
  'to wring': 'ညှစ်',
  'to squeeze': 'ညှစ်ယူ',
  'to till': 'ထွန်ယက်',
  'to plow': 'ထွန်',
  'to cultivate': 'စိုက်ပျိုး',
  'arable land': 'စိုက်ပျိုးမြေ',
  '(1) line': 'လိုင်း',
  'procession': 'ချီတက်တန်း',
  '(2) matrix (math)': 'မက်ထရစ်',
  'lecturer': 'ကထိက',
  'rational': 'ယုတ္တိကျ',
  'to mince': 'အသေးလှီး',
  'nationality': 'နိုင်ငံသားဖြစ်မှု',
  'to sit (down)': 'ထိုင်',
  'to curse': 'ကျိန်ဆဲ',
  'to feel bitter': 'ခါးသီးခံစား',
  'to stir': 'မွှေ',
  'navy blue': 'ရေတပ်ပြာ',
  'cushion (Japanese)': 'ဂျပန်ခုံ',
  'tatami room': 'တာတာမိခန်း',
  'again and again': 'ထပ်ခါထပ်ခါ',
  'month after next': 'နောက်နှစ်လ',
  'week after next': 'နောက်နှစ်ပတ်',
  'to be plugged up': 'ပိတ်နေ',
  'to be shut up': 'ပိတ်မိ',
  'to stop up': 'ပိတ်',
  'to close up': 'ပိတ်ထား',
  'to block (up)': 'ပိတ်ဆို့',
  '(1) to adopt (measure': 'မူဝါဒချမှတ်',
  'proposal)': 'အဆို',
  '(2) to pick (fruit)': 'အသီးခူး',
  'marking': 'မှတ်ချက်ပေး',
  'grading': 'အမှတ်ပေး',
  'looking over': 'ကြည့်စစ်',
  'to deify': 'နတ်အဖြစ်ကိုးကွယ်',
  'to enshrine': 'ဘုရားတည်',
  'festival day': 'ပွဲနေ့',
  'sewing': 'ချုပ်လုပ်',
  'to appear (in print)': 'ပုံနှိပ်ထွက်',
  'to be recorded': 'မှတ်တမ်းတင်ခံရ',
  '(enrolled) in school': 'ကျောင်းစာရင်းဝင်',
  'lumber': 'သစ်သား',
  'timber': 'သစ်',
  'authoress': 'အမျိုးသမီးစာရေး',
  'to cut down little by little': 'တဖြည်းဖြည်းခုတ်',
  'to take a percentage': 'ရာခိုင်နှုန်းယူ',
  'deletion': 'ဖျက်ခြင်း',
  'erasure': 'ဖျက်ပစ်',
  'indices': 'ညွှန်းကိန်း',
  'photographing': 'ဓာတ်ပုံရိုက်',
  'to chafe': 'ပွတ်တိုက်',
  'to frost (glass)': 'မှန်မှုန်',
  'noise (jarring': 'ဆူညံသံ',
  'grating)': 'ကြိတ်သံ',
  'house-cloth': 'အိမ်သုံးအဝတ်',
  'dust cloth': 'ဖုန်သုတ်အဝတ်',
  'to rust': 'သံချေးတက်',
  'to become rusty': 'သံချေးဖြစ်',
  'triangle': 'တြိဂံ',
  'triangular': 'တြိဂံပုံ',
  'mountain forest': 'တောင်တော',
  'mountains and forest': 'တောင်နှင့်တော',
  'to sprinkle': 'ဖြန်း',
  'to sow': 'ကြဲ',
  'to scatter around': 'ကြဲဖြန့်',
  'to leave untidy': 'ရှုပ်ထွေးထား',
  'to be in disorder': 'မစနစ်တကျ',
  'to lie scattered around': 'ကြဲပြန့်နေ',
  'to disperse': 'ပြန့်ကျဲ',
  'producing area': 'ထုတ်လုပ်ဒေသ',
  'abacus': 'ပေသီး',
  'acidity': 'အက်ဆစ်ဓာတ်',
  '(v5r) to behead': 'ခေါင်းဖြတ်',
  'to murder': 'လူသတ်',
  'to stab': 'ထိုး',
  'to prick': 'ထိုးဖောက်',
  'to thrust': 'ထိုးသွင်း',
  'chairmanship': 'ဥက္ကဋ္ဌရာထူး',
  'four corners': 'ထောင့်လေးခု',
  'four seasons': 'ရာသီလေးပါး',
  'rounding up (fractions)': 'အပိုင်းပြည့်',
  'continuously': 'ဆက်တိုက်',
  'posture': 'ကိုယ်နေဟန်ထား',
  'posterity': 'နောက်မျိုးဆက်',
  'to be under impression that': 'ထင်မြင်နေ',
  'to be convinced that': 'ယုံကြည်နေ',
  'to think of': 'တွေး',
  'to hit upon': 'ပေါ်လာ',
  'designation': 'သတ်မှတ်ခေါ်',
  'specification': 'အသေးစိတ်သတ်မှတ်',
  'pointing at': 'ညွှန်ပြ',
  'corpse': 'အလောင်း',
  'identity': 'အမှတ်အသား',
  'private railway': 'ပုဂ္ဂလိကရထား',
  'private (establishment)': 'ပုဂ္ဂလိကအဖွဲ့',
  'wastepaper': 'စက္ကူအမှိုက်',
  'notes': 'မှတ်စု',
  'bills': 'ငွေစက္ကူ',
  'purple colour': 'ခရမ်းရောင်',
  'gear': 'ဂီယာ',
  'cog-wheel': 'သွားဘီး',
  'bringing': 'ယူလာ',
  'taking': 'ယူသွား',
  'carrying': 'သယ်ဆောင်',
  'timetable': 'အချိန်ဇယား',
  'speed (per hour)': 'နာရီအမြန်နှုန်း',
  'to rank next to': 'နောက်ဆင့်',
  'to come after': 'နောက်မှလာ',
  '(1) to govern': 'အုပ်ချုပ်',
  'to manage': 'စီမံ',
  '(2) to subdue': 'နှိမ်နင်း',
  'self-government': 'ကိုယ်ပိုင်အုပ်ချုပ်',
  'self-study': 'ကိုယ်တိုင်လေ့လာ',
  'natural science': 'သဘာဝသိပ္ပံ',
  'to sow (seeds)': 'မျိုးကြဲ',
  'disappointed love': 'ချစ်မရ',
  'broken heart': 'နှလုံးကွဲ',
  'be lovelorn': 'ချစ်ဆုံးရှုံး',
  'to be wet': 'စို',
  'to become wet': 'စိုလာ',
  'humidity': 'စိုထိုင်းမှု',
  'level of humidity': 'စိုထိုင်းအဆင့်',
  'to ripen': 'မှည့်',
  'feelings (actual': 'စစ်မှန်ခံစားချက်',
  'true)': 'အမှန်',
  'actual results': 'အမှန်တကယ်ရလဒ်',
  'utility': 'အသုံးဝင်မှု',
  'stripe': 'အစင်း',
  'to be photographed': 'ဓာတ်ပုံရိုက်ခံရ',
  'to be projected': 'ပရိုဂျက်ရှင်ခံရ',
  'sketching': 'ပုံကြမ်းဆွဲ',
  'drawing from nature': 'သဘာဝမှဆွဲ',
  'obliqueness': 'စောင်းမှု',
  'social science': 'လူမှုသိပ္ပံ',
  'editorial': 'အယ်ဒီတာ့အာဘော်',
  'leading article': 'ဦးဆောင်ဆောင်းပါး',
  'garage': 'ဂိုဒေါင်',
  'car shed': 'ကားရုံ',
  '(train) conductor': 'ရထားကြီးကြပ်',
  '(car) wheel': 'ကားဘီး',
  'tap': 'ပိုက်ခေါင်း',
  'to serve sake': 'ဆာကေလောင်း',
  '(gram) subject': 'ကတ္တား',
  'leading part': 'ဦးဆောင်ဇာတ်ကောင်',
  'leading actor (actress)': 'ဦးဆောင်သရုပ်ဆောင်',
  'to cancel': 'ပယ်ဖျက်',
  'to take in': 'ယူဝင်',
  'to adopt': 'မွေးစား',
  'handy': 'အဆင်ပြေ',
  'wrist': 'လက်ကောက်ဝတ်',
  'restroom': 'အိမ်သာ',
  'lavatory': 'ရေဆေးခန်း',
  'hand-washing': 'လက်ဆေး',
  '(legal) process': 'တရားဝင်လုပ်ထုံး',
  'formalities': 'လုပ်ထုံးလုပ်နည်း',
  'repairs': 'ပြုပြင်',
  'bar-room': 'ဘားခန်း',
  'to take (be in) charge of': 'တာဝန်ယူ',
  'taking an examination': 'စာမေးပွဲဖြေ',
  '(telephone) receiver': 'ဖုန်းနားကြပ်',
  'life span': 'သက်တမ်း',
  'assumption of office': 'ရာထူးယူ',
  'terminus': 'နောက်ဆုံးဘူတာ',
  'last stop (e.g train)': 'နောက်ဆုံးရပ်',
  'penmanship': 'စာရေးအတတ်',
  'to kick': 'ကန်',
  'money collection': 'ငွေကောက်',
  'cousin (female)': 'အမျိုးသမီးဝမ်းကွဲ',
  'to be piled up': 'ပုံနေ',
  'lie on top of one another': 'ထပ်လျက်နေ',
  'overlap each other': 'ထပ်နေ',
  'to put something on another': 'တစ်ခုပေါ်တစ်ခုတင်',
  'to heap up': 'ပုံ',
  'seriously ill': 'ပြင်းထန်နာ',
  'serious condition': 'အခြေအနေဆိုး',
  'critical state': 'အရေးပေါ်အခြေအနေ',
  'important point': 'အရေးကြီးချက်',
  'lay stress on': 'အလေးပေး',
  'colon': 'အူမကြီး',
  'high executive': 'အမှုဆောင်အဆင့်မြင့်',
  '(1) weight': 'အလေးချိန်',
  '(2) heavyweight boxer': 'လေးချိန်လက်ဝှေ့သမား',
  '(1) aunt': 'အဒေါ်',
  '(2) middle-aged lady': 'လူလတ်ပိုင်းအမျိုးသမီး',
  'to reduce': 'လျှော့',
  'to boil down': 'ကျိုကျဉ်',
  'to be wavy': 'လှိုင်းတွန့်',
  'to be curled': 'ကောက်ကွေး',
  'curtailment': 'လျှော့ချ',
  'idiom': 'စကားပုံ',
  'idiomatic phrase': 'အသုံးအနှုန်း',
  'kanji compound': 'ကန်ဂျိပေါင်းစကား',
  'going to work': 'အလုပ်သွား',
  'at work': 'အလုပ်မှာ',
  'an encounter': 'တွေ့ဆုံမှု',
  'official tour': 'တရားဝင်ခရီး',
  'business trip': 'အလုပ်ခရီး',
  'in and out': 'ဝင်ထွက်',
  'free association': 'လွတ်လပ်ဆက်စပ်',
  'be finished': 'ပြီး',
  'ready': 'အဆင်သင့်',
  'made for': 'အတွက်လုပ်',
  'cut out': 'ဖြတ်ထား',
  '(1) to be finished': 'ပြီးပြီ',
  'to be ready': 'အဆင်သင့်ဖြစ်',
  'by definition': 'အဓိပ္ပာယ်အရ',
  '(2) to be very drunk': 'မူးနေ',
  'predicate': 'ကြိယာပိုင်း',
  'pure heart': 'စိတ်သန့်',
  'self-sacrificing devotion': 'ကိုယ်ကျိုးစွန့်',
  'in order': 'အစဉ်အတိုင်း',
  'elementary level': 'မူလတန်းအဆင့်',
  'first 10 days of the month': 'လ၏ပထမဆယ်ရက်',
  'bookshop': 'စာအုပ်ဆိုင်',
  'calligraphy': 'စာလက်ရေး',
  'writing down': 'ရေးမှတ်',
  'putting on record': 'မှတ်တမ်းတင်',
  'recording': 'အသံဖမ်း',
  'making a note of': 'မှတ်စုရေး',
  'assistant professor': 'လက်ထောက်ပါမောက္ခ',
  'victory or defeat': 'အနိုင်အရှုံး',
  'issue (of battle)': 'တိုက်ပွဲရလဒ်',
  'trading company': 'ကုန်သွယ်ကုမ္ပဏီ',
  'firm': 'ကုမ္ပဏီ',
  'grade school student': 'မူလတန်းကျောင်းသား',
  'personal expenses': 'ကိုယ်ပိုင်အသုံးစရိတ်',
  'pocket money': 'အိတ်ကပ်ငွေ',
  'spending money': 'သုံးငွေ',
  'incidental expenses': 'အပိုအသုံးစရိတ်',
  'little finger': 'လက်သေးချောင်း',
  'fraction (part of)': 'အပိုင်းကိန်း',
  'decimal': 'ဒဿမ',
  '(col) urine': 'ဆီး',
  'piss': 'ဆီး',
  'alcove': 'နံရံအခေါင်း',
  'digestion': 'အစာချေ',
  'disinfection': 'ပိုးသတ်',
  'sterilization': 'ပိုးသတ်ခြင်း',
  'fire station': 'မီးသတ်ဌာန',
  'to shine on': 'ထိုးလင်း',
  'to illuminate': 'လင်းစေ',
  'abridgment': 'ချုံ့ချက်',
  'monetary award': 'ငွေဆု',
  'trophy': 'ဖလား',
  'paper sliding door': 'စက္ကူတံခါး',
  'up-train (going to Tokyo)': 'တိုကျိုသွားရထား',
  'ascent': 'တက်ခြင်း',
  'first 10 days of month': 'လ၏ပထမဆယ်ရက်',
  '(n) transfer (trains': 'ရထားဘတ်စ်ပြောင်း',
  'buses': 'ဘတ်စ်',
  'taking a train': 'ရထားစီး',
  'entraining': 'ရထားတက်',
  'to fold (clothes)': 'အဝတ်ခေါက်',
  'humid': 'စိုထိုင်း',
  'to steam': 'ငွေ့',
  'to poultice': 'ပူထုပ်',
  'to be sultry': 'ပူအိုက်',
  'evaporation': 'ငွေ့ပျံ',
  'unexplained disappearance': 'ရှင်းမရပျောက်',
  'to wipe': 'သုတ်',
  'to dry': 'ခြောက်',
  'garden shrubs': 'ဥယျာဉ်ချုံ',
  'trees': 'သစ်ပင်',
  'potted plant': 'အိုးပင်',
  'mechanic': 'စက်ပြင်',
  'craftsman': 'လက်မှုပညာသည်',
  'table salt': 'စားပွဲဆား',
  'tableware': 'ပန်းကန်ခွက်',
  'mind and body': 'ကိုယ်နှင့်စိတ်',
  'having some knowledge of': 'အနည်းငယ်သိ',
  'happening to know': 'မတော်တဆသိ',
  'to be informed': 'အကြောင်းကြားခံရ',
  'to have thorough knowledge': 'နှံ့စပ်သိ',
  'pronunciation key': 'အသံထွက်သော့',
  'to behave': 'ကျင့်သုံး',
  'to conduct oneself': 'ကိုယ်ကိုဆောင်',
  'to entertain (vt)': 'ဧည့်ခံ',
  'bullet train (very high speed)': 'မြန်ရထား',
  'shinkansen': 'ရှင်ကန်ဆဲန်',
  'inexcusable': 'ခွင့်မလွှတ်နိုင်',
  'total darkness': 'မှောင်မိုက်လုံးဝ',
  'pitch dark': 'မှောင်မှောင်',
  'pitch black': 'မဲမှောင်',
  'ghastly pale': 'ဖြူဖျော့',
  'pure white': 'ဖြူစင်',
  'to mimic': 'တုပ',
  'myth': 'ဒဏ္ဍာရီ',
  'thumb': 'လက်မ',
  'to examine (medical)': 'ဆေးစစ်',
  'social position': 'လူမှုအဆင့်',
  'social status': 'လူမှုအဆင့်အတန်း',
  'wire': 'ဝါယာ',
  'index finger': 'လက်ညှိုး',
  'man-made': 'လူလုပ်',
  'synthetic': 'ဓာတုပေါင်း',
  'pedestrian traffic': 'လမ်းသွားသူစီးဆင်း',
  'social sciences': 'လူမှုသိပ္ပံများ',
  'humanities': 'လူသားပညာ',
  '(human) life': 'လူ့ဘဝ',
  'toilet paper': 'အိမ်သာစက္ကူ',
  'vinegar': 'ရှလကာရည်',
  'picture book': 'ပုံပြင်စာအုပ်',
  'snow storm': 'နှင်းမုန်တိုင်း',
  'vertical': 'ဒေါင်လိုက်',
  'perpendicular': 'ထောင်လိုက်',
  'presumption': 'ခန့်မှန်း',
  'marine products': 'ရေထွက်ကုန်',
  'fisheries': 'ငါးလုပ်ငန်း',
  'water vapour': 'ရေငွေ့',
  'hydrogen': 'ဟိုက်ဒရိုဂျင်',
  'drop of water': 'ရေစက်',
  'canteen': 'ရေဘူး',
  'flask': 'ဖလက်စ်',
  'water bottle': 'ရေပုလင်း',
  'water level': 'ရေအဆင့်',
  'culinary arts': 'ချက်ပြုတ်အတတ်',
  'essays': 'ဆောင်းပါးများ',
  'miscellaneous writings': 'အမျိုးမျိုးရေးသားချက်',
  'Japanese cedar': 'ဂျပန်ဆီဒါ',
  'to clear (e.g. weather)': 'ရှင်းလင်း',
  'to become transparent': 'ကြည်လင်လာ',
  'earthenware': 'မြေထည်',
  'crockery': 'ခွက်ပန်းကန်',
  'work (film': 'လက်ရာ',
  'book)': 'စာအုပ်',
  'distinction by sex': 'ကျားမခွဲခြား',
  '(member of) political party': 'နိုင်ငံရေးပါတီဝင်',
  'to be prepared': 'ပြင်ဆင်ပြီး',
  'to be put in order': 'စနစ်တကျ',
  'to be arranged': 'စီစဉ်ပြီး',
  'integer': 'ကိန်းပြည့်',
  'net (weight)': 'အသားတင်အလေး',
  'main gate': 'ဂိတ်ကြီး',
  'main entrance': 'ဝင်ပေါက်ကြီး',
  'clean copy': 'သန့်ရှင်းမိတ္တူ',
  '(1) to grow': 'ပေါက်',
  'to spring up': 'ပေါက်ထွက်',
  '(2) to cut (teeth)': 'သွားပေါက်',
  'vividly': 'ထင်ရှား',
  '(1) flower arrangement': 'ပန်းစီ',
  'impertinent': 'ရိုင်းစိုင်း',
  'saucy': 'ရဲရင့်ရိုင်း',
  'cheeky': 'ရိုင်း',
  'survival': 'ရှင်သန်',
  'increment': 'တိုး',
  'birth date': 'မွေးနေ့စွဲ',
  '(1) to serve (food': 'အစားတင်',
  '(2) to fill up': 'ဖြည့်',
  '(3) to prescribe': 'ဆေးညွှန်း',
  'Christian Era': 'ခရစ်နှစ်',
  'anno domini (A.D.)': 'အေဒီ',
  'to swear': 'ကျိန်ဆို',
  'to vow': 'ကတိ',
  'to take an oath': 'ကျိန်ကြား',
  'to pledge': 'ကတိပြု',
  'young person': 'လူငယ်',
  'pale': 'ဖြူဖျော့',
  'pallid': 'အရောင်မှိန်',
  'to quieten down': 'တိတ်ဆိတ်',
  'customs house': 'အကောက်ခွန်ရုံး',
  'disappointing': 'စိတ်ပျက်ဖွယ်',
  'soap': 'ဆပ်ပြာ',
  'to stack': 'ပုံ',
  'equator': 'အီကွေတာ',
  'getting closer': 'နီးလာ',
  'drawing nearer': 'ပိုနီး',
  'approaching': 'ချဉ်းကပ်',
  'with trouble': 'ခက်ခဲစွာ',
  'at great pains': 'အလွန်ကြိုးစား',
  'long-awaited': 'စောင့်မျှော်ကြာ',
  'constantly': 'အမြဲ',
  'pointed end': 'ထိပ်စွန်း',
  'fine point': 'အစွန်းသေး',
  'to forecast': 'ခန့်မှန်း',
  'to predict': 'ကြိုတင်ပြော',
  'propaganda': 'ဝါဒဖြန့်',
  'publicity': 'ပြန်ကြား',
  'autocracy': 'အာဏာရှင်စနစ်',
  'to taper to a point': 'ထိပ်သွယ်',
  'to become sharp': 'ထက်လာ',
  'to be sour': 'ချဉ်',
  'to look displeased': 'မကျေနပ်မျက်နှာ',
  'to fan': 'ယပ်ခတ်',
  'to flap': 'ခတ်',
  'electric fan': 'လျှပ်စစ်ပန်ကာ',
  'stopper': 'ပိတ်စ',
  'stopcock': 'ပိတ်ခလုတ်',
  'detergent': 'ဆပ်ပြာဆေး',
  'washing material': 'ဆေးကြောပစ္စည်း',
  '(1) to drive': 'မောင်း',
  '(2) to evade': 'ရှောင်',
  'to parch': 'လှော်',
  'envious': 'မနာလို',
  'enviable': 'မနာလိုဖွယ်',
  'to envy': 'မနာလိုဖြစ်',
  'surface mail (ship)': 'သင်္ဘောစာပို့',
  'around': 'ပတ်လည်',
  'front and back': 'ရှေ့နောက်',
  'before and behind': 'ရှေ့နှင့်နောက်',
  'complete works': 'စုစုပေါင်းလက်ရာ',
  'the whole body': 'ကိုယ်တစ်ခုလုံး',
  'full-length (portrait)': 'ကိုယ်လုံးပုံ',
  'novice': 'အသစ်သင်',
  'obedient': 'နာခံ',
  'meek': 'နူးညံ့',
  'docile': 'ယဉ်ကျေး',
  'unaffected': 'သဘာဝကျ',
  'to be resurrected': 'ပြန်ရှင်',
  'to be revived': 'ပြန်နိုး',
  'to be resuscitated': 'ပြန်အသက်ရှင်',
  'to be rehabilitated': 'ပြန်ထူထောင်',
  'to sweep': 'တံမြက်လှည်း',
  'to brush': 'ပွတ်',
  'to gather up': 'စု',
  'to perspire': 'ချွေးထွက်',
  'fast-talking': 'မြန်ပြော',
  'to argue': 'ငြင်းခုန်',
  'to be at variance': 'ကွဲလွဲ',
  'to compete': 'ယှဉ်ပြိုင်',
  'sumo wrestling': 'ဆူမို',
  'ticket window': 'လက်မှတ်ပြတင်း',
  'zoori (Japanese footwear)': 'ဇိုးရီ',
  'sandals': 'ဖိနပ်ပွင့်',
  'part of word written in kana': 'ကနာရေးအပိုင်း',
  'send-off': 'ပို့ဆောင်',
  'postage': 'စာပို့ခ',
  'increase and decrease': 'တိုးလျှော့',
  'fluctuation': 'အတက်အကျ',
  'odious': 'မုန်းစရာ',
  'shipbuilding': 'သင်္ဘောတည်ဆောက်',
  'surveying': 'တိုင်းတာ',
  'footprints': 'ခြေရာ',
  'tabi': 'တာဘိ',
  'Japanese socks (with split toe)': 'ဂျပန်ခြေအိတ်',
  'to belong to': 'ပိုင်ဆိုင်',
  'to come under': 'အောက်ကျ',
  'to be affiliated with': 'ဆက်နွှယ်',
  'to be subject to': 'လက်အောက်ခံ',
  'successively': 'ဆက်တိုက်',
  'one after another': 'တစ်ခုပြီးတစ်ခု',
  'to put things in order': 'စနစ်တကျထား',
  'to make uniform': 'တူညီအောင်လုပ်',
  'to get something ready': 'ပြင်ဆင်',
  '(hum) to know': 'သိ',
  'loss and gain': 'အရှုံးအမြတ်',
  'advantage and disadvantage': 'အကျိုးအပြစ်',
  'drum': 'ဗုံ',
  'tambourine': 'တမ်ဘူရင်း',
  'to deny': 'ငြင်း',
  'to negate': 'ပယ်',
  'ellipse': 'ဘဲဥပုံ',
  'physical exercises': 'ကိုယ်လက်လှုပ်ရှား',
  'calisthenics': 'ကိုယ်ကာယလေ့ကျင့်',
  'counter-plan': 'တန်ပြန်အစီအစဉ်',
  'counter-measure': 'တန်ပြန်အစီအမံ',
  'antithesis': 'ဆန့်ကျင်ဘက်',
  'to rendezvous': 'ချိန်းတွေ့',
  'to meet at a prearranged place and time': 'ကြိုချိန်းတွေ့',
  'to be off guard': 'မသတိထား',
  'to be feeling better': 'ခံစားချက်ပိုကောင်း',
  'loaning': 'ချေးငှား',
  'house for rent': 'ငှားအိမ်',
  'room to let': 'ငှားခန်း',
  'to dislodge': 'ဖယ်ရှား',
  'to put something out of the way': 'လမ်းရှင်း',
  'leaving hospital': 'ဆေးရုံဆင်း',
  '(v5r': 'ကြိယာ',
  'vi) to take the place of': 'အစားထိုး',
  'to be substituted for': 'အစားခံ',
  'pronoun': 'နာမ်စား',
  '(not so) much': 'သိပ်မ',
  'graduate school': 'ဘွဲ့လွန်ကျောင်း',
  'very fine': 'အလွန်ကောင်း',
  'main street': 'လမ်းမကြီး',
  'large tree': 'သစ်ပင်ကြီး',
  'to become muddy': 'နောက်ကျိ',
  'to get impure': 'ညစ်လာ',
  'derailment': 'လမ်းချော်',
  'digression': 'ခေါင်းစဉ်လွဲ',
  'singular (number)': 'တစ်ခုတည်းကိန်း',
  'to shoulder': 'ပခုံးထမ်း',
  'fresh water': 'ရေချို',
  'coal mine': 'ကျောက်မီးသွေးတွင်း',
  'coal pit': 'ကျောက်မီးသွေးတွင်း',
  'short term': 'ကာလတို',
  '(1) defect': 'ချို့ယွင်း',
  'demerit': 'အားနည်းချက်',
  '(2) disadvantage': 'အားနည်းချက်',
  'short (e.g. story': 'တို',
  'film)': 'ရုပ်ရှင်',
  'multi-unit apartments': 'တိုက်ခန်းများ',
  'water outage': 'ရေပြတ်',
  'to warm up': 'နွေးအောင်လုပ်',
  'to get warm': 'နွေးလာ',
  'underground water': 'မြေအောက်ရေ',
  'geological features': 'ဘူမိလက္ခဏာ',
  'point on a map': 'မြေပုံအမှတ်',
  '(the) ground': 'မြေပြင်',
  'place name': 'နေရာအမည်',
  'middle (of a three-tier ranking system)': 'အလယ်အဆင့်',
  '(1) to attach': 'တွဲ',
  'to put on clothes': 'အဝတ်ဝတ်',
  'changing clothes': 'အဝတ်လဲ',
  'change of clothes': 'အဝတ်အစားလဲ',
  'second third of a month': 'လ၏ဒုတိယဆယ်ရက်',
  'Middle Ages': 'အလယ်ခေတ်',
  'mediaeval times': 'အလယ်ခေတ်',
  'neuter gender': 'လိင်မဲ့',
  'neutral (chem.)': 'ကြားနေ',
  'sterility': 'မျိုးမပွားနိုင်',
  'in the middle': 'အလယ်တွင်',
  'half-way': 'တစ်ဝက်လမ်း',
  'middle-aged': 'လူလတ်ပိုင်း',
  'reconciliation': 'ပြန်လည်သင့်မြတ်',
  'make peace with': 'ငြိမ်းချမ်း',
  'intimate friend': 'ရင်းနှီးသူငယ်ချင်း',
  'bosom buddy': 'ရင်းနှီးသူ',
  'chum': 'သူငယ်ချင်း',
  'abstract': 'စိတ္တဇ',
  'nap (at home)': 'နေ့အိပ်',
  'siesta': 'နေ့အိပ်',
  'to pour (drink)': 'လောင်း',
  'to serve (drinks)': 'သောက်စရာလောင်း',
  'to be in high spirits': 'စိတ်အားတက်',
  'to be full of vigor': 'အားပြည့်',
  'to sculpture': 'ရုပ်ထုထွင်း',
  'to chisel': 'ထွင်း',
  'carving': 'ထွင်းထု',
  'engraving': 'ထွင်းရေး',
  'sculpture': 'ရုပ်ထု',
  'condiment': 'ဟင်းခတ်',
  'being more than': 'ပိုနေ',
  'to jump': 'ခုန်',
  'to leap': 'ခုန်တက်',
  'to drag on': 'ဆွဲငင်ရှည်',
  '(1) strong point': 'အားသာချက်',
  '(2) advantage': 'အကျိုး',
  'eldest daughter': 'သမီးအကြီး',
  'eldest son': 'သားအကြီး',
  'rectangle': 'စတုဂံ',
  'oblong': 'ရှည်စတုဂံ',
  'right angle': 'ထောင့်မှန်',
  'immediately following': 'ချက်ချင်းနောက်',
  'straight line': 'မျဉ်းဖြောင့်',
  'just before': 'မတိုင်မီချက်ချင်း',
  'direct communication': 'တိုက်ရိုက်ဆက်သွယ်',
  'direct current': 'တိုက်ရိုက်လျှပ်စီး',
  'to pass (e.g. car)': 'ကျော်',
  'to outdistance': 'ကျော်တက်',
  'to chase or run after someone': 'လိုက်ဖမ်း',
  'to run down': 'လိုက်ရောက်',
  'to pursue': 'လိုက်လံ',
  'currency': 'ငွေကြေး',
  'commuting to work': 'အလုပ်သွားလာ',
  'notification': 'အကြောင်းကြား',
  'passbook': 'စာအုပ်ကတ်',
  'interpretation': 'ဘာသာပြန်',
  'popular use': 'အများသုံး',
  'pathway': 'လမ်းကြောင်း',
  'to be smashed': 'ကြေမွ',
  'to go bankrupt': 'ဒေဝါလီခံ',
  'fingernail or toenail': 'လက်သည်းခြေသည်း',
  'claw': 'ခြေသည်း',
  'talon': 'တောင်ပံသည်း',
  'hoof': 'ခွာ',
  'stopping (e.g. train)': 'ရပ်',
  'failure of electricity': 'လျှပ်စစ်ပြတ်',
  'razor': 'ရိတ်ဓား',
  'fixed number of regular personnel': 'ပုံမှန်ဝန်ထမ်းအရေ',
  'capacity (of boat': 'လှေစွမ်းရည်',
  'established price': 'သတ်မှတ်ဈေး',
  'commuter pass': 'အလုပ်သွားလက်မှတ်',
  'season ticket': 'ရာသီလက်မှတ်',
  '(measuring) ruler': 'ပေတံ',
  'regular holiday': 'ပုံမှန်အားလပ်ရက်',
  'to shut up': 'ပိတ်ထား',
  'nail': 'လက်သည်း',
  'railway bridge': 'ရထားတံတား',
  'iron bridge': 'သံတံတား',
  'to be collected': 'စုမိ',
  'to be settled': 'အဆုံးသတ်',
  'to bring to a conclusion': 'နိဂုံးချုပ်',
  'to tumble': 'လိမ့်',
  'to catch fire': 'မီးစွဲ',
  '(electricity) comes on': 'လျှပ်စစ်လာ',
  'marks': 'အမှတ်',
  'points': 'အမှတ်များ',
  'to be handed down': 'လက်ဆင့်ကမ်း',
  'to be introduced': 'မိတ်ဆက်ခံရ',
  'to be transmitted': 'ထုတ်လွှင့်ခံရ',
  'biography': 'အတ္ထုပ္ပတ္တိ',
  'life story': 'ဘဝဇာတ်ကြောင်း',
  'rice planting': 'စပါးစိုက်',
  'light bulb': 'မီးသီး',
  'telephone pole': 'ဖုန်းတိုင်',
  'telegraph pole': 'ကြေးနန်းတိုင်',
  'lightpole': 'မီးတိုင်',
  'electro-magnetic wave': 'လျှပ်စစ်သံလိုက်လှိုင်း',
  'electric current': 'လျှပ်စီး',
  'electric power': 'လျှပ်စစ်စွမ်းအား',
  'nausea': 'ပျို့အန်ချင်',
  'sickness in the stomach': 'ဗိုက်မအီမသာ',
  'entry (on stage)': 'ဇာတ်ခုံဝင်',
  'heart (of city)': 'မြို့ဗဟို',
  'to be chilled': 'အေးခဲ',
  'to be frozen': 'အေးခဲ',
  'letter to the editor': 'အယ်ဒီတာသို့စာ',
  'letter from a reader': 'စာဖတ်သူစာ',
  'East and West': 'အရှေ့အနောက်',
  'Orient': 'အရှေ့တိုင်း',
  'theft': 'ခိုးမှု',
  'teacup': 'လက်ဖက်ရည်ခွက်',
  'lighthouse': 'မီးပြတိုက်',
  'lamp oil': 'ဆီမီးဆီ',
  'kerosene': 'ကေရိုဆင်း',
  'very day': 'နေ့တိုင်း',
  'being on duty': 'တာဝန်ကျ',
  'division into equal parts': 'ညီမျှခွဲ',
  'unity': 'ညီညွတ်မှု',
  'a scatter': 'ကြဲဖြန့်',
  'railway crossing': 'ရထားလမ်းဖြတ်',
  'level crossing': 'လမ်းဖြတ်',
  'starting line': 'စတင်မျဉ်း',
  'to be(come) transparent': 'ကြည်လင်',
  'transparency': 'ကြည်လင်မှု',
  'cleanness': 'သန့်ရှင်းမှု',
  'movements': 'လှုပ်ရှားမှုများ',
  'motions': 'လှုပ်ရှားမှု',
  'bearing': 'ဟန်ထား',
  'the same rank': 'အဆင့်တူ',
  'apposition': 'တွဲဖက်',
  'to long for': 'တမ်းတ',
  'to yearn after': 'လွမ်းဆွတ်',
  'to admire': 'ချီးမွမ်း',
  'fairy tale': 'ပုံပြင်',
  'itinerary': 'ခရီးစဉ်',
  '(mountain) pass': 'တောင်ကြားလမ်း',
  'difficult part': 'ခက်ခဲသောအပိုင်း',
  'forte': 'အားသာချက်',
  'special sale': 'အထူးလျှော့ဈေး',
  'a soliloquy': 'တစ်ယောက်တည်းပြော',
  'a monologue': 'တစ်ယောက်တည်းစကား',
  'speaking to oneself': 'ကိုယ်နှင့်ပြော',
  'unevenness': 'မညီညာ',
  'roughness': 'ကြမ်းတမ်း',
  'ruggedness': 'ကြမ်းခက်',
  'end (e.g. of street)': 'လမ်းဆုံး',
  '(1) to thrust': 'ထိုး',
  '(2) to poke': 'ထိုးနှစ်',
  'to go into deeply': 'နက်နက်ဝင်',
  'optimistic': 'အကောင်းမြင်',
  'dull (e.g. a knife)': 'တုံး',
  'thickheaded': 'ထုံထိုင်း',
  'slow (opposite of fast)': 'နှေး',
  'internist clinic': 'အတွင်းဆေးခန်း',
  'internal medicine': 'အတွင်းဆေး',
  'phone extension': 'ဖုန်းတိုးချဲ့',
  'indoor wiring': 'အတွင်းဝါယာ',
  'inner line': 'အတွင်းလိုင်း',
  'to become domesticated': 'ယဉ်ပါး',
  'to become tame': 'ယဉ်',
  'south pole': 'တောင်ဝင်ရိုးစွန်း',
  'Antarctic': 'အန္တာတိက',
  'South America': 'တောင်အမေရိက',
  'south and north': 'တောင်နှင့်မြောက်',
  'to be fragrant': 'မွှေး',
  'to stink': 'နံ့ဆိုး',
  'sunrise': 'နေထွက်',
  'daily lesson': 'နေ့စဉ်သင်ခန်းစာ',
  'daily work': 'နေ့စဉ်အလုပ်',
  'daily routine': 'နေ့စဉ်လုပ်ရိုး',
  'day trip': 'တစ်နေ့ခရီး',
  'date and time': 'နေ့နှင့်အချိန်',
  'exposure to the sun': 'နေရောင်ခံ',
  'daily necessities': 'နေ့စဉ်လိုအပ်ချက်',
  'entry to a company': 'ကုမ္ပဏီဝင်',
  'to heat': 'အပူပေး',
  'to turn (a switch) on or off': 'ခလုတ်ဖွင့်ပိတ်',
  'to puzzle over': 'တွေးမရ',
  'agricultural produce': 'စိုက်ပျိုးထွက်ကုန်',
  'agricultural community': 'စိုက်ပျိုးအသိုင်းအဝိုင်း',
  'farm village': 'ကျေးရွာ',
  'rural': 'ကျေးလက်',
  'agricultural chemicals': 'စိုက်ပျိုးဓာတု',
  'to peep in': 'လှမ်းကြည့်',
  'to look in': 'ကြည့်ဝင်',
  'to peek in': 'လှမ်းကြည့်',
  'to stick out': 'ထွက်နေ',
  'loud': 'ကျယ်လောင်',
  'flashy': 'ထင်ရှားရောင်',
  'to get torn': 'စုတ်ပြဲ',
  'to wear out': 'စားသုံးပျက်',
  'broken piece': 'အပိုင်းအစ',
  'haiku poetry': 'ဟိုင်ကူကဗျာ',
  'to worship': 'ကိုးကွယ်',
  'to beg': 'တောင်းပန်',
  'to make a supplication': 'ဆုတောင်း',
  'to deliver': 'ပို့ဆောင်',
  'sold-out': 'ရောင်းကုန်',
  'to be sold out': 'ရောင်းကုန်ပြီ',
  'amount sold': 'ရောင်းရငွေ',
  'to creep': 'တွား',
  'to crawl': 'တွားသွား',
  'scales': 'ချိန်ခွင်',
  'weighing machine': 'ချိန်စက်',
  '(hon) aunt': 'အဒေါ်',
  'to peel': 'အခွံခွာ',
  'to skin': 'အရေခွာ',
  'to pare': 'ခုတ်ဖြတ်',
  'to hull': 'အခွံဖယ်',
  '(v5s) to tear off': 'ဆုတ်ခွာ',
  'to give shelter to': 'ခိုလှုံခွင့်ပေး',
  'to lodge': 'တည်းခို',
  'white or grey hair': 'ဆံပင်ဖြူ',
  'trendy hair bleaching': 'ဆံပင်ချွတ်',
  'to dilute': 'ရော',
  'to water down': 'ရေရော',
  'a bowl': 'ပန်းကန်',
  'a pot': 'အိုး',
  'expression (music)': 'ဂီတဖော်ပြချက်',
  'conceptualization': 'သဘောတရားဖော်',
  'generation (e.g. power)': 'ဓာတ်အားထုတ်',
  'seal (used for signature)': 'တံဆိပ်',
  'radius': 'အချင်းဝက်',
  'peninsula': 'ကျွန်းဆွယ်',
  'to be warped': 'ကွေး',
  'to curve': 'ကောက်',
  'cynicism': 'ကဲ့ရဲ့',
  'sarcasm': 'သရော်',
  'to cover (with something)': 'ဖုံး',
  'to jump in': 'ခုန်ဝင်',
  'to leap in': 'ခုန်ဝင်',
  'to dive': 'ရေငုပ်',
  'beauty of figure or form': 'ပုံသဏ္ဌာန်လှ',
  'elbow': 'တံတောင်',
  'necessities': 'လိုအပ်ချက်များ',
  'necessary article': 'လိုအပ်ပစ္စည်း',
  'requisite': 'မရှိမဖြစ်',
  '(taking) notes': 'မှတ်စုရေး',
  'front cover': 'အဖုံး',
  'binding': 'ချုပ်တုပ်',
  'critique': 'ဝေဖန်ချက်',
  'bottling': 'ပုလင်းထည့်',
  'bottled': 'ပုလင်းထည့်ပြီး',
  'unlucky': 'ကံဆိုး',
  'unsteadiness': 'မတည်ငြိမ်',
  'disorderly': 'ရှုပ်ထွေး',
  'man and wife': 'ဇနီးမောင်နှံ',
  'to spread out': 'ဖြန့်',
  'to lay out': 'ခင်း',
  'to look (sad': 'ကြည့်',
  'glad)': 'ဝမ်းသာ',
  'to become merry': 'ပျော်ရွှင်',
  'to brush gently': 'ညင်သာပွတ်',
  'to stroke': 'သုံးသပ်',
  'radical (of a kanji character)': 'ကန်ဂျိအစိတ်',
  'accessories': 'အသုံးအဆောင်များ',
  'balloon': 'ပူဖောင်း',
  'wrapping cloth': 'ထုပ်အဝတ်',
  'cloth wrapper': 'ထုပ်စ',
  'adverb': 'ကြိယာဝိသေသန',
  'plural': 'ဗဟု',
  'multiple': 'မျိုးစုံ',
  'to pay in': 'ပေးသွင်း',
  'to repay': 'ပြန်ဆပ်',
  'to pay back': 'ပြန်ပေး',
  'earth-shattering': 'ကမ္ဘာလှုပ်',
  'staggering': 'အံ့ဩဖွယ်',
  'to a very great extent': 'အလွန်ကြီးမား',
  'storage room': 'သိုလှောင်ခန်း',
  'to branch off': 'ခွဲထွက်',
  'to diverge from': 'ကွဲထွက်',
  'to fork': 'ခွဲ',
  'disassembly': 'ဖြုတ်သိမ်း',
  'fraction (in math)': 'အပိုင်းကိန်း',
  'water fountain': 'ရေထွက်ပန်း',
  'literary style': 'စာပေစတိုင်',
  'context': 'အကြောင်းအရာ',
  'hiragana': 'ဟီရာဂန',
  '47 syllables': '၄၇ သရသံ',
  'the cursive syllabary': 'ကောက်စာလုံး',
  'calmness': 'ငြိမ်သက်',
  'unconcern': 'မစိုးရိမ်',
  'roadside tree': 'လမ်းဘေးပင်',
  'row of trees': 'ပင်တန်း',
  'individually': 'တစ်ဦးချင်း',
  'holiday house': 'အားလပ်အိမ်',
  'katakana': 'ကတာကန',
  'one-way (trip)': 'တစ်လမ်း',
  'to dispose of': 'စွန့်ပစ်',
  'to solve': 'ဖြေရှင်း',
  'to knit': 'ရက်',
  'editing': 'တည်းဖြတ်',
  'editorial (e.g. committee)': 'အယ်ဒီတာအဖွဲ့',
  'knitting': 'ရက်လုပ်',
  'web': 'ပိုက်ကွန်',
  'writing paper': 'စာရေးစက္ကူ',
  'hygiene': 'ကျန်းမာရေး',
  'sanitation': 'သန့်ရှင်းရေး',
  'to compensate for': 'လျော်ကြေး',
  'recruiting': 'စုဆောင်း',
  'taking applications': 'လျှောက်လွှာခံ',
  'to emulate': 'တုပ',
  'wrapping': 'ထုပ်ပိုး',
  'bandage': 'ပတ်တီး',
  'dressing': 'ဒဏ်ရာစည်း',
  'to pull down': 'ဆွဲချ',
  'to make change (money)': 'ငွေလဲ',
  'to collapse': 'ပြိုကျ',
  'to crumble': 'ပြို',
  'kitchen knife': 'မီးဖိုချောင်ဓား',
  'carving knife': 'ထွင်းဓား',
  'to let go': 'လွှတ်',
  'dialect': 'ဒေသိယစကား',
  'to sew': 'ချုပ်',
  'to the end': 'အဆုံးထိ',
  'to the last': 'နောက်ဆုံးထိ',
  'stubbornly': 'ဇွဲကြီး',
  'to prevent': 'ကာကွယ်',
  'to act violently': 'အကြမ်းဖက်',
  'to rage': 'ဒေါသထွက်',
  'to be riotous': 'ဆူပူ',
  'telescope': 'မှန်ဘီလူး',
  'to swell': 'ဖောင်း',
  'to inflate': 'လေမှုတ်',
  'to bulge': 'ဖောင်းထွက်',
  'to get big': 'ကြီးလာ',
  'to become inflated': 'ဖောင်းလာ',
  'bulky': 'ထုထည်ကြီး',
  'prevention of crime': 'ရာဇဝတ်ကာကွယ်',
  'North Pole': 'မြောက်ဝင်ရိုးစွန်း',
  '(1) farm (livestock)': 'မွေးမြူခြံ',
  '(2) pasture land': 'ကျက်စားမြေ',
  'meadow': 'မြက်ခင်း',
  'grazing land': 'ကျက်စားမြေ',
  'stock-farming': 'မွေးမြူရေး',
  'headquarters': 'ဌာနချုပ်',
  'Lantern Festival': 'မီးအိမ်ပွဲ',
  'Festival of the Dead': 'သေသူပွဲ',
  'basin (e.g. between mountains)': 'ချိုင့်ဝှမ်း',
  'friction': 'ပွတ်တိုက်မှု',
  'rubbing': 'ပွတ်',
  'rubdown': 'ပွတ်သုတ်',
  'to fill up': 'ဖြည့်',
  'to fill (a seat': 'ထိုင်ခုံဖြည့်',
  'a vacant position)': 'နေရာလစ်',
  'the number of flat things': 'ပြားချပ်ရေတွက်',
  'each time': 'အကြိမ်တိုင်း',
  'common service-sector greeting': 'ဝန်ဆောင်နှုတ်ဆက်',
  'pillow': 'ခေါင်းအုံး',
  'bolster': 'ခေါင်းအုံး',
  'youngest child': 'သားသမီးအငယ်ဆုံး',
  'hurrah': 'ဟားရာ',
  'cheers': 'ကျန်းမာရေးအတွက်',
  'full house': 'ပြည့်',
  'no vacancy': 'နေရာမရှိ',
  'sold out': 'ရောင်းကုန်',
  'perfect score': 'အမှတ်ပြည့်',
  'cape (on coast)': 'ကမ်းစွန်း',
  'folk song': 'ရိုးရာသီချင်း',
  'popular song': 'လူကြိုက်များသီချင်း',
  'infinite': 'အဆုံးမရှိ',
  'neglecting to stay in contact': 'ဆက်သွယ်မေ့',
  'countless number': 'ရေမတွက်နိုင်',
  'infinite number': 'အဆုံးမရှိအရေ',
  'contradiction': 'ဆန့်ကျင်မှု',
  'inconsistency': 'မကိုက်ညီ',
  'business card': 'နာမည်ကတ်',
  'noun': 'နာမ်',
  'famous place': 'နာမည်ကြီးနေရာ',
  'famous product': 'နာမည်ကြီးထုတ်ကုန်',
  'speciality': 'အထူးထုတ်ကုန်',
  'to command': 'အမိန့်ပေး',
  'superstition': 'အယူသီး',
  'niece': 'တူမ',
  'tax exemption': 'အခွန်ကင်းလွတ်',
  'duty exemption': 'အခွန်ကင်း',
  'bother to do': 'လုပ်ရခက်',
  'tiresome': 'ပင်ပန်း',
  'to grow thick': 'ထူထပ်ပေါက်',
  'to luxuriate': 'စည်ပင်',
  'to be luxurious': 'ဇိမ်ခံ',
  'knitting wool': 'ရက်သိုးမွေး',
  'to be profitable': 'အမြတ်ရ',
  'to yield a profit': 'အမြတ်ထွက်',
  'criterion': 'စံနှုန်း',
  'landmark': 'မှတ်တိုင်',
  '(abbr) alarm-clock': 'နှိုးစက်',
  'to have an eye on': 'မျက်စိထား',
  'table of contents': 'မာတိကာ',
  'to be conspicuous': 'ထင်ရှား',
  'to stand out': 'ပေါ်လွင်',
  'sticky rice cake': 'ကောက်ညှင်းမုန့်',
  'questions and answers': 'မေးဖြေ',
  'dialogue': 'ဆွေးနွေး',
  'at night': 'ညတွင်',
  'nighttime': 'ညအချိန်',
  'directing arrow': 'ဦးတည်မြှား',
  'public office': 'အစိုးရရုံး',
  'government official': 'အစိုးရအရာရှိ',
  'pharmacy': 'ဆေးဆိုင်',
  'drugstore': 'ဆေးဆိုင်',
  'ring finger': 'လက်မူချောင်း',
  'medicine(s)': 'ဆေးများ',
  'chemical(s)': 'ဓာတုပစ္စည်းများ',
  'to translate': 'ဘာသာပြန်',
  'blood transfusion': 'သွေးသွင်း',
  'brave': 'ရဲရင့်',
  'valiant': 'ရဲရင့်',
  'gallant': 'ရဲရင့်',
  'courageous': 'သတ္တိရှိ',
  'grateful': 'ကျေးဇူးတင်',
  'thankful': 'ကျေးဇူးတင်',
  'appreciated': 'ကျေးဇူးတင်ဖွယ်',
  'yes or no': 'ဟုတ်မဟုတ်',
  'flag indicator (comp)': 'အလံညွှန်း',
  'presence or absence marker': 'ရှိမရှိအမှတ်',
  'admission-paid': 'ဝင်ကြေးပေး',
  'amusement park': 'ပျော်ပွဲဥယျာဉ်',
  'mailing': 'စာပို့',
  'evening paper': 'ညနေစာရွက်',
  '(in) the evening sun': 'ညနေနေရောင်',
  'setting sun': 'နေဝင်',
  '(sudden) evening shower (rain)': 'ညနေမိုးသက်',
  'too much': 'အလွန်များ',
  'unnecessary': 'မလိုအပ်',
  'another place': 'အခြားနေရာ',
  'somewhere else': 'တစ်နေရာရာ',
  'strange parts': 'ထူးဆန်းဒေသ',
  'to keep in custody': 'ထိန်းသိမ်း',
  'to receive on deposit': 'အပ်နှံခံ',
  'infantile': 'ကလေးဆန်',
  'kindergarten': 'မူကြို',
  'to lift': 'မြှောက်',
  'shop which handles Western-style apparel and accessories': 'အနောက်တိုင်းအဝတ်ဆိုင်',
  'to dissolve (paint)': 'ပျော်ဝေ',
  'to thaw': 'အရည်ပျော်',
  'to fuse': 'ပေါင်းစပ်',
  'to melt into': 'ပျော်ဝင်',
  'lava': 'ချော်ရည်',
  'terminology': 'အသုံးအနှုန်း',
  'essentials': 'အခြေခံလိုအပ်',
  'fundamentals': 'အခြေခံ',
  'rays of the sun': 'နေရောင်ခြည်',
  'nutrient': 'အာဟာရ',
  'avarice': 'လောဘ',
  'bathrobe': 'ရေချိုးဝတ်',
  'informal summer kimono': 'နွေရာသီကီမိုနို',
  'yukata': 'ယုကတာ',
  'arrival in Japan': 'ဂျပန်ရောက်',
  'coming to Japan': 'ဂျပန်လာ',
  'visit to Japan': 'ဂျပန်လည်',
  'reliable': 'ယုံကြည်ရ',
  'trustworthy': 'ယုံကြည်ရ',
  'hopeful': 'မျှော်လင့်ဖွယ်',
  'lost property': 'ပစ္စည်းပျောက်',
  'to settle down': 'အခြေချ',
  'lawless': 'ဥပဒေမဲ့',
  'column of text (e.g. as in a newspaper)': 'စာတိုင်',
  'backdoor': 'နောက်တံခါး',
  'rear entrance': 'နောက်ဝင်ပေါက်',
  'to turn inside out': 'ပြောင်းပြန်လှန်',
  'to turn (something) over': 'လှန်',
  'to abbreviate': 'အတိုကောက်',
  '(river) basin': 'မြစ်ဝှမ်း',
  'to thrive': 'စည်ပင်',
  'to come into fashion': 'ဖက်ရှင်ဖြစ်',
  'to amass': 'စုဆောင်း',
  'to accumulate': 'စု',
  'a sigh': 'ညည်းတွား',
  '(1) to be fixed': 'တည်ငြိမ်',
  '(2) to abide': 'နေ',
  'to stay (in the one place)': 'တစ်နေရာတည်းနေ',
  'care-taking': 'စောင့်ရှောက်',
  'caretaker': 'စောင့်ရှောက်သူ',
  'house-watching': 'အိမ်စောင့်',
  'to cool oneself': 'အေးအောင်နေ',
  'to cool off': 'အေးလာ',
  'to enjoy evening cool': 'ညအေးခံစား',
  'consul': 'ကောင်စစ်ဝန်',
  'emboldened': 'သတ္တိတက်',
  'to become cool': 'အေးလာ',
  'to wear off': 'လျော့ပျောက်',
  'freezing': 'အေးခဲ',
  'chain of islands': 'ကျွန်းဆွဲကြိုး',
  '(1) dear': 'ချစ်ခင်',
  'beloved': 'ချစ်ရ',
  'darling': 'ချစ်သူ',
  '(2) yearned for': 'တမ်းတ',
  'brick': 'အုတ်ခဲ',
  'cheerfulness': 'ရွှင်လန်း',
  'melodious': 'သံစဉ်ညှိ',
  'candle': 'ဖယောင်းတိုင်',
  '(audio) recording': 'အသံဖမ်း',
  'Japanese-English': 'ဂျပန်-အင်္ဂလိပ်',
  'Japanese clothes': 'ဂျပန်အဝတ်',
  'to accost a person': 'စကားစမြည်ဆို',
  'to talk (to someone)': 'စကားပြော',
  'while talking': 'စကားပြောရင်း',
  'the line is busy': 'လိုင်းမအား',
  'Japanese soup bowl': 'ဂျပန်ဟင်းခွက်',
  'wooden bowl': 'သစ်သားခွက်',
  'porcelain bowl': 'ကြွေခွက်',
  'bowl of rice with food on top': 'ထမင်းပေါ်ဟင်း',
  'to sniff': 'နမ်းရှူ',
  'to whisper': 'တီးတိုး',
  'to crumple (up)': 'ချုံ့',
  'to wrinkle': 'တွန့်',
  'pun': 'စကားလုံးကစား',
  'witticism': 'ဟာသစကား',
  'sly': 'လှည့်ဖြား',
  'to glare at': 'စိုက်ကြည့်',
  'to scowl at': 'မျက်နှာကြုတ်',
  'to keep an eye on': 'စောင့်ကြည့်',
  '(n) broom': 'တံမြက်စည်း',
  'accelerator': 'အရှိန်မြှင့်',
  '1.  gaudy': 'ရောင်စုံ',
  '2.  vicious': 'ဆိုးယုတ်',
  'to sneer at': 'သရော်',
  'to ridicule': 'ပြက်ရယ်',
  'easily': 'လွယ်ကူ',
  'readily': 'ချက်ချင်း',
  'approach (in golf)': 'ဂေါက်ချဉ်းကပ်',
  'contrary': 'ဆန့်ကျင်',
  'inverse': 'ပြောင်းပြန်',
  'uncertain': 'မသေချာ',
  'oh': 'အို',
  'ah': 'အာ',
  'saw-edged perch (Niphon spinosus)': 'လွှသွားငါး',
  'Arab': 'အာရပ်',
  'kind of cookie': 'ကွတ်ကီးအမျိုး',
  'cartoon character': 'ကာတွန်းဇာတ်ကောင်',
  'alkali': 'အယ်ကာလီ',
  'aluminum (Al)': 'အလူမီနီယမ်',
  'aluminium': 'အလူမီနီယမ်',
  '(fr:) (n) questionnaire (fr: enquete)': 'မေးခွန်းလွှာ',
  'encore': 'အန်ကော',
  'sooner': 'ပိုမြန်',
  'might as well': 'လုပ်လိုက်',
  'awfully': 'အလွန်',
  'terribly': 'ပြင်းထန်',
  'intercom': 'အင်တာကွမ်',
  'egghead': 'ဉာဏ်ကြီးရှင်',
  'intelligentsia': 'ဉာဏ်ပညာအလွှာ',
  'inflation': 'ငွေကြေးဖောင်းပွ',
  'air mail': 'လေကြောင်းစာပို့',
  'ray (fish)': 'ငါးမန်းမျိုး',
  'hey!': 'ဟေး',
  'OK': 'အိုကေ',
  'coweringly': 'ကြောက်ရွံ့',
  'hesitantly': 'တွန့်ဆုတ်',
  'orientation': 'ဦးတည်ချက်',
  'an orange': 'လိမ္မော်',
  'on-line': 'အွန်လိုင်း',
  '(your) backing': 'ထောက်ခံမှု',
  'attendant': 'အကူအညီ',
  '(giving) birth': 'မွေးဖွား',
  'Excuse me for disturbing (interrupting) you': 'နှောင့်ယှက်ခွင့်တောင်း',
  'all over': 'အနှံ့',
  'given in': 'အရှုံးပေး',
  'given up hope': 'မျှော်လင့်ချက်စွန့်',
  'bring to knees': 'ဒူးထောက်အောင်',
  'policeman (friendly term)': 'ရဲသား',
  'Good morning': 'မင်္ဂလာနံနက်ခင်း',
  '1.  (uk) between meal snack': 'ကြားနာမုန့်',
  'afternoon tea': 'နေ့လယ်လက်ဖက်',
  '2.  mid-day snack': 'နေ့လယ်စာလေး',
  '(ateji) (int) (uk) Congratulations!': 'ဂုဏ်ယူပါ၏',
  'diaper': 'ဒိုင်ပါ',
  'nappy': 'ကလေးအနှီး',
  'tour guide': 'ခရီးလမ်းညွှန်',
  'cocktail': 'ကော့တေး',
  'heartbroken': 'နှလုံးကွဲ',
  'solidly built': 'ခိုင်ခံ့ကိုယ်ထည်',
  'shrewd': 'ဉာဏ်ရှိ',
  'calculating': 'တွက်ချက်တတ်',
  'category': 'အမျိုးအစား',
  'comeback': 'ပြန်လာ',
  'cameraman': 'ဓာတ်ပုံဆရာ',
  'feel': 'ခံစားချက်',
  '(de:) (n) clinical records (de: Karte)': 'ဆေးမှတ်တမ်း',
  'garage (at house)': 'အိမ်ဂိုဒေါင်',
  'career government employee': 'အသက်မွေးဝန်ထမ်း',
  'quiz': 'ပဟေဠိ',
  'club': 'ကလပ်',
  'crab': 'ကဏန်း',
  'being disheartened': 'စိတ်ဓာတ်ကျ',
  'losing weight': 'ကိုယ်အလေးကျ',
  'to fuss over': 'ဂရုစိုက်',
  'to be particular about': 'အသေးစိတ်ဂရု',
  'to be concerned about': 'စိုးရိမ်',
  'a commercial': 'ကြော်ငြာ',
  'contest': 'ပြိုင်ပွဲ',
  'compass': 'သံလိုက်အိမ်မြှောင်',
  'to be truant': 'ကျောင်းရှောင်',
  'to sabotage by slowness': 'နှေးနှေးဖျက်ဆီး',
  'Mr or Mrs': 'ဦး/ဒေါ်',
  'Santa Claus': 'ဆန်တာကလော့စ်',
  '10^24 (kanji is JIS X 0212 kuten 4906)': '၁၀²⁴',
  'septillion (American)': 'ဆက်တီလျံ',
  'quadrillion (British)': 'ကွာဒရီလျံ',
  'jeans (lit: jeans pants)': 'ဂျင်းဘောင်းဘီ',
  'dungarees': 'အလုပ်ဘောင်းဘီ',
  'chic': 'ခေတ်မီ',
  'deliberately': 'ရည်ရွယ်ချက်ရှိ',
  'carefully': 'ဂရုတစိုက်',
  'jazz': 'ဂျက်ဇ်',
  'jump': 'ခုန်',
  'jumbo': 'ဂျမ်ဘို',
  'genre': 'အမျိုးအစား',
  'rock-scissors-paper game': 'ကျောက်ကတ်စက္ကူ',
  'show': 'ရှိုး',
  'studio': 'စတူဒီယို',
  'stroboscope (lit: strobo)': 'စထရိုဘို',
  'strobe lamp': 'စထရိုမီး',
  'stroboscopic lamp': 'စထရိုမီးခွက်',
  'decisively': 'ပြတ်သား',
  'decidedly': 'ပြတ်သား',
  'once and for all': 'တစ်ခါတည်း',
  'unreservedly': 'မချန်ထား',
  'soaked': 'စိုရွှဲ',
  'dripping wet': 'စိုရွှဲ',
  'sports car': 'အားကစားကား',
  'slacks': 'ဘောင်းဘီရှည်',
  'in a line': 'တန်းစီ',
  'in a row': 'တန်းတူ',
  'sound or act of dragging': 'ဆွဲသံ',
  'inconclusive but unwanted situation': 'မလိုလားအခြေအနေ',
  'trailingly': 'ဆွဲငင်',
  'slippage': 'ချော်မှု',
  'to miss each other': 'လွဲချော်',
  'pass with no objection': 'ကန့်ကွက်မရှိ',
  'sexual intercourse': 'လိင်ဆက်ဆံ',
  '1.  jelly': 'ဂျယ်လီ',
  '2.  Jerry': 'ဂျယ်ရီ',
  'good sense (for music  style  tact  etc.)': 'အရသာကောင်း',
  'solo': 'တစ်ဦးတည်း',
  'dozen': 'ဒါဇင်',
  'typist': 'စာရိုက်သူ',
  'timer': 'အချိန်တိုင်း',
  'timing': 'အချိန်ကိုက်',
  'timely': 'အချိန်မှန်',
  'run-batted-in (baseball)': 'ရိုက်မှတ်',
  'RBI': 'အာဘီအိုင်',
  'tile': 'ကြွေပြား',
  'to coincide (fall on the same day)': 'တစ်နေ့တည်းကျ',
  'to have two of something': 'နှစ်ခုရှိ',
  'to repeat a school year after failing': 'နှစ်ကျော့တက်',
  'implying (negatively) that something is full of  e.g. mistakes': 'အမှားများပြည့်',
  'dump': 'အမှိုက်ပုံ',
  'teamwork': 'အဖွဲ့လိုက်လုပ်',
  'chime': 'ခေါင်းလောင်း',
  'pamper': 'ချော့မော့',
  'make a fuss of': 'ချော့',
  'spoil': 'ပျက်စီး',
  'a channel': 'ချန်နယ်',
  'at a glance': 'တစ်ချက်ကြည့်',
  'by accident': 'မတော်တဆ',
  'data': 'ဒေတာ',
  'dessert': 'အချိုပွဲ',
  '(fr:) (n) rough sketch (fr: dessin)': 'ပုံကြမ်း',
  'telex': 'တယ်လက်စ်',
  'teletypewriter exchange': 'တယ်လီတိုက်ပ',
  '1.  if (conjunction)': 'အကယ်၍',
  '2.  promoted pawn (shogi) (abbr)': 'မြှင့်စစ်သား',
  'in some way or other': 'တစ်နည်းနည်း',
  'one way or another': 'တစ်နည်းမဟုတ်တစ်နည်း',
  'it seems like': 'ထင်ရ',
  'drive in': 'မောင်းဝင်',
  'trouble (sometimes used as a verb)': 'ဒုက္ခ',
  'transistor': 'ထရန်စစ္စတာ',
  'drill': 'လေ့ကျင့်',
  'game under lights (e.g. baseball) (lit: nighter)': 'ညဘက်ပွဲ',
  'night game': 'ညကစားပွဲ',
  'napkin': 'နှာခေါင်းပုဝါ',
  'things like ...': 'ကဲ့သို့အရာ',
  'or something like that .. (often derogatory)': 'တမျိုးမျိုး',
  'something or other': 'တစ်ခုခု',
  'in spite of': 'သော်လည်း',
  'nuance': 'နုန်းစ်',
  '(photographic) negative': 'ဓာတ်ပုံနက်ဂတိ',
};
