module.exports = {
  'still less': 'ပို၍မဆို',
  'the palm': 'လက်ဖဝါး',
  'treetop': 'သစ်ပင်ထိပ်',
  'erasing': 'ဖျက်ခြင်း',
  'dying out': 'တိမ်ကောခြင်း',
  'melting away': 'အရည်ပျော်ပျောက်',
  'to be in a hurry': 'အလျင်လိုသည်',
  'to throw back light': 'အလင်းပြန်ဟပ်သည်',
  'collation': 'တိုက်ဆိုင်စစ်ဆေး',
  'illumination': 'အလင်းပေးခြင်း',
  'to pretend': 'ဟန်ဆောင်သည်',
  'to take the name of': 'အမည်ခံသည်',
  'to feign': 'ဟန်ဆောင်သည်',
  'to purport': 'ဟန်ဆောင်ပြောသည်',
  'impact': 'ထိခိုက်မှု',
  'ballistic': 'ပစ်လွှတ်လမ်းကြောင်း',
  'detail': 'အသေးစိတ်',
  'to interfere with': 'ဝင်ရောက်စွက်ဖက်သည်',
  'to do one harm': 'ထိခိုက်စေသည်',
  'superior (rank not class)': 'အထက်အရာရှိ',
  'higher order (e.g. byte)': 'အဆင့်မြင့်',
  'host computer (of connected device)': 'အဓိကကွန်ပျူတာ',
  'performance (e.g. music)': 'ဖျော်ဖြေတင်ဆက်မှု',
  'superior authorities': 'အထက်အာဏာပိုင်',
  'boss': 'အကြီးအကဲ',
  '1.  upper part': 'အပေါ်ပိုင်း',
  'upper stream': 'မြစ်အထက်ပိုင်း',
  'left side (of a stage)': 'ဇာတ်စင်ဘယ်ဘက်',
  '2.  skillful (only in comparisons)': 'ကျွမ်းကျင် (နှိုင်းယှဉ်)',
  'ascending': 'တက်ခြင်း',
  'climbing': 'တက်ခြင်း',
  'disembarkation': 'ဆင်းသက်ခြင်း',
  'to capture': 'သိမ်းပိုက်သည်',
  'to occupy': 'သိမ်းပိုက်သည်',
  'to usurp': 'အာဏာသိမ်းသည်',
  'transfer (trains  buses  etc.)': 'ယာဉ်ပြောင်းစီး',
  'to board': 'တက်စီးသည်',
  'to embark on': 'စတင်လုပ်သည်',
  'to get into (a car)': 'ကားတက်သည်',
  'to ship (passengers)': 'ခရီးသည်တင်သည်',
  'land near the castle': 'ရဲတိုက်အနီးမြေ',
  'young woman': 'လူပျိုမ',
  'feelings': 'ခံစားချက်',
  'compassionate': 'သနားကြင်နာ',
  'treaty': 'စာချုပ်',
  'pact': 'သဘောတူညီချက်',
  'cane': 'ကြံ/တုတ်',
  'distillation': 'အငွေ့ပြန်ချက်ခြင်း',
  'concession': 'အပေးအယူ',
  'to be planted': 'စိုက်ပျိုးခံရသည်',
  'colony': 'ကိုလိုနီ',
  'weaving': 'ရက်လုပ်ခြင်း',
  'woven item': 'ရက်ထည်',
  'to weave': 'ရက်သည်',
  'staff member': 'ဝန်ထမ်း',
  'personnel': 'ဝန်ထမ်းများ',
  'professional duties': 'အလုပ်တာဝန်',
  'believer': 'ယုံကြည်သူ',
  'adherent': 'နောက်လိုက်',
  'devotee': 'ကိုးကွယ်သူ',
  'Christian': 'ခရစ်ယာန်',
  'to raid': 'ဝင်တိုက်သည်',
  'to trespass': 'ကျူးကျော်သည်',
  'to put to bed': 'အိပ်ရာထည့်သည်',
  'to lay down': 'လှဲထားသည်',
  'to ferment': 'အချဉ်ဖောက်သည်',
  'to aim to do': 'လုပ်ရန်ရည်ရွယ်သည်',
  'heartening': 'အားတက်ဖွယ်',
  'forlorn': 'စိတ်ပျက်ငယ်',
  'hopeless': 'မျှော်လင့်ချက်မဲ့',
  'unpromising': 'အလားအလာမရှိ',
  'double suicide': 'နှစ်ဦးအတူသေ',
  'lovers suicide': 'ချစ်သူနှစ်ဦးသေ',
  'to be chaste or discreet': 'သန့်ရှင်း/သတိရှိသည်',
  'to abstain or refrain': 'ရှောင်ကြဉ်သည်',
  'outset': 'အစ',
  'drawing or issuing (draft)': 'ထုတ်ပေးခြင်း',
  'oscillation': 'တုန်ခါခြင်း',
  'vibration': 'တုန်ခါမှု',
  'developing': 'ဖွံ့ဖြိုးဆဲ',
  'emergent': 'ပေါ်ပေါက်ဆဲ',
  'newly-wed': 'အိမ်ထောင်သစ်',
  'new face': 'မျက်နှာသစ်',
  'newcomer': 'လူသစ်',
  'new building': 'အဆောက်အအုံသစ်',
  'new construction': 'ဆောက်လုပ်မှုသစ်',
  'freshman': 'နှစ်သစ်ကျောင်းသား',
  'first-year student': 'ပထမနှစ်ကျောင်းသား',
  'to propose': 'အဆိုပြုသည်',
  'shortcomings': 'ချို့ယွင်းချက်',
  'in two equal parts': 'ညီမျှနှစ်ပိုင်း',
  'perfectly circular': 'စက်ဝိုင်းပြည့်',
  'right in front': 'ရှေ့တည့်တည့်',
  'under the nose': 'နှာခေါင်းအောက်',
  'right under': 'အောက်တည့်တည့်',
  'directly below': 'တည့်တည့်အောက်',
  'just above': 'အပေါ်ချက်ချင်း',
  'right overhead': 'ခေါင်းပေါ်တည့်',
  'devotion': 'ဆက်ကပ်ကိုးကွယ်မှု',
  'to be intimate with': 'ရင်းနှီးသည်',
  'medical examination and treatment': 'ဆေးစစ်ကုသမှု',
  'personal appearance': 'ကိုယ်ပုံသဏ္ဌာန်',
  'near oneself': 'မိမိအနီး',
  'close to one': 'မိမိနှင့်နီး',
  'familiar': 'ရင်းနှီးကျွမ်းဝင်',
  'gesture': 'လက်ဟန်ခြေဟန်',
  'barely': 'မွန်းမံမျှ',
  'narrowly': 'ကျဉ်းကျဉ်း',
  'just manage to do st': 'မွန်းမံမျှလုပ်နိုင်',
  'step forward': 'ရှေ့တက်',
  'to be shaking': 'တုန်နေသည်',
  'to be trembling': 'တုန်ရီသည်',
  'man of talent': 'ထူးချွန်သူ',
  'hostage': 'ဓားစာခံ',
  'human body': 'လူ့ခန္ဓာကိုယ်',
  'glimpse': 'မျှော်ကြည့်ချက်',
  'public gaze': 'လူမြင်ကွင်း',
  'edge (of a sword)': 'ဓားသွား',
  'dustpan': 'အမှိုက်တံစဉ်',
  'to be used up': 'ကုန်ဆုံးသည်',
  'to be run out': 'ကုန်သွားသည်',
  'to be consumed': 'စားသုံးခံရသည်',
  'to exhaust': 'ကုန်ဆုံးစေသည်',
  'to serve (a person)': 'အစေခံသည်',
  'playing wind instruments': 'လေမှုတ်တူရိယာတီး',
  'propulsion': 'တွန်းအား',
  'driving force': 'မောင်းနှင်အား',
  'reasoning': 'ကျိုးကြောင်းဆင်ခြင်',
  'inference': 'ကောက်ချက်ချခြင်း',
  'mystery or detective genre (movie  novel  etc.)': 'လျှို့ဝှက်/စုံထောက်ဇာတ်',
  '1.  moisture': 'အစိုဓာတ်',
  '2.  dropsy': 'ရေဖေါင်းရောဂါ',
  'source of river': 'မြစ်ရင်းမြစ်',
  'fountainhead': 'ရေတွင်းရင်းမြစ်',
  'flushing': 'ရေဆေးခြင်း',
  '(water-filled) paddy field': 'ရေပြည့်လယ်ကွင်း',
  'cult': 'ဂိုဏ်း/ကိုးကွယ်မှု',
  'to be bulky': 'ထုထည်ကြီးသည်',
  'to be unwieldy': 'ကိုင်ရခက်သည်',
  'to grow voluminous': 'ထုထည်ကြီးလာသည်',
  'numeral': 'ဂဏန်း',
  'young bird': 'ငှက်ငယ်',
  'to set (table)': 'စားပွဲခင်းသည်',
  'to lay (foundation)': 'အခြေခံချသည်',
  'to place (gun)': 'သေနတ်ချိန်သည်',
  'to apply (moxa)': 'မောက်ဆာကပ်သည်',
  'to mount': 'တပ်ဆင်/တက်သည်',
  '(trouser) cuff': 'ဘောင်းဘီခြေရစ်',
  '(skirt) hem': 'စကတ်အနား',
  'cut edge of a hairdo': 'ဆံပင်ညှပ်အနား',
  'foot of mountain': 'တောင်ခြေ',
  'public opinion': 'ပြည်သူ့အမြင်',
  'overcoming': 'ကျော်လွှားခြင်း',
  'to conclude': 'နိဂုံးချုပ်သည်',
  'to consist of': 'ဖွဲ့စည်းထားသည်',
  'to be practical (logical  feasible  viable)': 'လက်တွေ့ကျသည်',
  'to hold true': 'မှန်ကန်သည်',
  'results': 'ရလဒ်များ',
  'fruits': 'အသီးအပွင့်/ရလဒ်',
  'maturity': 'ရင့်ကျက်မှု',
  'ripeness': 'မှည့်ခြင်း',
  'adult age': 'အရွယ်ရောက်',
  'political power': 'နိုင်ငံရေးအာဏာ',
  'political measures': 'နိုင်ငံရေးဆောင်ရွက်',
  'policy': 'မူဝါဒ',
  'to get ready': 'ပြင်ဆင်သည်',
  'to adjust': 'ညှိသည်',
  'orderly': 'စနစ်တကျ',
  'well-organized': 'ကောင်းစွာစီစဉ်',
  'stand in a row': 'တန်းစီရပ်',
  'form a line': 'တန်းဖွဲ့',
  'constellation': 'ကြယ်စု',
  'fine weather': 'ကောင်းကင်သာ',
  'liquidation': 'ရှင်းလင်းရောင်းချ',
  'purity': 'သန့်ရှင်းမှု',
  'good and evil': 'ကောင်းမကောင်း',
  'purity and impurity': 'သန့်/မသန့်',
  'undiluted': 'မရောမနှော',
  'to revive': 'ပြန်ရှင်သည်',
  'to resuscitate': 'အသက်ပြန်သွင်းသည်',
  'to make use of': 'အသုံးချသည်',
  'by birth': 'မွေးရာပါ',
  'native': 'ဇာတိ',
  'lukewarm': 'နွေးနွေး',
  'halfhearted': 'စိတ်မပါ',
  'livelihood': 'အသက်မွေးဝမ်းကြောင်း',
  'life and death': 'အသက်နှင့်သေ',
  'smelling of fish or blood': 'ငါး/သွေးနံ့',
  'fish or meat': 'ငါးသို့မဟုတ်အသား',
  'too serious': 'အလွန်တည်ကြည်',
  'person who is too serious': 'အလွန်တည်ကြည်သူ',
  'living flesh': 'အသက်ရှိအသား',
  'flesh and blood': 'သားရင်းသွေးရင်း',
  'the quick': 'အသက်ရှိအစိတ်',
  'physiology': 'ဇီဝကမ္မဗေဒ',
  'menses': 'ရာသီလာခြင်း',
  'to copulate (animals)': 'မွေးဖွားဆက်ဆံသည်',
  'be dressed up': 'ဝတ်စားဆင်ယင်',
  'wear rich clothes': 'ကောင်းသောအဝတ်ဝတ်',
  'elaborate': 'သေချာစီမံ',
  'exquisite': 'နူးညံ့လှပ',
  'Bible': 'ကျမ်းစာ',
  'scriptures': 'ဓမ္မကျမ်းများ',
  'statement': 'ကြေညာချက်',
  'iron manufacture': 'သံထည်လုပ်ငန်း',
  'manufacturing method': 'ထုတ်လုပ်နည်း',
  'recipe': 'ဟင်းချက်နည်း',
  'westering sun': 'နေဝင်ရောင်',
  'sincere': 'ရိုးသားစစ်မှန်',
  'honest': 'ရိုးသား',
  'faithful': 'သစ္စာရှိ',
  'springtime of life': 'ဘဝနွေဦး',
  'adolescent': 'ဆယ်ကျော်သက်',
  'stillness': 'ငြိမ်သက်မှု',
  'repose': 'အနားယူခြင်း',
  'standing still': 'ရပ်တန့်နေခြင်း',
  'static': 'ငြိမ်/မရွေ့',
  'tax office': 'အခွန်ရုံး',
  'brittle': 'ကြွပ်ဆတ်',
  'fragile': 'ပျက်လွယ်',
  'to become red': 'နီလာသည်',
  'to redden': 'နီသည်',
  'deficit': 'လိုငွေ',
  'go in the red': 'အရှုံးပေါ်သည်',
  'heir': 'အမွေဆက်ခံသူ',
  'successor': 'ဆက်ခံသူ',
  'to pause': 'ခဏရပ်သည်',
  'to be interrupted': 'ပြတ်တောက်သည်',
  'clearing (land)': 'မြေရှင်းခြင်း',
  'opening up': 'ဖွင့်လှစ်ခြင်း',
  'cutting through': 'ဖြတ်သန်းဖြတ်',
  'to piece together': 'ဆက်စပ်စုသည်',
  'to set (bones)': 'အရိုးညှိသည်',
  'to graft (trees)': 'သစ်ကိုင်းဆက်သည်',
  'conjunction': 'ချိတ်ဆက်/စပ်ဆက်',
  'to turn up': 'လှန်သည်',
  'to fold back': 'ပြန်ခေါက်သည်',
  'blending': 'ရောစပ်ခြင်း',
  'eclecticism': 'ရွေးချယ်စုစည်းမှု',
  'persuasion': 'စည်းရုံးခြင်း',
  'avalanche': 'နှင်းပြို',
  'to peter out': 'တဖြည်းဖြည်းကုန်သည်',
  'to become extinct': 'မျိုးတုံးသည်',
  'to sever': 'ဖြတ်တောက်သည်',
  'to cut off': 'ဖြတ်ပစ်သည်',
  'to abstain (from)': 'ရှောင်သည်',
  'out of print': 'ပုံနှိပ်မရှိတော့',
  'despair': 'စိတ်ပျက်အားငယ်',
  'hopelessness': 'မျှော်လင့်ချက်မဲ့မှု',
  'preceding': 'ရှေ့က',
  'going first': 'ဦးစွာသွား',
  'week before last': 'ပြီးခဲ့သည့်နှစ်ပတ်',
  'family predecessor': 'မိသားစုရှေ့ဆောင်',
  'previous age': 'ယခင်ခေတ်',
  'previous generation': 'ယခင်မျိုးဆက်',
  'first arrival': 'ဦးဆုံးရောက်',
  'a priori': 'ကြိုတင်သိ',
  'inborn': 'မွေးရာပါ',
  'innate': 'ပင်ကိုယ်ပါ',
  'occupation': 'အလုပ်အကိုင်/သိမ်းပိုက်',
  'have a room to oneself': 'အခန်းတစ်ခန်းပိုင်',
  'religious mission': 'ဘာသာရေးမစ်ရှင်',
  'exclusive use': 'သီးသန့်အသုံး',
  'war damage': 'စစ်ဒဏ်',
  'war potential': 'စစ်စွမ်းအား',
  'to permeate': 'စိမ့်ဝင်သည်',
  'to colour': 'အရောင်ဆိုးသည်',
  '1.  to drive': 'မောင်းသည်',
  '2.  to evade': 'ရှောင်သည်',
  'diving': 'ငုပ်ခြင်း',
  'infiltration': 'ထိုးဖောက်ဝင်ရောက်',
  'sneaking in': 'လျှို့ဝှက်ဝင်',
  'to instigate': 'နှိုးဆော်သည်',
  'to flatter': 'ချော့မော့သည်',
  'fibre': 'အမျှင်',
  'fiber': 'အမျှင်',
  'election': 'ရွေးကောက်ပွဲ',
  'screening': 'စိစစ်ရွေးချယ်',
  'future prospects': 'အနာဂတ်အလားအလာ',
  'the journey ahead': 'ရှေ့ခရီး',
  'advance sale': 'ကြိုရောင်း',
  'booking': 'ကြိုတင်မှာယူ',
  'precedent': 'ရှေ့ပြေးနမူနာ',
  'with gusto': 'စိတ်အားထက်သန်စွာ',
  'with satisfaction': 'ကျေနပ်စွာ',
  'complete recovery of health': 'ကျန်းမာရေးပြည့်ပြန်',
  'height of prosperity': 'စည်ပင်ထိပ်ဆုံး',
  'annihilation': 'မျိုးဖြုတ်ခြင်း',
  'Zen (Buddhism)': 'ဇင် (ဗုဒ္ဓဘာသာ)',
  'subject matter': 'အကြောင်းအရာ',
  'artlessness': 'ရိုးသားမှု',
  'to join up': 'ပူးပေါင်းသည်',
  'litigation': 'တရားစွဲဆိုမှု',
  '1.  mouse': 'ကြွက်',
  '2.  dark gray': 'မီးခိုးရင့်',
  'priest': 'ဘုန်းတော်ကြီး',
  'launching (e.g. newspaper)': 'စတင်ထုတ်ဝေ',
  'first issue': 'ပထမထုတ်',
  'creation': 'ဖန်တီးမှု',
  'search (esp. in criminal investigations)': 'ရှာဖွေ (စုံစမ်း)',
  'search (esp. for someone or something missing)': 'ရှာဖွေ (ပျောက်ဆုံး)',
  'to churn': 'မွှေသည်',
  'to ransack': 'ရှာဖွေမွှေနှောက်သည်',
  'to manipulate': 'ချယ်လှယ်သည်',
  'to operate': 'လည်ပတ်/ခွဲစိတ်သည်',
  'to pull strings': 'ကြိုးကိုင်သည်',
  'to quicken': 'မြန်စေသည်',
  'to expedite': 'အရှိန်မြှင့်သည်',
  'to precipitate': 'အရှိန်မြှင့်/ရွာသည်',
  'quarrel': 'ရန်ဖြစ်',
  'dissension': 'သဘောကွဲလွဲ',
  'market price': 'ဈေးကွက်ဈေး',
  'speculation': 'ထင်ကြေး/ဈေးကစား',
  'between ourselves': 'ကျွန်တော်တို့အကြား',
  'no third party': 'တတိယသူမရှိ',
  'general meeting': 'အထွေထွေအစည်းအဝေး',
  'coordination': 'ညှိနှိုင်းခြင်း',
  'putting together': 'စုစည်းခြင်း',
  'to inter': 'မြှုပ်နှံသည်',
  'to entomb': 'ဂူသွင်းသည်',
  'to consign to oblivion': 'မေ့ပျောက်စေသည်',
  'to wriggle': 'တွန့်လိမ်သည်',
  'running a wheeled vehicle (e.g. car)': 'ယာဉ်မောင်းနှင်',
  'traveling': 'ခရီးသွားခြင်း',
  'remittance': 'ငွေလွှဲ',
  'sending money': 'ငွေပို့ခြင်း',
  'additional': 'အပို',
  'less objectionable': 'ကန့်ကွက်မှုနည်း',
  'hatred': 'မုန်းတီးမှု',
  'Minister of Finance': 'ဘဏ္ဍာရေးဝန်ကြီး',
  'to urge': 'တိုက်တွန်းသည်',
  'to demand': 'တောင်းဆိုသည်',
  'facilitation': 'လွယ်ကူစေခြင်း',
  'to agree with': 'သဘောတူသည်',
  'to be adapted to': 'လိုက်လျောညီထွေသည်',
  'brief time': 'ခဏတာ',
  'brief': 'တိုတောင်း',
  'transient': 'ယာယီ',
  'shackles': 'ခြေချင်း',
  'confinement': 'ချုပ်နှောင်ခြင်း',
  'everywhere': 'နေရာတိုင်း',
  'that area': 'အဲဒီဒေသ',
  'duration': 'ကြာချိန်',
  'continuance': 'ဆက်လက်တည်ရှိ',
  'ill will': 'မကောင်းသောစိတ်',
  'another intention': 'အခြားရည်ရွယ်',
  'secret purpose': 'လျှို့ဝှက်ရည်ရွယ်',
  'transitive verb (direct obj)': 'ကံလိုကြိယာ',
  'another side': 'အခြားဘက်',
  'different direction': 'အခြားဦးတည်',
  '(on) the other hand': 'တစ်ဖက်တွင်',
  'majority rule': 'အများစုအုပ်ချုပ်',
  'diversity': 'ကွဲပြားမှု',
  'saliva': 'တံတွေး',
  'sputum': 'သလိပ်',
  'giving in': 'အရှုံးပေးခြင်း',
  'to knock together': 'ထိခိုက်ဆက်သည်',
  'to drive in (e.g. nail  stake)': 'ထိုးသွင်းသည်',
  'to devote oneself to': 'စွဲမြဲလုပ်သည်',
  'to shoot into': 'ပစ်သွင်းသည်',
  'break in the deadlock': 'ရပ်တန့်မှုဖြေရှင်း',
  '1.  blow': 'ထိုးချက်',
  'physique': 'ကိုယ်ထည်',
  'personal experience': 'ကိုယ်တွေ့အတွေ့အကြုံ',
  'physical strength': 'ရုပ်အား',
  'interaction': 'အပြန်အလှန်ဆက်ဆံ',
  'correspondence': 'စာပေးစာယူ/ကိုက်ညီ',
  'coping with': 'ကိုင်တွယ်ခြင်း',
  'showdown': 'နောက်ဆုံးထိပ်တိုက်',
  'deal with': 'ကိုင်တွယ်',
  'cope': 'ရင်ဆိုင်',
  'equivalent': 'တူညီသော',
  '(geometrical) opposite side': 'ဆန့်ကျင်ဘက် (ဂျီဩ)',
  'looking forward to': 'မျှော်လင့်စောင့်',
  'to look anxiously for': 'စိုးရိမ်စွာစောင့်သည်',
  'to wait eagerly for': 'စိတ်အားထက်သန်စောင့်သည်',
  'expectant waiting': 'မျှော်လင့်စောင့်ဆိုင်း',
  'sluggish': 'နှေးကွေး',
  'feel heavy': 'လေးလံခံစား',
  'dull': 'မှိုင်း/နှေး',
  'procrastination': 'ရွှေ့ဆိုင်းခြင်း',
  'expressly': 'အထူးသဖြင့်',
  'specially': 'အထူး',
  'doing something especially rather than incidentally': 'အထူးလုပ်ခြင်း',
  'to stagnate': 'ရပ်တန့်သည်',
  'to be delayed': 'နှောင့်နှေးသည်',
  'non-payment': 'မပေးချေခြင်း',
  'default': 'ပျက်ကွက်ခြင်း',
  'femur': 'ပေါင်ရိုး',
  'to repel': 'တွန်းလှန်သည်',
  'to drive away': 'မောင်းထုတ်သည်',
  'retrogression': 'နောက်ပြန်ဆုတ်',
  'dropping out of school': 'ကျောင်းထွက်ခြင်း',
  'extermination': 'မျိုးဖြုတ်ခြင်း',
  'retirement (from office)': 'ရာထူးမှအနားယူ',
  'alternately': 'အလှည့်ကျ',
  'pay by proxy': 'ကိုယ်စားပေးချေ',
  'act for another': 'ကိုယ်စားလုပ်',
  'speak for another': 'ကိုယ်စားပြော',
  'substitution': 'အစားထိုးခြင်း',
  'libretto': 'သီချင်းစာသား',
  'mess': 'ရောထွေး/ပျက်စီး',
  'spoiled': 'ပျက်စီး/အပျက်',
  '(come to) nothing': 'အချည်းနှီးဖြစ်',
  'grandiose': 'ကြီးကျယ်ဟန်',
  'rough (as in not precise)': 'ကြမ်း/မတိကျ',
  'in general': 'ယေဘုယျအားဖြင့်',
  'great cost': 'ကုန်ကျစရိတ်ကြီး',
  'general public': 'အများပြည်သူ',
  'bold': 'ရဲရင့်',
  'daring': 'သတ္တိရှိ',
  'audacious': 'ရဲတင်း',
  'full width': 'အပြည့်အကျယ်',
  'large scale': 'အကြီးစား',
  'drastic': 'ပြင်းထန်',
  'large build': 'ကိုယ်ထည်ကြီး',
  'large pattern': 'ပုံကြီး',
  'feces': 'မစင်',
  'excrement': 'မစင်',
  'shit': 'မစင်',
  'ordinal': 'အစဉ်အဆက်ဂဏန်း',
  'to rinse': 'ရေဆေးသည်',
  'to wash out': 'ဆေးထုတ်သည်',
  'achievement': 'အောင်မြင်မှု',
  'to get out': 'ထွက်သည်',
  'secession': 'ခွဲထွက်ခြင်း',
  'to grope along to': 'ကိုယ်ထိလက်ရောက်ရှာသွား',
  'to struggle on to': 'ရုန်းကန်ရောက်သည်',
  'to arrive somewhere after a struggle': 'ရုန်းကန်ပြီးရောက်သည်',
  'to follow (road)': 'လမ်းလိုက်သည်',
  'to pursue (course)': 'လမ်းကြောင်းလိုက်သည်',
  'to follow up': 'ဆက်လုပ်သည်',
  'adjectival suffix for a person': 'လူအတွက်နာမဝိသေသန',
  'one layer': 'တစ်လွှာ',
  'monotone': 'တစ်သံတည်း',
  'solo (flight)': 'တစ်ဦးတည်း (ပျံသန်း)',
  'to sigh': 'ညည်းသည်',
  'to lament': 'ငိုကြွေးသည်',
  'to grieve': 'ဝမ်းနည်းသည်',
  'to bear (burden)': 'ဝန်ထမ်းသည်',
  'to shoulder (gun)': 'ပခုံးတင်သည်',
  'stretcher': 'လူတင်ညောင်စောင်း',
  'litter': 'ညောင်စောင်း/အမှိုက်',
  'exploration': 'စူးစမ်းရှာဖွေ',
  'expedition': 'စူးစမ်းခရီး',
  'master (of house)': 'အိမ်ရှင်',
  'husband (informal)': 'ခင်ပွန်း (ရင်းနှီး)',
  'lamentation': 'ငိုကြွေးခြင်း',
  'carbon (C)': 'ကာဗွန်',
  'tanka': 'တန်ကာကဗျာ',
  '31-syllable Japanese poem': 'ဂျပန်ကဗျာ ၃၁ လုံး',
  'quick temper': 'စိတ်မြန်',
  'shortening': 'တိုစေခြင်း',
  'junior college': 'တိုတောင်းကောလိပ်',
  'short wave': 'လှိုင်းတို',
  'to come apart at the seams': 'ချုပ်ရိုးပြတ်သည်',
  'to begin to open': 'စဖွင့်သည်',
  'to smile broadly': 'ကျယ်ကျယ်ပြုံးသည်',
  'protein': 'ပရိုတင်း',
  '1.  platform': 'စင်/ပလက်ဖောင်း',
  '2.  (arch) mandala': 'မဏ္ဍလ (ရှေး)',
  'to flip': 'လှန်သည်',
  'to snap': 'ပြတ်/ခေါက်သည်',
  'elasticity': 'ပျော့ပြောင်းမှု',
  'flexibility': 'လိုက်လျောညီထွေမှု',
  'cross section': 'ဖြတ်ပိုင်း',
  'to be worth': 'တန်ဖိုးရှိသည်',
  'to deserve': 'ထိုက်တန်သည်',
  'to merit': 'ထိုက်သည်',
  'price reduction': 'ဈေးလျှော့',
  'intellectual': 'ဉာဏ်ရည်ရှိသူ',
  'terrain': 'မြေမျက်နှာသွင်ပြင်',
  'geographical features': 'ပထဝီအင်္ဂါရပ်',
  'hell': 'ငရဲ',
  'slack': 'လျော့ရဲ',
  'slackening': 'လျော့ခြင်း',
  'letdown': 'စိတ်ပျက်ဖွယ်',
  'to relax': 'အပန်းဖြေသည်',
  'embarrassment': 'ရှက်ရွံ့မှု',
  'to feel shy': 'ရှက်သည်',
  'to be bashful': 'ရှက်ရွံ့သည်',
  'to feel ashamed': 'အရှက်ရသည်',
  'at the latest': 'နောက်ဆုံးထား၍',
  'to retard': 'နှောင့်နှေးစေသည်',
  'lag': 'နောက်ကျမှု',
  'animal husbandry': 'မွေးမြူရေး',
  'damn': 'ကျိန်ဆဲ',
  'suffocation': 'အသက်ရှူကြပ်',
  'living room (Japanese style)': 'ဧည့်ခန်း (ဂျပန်)',
  'tea ceremony': 'လက်ဖက်ရည်အခမ်းအနား',
  'start of (construction) work': 'ဆောက်လုပ်စတင်',
  'embarkation': 'သင်္ဘောတက်ခြင်း',
  'to dress up': 'ဝတ်စားဆင်ယင်သည်',
  'colouring': 'အရောင်ဆိုးခြင်း',
  'touch down': 'ဆင်းသက်',
  'hook-up': 'ချိတ်ဆက်',
  'libel': 'စာဖြင့်စော်ကား',
  'defamation': 'ဂုဏ်သိက္ခာဖျက်',
  'centre': 'ဗဟို',
  'mainstay': 'အဓိကထောက်တိုင်',
  'poisoning': 'အဆိပ်သင့်ခြင်း',
  'irritated': 'စိတ်တို',
  'offended': 'စိတ်နာ',
  'neutrality': 'ကြားနေမှု',
  'counteract': 'တန်ပြန်လုပ်',
  'matchmaker': 'စေ့စပ်သူ',
  'somersault': 'လှည့်လှန်ခုန်',
  'looping-the-loop': 'ကွင်းလှည့်ပျံ',
  'raffle': 'မဲနှိုက်',
  'drawing (of lots)': 'မဲနှိုက်ခြင်း',
  'remarkable': 'ထူးခြား',
  'considerable': 'များစွာ',
  'savings': 'စုဆောင်းငွေ',
  'clashing of swords': 'ဓားထိခိုက်သံ',
  'felling of trees': 'သစ်ခုတ်ခြင်း',
  'ringing of an ax': 'ပုဆိန်သံ',
  'district of a town': 'မြို့ရပ်ကွက်',
  'city block (of irregular size)': 'မြို့ကွက်',
  'paper patch': 'စက္ကူကပ်',
  'paper backing': 'စက္ကူနောက်ခံ',
  'to learn by experience': 'အတွေ့အကြုံမှသင်သည်',
  'to be disgusted with': 'စက်ဆုပ်သည်',
  'to contend for': 'ယှဉ်ပြိုင်သည်',
  'to make love to': 'ချစ်ခင်ပြသည်',
  'defiance': 'ဆန့်ကျင်မှု',
  'oversleeping': 'အိပ်ပျော်လွန်',
  'late riser': 'နောက်ကျထသူ',
  'tide': 'ဒီရေ',
  'the sense of hearing': 'နားအာရုံ',
  'lecture attendance': 'ဟောပြောပွဲတက်',
  'auditing': 'စာရင်းစစ်/နားထောင်',
  'stethoscope': 'နှလုံးနားကြပ်',
  'sealing': 'တံဆိပ်ခတ်ခြင်း',
  'arbitration': 'စေ့စပ်ဖြေရှင်း',
  'hyper-': 'အလွန်-',
  'very long': 'အလွန်ရှည်',
  'great length': 'အရှည်ကြီး',
  'long (e.g. novel  film)': 'ရှည်လျား (ဝတ္ထု/ရုပ်ရှင်)',
  '(top of) head': 'ခေါင်းထိပ်',
  'spire': 'မျှော်စင်ထိပ်',
  'torii (Shinto shrine archway)': 'တိုရီအီ (ဘုရားဝင်တံခါး)',
  'to submerge': 'နစ်မြုပ်သည်',
  'sinking': 'နစ်မြုပ်ခြင်း',
  'foundering': 'နစ်မြုပ်ပျက်စီး',
  'tsunami': 'ဆူနာမီ',
  'tidal wave': 'ဒီလှိုင်းကြီး',
  'falling': 'ကျခြင်း',
  'crashing': 'ပျက်ကျခြင်း',
  'to expel': 'နှင်ထုတ်သည်',
  'to drive out': 'မောင်းထုတ်သည်',
  'gaining on': 'လိုက်မီခြင်း',
  'solving (crime)': 'မှုခင်းဖြေရှင်း',
  'pursuit': 'လိုက်လံရှာဖွေ',
  'banishment': 'နှင်ထုတ်ခြင်း',
  'to hurt': 'နာကျင်စေသည်',
  'to feel a pain': 'နာကျင်ခံစားသည်',
  'to be injured': 'ဒဏ်ရာရသည်',
  'feeling keenly': 'ပြင်းပြင်းခံစား',
  'fully realizing': 'အပြည့်အဝနားလည်',
  'keen': 'ထက်မြက်/ပြင်း',
  'acute': 'ပြင်းထန်/ထက်',
  'connoisseur': 'ကျွမ်းကျင်သိသူ',
  'counter for letters': 'စာရေတွက်',
  'coherence': 'ညီညွတ်မှု',
  'to bind': 'ချည်နှောင်သည်',
  'tsubo jar': 'ဆူဘိုအိုး',
  'vase': 'ပန်းအိုး',
  'strap': 'ပတ်ကြိုး',
  'angling': 'ငါးမျှားခြင်း',
  'hanging bell': 'ဆွဲခေါင်းလောင်း',
  'retention': 'ထိန်းသိမ်းထားရှိ',
  'definition': 'အဓိပ္ပာယ်ဖွင့်',
  'set meal': 'အစုံအစားအသောက်',
  'special (of the day)': 'နေ့ထူးဟင်း',
  'retirement age': 'အငြိမ်းစားအသက်',
  'offer': 'ကမ်းလှမ်း',
  'tender': 'တင်ဒါ/နူးညံ့',
  'program sponsoring': 'အစီအစဉ်ပံ့ပိုး',
  'furnishing': 'ပစ္စည်းတပ်ဆင်',
  'joint business': 'ပူးတွဲလုပ်ငန်း',
  'link-up': 'ချိတ်ဆက်မှု',
  'suggest': 'အကြံပြု',
  'typical': 'ပုံမှန်/သာမန်',
  'adaptation': 'လိုက်လျောညီထွေ',
  'conformity': 'လိုက်နာညီညွတ်',
  'aptitude': 'စွမ်းရည်အရည်အချင်း',
  'to sink in': 'စိမ့်ဝင်သည်',
  'to penetrate': 'ထိုးဖောက်သည်',
  'to devote oneself': 'ဆက်ကပ်သည်',
  'to believe in': 'ယုံကြည်သည်',
  'iron and steel': 'သံနှင့်သံမဏိ',
  'iron scraps': 'သံအပိုင်းအစ',
  'iron rod': 'သံချောင်း',
  'crowbar': 'သံတုံး',
  'horizontal bar (gymnastics)': 'အလျားတန်း (အားကစား)',
  'ceiling': 'မျက်နှာကြက်',
  'ceiling price': 'အမြင့်ဆုံးဈေး',
  'Kingdom of Heaven': 'ကောင်းကင်နိုင်ငံ',
  'prodigy': 'ထူးချွန်ကလေး',
  'natural gift': 'ပင်ကိုယ်ပါရမီ',
  'heavenly body': 'ကောင်းကင်အလောင်း',
  'prospect': 'အလားအလာ',
  'to become married': 'အိမ်ထောင်ပြုသည်',
  'to add to': 'ပေါင်းထည့်သည်',
  'convert': 'ပြောင်းလဲ',
  'transmission': 'ထုတ်လွှင့်/ကူးစက်',
  'change schools': 'ကျောင်းပြောင်း',
  'rolling about': 'လူးလိမ့်ခြင်း',
  'moving from place to place': 'နေရာအမျိုးမျိုးရွှေ့',
  'being passed around repeatedly': 'လက်ဆင့်ကမ်းနေခြင်း',
  'change of post': 'ရာထူးပြောင်း',
  'ignition': 'မီးညှိခြင်း',
  'lighting': 'မီးထွန်းခြင်း',
  'set fire to': 'မီးရှို့',
  'dotted line': 'အစက်လိုင်း',
  'perforated line': 'အပေါက်လိုင်း',
  'folklore': 'ရိုးရာပုံပြင်',
  'ancestral': 'ဘိုးဘေးဆိုင်ရာ',
  'hereditary': 'အမွေဆက်ခံ',
  'transmitted': 'ကူးစက်/လက်ဆင့်ကမ်း',
  'rear': 'နောက်ပိုင်း',
  'rear unit guard': 'နောက်တန်းစောင့်',
  'feudal lord': 'နယ်စား',
  'source of electricity': 'လျှပ်စစ်ရင်းမြစ်',
  'power (button on TV  etc.)': 'ပါဝါ (ခလုတ်)',
  'electric line': 'လျှပ်စစ်လိုင်း',
  '1.  to breathe': 'အသက်ရှူသည်',
  '2.  to tell (lies)': 'လိမ်ပြောသည်',
  '3.  to vomit': 'အန်သည်',
  'to be jealous': 'မနာလိုသည်',
  'to be envious': 'ငြူစူသည်',
  'going on foot': 'ခြေလျင်သွား',
  'migratory bird': 'ရွှေ့ပြောင်းငှက်',
  'bird of passage': 'ဖြတ်သန်းငှက်',
  'attendance (at school)': 'ကျောင်းတက်ခြင်း',
  'betting': 'လောင်းကစား',
  'gambling': 'လောင်းကစား',
  'a gamble': 'အလောင်းအစား',
  'to wager': 'လောင်းသည်',
  'to bet': 'လောင်းသည်',
  'to risk': 'အန္တရာယ်ယူသည်',
  'to stake': 'အလောင်းထားသည်',
  'en route': 'လမ်းတွင်',
  'half way': 'လမ်းတစ်ဝက်',
  'make an effort!': 'ကြိုးစားပါ!',
  'work hard!': 'ကြိုးကြိုးလုပ်ပါ!',
  'lapse of memory': 'မှတ်ဉာဏ်ပျောက်',
  'forget for a moment': 'ခဏမေ့',
  'product of the land': 'ဒေသထွက်ကုန်',
  'arena': 'ကွင်း/ဇာတ်ရုံ',
  'public works': 'အများပြည်သူအလုပ်',
  '(corporate) bankruptcy': 'ဒေဝါလီခံ',
  'insolvency': 'ပေးဆပ်မနိုင်မှု',
  'hibernation': 'ဆောင်းခိုအိပ်',
  'winter sleep': 'ဆောင်းရာသီအိပ်',
  'to sacrifice': 'စွန့်လွှတ်သည်',
  'to throw out': 'ပစ်ထုတ်သည်',
  'making (an electrical circuit)': 'ဆားကစ်ချိတ်ခြင်း',
  'stealing': 'ခိုးခြင်း',
  'to apply (a rule)': 'စည်းမျဉ်းသုံးသည်',
  'phonetic-equivalent character': 'အသံတူစာလုံး',
  'substitute character': 'အစားထိုးစာလုံး',
  'the one concerned': 'သက်ဆိုင်သူ',
  'the said person': 'အဆိုပါသူ',
  'being elected': 'ရွေးချယ်ခံရခြင်း',
  'winning the prize': 'ဆုရခြင်း',
  'unification': 'တစ်သားတည်းဖြစ်ခြင်း',
  'generalship': 'စစ်ဦးစီးမှု',
  'reaching': 'ရောက်ခြင်း',
  'attaining': 'ရရှိခြင်း',
  '(cannot) possibly': 'မဖြစ်နိုင်',
  'to be enchanted with': 'စွဲလမ်းသည်',
  'to have origin in': 'အရင်းခံသည်',
  'to run away': 'ပြေးသည်',
  'flight': 'ထွက်ပြေးခြင်း',
  'desertion': 'စွန့်ခွာခြင်း',
  'ceramics': 'ကြွေထည်',
  'mobilization': 'စုဆောင်းအသုံးချ',
  'dynamic': 'လှုပ်ရှားမှုရှိ',
  'kinetic': 'ရွေ့လျားဆိုင်ရာ',
  'unrest': 'မငြိမ်သက်မှု',
  'shaking': 'တုန်ခါခြင်း',
  'trembling': 'တုန်ရီခြင်း',
  'of the same age': 'အသက်တူ',
  'the same grade': 'အတန်းတူ',
  'same class': 'အတန်းတူ',
  'living together': 'အတူနေခြင်း',
  'same mind': 'စိတ်တူ',
  'kindred soul': 'စိတ်တူသူ',
  'sympathize': 'စာနာ',
  'agree with': 'သဘောတူ',
  'alignment': 'တန်းညှိခြင်း',
  'enclosure (e.g. in a letter)': 'ပူးတွဲပစ္စည်း',
  'impressive': 'ထင်ရှားစေသော',
  'to be guided': 'လမ်းညွှန်ခံရသည်',
  'to be shown': 'ပြသခံရသည်',
  'yearning': 'တမ်းတမှု',
  'dojo': 'ဒိုဂျို',
  'hall used for martial arts training': 'ကိုယ်ခံပညာခန်းမ',
  'mandala': 'မဏ္ဍလ',
  'points made': 'ရမှတ်',
  'marks obtained': 'ရမှတ်',
  'special skill': 'အထူးကျွမ်းကျင်မှု',
  'special permission': 'အထူးခွင့်ပြု',
  'patent': 'မူပိုင်ခွင့်',
  'privilege': 'အခွင့်ထူး',
  'special right': 'အထူးအခွင့်အရေး',
  'send specially': 'အထူးပို့',
  'special envoy': 'အထူးသံတမန်',
  'characteristic (of)': 'ထူးခြားချက်',
  'peculiar (to)': 'ထူးခြားသော',
  'dictatorship': 'အာဏာရှင်စနစ်',
  'monopoly': 'တစ်ဦးတည်းလက်ဝါးရိုက်',
  'originality': 'မူလဆန်းသစ်မှု',
  'to read out loud (and clearly)': 'ကျယ်ကျယ်ဖတ်သည်',
  'to call a roll': 'အမည်ခေါ်သည်',
  'reader': 'စာဖတ်သူ',
  'breaking through': 'ထိုးဖောက်ခြင်း',
  'breakthrough': 'အောင်မြင်ထိုးဖောက်',
  'to become less capable': 'စွမ်းရည်ကျသည်',
  'to grow dull': 'မှိုင်းလာသည်',
  'to become blunt': 'တုံးလာသည်',
  'thickheadedness': 'ဉာဏ်မဲ့မှု',
  'stolidity': 'ခံစားမှုမဲ့',
  'cabinet': 'ဝန်ကြီးအဖွဲ့/ဗီရို',
  '(government) ministry': 'ဝန်ကြီးဌာန',
  'internal organs': 'အတွင်းအင်္ဂါ',
  'the items': 'အချက်များ',
  'breakdown': 'အသေးစိတ်ခွဲ',
  'civil war': 'ပြည်တွင်းစစ်',
  'domestic conflict': 'ပြည်တွင်းပဋိပက္ခ',
  'inland': 'ပြည်တွင်း',
  'to domesticate': 'အိမ်မွေးပြုသည်',
  'to tame': 'ယဉ်ပါးစေသည်',
  'over-familiar': 'အလွန်ရင်းနှီး',
  'to do thriving business': 'လုပ်ငန်းစည်ပင်သည်',
  'to be crowded with people': 'လူစည်ကားသည်',
  'blood relationship': 'သွေးသားတော်စပ်',
  'blood relative': 'သွေးသားရင်း',
  'the Japanese flag': 'ဂျပန်အလံ',
  'in the sun': 'နေရောင်တွင်',
  'normally': 'ပုံမှန်အားဖြင့်',
  'habitually': 'အလေ့အထအရ',
  'sunburn': 'နေလောင်',
  'daily allowance': 'နေ့စားကြေး',
  'to get in': 'ဝင်သည်',
  'to go in': 'ဝင်သွားသည်',
  'to come in': 'ဝင်လာသည်',
  'to flow into': 'စီးဝင်သည်',
  'obtaining': 'ရရှိခြင်း',
  'coming to hand': 'လက်ဝယ်ရောက်',
  'winning a prize or place (in a contest)': 'ဆု/နေရာရခြင်း',
  'bathing': 'ရေချိုးခြင်း',
  'to leave to a person': 'လူတစ်ဦးလွှဲသည်',
  'nomination': 'အမည်တင်သွင်း',
  'ordination': 'ဘိသိက်ပေးခြင်း',
  'commission': 'ကော်မရှင်/တာဝန်ပေး',
  'to write up': 'ရေးတင်သည်',
  'recognition': 'အသိအမှတ်ပြု',
  'cognizance': 'သိရှိမှု',
  'boiling water': 'ရေဆူ',
  'yearbook': 'နှစ်ပတ်လည်စာအုပ်',
  'name of an era': 'ခေတ်အမည်',
  'year number': 'နှစ်ဂဏန်း',
  'pupil in .... year': '...နှစ်ကျောင်းသား',
  'student in .... year': '...နှစ်ကျောင်းသား',
  'seniority': 'အကြီးအကဲအစဉ်',
  'annual tree ring': 'သစ်ပင်နှစ်ကွင်း',
  'to wrench': 'လိမ်ညှစ်သည်',
  'to screw': 'ဝက်အူတပ်သည်',
  'screw': 'ဝက်အူ',
  'helix': 'ခရုပတ်',
  'spiral': 'ခရုပတ်ပုံ',
  'combustion': 'လောင်ကျွမ်းခြင်း',
  'stickyness': 'ကပ်ငြိမှု',
  'viscosity': 'ပျစ်ခဲမှု',
  'to be sticky': 'ကပ်သည်',
  'to be adhesive': 'ကပ်ငြိသည်',
  'to persevere': 'ဇွဲရှိသည်',
  'to persist': 'ဇွဲနှင့်ဆက်သည်',
  'seductive': 'ဆွဲဆောင်မှုရှိ',
  'to afflict': 'ဒုက္ခပေးသည်',
  'to molest': 'နှောင့်ယှက်သည်',
  'farm (agriculture)': 'လယ်ယာခြံ',
  'agricultural land': 'စိုက်ပျိုးမြေ',
  'revocation': 'ရုပ်သိမ်းခြင်း',
  'annulment': 'ပယ်ဖျက်ခြင်း',
  'breaking (e.g. treaty)': 'ဖောက်ဖျက်ခြင်း',
  'rupture': 'ပြတ်တောက်ခြင်း',
  'break off': 'ဖြတ်တောက်',
  'to abuse': 'အလွဲသုံးသည်',
  'to go out of use': 'အသုံးမရှိတော့',
  'to become obsolete': 'ခေတ်မမီတော့',
  'to go out of fashion': 'ခေတ်မစားတော့',
  'annullment': 'ပယ်ဖျက်ခြင်း',
  'disposal': 'စွန့်ပစ်ခြင်း',
  'abolition': 'ဖျက်သိမ်းခြင်း',
  'repeal': 'ရုပ်သိမ်းခြင်း',
  'Dear (so and so)': 'ချစ်ခင်ရပါသော',
  'losing a war': 'စစ်ရှုံးခြင်း',
  'wine cups': 'စပျစ်ရည်ခွက်',
  'to run counter to': 'ဆန့်ကျင်သည်',
  'to infringe': 'ချိုးဖောက်သည်',
  'setting': 'အခြေအနေ/ဆက်တင်',
  'circumstance': 'အခြေအနေ',
  'lung': 'အဆုတ်',
  'distribution (eg. films  rice)': 'ဖြန့်ဖြူးခြင်း',
  'arrangement (of resources)': 'စီစဉ်ခွဲဝေ',
  'forethought': 'ကြိုတင်စဉ်းစား',
  'dried plum': 'ဇီးသီးခြောက်',
  '(bargain) sale': 'လျှော့ဈေးရောင်း',
  'reparations': 'လျော်ကြေး',
  'to be worn off': 'စားသွားသည်',
  'to discolor': 'အရောင်ပျက်သည်',
  'counter for nights of a stay': 'ညအိပ်ရေတွက်',
  'persecution': 'ညှဉ်းပန်းနှိပ်စက်',
  'blast': 'ပေါက်ကွဲ/လေပြင်း',
  'blow up': 'ပေါက်ကွဲစေ',
  'burgeoning': 'ကြီးထွားလာခြင်း',
  'exhumation': 'အလောင်းတူးဖော်',
  'fit': 'တက်ခြင်း/ကိုက်ညီ',
  'spasm': 'ကြွက်သားကျုံ့',
  'spring (e.g. coil  leaf)': 'စပရိန်',
  'starting': 'စတင်ခြင်း',
  'attack (disease)': 'ရောဂါကျရောက်',
  '(divine) punishment': 'ဘုရားဒဏ်',
  'to leave out': 'ချန်လှပ်သည်',
  'to slip out': 'လွတ်ထွက်သည်',
  'to sneak away': 'တိတ်တဆိတ်ထွက်သည်',
  'to bring with': 'ခေါ်ဆောင်သည်',
  'to be accompanied by': 'လိုက်ပါသည်',
  'to be involved in': 'ပါဝင်သည်',
  'monogram signature': 'လက်မှတ်အမှတ်',
  'incomplete set': 'မပြည့်အစုံ',
  'fraction': 'အပိုင်းကိန်း',
  'roll of cloth (c. 10 yds.)': 'အထည်လိပ်',
  '.245 acres': 'ဧက ၀.၂၄၅',
  '300 tsubo': 'ဆူဘို ၃၀၀',
  'to be inconsistent with': 'မကိုက်ညီသည်',
  'to transgress': 'ကျူးလွန်သည်',
  'warp': 'ကွေးညွတ်',
  'curvature': 'ကွေးမှု',
  'antipathy': 'မုန်းတီးမှု',
  'animosity': 'ရန်ငြိုး',
  'echo': 'ပဲ့တင်သံ',
  'reverberation': 'ပဲ့တင်သံ',
  'repercussion': 'နောက်ဆက်တွဲသက်ရောက်',
  'reaction': 'တုံ့ပြန်မှု',
  'counterattack': 'တန်ပြန်တိုက်ခိုက်',
  'counteroffensive': 'တန်ပြန်ထိုးစစ်',
  'counterblow': 'တန်ပြန်ထိုးချက်',
  'repelling': 'တွန်းလှန်ခြင်း',
  'rebound': 'ပြန်ကန်ခြင်း',
  'recover': 'ပြန်လည်ရရှိ',
  'mutiny': 'ပုန်ကန်မှု',
  'spots': 'အစက်အပျောက်',
  'speckles': 'အစက်ငယ်များ',
  'mottles': 'အစက်ရောင်စုံ',
  'overflowing': 'လျှံကျခြင်း',
  'art print': 'ပုံနှိပ်ပန်းချီ',
  'to commit': 'ကျူးလွန်သည်',
  'to perpetrate': 'ကျူးလွန်သည်',
  'to rape': 'မုဒိမ်းကျင့်သည်',
  'prospering': 'စည်ပင်ခြင်း',
  'cardinal number suffix': 'အခြေခံဂဏန်းနောက်ဆက်',
  'voting down': 'မဲဖြင့်ပယ်ချ',
  'misery': 'ဆင်းရဲဒုက္ခ',
  'shriek': 'အော်ဟစ်သံ',
  'specific gravity': 'သိပ်သည်းဆ',
  'proportion': 'အချိုးအစား',
  'weariness': 'ပင်ပန်းမှု',
  'stone monument bearing an inscription': 'စာထွင်းကျောက်တိုင်',
  '(private) secretary': 'ကိုယ်ရေးအတွင်းဝန်',
  'to spend': 'သုံးစွဲသည်',
  'to devote': 'ဆက်ကပ်သည်',
  'taking refuge': 'ခိုလှုံခြင်း',
  'finding shelter': 'ခိုရာရှာခြင်း',
  'faulty-': 'ချို့ယွင်း-',
  'non-': 'မ-',
  'delinquency': 'ပြစ်မှုကျူးလွန်',
  'misconduct': 'မကောင်းကျင့်',
  'to provide': 'ပံ့ပိုးသည်',
  'to possess': 'ပိုင်ဆိုင်သည်',
  'to be among': 'အထဲတွင်ရှိသည်',
  'tail': 'အမြီး',
  'minuscule amount': 'အနည်းငယ်မျှ',
  'extremely small quantity': 'အလွန်နည်းသောပမာဏ',
  'required (subject)': 'မသင်မနေရဘာသာ',
  'motto': 'ဆောင်ပုဒ်',
  'slogan': 'ကြွေးကြော်သံ',
  'catchword': 'ဆွဲဆောင်စကား',
  'to drift about': 'မျောနေသည်',
  'to hang in air': 'လေထဲဆွဲနေသည်',
  'depiction': 'ပုံဖော်ခြင်း',
  'description': 'ဖော်ပြချက်',
  'portrayal': 'ပုံဖော်တင်ဆက်',
  'to fall ill': 'နာမကျန်းဖြစ်သည်',
  'to be ill': 'နေမကောင်းသည်',
  'rice seedling': 'စပါးပျိုးပင်',
  'foreshore': 'ကမ်းခြေအနီး',
  'sensibility': 'ခံစားနိုင်မှု',
  'susceptibility': 'ခံနိုင်ရည်/ထိလွယ်',
  'sensitive (to)': 'ထိခိုက်လွယ်',
  'well attuned to': 'ကောင်းစွာလိုက်ဖက်',
  'earthenware pot': 'မြေအိုး',
  'indispensable': 'မရှိမဖြစ်',
  'ominous': 'မကောင်းလက္ခဏာ',
  'sinister': 'ဆိုးရွား',
  'ill omen': 'မကောင်းနိမိတ်',
  'recession': 'စီးပွားကျဆင်း',
  'business recession': 'လုပ်ငန်းကျဆင်း',
  'hard times': 'ခက်ခဲသောကာလ',
  'unseasonableness': 'ရာသီမကိုက်',
  'bad condition': 'အခြေအနေဆိုး',
  'not to work out (ie a deal)': 'မအောင်မြင် (သဘောတူ)',
  'break-off': 'ဖြတ်တောက်ခြင်း',
  'real estate': 'အိမ်ခြံမြေ',
  'bad reputation': 'နာမည်ဆိုး',
  'unpopularity': 'လူကြိုက်မများ',
  'disapproval': 'မနှစ်သက်မှု',
  'to add one thing to another': 'တစ်ခုပေါ်တစ်ခုပေါင်း',
  'annexed': 'ပူးတွဲထား',
  'to be rich': 'ချမ်းသာသည်',
  'to become rich': 'ချမ်းသာလာသည်',
  'wealthy person': 'ချမ်းသာသူ',
  'millionaire': 'သန်းကြွယ်သူ',
  'tea-towel': 'ပန်းကန်သုတ်ပုဝါ',
  'dish cloth': 'ပန်းကန်သုတ်ထည်',
  'edict': 'အမိန့်တော်',
  'universality': 'စကြဝဠာကျယ်မှု',
  'ubiquity': 'နေရာတိုင်းရှိမှု',
  'omnipresence': 'အနှံ့အပြားရှိမှု',
  'flighty': 'မတည်ငြိမ်',
  'wanton': 'လော်လည်',
  'unfaithful': 'သစ္စာမဲ့',
  'buoyancy': 'ပေါလောမျောနိုင်မှု',
  'floating power': 'မျောအား',
  'depravity': 'ဖောက်ပြန်မှု',
  'to owe': 'ကြွေးတင်သည်',
  'wound': 'ဒဏ်ရာ',
  '(proceeding to) new appointment': 'ရာထူးသစ်သို့',
  'slight': 'နည်းနည်း/စော်ကား',
  'armament': 'လက်နက်တပ်ဆင်',
  'armed': 'လက်နက်ကိုင်',
  'armed might': 'လက်နက်အား',
  'military power': 'စစ်အင်အား',
  'the sword': 'ဓား',
  'subordinate person': 'လက်အောက်ခံ',
  'feudalistic': 'နယ်စားစနစ်ဆန်',
  'blockade': 'ပိတ်ဆို့ခြင်း',
  'freezing (funds)': 'ငွေထိန်းချုပ်',
  '1.  windmill': 'လေရဟတ်',
  '2.  pinwheel': 'လေရဟတ်ကစားစရာ',
  '1.  manners': 'ယဉ်ကျေးမှု',
  '2.  sex service': 'လိင်ဝန်ဆောင်မှု',
  'sex industry': 'လိင်လုပ်ငန်း',
  'natural features': 'သဘာဝအင်္ဂါရပ်',
  'spiritual features': 'စိတ်ဓာတ်အင်္ဂါရပ်',
  'revival (e.g. musical)': 'ပြန်လည်တင်ဆက်',
  'restitution': 'ပြန်လည်ပေးအပ်',
  'revival': 'ပြန်လည်ရှင်သန်',
  'renaissance': 'ပြန်လည်နိုးထ',
  'good fortune': 'ကံကောင်းခြင်း',
  'welfare': 'လူမှုဖူလုံရေး',
  'well-being': 'ကျန်းမာချမ်းသာ',
  'to undermine': 'အားနည်းစေသည်',
  'boiling': 'ဆူခြင်း',
  'seething': 'ဆူပွက်ခြင်း',
  'French': 'ပြင်သစ်',
  'Buddhist image (statue)': 'ဗုဒ္ဓရုပ်ပွားတော်',
  'public discussion (criticism)': 'အများဆွေးနွေး',
  'unsatisfied': 'မကျေနပ်',
  'unsatisfactory': 'မကျေနပ်ဖွယ်',
  'storeroom': 'သိုလှောင်ခန်း',
  'minute': 'မိနစ်/အသေးစိတ်',
  'division of labor': 'အလုပ်ခွဲဝေ',
  'assembly-line production': 'အစဉ်လိုက်ထုတ်လုပ်',
  'decentralization': 'ဗဟိုလျှော့ချ',
  'variance (statistics)': 'ကွဲလွဲမှု (စာရင်း)',
  'numerator': 'ပိုင်းဝေ',
  'molecule': 'မော်လီကျူး',
  'apportionment': 'ခွဲဝေခြင်း',
  'denominator': 'ပိုင်းခြေ',
  'detachment': 'ခွဲထုတ်အဖွဲ့',
  'segregation': 'ခွဲခြားခြင်း',
  'break up': 'ကွဲအက်/ခွဲထွက်',
  'spewing': 'ထွက်ပန်းခြင်း',
  'gushing': 'စီးထွက်ခြင်း',
  'spouting': 'ပန်းထွက်ခြင်း',
  'indignation': 'ဒေါသထွက်မှု',
  '(open) fire': 'ပစ်ခတ်မှု',
  'hard struggle': 'ခက်ခဲရုန်းကန်',
  'strenuous effort': 'အားစိုက်မှု',
  'in very small pieces': 'အမှုန့်အမှုန့်',
  'fine powder': 'အမှုန့်နု',
  'confusing': 'ရှုပ်ထွေးစေသော',
  'misleading': 'အထင်မှားစေသော',
  'equivocal': 'နှစ်ခုလုံးဆန်',
  'to be diverted': 'လွှဲသွားသည်',
  'to slip into': 'ချော်ဝင်သည်',
  'losing something': 'ပစ္စည်းပျောက်',
  'cultural assets': 'ယဉ်ကျေးမှုပိုင်ဆိုင်',
  'cultural property': 'ယဉ်ကျေးမှုပစ္စည်း',
  'written language': 'ရေးသားဘာသာ',
  'literary language': 'စာပေဘာသာ',
  'listening comprehension': 'နားထောင်နားလည်',
  'weapons': 'လက်နက်များ',
  'square (e.g. metre)': 'စတုရန်း',
  'shut mouth': 'ပါးစပ်ပိတ်',
  'shutdown': 'ပိတ်သိမ်း',
  'lockout': 'အလုပ်သမားပိတ်ထုတ်',
  'to be prejudiced': 'ဘက်လိုက်သည်',
  'prejudice': 'ဘက်လိုက်မှု',
  'narrow view': 'အမြင်ကျဉ်း',
  'a smattering': 'အပေါ်ယံသိ',
  'talk like a baby': 'ကလေးလိုပြော',
  'speak haltingly': 'တုန့်တုန့်ပြော',
  'tidying up': 'ရှင်းလင်းခြင်း',
  'finishing': 'ပြီးဆုံးခြင်း',
  '(in the) neighbourhood': 'အနီးအနား',
  'repayment': 'ပြန်ဆပ်ခြင်း',
  'expedience': 'အဆင်ပြေမှု',
  'pleading': 'တောင်းပန်/လျှောက်လဲ',
  'advocacy': 'ထောက်ခံပြောဆို',
  'next word': 'နောက်စကားလုံး',
  'nurturing': 'ပြုစုပျိုးထောင်',
  'lactation': 'နို့တိုက်ခြင်း',
  'retaining warmth': 'နွေးထိန်းခြင်း',
  'keeping heat in': 'အပူထိန်းခြင်း',
  'heat insulation': 'အပူကာကွယ်',
  'safekeeping': 'လုံခြုံသိမ်းဆည်း',
  'insurance': 'အာမခံ',
  'guardianship': 'အုပ်ထိန်းမှု',
  'conservative': 'ရှေးရိုးဆန်',
  'maintaining': 'ထိန်းသိမ်းခြင်း',
  'day care worker in a kindergarten  nursery school  etc.': 'ကလေးထိန်းသူ',
  'recuperation': 'ပြန်လည်နာလန်ထူ',
  'pavement': 'လမ်းခင်း',
  'road surface': 'လမ်းမျက်နှာပြင်',
  'seizure': 'သိမ်းယူခြင်း',
  'whaling': 'ငါးဝှဲဖမ်းခြင်း',
  'whale fishing': 'ငါးဝှဲဖမ်းခြင်း',
  'constable': 'ရဲတပ်သား',
  'prisoner (of war)': 'စစ်သုံ့ပန်း',
  'pawn (in chess or shogi)': 'ကြက်တောင် (စစ်တုရင်)',
  'supplying': 'ထောက်ပံ့ခြင်း',
  'reinforcement': 'အားဖြည့်ခြင်း',
  'supplementation': 'ဖြည့်စွက်ခြင်း',
  'replenishing': 'ပြန်ဖြည့်ခြင်း',
  'auxiliary': 'အရန်',
  'complement': 'ဖြည့်စွက်',
  'ear (of plant)': 'အနှံ',
  'head (of plant)': 'ပန်းပွင့်ခေါင်း',
  'fund-raising': 'ရန်ပုံငွေစုဆောင်း',
  'collection of funds': 'ငွေစုဆောင်းခြင်း',
  'cemetery': 'သင်္ချိုင်း',
  'graveyard': 'သင်္ချိုင်းမြေ',
  'to yearn for': 'တမ်းတသည်',
  'to adore': 'ချစ်ခင်မြတ်နိုးသည်',
  'to love dearly': 'အလွန်ချစ်သည်',
  'alma mater': 'မိခင်ကျောင်း',
  'to tuck in': 'ထည့်ခေါက်သည်',
  'not enough': 'မလုံလောက်',
  'too quick (short  long  etc.)': 'အလွန်မြန်/တို/ရှည်',
  'dumbfounded': 'အံ့အားသင့်',
  'overcome with surprise': 'အံ့ဩမဆုံး',
  'in blank amazement': 'မျက်စိမှိတ်အံ့ဩ',
  'remuneration': 'အခကြေးငွေ',
  'treasured article or vessel': 'တန်ဖိုးထားပစ္စည်း',
  'outstanding individual': 'ထူးချွန်သူ',
  'decay (physics)': 'ယိုယွင်း (ရူပဗေဒ)',
  'crumbling': 'ပြိုကျခြင်း',
  'breaking down': 'ပျက်စီးခြင်း',
  'to throw into': 'ပစ်ထည့်သည်',
  'abandonment': 'စွန့်ပစ်ခြင်း',
  'renunciation': 'စွန့်လွှတ်ခြင်း',
  'abdication (responsibility  right)': 'တာဝန်/အခွင့်စွန့်',
  'radiation': 'ဓာတ်ရောင်ခြည်',
  'emission': 'ထုတ်လွှတ်ခြင်း',
  'radioactivity': 'ရေဒီယိုသတ္တိကြွ',
  'leave to chance': 'ကံအပ်',
  'leave alone': 'ထားခဲ့',
  'bill (law)': 'ဥပဒေကြမ်း',
  'courtroom': 'တရားရုံးခန်း',
  'abundant harvest': 'အထွက်ကောင်း',
  'bumper crop': 'အထွက်များ',
  'saturation': 'ပြည့်ဝခြင်း',
  'beside(s)': 'အပြင်/ဘေးတွင်',
  'while': 'နေစဉ်/တဖက်',
  'windstorm': 'လေပြင်းမုန်တိုင်း',
  'gale': 'လေပြင်း',
  'violence': 'အကြမ်းဖက်မှု',
  'disclosure': 'ဖော်ထုတ်ခြင်း',
  'exposure': 'ထိတွေ့/ဖော်ထုတ်',
  'desirable': 'လိုလားဖွယ်',
  'hoped for': 'မျှော်လင့်ထား',
  'to get cross': 'စိတ်ဆိုးသည်',
  'to get sulky': 'မုန်းတီးငြင်းသည်',
  'fire prevention': 'မီးကာကွယ်',
  'fire proof': 'မီးခံ',
  'cheek': 'ပါး',
  'servant (of God)': 'ဘုရားအစေခံ',
  'pastor': 'သင်းအုပ်ဆရာ',
  'minister': 'ဓမ္မဆရာ/ဝန်ကြီး',
  'clergyman': 'ဘာသာရေးဆရာ',
  'forfeited': 'သိမ်းဆည်းခံ',
  'real intention': 'အစစ်အမှန်ရည်ရွယ်',
  'propriety': 'သင့်လျော်မှု',
  'fundamental rules': 'အခြေခံစည်းမျဉ်း',
  'main building': 'အဓိကအဆောက်အအုံ',
  'true nature': 'အစစ်အမှန်သဘော',
  'real form': 'အစစ်ပုံသဏ္ဌာန်',
  'object of worship': 'ကိုးကွယ်ရာ',
  'instinct': 'ပင်ကိုယ်သိစိတ်',
  'text (of document)': 'စာသား',
  'body (of letter)': 'စာကိုယ်',
  'real name': 'အမည်ရင်း',
  'linen': 'ပိုက်ဆံပင်ထည်',
  'anaesthesia': 'မေ့ဆေး',
  'paralysis': 'လေဖြတ်ခြင်း',
  'palsy': 'လေဖြတ်ရောဂါ',
  'numbness': 'ထုံကျင်ခြင်း',
  'stupor': 'မေ့မြောမှု',
  'to be buried': 'မြှုပ်နှံခံရသည်',
  'to be surrounded': 'ဝန်းရံခံရသည်',
  'to be filled': 'ပြည့်သည်',
  'buried property': 'မြှုပ်နှံပစ္စည်း',
  'treasure trove': 'ရတနာသိုက်',
  'counter for flat objects (e.g. sheets of paper)': 'ပြားချပ်ရေတွက်',
  'each respectively': 'အသီးသီး',
  'film': 'ဖလင်/ရုပ်ရှင်',
  'top end': 'ထိပ်ဆုံး',
  'closing years (period  days)': 'နောက်ဆုံးနှစ်များ',
  'last stage': 'နောက်ဆုံးအဆင့်',
  'all-purpose': 'အသုံးစုံ',
  'almighty': 'အနန္တတန်ခိုးရှင်',
  'omnipotent': 'အနန္တစွမ်းအား',
  'to ingratiate': 'ကြိုက်နှစ်သက်အောင်လုပ်သည်',
  'to fill': 'ဖြည့်သည်',
  'full moon': 'လပြည့်',
  'unanimous': 'တစ်ညီတစ်ညွတ်',
  'whole audience': 'ပရိသတ်အားလုံး',
  'eighth sign of Chinese zodiac (The Ram  1pm-3pm  south-southwest  June)': 'တရုတ်ရာသီခွင် ၈ (သိုး)',
  'as yet': 'ယခုထိ',
  'hitherto': 'ယခုအထိ',
  'not yet (neg)': 'မသေး (ငြင်း)',
  'savage land': 'ရိုင်းသောမြေ',
  'backward region': 'နောက်ကျဒေသ',
  'uncivilized': 'ယဉ်ကျေးမှုမရှိ',
  'inexperience': 'အတွေ့အကြုံမရှိ',
  'unripeness': 'မမှည့်သေး',
  'unskilled': 'ကျွမ်းကျင်မှုမရှိ',
  'not yet known': 'မသိရသေး',
  'not yet fixed': 'မဆုံးဖြတ်ရသေး',
  'undecided': 'မဆုံးဖြတ်ရသေး',
  'pending': 'ဆိုင်းငံ့',
  'lingering affection': 'ကျန်ရစ်ချစ်ခြင်း',
  'regret(s)': 'နောင်တ',
  'reluctance': 'မလိုလားမှု',
  'close formation': 'ကျစ်လစ်ဖွဲ့စည်း',
  'dense': 'သိပ်သည်း',
  'density': 'သိပ်သည်းဆ',
  'nectar': 'ပန်းဝတ်ရည်',
  'pulse': 'သွေးခုန်နှုန်း',
  'democratic': 'ဒီမိုကရေစီဆန်',
  'the head of the nation': 'နိုင်ငံခေါင်းဆောင်',
  'private home providing lodging for travelers': 'ခရီးသည်အိမ်တည်း',
  'unreasonably': 'မတရားစွာ',
  'absurdly': 'ရယ်စရာကောင်းစွာ',
  'indiscreetly': 'မသတိထားစွာ',
  'no meaning': 'အဓိပ္ပာယ်မရှိ',
  'invalid': 'မမှန်ကန်/မသက်ရောက်',
  'no effect': 'အကျိုးမရှိ',
  'unavailable': 'မရနိုင်',
  'simple-mindedness': 'စိတ်ရိုးသားမှု',
  'waste money on': 'ငွေဖြုန်း',
  'squander money on': 'ငွေအလဟဿသုံး',
  'flog a dead horse': 'အချည်းနှီးကြိုးစား',
  'without permission': 'ခွင့်မပြုဘဲ',
  'without notice': 'ကြိုမပြောဘဲ',
  'ignorance': 'မသိနားမလည်',
  'jumbled': 'ရောထွေး',
  'mixed up': 'ရောနှော',
  'chagrin': 'စိတ်ပျက်အားငယ်',
  'inefficiency': 'ထိရောက်မှုမရှိ',
  'incompetence': 'စွမ်းရည်မရှိ',
  'useless': 'အသုံးမဝင်',
  'needlessness': 'မလိုအပ်မှု',
  'unnecessariness': 'မလိုအပ်မှု',
  'impolite': 'မယဉ်ကျေး',
  'name plate': 'အမည်ပြား',
  'name tag': 'အမည်တံဆိပ်',
  'noted product': 'နာမည်ကြီးကုန်',
  'to name (someone)': 'အမည်ပေးသည်',
  'register of names': 'အမည်စာရင်း',
  'prestige': 'ဂုဏ်သိက္ခာ',
  'a hit': 'အောင်မြင်မှု/ထိမှန်',
  'obvious': 'ထင်ရှား',
  'overt': 'ပေါ်လွင်',
  'plainly': 'ရှင်းရှင်းလင်းလင်း',
};
