/** Cursor-agent Myanmar for N3–N1 (part 07) */
module.exports = {
  'frankly': 'ပွင့်ပွင့်လင်းလင်း',
  'clarity': 'ရှင်းလင်းမှု',
  'to be ruined': 'ပျက်စီးသည်',
  'to go under': 'နစ်မြုပ်သည်',
  'to perish': 'သေဆုံးသည်',
  'to be destroyed': 'ဖျက်ဆီးခံရသည်',
  'to wreck': 'ဖျက်ဆီးသည်',
  'to ruin': 'ပျက်စီးစေသည်',
  'downfall': 'ပျက်စီးခြင်း',
  'to be rescued from': 'ကယ်တင်ခံရသည်',
  'to evade': 'ရှောင်သည်',
  'to face on': 'မျက်နှာမူသည်',
  'to look out on to': 'မျက်နှာချင်းဆိုင်သည်',
  'pimple': 'ဝက်ခြံ',
  'acne': 'ဝက်ခြံ',
  'groping (for)': 'စမ်းတဝါးရှာခြင်း',
  'rage': 'ဒေါသ',
  'blind spot': 'မျက်စိကွယ်ရာ',
  'net': 'ပိုက်ကွန်',
  'eyelid': 'မျက်ခွံ',
  'gradations': 'အဆင့်ဆင့်',
  'catalogue': 'ကတ်တလောက်',
  'catalog': 'ကတ်တလောက်',
  'to enquire': 'မေးမြန်းသည်',
  'to seek information': 'သတင်းရှာသည်',
  'wholesale store': 'လက်ကားဆိုင်',
  'bedding': 'အိပ်ရာခင်း',
  'staying up late': 'ညဉ့်နက်အိပ်မပျော်',
  'keeping late hours': 'ညဉ့်နက်ထိုင်ခြင်း',
  'sitting up late at night': 'ညဉ့်နက်ထိုင်ခြင်း',
  'nighthawk': 'ညဉ့်လူ',
  'the whole night': 'တညလုံး',
  'designs': 'ပုံစံများ',
  'treachery': 'သစ္စာဖောက်မှု',
  'opposition party': 'အတိုက်အခံပါတီ',
  'town hall': 'မြို့တော်ခန်းမ',
  'oil painting': 'ဆီဆေးပန်းချီ',
  'affectionate': 'ချစ်ခင်သော',
  'ascendancy': 'လွှမ်းမိုးမှု',
  'being superior to': 'သာလွန်ခြင်း',
  'superior power': 'သာလွန်အား',
  'preponderance': 'လွှမ်းမိုးအား',
  'preference': 'ဦးစားပေး',
  'priority': 'ဦးစားပေး',
  'heroism': 'ရဲစွမ်းသတ္တိ',
  'gallantry': 'ရဲရင့်မှု',
  'specter': 'ဘီလူး',
  'phantom': 'အရိပ်',
  'dejection': 'စိတ်ညစ်ခြင်း',
  'to own': 'ပိုင်ဆိုင်သည်',
  'beneficial': 'အကျိုးရှိသော',
  'organic': 'သဘာဝအတိုင်း',
  'good prospects': 'မျှော်လင့်ချက်ကောင်း',
  'full of hope': 'မျှော်လင့်ချက်ပြည့်',
  '1.  influence': '၁. လွှမ်းမိုးမှု',
  'prominence': 'ထင်ပေါ်မှု',
  '2.  potent': '၂. အစွမ်းထက်',
  'temptation': 'သွေးဆောင်မှု',
  'allurement': 'ဆွဲဆောင်မှု',
  'lure': 'သွေးဆောင်ရာ',
  'nomadism': 'ခြေသလုံးလှည့်ခြင်း',
  'male (animal)': 'အထီး (တိရစ္ဆာန်)',
  'financing': 'ငွေကြေးထောက်ပံ့',
  'lending (money)': 'ငွေချေးခြင်း',
  'adaptability': 'လိုဆင်နိုင်မှု',
  'versatility': 'စုံလင်မှု',
  'presentiment': 'ကြိုတင်ခံစားမှု',
  'premonition': 'ရှေ့ပြေးလက္ခဏာ',
  'anticipation': 'မျှော်မှန်းခြင်း',
  'leisure time': 'အားလပ်ချိန်',
  'spare time': 'အချိန်ပို',
  'side show': 'ဘေးဖက်ပြပွဲ',
  'entertainment': 'ဖျော်ဖြေရေး',
  'looking away': 'မျက်စိလွှဲခြင်း',
  'looking aside': 'ဘေးသို့ကြည့်ခြင်း',
  'bank account': 'ဘဏ်အကောင့်',
  'aspect': 'ရှုထောင့်',
  'western style': 'အနောက်တိုင်းပုံစံ',
  'solution (liquid)': 'ဖျော်ရည်',
  'blank form': 'ပုံစံစာရွက်',
  'articles': 'ပစ္စည်းများ',
  'supplies': 'ထောက်ပံ့ပစ္စည်း',
  'rules of use': 'အသုံးပြုနည်းစည်း',
  'primary factor': 'အဓိကအကြောင်း',
  'main cause': 'အဓိကအကြောင်းရင်း',
  'protective care': 'ကာကွယ်စောင့်ရှောက်',
  'greedy': 'လိုက်မက်သော',
  'appetite': 'အငတ်အပြေ',
  'barefoot': 'ခြေဗလာ',
  'to entangle': 'ရစ်ပတ်သည်',
  'to entwine': 'ရစ်ယှက်သည်',
  'to fall into': 'ကျရောက်သည်',
  'to feel down (sad)': 'စိတ်ညစ်သည်',
  'fallen leaves': 'ရွက်ကြွေ',
  'leaf litter': 'ရွက်ခြောက်',
  'defoliation': 'ရွက်ကြွေခြင်း',
  'shedding leaves': 'ရွက်ကြွေခြင်း',
  'dairy (farm)': 'နို့ခြံ',
  'to throw out of order': 'ရှုပ်ထွေးစေသည်',
  'to disarrange': 'ရောထွေးစေသည်',
  'to get confused': 'ရှုပ်ထွေးသည်',
  'to be disordered': 'မရိပ်မရာဖြစ်သည်',
  'to be disturbed': 'နှောင့်ယှက်ခံရသည်',
  'misuse': 'အလွဲသုံး',
  'misappropriation': 'အလွဲအသုံးပြု',
  'using to excess': 'အလွန်အကျွံသုံး',
  'point in favor': 'အားသာချက်',
  'log': 'သစ်လုံး',
  'inside out': 'ပြန်လှန်',
  'to stop by': 'လမ်းဆုံဝင်သည်',
  'to drop in for a short visit': 'ခဏဝင်ကြည့်သည်',
  'solid body': 'အစိုင်အခဲ',
  'dancing (geisha)': 'ကခုန်ခြင်း (ဂေရှ)',
  'legislation': 'ဥပဒေပြုခြင်း',
  'lawmaking': 'ဥပဒေပြုခြင်း',
  'acronym': 'အတိုကောက်',
  'pillage': 'လုယက်ခြင်း',
  'plunder': 'လုယက်ခြင်း',
  'looting': 'ဓားပြတိုက်ခြင်း',
  'styleof': 'ပုံစံ',
  'method of': 'နည်းလမ်း',
  'manner of': 'ပုံစံ',
  'circulation of money or goods': 'ငွေ/ကုန်လည်ပတ်မှု',
  'flow of water or air': 'ရေ/လေစီးဆင်းမှု',
  'collected things': 'စုဆောင်းပစ္စည်း',
  'gathering place': 'စုဝေးရာနေရာ',
  'passenger (transport)': 'ခရီးသည်',
  'roger (on the radio)': 'နားလည်ပါပြီ (ရေဒီယို)',
  'understanding (e.g. please be understanding of the mess during our renovation)': 'နားလည်မှု',
  'both extremities': 'အစွန်းနှစ်ဖက်',
  'north and south poles': 'မြောက်တောင်ဝင်ရိုး',
  'positive and negative poles': 'အပေါင်းအနုတ်ဝင်ရိုး',
  'compatibility': 'လိုက်ဖက်မှု',
  'standing together': 'အတူရပ်တည်ခြင်း',
  'to outdo': 'ကျော်လွန်သည်',
  'to keep out (rain)': 'ကာကွယ်သည် (မိုး)',
  'good sense': 'ကောင်းသောအသိ',
  'good quality': 'အရည်အသွေးကောင်း',
  'superior quality': 'အရည်အသွေးမြင့်',
  'conscience': 'သိက္ခာစိတ်',
  'territorial waters': 'ပိုင်နက်ရေပိုင်',
  'forestry': 'သစ်တောလုပ်ငန်း',
  'counter for wheels and flowers': 'ဘီး/ပန်းရေတွက်',
  'analogous': 'ဆင်တူသော',
  'analogy': 'နှိုင်းယှဉ်ချက်',
  'coldheartedness': 'စိတ်မေတ္တာမဲ့',
  'relentless': 'မညှာမတာ',
  'ruthless': 'ရက်စက်သော',
  'to cheer': 'အားပေးသည်',
  'to raise (the voice)': 'အသံမြှင့်သည်',
  'to be zealous': 'အားထုတ်သည်',
  'to brace oneself': 'ကိုယ်ကိုတင်းသည်',
  'to endeavour': 'ကြိုးပမ်းသည်',
  'to strive': 'ကြိုးစားသည်',
  'to burst': 'ပေါက်ကွဲသည်',
  'to knead': 'နယ်သည်',
  'to work over': 'ပြန်လုပ်သည်',
  'to polish up': 'ပွတ်တိုက်သည်',
  'to stretch out': 'ဆန့်ထုတ်သည်',
  'to stand in a row': 'တန်းစီရပ်သည်',
  'to link': 'ချိတ်ဆက်သည်',
  'consecutive holidays': 'ဆက်တိုက်အားလပ်ရက်',
  'solidarity': 'စည်းလုံးမှု',
  'commonwealth': 'ဓနသဟာယ',
  'federation of states': 'ပြည်နယ်များအဖွဲ့',
  'to pity': 'သနားသည်',
  'to sympathize with': 'စာနာသည်',
  'to care for': 'ဂရုစိုက်သည်',
  'reading aloud': 'ကျယ်လောင်ဖတ်ခြင်း',
  'recitation': 'ရွတ်ဆိုခြင်း',
  'to let leak': 'ယိုစိမ့်စေသည်',
  'to reveal': 'ဖော်ထုတ်သည်',
  'to leak': 'ယိုသည်',
  'to seclude oneself': 'တစ်ဦးတည်းနေသည်',
  'to be confined in': 'ပိတ်လှောင်ခံရသည်',
  'to be implied': 'ပါရှိသည်',
  'to be stuffy': 'လေမဝဖြစ်သည်',
  'senility': 'အိုမင်းရင့်ရော်',
  'senile decay': 'အိုမင်းပျက်စီး',
  '(num) six': '(ဂဏန်း) ခြောက်',
  'logic': 'ယုတ္တိ',
  'to soften': 'ပျော့ပျောင်းစေသည်',
  'to moderate': 'လျှော့ချသည်',
  'Japanese style': 'ဂျပန်ပုံစံ',
  'Japanese text': 'ဂျပန်စာသား',
  'sentence in Japanese': 'ဂျပန်ဝါကျ',
  'to swerve': 'လွဲသည်',
  'to deflect': 'ကွေ့သည်',
  'to be crooked': 'ကောက်သည်',
  'planet': 'ဂြိုဟ်',
  'my son': 'ကျွန်ုပ်သား',
  'methodical': 'စနစ်တကျ',
  'punctual': 'အချိန်မှန်',
  'steady': 'တည်ငြိမ်သော',
  'skinflint': 'စေးကပ်သူ',
  'to find fault': 'အပြစ်ရှာသည်',
  'to take someone to task': 'အပြစ်တင်သည်',
  'to aggravate (an injury)': 'ပိုဆိုးစေသည်',
  'to mutter': 'ညည်းညူသည်',
  'to roar': 'ဟောက်သည်',
  'to howl': 'ဟောင်သည်',
  'Alas!': 'အို!',
  'abundantly': 'ပေါများစွာ',
  'innumerably': 'မရေတွက်နိုင်အောင်',
  'euphemistic': 'သိမ်မွေ့သော',
  'circumlocution': 'လှည့်ပတ်ပြောခြင်း',
  'roundabout': 'လှည့်ပတ်သော',
  'indirect': 'သွယ်ဝိုက်သော',
  'supple': 'ပျော့ပျောင်းသော',
  'elastic': 'ပျော့ညံ့သော',
  'excreta': 'ကျင်ငယ်စွန့်',
  'raw sewage': 'ရေဆိုး',
  'human waste': 'လူ့အညစ်အကြေး',
  'night soil': 'ညဥ့်မြေဩဇာ',
  'to pinch': 'ညှစ်သည်',
  'to get complicated': 'ရှုပ်ထွေးသည်',
  'to grow worse': 'ပိုဆိုးလာသည်',
  'ticklish': 'ယားယံသော',
  'to pluck': 'နှုတ်သည်',
  'to pick': 'ရွေးသည်',
  'frank': 'ပွင့်လင်းသော',
  'open-hearted': 'စိတ်ပွင့်လင်းသော',
  'to play on words': 'စကားလုံးကစားသည်',
  'to dress stylishly': 'စတိုင်ကျဝတ်သည်',
  'to dry up': 'ခြောက်သွေ့သည်',
  'to stir-fry': 'ကြော်သည်',
  'brilliantly': 'တောက်ပစွာ',
  'brightly': 'လင်းလက်စွာ',
  'gaudy': 'ပြောင်ပြောင်တောက်သော',
  'to go to sleep (i.e.  a limb)': 'ထုံကျင်သည်',
  'wrinkles': 'အရေးအကြောင်း',
  'creases': 'အရေးအကြောင်း',
  'to close the eyes': 'မျက်စိပိတ်သည်',
  'decent': 'သင့်တင့်သော',
  'drawn lot': 'မဲနှိုက်ခြင်း',
  'flower bud': 'ပန်းဖူး',
  'to give an order': 'အမိန့်ပေးသည်',
  'to place an order': 'မှာယူသည်',
  '(shoe) heel': '(ဖိနပ်) ဖနောင့်',
  'to jar': 'တုန်ခါသည်',
  'to creak': 'ကြိတ်သည်',
  'to grate': 'ပွတ်သည်',
  'wince': 'မျက်နှာရှုံ့',
  'shrink back': 'နောက်ဆုတ်',
  'succumbing to': 'ကြောက်ရွံ့ခြင်း',
  'being frightened': 'ခြောက်လန့်ခြင်း',
  'germ(s)': 'ပိုးမွှား',
  'snoring': 'ဟောက်သံ',
  'debate': 'ဆွေးနွေးငြင်းခုန်',
  'sutra': 'ကျမ်းစာ',
  'pass thru': 'ဖြတ်သန်း',
  'expire': 'သက်တမ်းကုန်',
  'task': 'အလုပ်တာဝန်',
  'duties': 'တာဝန်များ',
  'products': 'ထုတ်ကုန်များ',
  'give birth': 'မွေးဖွား',
  'being helped': 'ကူညီခံရခြင်း',
  'mingle': 'ရောနှော',
  'coming & going': 'သွားလာခြင်း',
  'yonder': 'ဟိုဘက်',
  'beyond': 'ကျော်လွန်',
  'tell': 'ပြောပြ',
  'inform': 'အကြောင်းကြား',
  'announce': 'ကြေညာ',
  'anti-': 'ဆန့်ကျင်-',
  'construct': 'တည်ဆောက်',
  'argument': 'အငြင်းအခုံ',
  'discourse': 'စကားပြော',
  'the government': 'အစိုးရ',
  'launch into': 'စတင်ဝင်ရောက်',
  'knock': 'ခေါက်',
  'pound': 'ထု',
  'straightaway': 'ချက်ချင်း',
  'fix': 'ပြင်ဆင်',
  'contend': 'ယှဉ်ပြိုင်',
  'argue': 'ငြင်းခုန်',
  'adhere': 'လိုက်နာ',
  'wherefore': 'ဘာကြောင့်',
  'a reason': 'အကြောင်းရင်း',
  'tenderness': 'နူးညံ့မှု',
  'extinguish': 'ငြိမ်းသတ်',
  'blow out': 'မှုတ်ငြိမ်း',
  'turn off': 'ပိတ်',
  'turn': 'လှည့်',
  'number in a series': 'အစဉ်အရေအတွက်',
  'distribute': 'ဖြန့်ဝေ',
  'spouse': 'အိမ်ထောင်ဖက်',
  'rationing': 'ခွဲတမ်းပေးခြင်း',
  'call on': 'လည်ပတ်',
  'look up': 'မော့ကြည့်',
  'offer sympathy': 'စာနာမှုပြ',
  'labor': 'အလုပ်သမား',
  'thank for': 'ကျေးဇူးတင်',
  'reward for': 'ဆုလာဘ်',
  'toil': 'ပင်ပန်းမှု',
  'restrict': 'ကန့်သတ်',
  'to best of ability': 'တတ်နိုင်သမျှ',
  'make a deal': 'စီးပွားလုပ်',
  'dealing in': 'ရောင်းဝယ်ခြင်း',
  'fond': 'နှစ်သက်သော',
  'pleasing': 'နှစ်သက်ဖွယ်',
  'like something': 'ကြိုက်နှစ်သက်',
  '-': '-',
  'have the honor to': 'ဂုဏ်ယူစွာ',
  'sign of the monkey': 'မျောက်ရာသီ',
  '3-5PM': 'မွန်းလွဲ ၃-၅',
  'ninth sign of Chinese zodiac': 'တရုတ်ဆယ့်နှစ်ရာသီ ၉',
  'call out to': 'ခေါ်ဆို',
  'protruding': 'ထွက်နေသော',
  'thrust': 'ထိုးထွက်',
  'product (x*y)': 'မြှောက်လဒ်',
  'acreage': 'ဧရိယာ',
  'big around': 'ပတ်လည်ကြီး',
  'ascend': 'တက်',
  'climb up': 'တက်သွား',
  'skip (pages)': 'စာမျက်နှာကျော်',
  'division (x/3)': 'စားလဒ်',
  'blame': 'အပြစ်တင်',
  'condemn': 'ရှုတ်ချ',
  'suffering': 'ဒုက္ခ',
  'hardship': 'ခက်ခဲမှု',
  'enrich': 'ချမ်းသာစေ',
  'deceased': 'ကွယ်လွန်သူ',
  'the late': 'ကွယ်လွန်ပြီး',
  'dying': 'သေဆုံးခြင်း',
  'in bulk': 'အမြောက်အများ',
  'included': 'ပါဝင်သော',
  'precipitous': 'မတ်စောက်သော',
  'impregnable position': 'အလွန်ခိုင်ခံ့ရာ',
  'steep place': 'မတ်စောက်နေရာ',
  'slip out': 'ထွက်လွတ်',
  'pull out': 'ဆွဲထုတ်',
  'disperse': 'ပြန့်ကြဲ',
  'spend': 'သုံးစွဲ',
  'squander': 'ဖြုန်းတီး',
  'floating': 'မျောနေသော',
  'float': 'မျော',
  'rise to surface': 'မျက်နှာပြင်ပေါ်တက်',
  'sever': 'ဖြတ်',
  'cut off': 'ဖြတ်တောက်',
  'abstain': 'ရှောင်ကြဉ်',
  'old age': 'အိုမင်း',
  'grow old': 'အိုလာ',
  'pay': 'ပေးချေ',
  'clear out': 'ရှင်းလင်း',
  'prune': 'ညှပ်ဖြတ်',
  'banish': 'နှင်ထုတ်',
  'diligence': 'ကြိုးစားအားထုတ်',
  'become employed': 'အလုပ်ရသည်',
  'miscellaneous': 'ရောနှောသော',
  'beckon': 'လက်ဟန်ခေါ်',
  'summon': 'ဆင့်ခေါ်',
  'engage': 'ခန့်အပ်',
  'quandary': 'အကျပ်အတည်း',
  'become distressed': 'ဒုက္ခရောက်သည်',
  'annoyed': 'စိတ်အနှောင့်အယှက်',
  'title or inscription on picture': 'ပုံခေါင်းစဉ်',
  'assist': 'ကူညီ',
  'embrace': 'ပွေ့ဖက်',
  'hug': 'ပွေ့ဖက်',
  'hold in arms': 'လက်နှစ်ဖက်ဖြင့်ကိုင်',
  'cross over': 'ဖြတ်ကျော်',
  'move to': 'ပြောင်းရွှေ့',
  'exceed': 'ကျော်လွန်',
  'becoming': 'ဖြစ်လာသော',
  'resemble': 'တူသည်',
  'grope': 'စမ်းတဝါးရှာ',
  'flee': 'ထွက်ပြေး',
  'shirk': 'ရှောင်လွှဲ',
  'astray': 'လမ်းမှား',
  'be perplexed': 'ရှုပ်ထွေးသည်',
  'in doubt': 'သံသယရှိ',
  'lost': 'ပျောက်ဆုံး',
  'closed': 'ပိတ်သော',
  'shut': 'ပိတ်',
  'proceed': 'ရှေ့ဆက်',
  'steal': 'ခိုး',
  'suck': 'စုပ်',
  'imbibe': 'သောက်သုံး',
  'inhale': 'ရှူသွင်း',
  'sip': 'ငုံ့သောက်',
  'govern': 'အုပ်ချုပ်',
  'inquire into': 'စုံစမ်း',
  'probe': 'စူးစမ်း',
  'accustomed': 'ကျင့်သားရသော',
  'get used to': 'အသားကျသည်',
  'become experienced': 'အတွေ့အကြုံရသည်',
  'once upon a time': 'ရှေးကာလက',
  'old times': 'ရှေးခေတ်',
  'swim': 'ရေကူး',
  'founder': 'နစ်မြုပ်',
  'exhausted': 'ပင်ပန်းလွန်း',
  'weary': 'ပင်ပန်းသော',
  'fearful': 'ကြောက်ရွံ့သော',
  'hair of the head': 'ဦးခေါင်းဆံပင်',
  'years old': 'အသက်နှစ်',
  'cubic shaku': 'ကုဗရှားကု',
  'dishonor': 'အရှက်ရခြင်း',
  'man & wife': 'ဇနီးမောင်နှံ',
  'co-': 'ပူးတွဲ-',
  'ward': 'ရပ်ကွက်',
  'jurisdiction': 'တရားစီရင်ပိုင်နက်',
  'fief': 'နယ်မြေ',
  'borough': 'မြို့နယ်',
  'urban prefecture': 'မြို့ပြစီရင်စု',
  'representative body': 'ကိုယ်စားလှယ်အဖွဲ့',
  'investigate': 'စုံစမ်းစစ်ဆေး',
  'committee': 'ကော်မတီ',
  'leave to': 'အပ်နှံ',
  'devote': 'ဆက်ကပ်',
  'become serious': 'တည်ကြည်လာ',
  'forces': 'တပ်ဖွဲ့',
  'military strength': 'စစ်အင်အား',
  'make good': 'ပြန်လည်ဖြည့်',
  'offset': 'ချေဖျက်',
  'region': 'ဒေသ',
  'province': 'ပြည်နယ်',
  'military': 'စစ်တပ်',
  'chivalry': 'ရဲဝံ့မှု',
  'correspond to': 'ကိုက်ညီ',
  'proportionate to': 'အချိုးကျ',
  'environs': 'ပတ်ဝန်းကျင်',
  'incur': 'ခံရ',
  'brood over': 'စဉ်းစားနေ',
  'restore': 'ပြန်လည်ထူထောင်',
  'return to': 'ပြန်သွား',
  'revert': 'ပြန်လည်ဖြစ်',
  'resume': 'ပြန်စ',
  'own': 'ပိုင်ဆိုင်',
  'have': 'ရှိသည်',
  'staple': 'အဓိကကုန်',
  'stinger': 'အဆိပ်အတောက်',
  'exclusive': 'သီးသန့်',
  'solely': 'သက်သက်',
  'storey': 'ထပ်ခိုး',
  'stair': 'လှေကားထစ်',
  'counter for storeys of a building': 'အဆောက်အအုံထပ်ရေတွက်',
  'efficacy': 'ထိရောက်မှု',
  'government ministry': 'အစိုးရဝန်ကြီးဌာန',
  'conserve': 'ထိန်းသိမ်း',
  'omit': 'ချန်လှပ်',
  'knit': 'ရက်ကန်း',
  'locate': 'တည်နေရာရှာ',
  'transcend': 'ကျော်လွန်',
  'heal': 'ကုသ',
  'compete with': 'ယှဉ်ပြိုင်',
  'bid': 'လေလံတင်',
  'sell at auction': 'လေလံရောင်း',
  'jammed in': 'ပိတ်ဆို့နေ',
  'mediate': 'ကြားဝင်',
  'concern oneself with': 'စိုးရိမ်ပူပန်',
  'radical': 'အစွန်းရောက်',
  'head (pimple)': 'ဦးခေါင်း (ဝက်ခြံ)',
  'passage of time': 'အချိန်ကုန်လွန်မှု',
  'attire': 'ဝတ်စားဆင်ယင်',
  'navigate': 'သင်္ဘောမောင်း',
  'cruise': 'ခရီးနှင်',
  'forbid': 'တားမြစ်',
  'inverted': 'ပြောင်းပြန်',
  'wicked': 'ဆိုးယုတ်သော',
  'old story': 'ဟောင်းနွမ်းဇာတ်လမ်း',
  'outburst': 'ပေါက်ကွဲမှု',
  'rave': 'ရူးမိုက်',
  'fret': 'စိတ်ပူ',
  'purify': 'သန့်စင်',
  'cleanse': 'ဆေးကြော',
  'exorcise': 'နှင်ထုတ်',
  'hundred million': 'သန်းတစ်ရာ',
  '10**8': '၁၀^၈',
  'push': 'တွန်း',
  'overwhelm': 'လွှမ်းမိုး',
  'halt': 'ရပ်တန့်',
  'stopping': 'ရပ်ခြင်း',
  'burst open': 'ပေါက်ကွဲဖွင့်',
  'pop': 'ပေါက်',
  'Poland': 'ပိုလန်',
  'sash': 'ခါးပတ်',
  'belt': 'ခါးပတ်',
  'obi': 'အိုဘိ',
  'prolong': 'ကြာရှည်စေ',
  'feathers': 'အမွေးများ',
  'counter for birds, rabbits': 'ငှက်/ယုန်ရေတွက်',
  'harden': 'မာကျော',
  'curdle': 'ခဲသည်',
  'shorten': 'တိုစေ',
  'lightly': 'ပေါ့ပေါ့ပါးပါး',
  'trifling': 'သေးငယ်သော',
  'unimportant': 'မအရေးကြီးသော',
  'afflicted': 'ခံစားရသော',
  'disease': 'ရောဂါ',
  'suffer from': 'ရောဂါခံရ',
  'be ill': 'နေမကောင်း',
  'stratum': 'အလွှာ',
  'social class': 'လူမှုအဆင့်',
  'layer': 'အလွှာ',
  'story': 'ဇာတ်လမ်း',
  'printing block': 'ပုံနှိပ်တုံး',
  'printing plate': 'ပုံနှိပ်ပြား',
  'entwine': 'ရစ်ပတ်',
  'coil around': 'ရစ်ခွေ',
  'get caught in': 'ပိတ်မိသည်',
  'recruit': 'စုဆောင်းခေါ်',
  'campaign': 'လှုံ့ဆော်ရေး',
  'gather (contributions)': 'လှူဒါန်းစု',
  'enlist': 'စုဆောင်းခေါ်',
  'France': 'ပြင်သစ်',
  'exploits': 'စွမ်းဆောင်မှုများ',
  'unreeling cocoons': 'ပိုးအိမ်ချည်ထုတ်',
  'blend': 'ရောနှော',
  'rise up': 'ထလာ',
  'seasons': 'ရာသီများ',
  'document': 'စာရွက်စာတမ်း',
  'records': 'မှတ်တမ်းများ',
  'incense': 'နံ့သာ',
  'Buddhist temple': 'ဗုဒ္ဓကျောင်းတော်',
  'quake': 'ငလျင်',
  'tremble': 'တုန်ရီ',
  'quiver': 'တုန်ခါ',
  'reliant': 'မှီခိုသော',
  'depend on': 'မှီခို',
  'enroll': 'စာရင်းသွင်း',
  'domiciliary register': 'အိမ်ထောင်စုစာရင်း',
  'membership': 'အဖွဲ့ဝင်ဖြစ်မှု',
  'sheet of...': 'ချပ်...',
  'counter for flat thin objects or sheets': 'ပြားချပ်ရေတွက်',
  'stagecoach stop': 'စခန်းမှတ်တိုင်',
  'glory': 'ဂုဏ်ကျက်သရေ',
  'tag': 'တံဆိပ်',
  'counter for bonds': 'ငွေချေးစာချုပ်ရေတွက်',
  'placard': 'ဆိုင်းဘုတ်',
  'tilt': 'စောင်း',
  'glow': 'တောက်ပ',
  'wrap': 'ထုပ်ပိုး',
  'pack up': 'ထုပ်သည်',
  'stop-over': 'လမ်းခရီးနား',
  'reside in': 'နေထိုင်',
  'employ': 'အလုပ်ခန့်',
  'leave with': 'အပ်နှံထား',
  'bake': 'ဖုတ်',
  'entrails': 'အတွင်းအင်္ဂါ',
  'illuminate': 'လင်းအောင်လုပ်',
  'bashful': 'ရှက်သော',
  'second (1/60 minute)': 'စက္ကန့်',
  'counter for pairs': 'အတွဲရေတွက်',
  'prick': 'ထိုး',
  'awe': 'ကြောက်ရွံ့မှု',
  'fishery': 'ငါးဖမ်းလုပ်ငန်း',
  'laid waste': 'ပျက်စီးသော',
  'be filled up': 'ပြည့်နေသည်',
  'embedded': 'မြှုပ်ထားသော',
  'offer prayers': 'ဆုတောင်း',
  'deify': 'နတ်ကဲ့သို့ကိုးကွယ်',
  'be favored with': 'ကျေးဇူးခံရ',
  'bask in': 'နေခြည်ခံ',
  'valuables': 'တန်ဖိုးရှိပစ္စည်း',
  'portent': 'ရှေ့ပြေးလက္ခဏာ',
  '10**12': '၁၀^၁၂',
  'trillion': 'ထရီလျံ',
  'revered': 'ရိုသေသော',
  'sap': 'အရည်',
  'childhood': 'ကလေးဘဝ',
  'shoulder-pole load': 'ပခုံးထမ်းဝန်',
  'bear (a burden)': 'ဝန်ထမ်း',
  'shoulder (a gun)': 'သေနတ်ထမ်း',
  'overnight stay': 'ညအိပ်ရပ်နား',
  'put up at': 'တည်းခို',
  'ride at anchor': 'ကျောက်ဆူးချ',
  'sweep': 'တံမြက်လှည်း',
  'dig': 'တူး',
  'delve': 'နက်နက်တူး',
  'excavate': 'တူးဖော်',
  'be submerged': 'နစ်မြုပ်သည်',
  'subside': 'နိမ့်ဆင်း',
  'be depressed': 'စိတ်ဓာတ်ကျ',
  'frozen': 'အေးခဲသော',
  'refrigerate': 'အအေးခံ',
  'romance': 'ချစ်ဇာတ်လမ်း',
  'in love': 'ချစ်မိနေ',
  'crimson': 'ကြက်သွေးရောင်',
  'loins': 'ခါး',
  'hips': 'တင်ပါး',
  'waist': 'ခါး',
  'low wainscoting': 'နိမ့်နံရံ',
  'charcoal': 'မီးသွေး',
  'tome': 'အုပ်',
  'cheer up': 'အားတက်',
  'be in high spirits': 'စိတ်ဓာတ်မြင့်',
  'ebb': 'ရေကျဆင်း',
  'thaw': 'ရေခဲပျော်',
  'ore': 'သတ္တုရိုင်း',
  'plaster': 'အင်္ဂတေ',
  'daub': 'လိမ်း',
  'smear': 'သုတ်လိမ်း',
  'flats': 'တိုက်ခန်းများ',
  'venom': 'အဆိပ်',
  'exclaim': 'အော်ဟစ်',
  'pray to': 'ဆုတောင်း',
  'icicle': 'ရေခဲချောင်း',
  'drought': 'မိုးခေါင်',
  'desiccate': 'ခြောက်သွေ့စေ',
  'drink up': 'သောက်ကုန်',
  'pray': 'ဆုတောင်း',
  'flour': 'မှုန့်',
  'perspire': 'ချွေးထွက်',
  'damp': 'စိုစွတ်',
  'moist': 'စိုသော',
  'vial': 'ပုလင်းငယ်',
  'jar': 'အိုး',
  'jug': 'အိုးကြီး',
  'blossom': 'ပွင့်',
  'bloom': 'ပွင့်ဖူး',
  'jar radical (no. 121)': 'အိုးရက်ဒီကယ် (၁၂၁)',
  'heat': 'အပူ',
  'foment': 'ပူနွေးစေ',
  'till': 'ထွန်ယက်',
  'plow': 'ထွန်',
  'mire': 'ရွှံ့ညွန်',
  'be attached to': 'တွယ်တာ',
  'barley': 'မုယော',
  'cylinder': 'ဆလင်ဒါ',
  'gun barrel': 'သေနတ်ပြောင်း',
  'part of speech': 'စကားလုံးအမျိုးအစား',
  'tatami mat': 'တာတာမိ',
  'counter for tatami mats': 'တာတာမိရေတွက်',
  'fold': 'ခေါက်',
  'shut up': 'ပိတ်ထား',
  'laundry': 'အဝတ်လျှော်',
  'pour on': 'ပေါ်လောင်း',
  'rinse': 'ဆေးကြော',
  'steeple': 'မျှော်စင်',
  'ashes': 'ပြာ',
  'cremate': 'မီးသင်္ဂြိုဟ်',
  'headgear': 'ဦးထုပ်',
  'token': 'အမှတ်တရ',
  'tally': 'တံဆိပ်',
  'domestic fowl and animals': 'အိမ်မွေးတိရစ္ဆာန်',
  'between': 'ကြားတွင်',
  'No.': 'အမှတ်',
  'propose': 'အဆိုပြု',
  'take along': 'ခေါ်ဆောင်',
  'carry in hand': 'လက်ဖြင့်ကိုင်',
  'wisteria': 'ဝစတီးရီးယား',
  'marsh': 'စိုစွတ်မြေ',
  'brilliance': 'တောက်ပမှု',
  'unfold': 'ဖြန့်',
  'spontaneously': 'အလိုအလျောက်',
  'Germany': 'ဂျာမနီ',
  'counter for bows & stringed instruments': 'လေး/ကြိုးတူရိယာရေတွက်',
  'put up (tent)': 'တဲထောင်',
  'accusation': 'စွပ်စွဲချက်',
  'complain of pain': 'နာကျင်ကြောင်းပြော',
  'appeal to': 'တိုင်ကြား',
  'stocks': 'ရှယ်ယာများ',
  'stump': 'ငုတ်တို',
  'shares': 'ရှယ်ယာများ',
  'great numbers': 'အရေအတွက်များ',
  'multitude': 'လူအုပ်ကြီး',
  'populace': 'ပြည်သူ',
  'evaluate': 'အကဲဖြတ်',
  'pine tree': 'ထင်းရှူးပင်',
  'core': 'အူတိုင်',
  'organize': 'စီမံဖွဲ့စည်း',
  'arranging': 'စီစဉ်ခြင်း',
  'made in...': '...တွင်ပြုလုပ်',
  'go cross': 'ဖြတ်သွား',
  'infer': 'ခန့်မှန်း',
  'suppose': 'ယူဆ',
  'samurai radical (no. 33)': 'ဆာမူရိုင်းရက်ဒီကယ် (၃၃)',
  'impart': 'ပေးအပ်',
  'instruct': 'သင်ကြား',
  'sponsor': 'ပံ့ပိုး',
  'hold (a meeting)': 'အစည်းအဝေးကျင်းပ',
  'give (a dinner)': 'ညစာကျွေး',
  'detach': 'ခွဲထုတ်',
  'disjoin': 'ခွဲခြား',
  'digress': 'လမ်းလွဲ',
  'get excited': 'စိတ်လှုပ်ရှား',
  'enraged': 'ဒေါသထွက်',
  'pick': 'ရွေး',
  'counter for sons': 'သားရေတွက်',
  'alliance': 'မဟာမိတ်',
  'oath': 'ကျမ်းကျိန်',
  'broaden': 'ကျယ်ပြန့်စေ',
  'extend': 'တိုးချဲ့',
  'enlarge': 'ချဲ့ထွင်',
  'stern': 'ကြမ်းတမ်းသော',
  'strictness': 'တင်းကျပ်မှု',
  'severity': 'ပြင်းထန်မှု',
  'rigidity': 'မာကျောမှု',
  'seacoast': 'ပင်လယ်ကမ်း',
  'bequeath': 'အမွေပေး',
  'leave behind': 'ချန်ထား',
  'bases': 'အခြေစိုက်စခန်း',
  'fort': 'ခံတပ်',
  'rampart': 'မြို့ရိုး',
  'walls': 'နံရံများ',
  'elementary': 'မူလတန်း',
  'defy': 'ဖီဆန်',
  'obsolete': 'ဟောင်းနွမ်းသော',
  'cessation': 'ရပ်စဲခြင်း',
  'discarding': 'စွန့်ပစ်ခြင်း',
  'prosper': 'ကြွယ်ဝ',
  'copulate': 'မိတ်လိုက်',
  'step': 'ခြေလှမ်း',
  'trample': 'နင်း',
  'carry through': 'ပြီးမြောက်အောင်လုပ်',
  'appraise': 'တန်ဖိုးဖြတ်',
  'bond': 'ငွေချေးစာချုပ်',
  'hinder': 'ဟန့်တား',
  'interment': 'သင်္ဂြိုဟ်ခြင်း',
  'shelve': 'ရွှေ့ဆိုင်း',
  'avoid': 'ရှောင်',
  'avert': 'ကာကွယ်',
  'ward off': 'တားဆီး',
  'apprehend': 'ဖမ်းဆီး',
  'imminent': 'နီးကပ်သော',
  'spur on': 'နှိုးဆော်',
  'beguile': 'လှည့်စား',
  'perplexity': 'ရှုပ်ထွေးမှု',
  'undress': 'အဝတ်ချွတ်',
  'removing': 'ဖယ်ရှားခြင်း',
  'escape from': 'လွတ်မြောက်',
  'get rid of': 'ဖယ်ရှား',
  'take hold': 'ကိုင်ထား',
  'take to heart': 'နှလုံးသားထဲသိမ်း',
  'disarm': 'လက်နက်ချ',
  'dismantle': 'ဖြုတ်သိမ်း',
  'density (pop)': 'သိပ်သည်းမှု (လူဦးရေ)',
  'carefulness': 'သတိထားမှု',
  'set aside': 'ခွဲထား',
  'give up': 'စွန့်လွှတ်',
  'Nara': 'နာရာ',
  'twang': 'တငြီးငြီး',
  'snap': 'ပြတ်',
  'make up for': 'ဖြည့်ဆည်း',
  'redeem': 'ရွေးနှုတ်',
  'foothold': 'ခြေကုပ်',
  'based on': 'အခြေခံ၍',
  'repel': 'တွန်းထုတ်',
  'hillock': 'တောင်ကုန်းငယ်',
  'winding': 'ရစ်ခွေသော',
  'reel': 'ခွေ',
  'turn (pages)': 'စာမျက်နှာလှည့်',
  'small bell': 'ခေါင်းလောင်းငယ်',
  'shallow bowl': 'ပန်းကန်တိမ်',
  'platter': 'ပန်းကန်ကြီး',
  'paragraph': 'စာပိုဒ်',
  'nape of neck': 'လည်ပင်းနောက်',
  'clause': 'အပိုဒ်',
  'consort': 'အိမ်ထောင်ဖက်',
  'bring with': 'ခေါ်ဆောင်လာ',
  'state of suspension': 'ဆိုင်းငံ့အခြေအနေ',
  'depend': 'မှီခို',
  'consult': 'တိုင်ပင်',
  'put up (a notice)': 'ကြော်ငြာတင်',
  'put up': 'တင်',
  'hoist': 'လွှင့်တင်',
  'belong': 'ပိုင်ဆိုင်ရာ',
  'genus': 'မျိုးစု',
  'subordinate official': 'လက်အောက်အရာရှိ',
  'framework': 'မူဘောင်',
  'spindle': 'ချည်ငုံ့',
  'spool': 'ခွေ',
  'expose': 'ထုတ်ဖော်',
  'Russia': 'ရုရှား',
  'offing': 'ကမ်းလွန်',
  'rise high into sky': 'ကောင်းကင်မြင့်တက်',
  'slacken': 'လျော့ရဲ',
  'loosen': 'လျှော့',
  'lessen': 'လျှော့ချ',
  'shine into': 'ထိုးလင်း',
  'onto': 'ပေါ်သို့',
  'archery': 'လေးပစ်',
  'brandish': 'ဝှေ့ယမ်း',
  'allot': 'ခွဲဝေ',
  'fill': 'ဖြည့်',
  'tribute': 'ဆက်ကပ်လှူ',
  'deer': 'သမင်',
  'step back': 'နောက်ဆုတ်',
  'county': 'ခရိုင်',
  'join': 'ပူးပေါင်း',
  'get together': 'စုဝေး',
  'unite': 'စည်းလုံး',
  'collective': 'စုပေါင်းသော',
  'collide': 'တိုက်မိ',
  'brunt': 'တိုက်ရိုက်ထိ',
  'opposition (astronomy)': 'ဆန့်ကျင် (နက္ခတ္တ)',
  'take by force': 'အင်အားဖြင့်ယူ',
  'snatch away': 'လုယူ',
  'dispossess': 'သိမ်းယူ',
  'chop': 'ခုတ်',
  'analyze': 'ခွဲခြမ်းစိတ်ဖြာ',
  'defer': 'ရွှေ့ဆိုင်း',
  'turnover': 'လည်ပတ်ငွေ',
  'convey': 'ပို့ဆောင်',
  'contend for': 'ယှဉ်ပြိုင်',
  'make love to': 'ချစ်ရေးဆက်',
  'distract': 'အာရုံလွှဲ',
  'be mistaken for': 'မှားယွင်းခံရ',
  'go astray': 'လမ်းမှားသွား',
  'stimulate': 'နှိုးဆွ',
  'demand': 'တောင်းဆို',
  'be careful': 'သတိထား',
  'prudent': 'ဆင်ခြင်သော',
  'draw in': 'ဆွဲသွင်း',
  'hold back': 'ထိန်းထား',
  'refrain from': 'ရှောင်ကြဉ်',
  'sagacious': 'ဉာဏ်ရှိသော',
  'astringent': 'ချဉ်သော',
  'hesitate': 'တွန့်ဆုတ်',
  'reluctant': 'မလိုလားသော',
  'have diarrhea': 'ဝမ်းလျှော',
  'maneuver': 'ထိန်းချုပ်မောင်း',
  'operate': 'လည်ပတ်',
  'steer': 'စတီယာ',
  'portable': 'သယ်ဆောင်ရသော',
  'carry (in hand)': 'လက်ဖြင့်သယ်',
  'armed with': 'လက်နက်ကိုင်',
  'bring along': 'ခေါ်ဆောင်လာ',
  'checkup': 'ကျန်းမာရေးစစ်',
  'seeing': 'ကြည့်ရှုခြင်း',
  'diagnose': 'ရောဂါရှာဖွေ',
  'examine': 'စစ်ဆေး',
  'consign': 'အပ်နှံ',
  'requesting': 'တောင်းဆိုခြင်း',
  'entrusting with': 'ယုံကြည်အပ်နှံ',
  'snapshot': 'ဓာတ်ပုံရိုက်ချက်',
  'take pictures': 'ဓာတ်ပုံရိုက်',
  'encroach': 'ကျူးကျော်',
  'invade': 'ကျူးကျော်',
  'trespass': 'ကျူးကျော်ဝင်',
  'fasten': 'ချည်နှောင်',
  'apologize': 'တောင်းပန်',
  'thank': 'ကျေးဇူးတင်',
  'transparent': 'ဖောက်ထွင်းမြင်',
  'permeate': 'စိမ့်ဝင်',
  'filter': 'စစ်ထုတ်',
  'haven': 'ဆိပ်ကမ်း',
  'port': 'ဆိပ်ကမ်း',
  'rice plant': 'စပါးပင်',
  'temporary': 'ယာယီ',
  'interim': 'ကြားကာလ',
  'assumed (name)': 'ယူဆထားသော (အမည်)',
  'rend': 'ဆုတ်ဖြဲ',
  'cleverness': 'ကျွမ်းကျင်မှု',
  'agile': 'လျင်မြန်သော',
  'alert': 'သတိရှိသော',
  'repudiate': 'ငြင်းပယ်',
  'expel': 'နှင်ထုတ်',
  'hawser': 'ကြိုးထူ',
  'class (genus)': 'အမျိုးအစား (မျိုးစု)',
  'entertain': 'ဧည့်ခံ',
  'thresh': 'နှံရိုက်',
  'strip': 'ချွတ်',
  'look back': 'ပြန်ကြည့်',
  'examine oneself': 'ကိုယ်ကိုစစ်ဆေး',
  'turn around': 'လှည့်ပြန်',
  'accuse': 'စွပ်စွဲ',
  'play music': 'တူရိယာတီး',
  'speak to a ruler': 'အုပ်စိုးသူအားပြော',
  'complete': 'ပြီးစီး',
  'boisterous': 'ဆူညံသော',
  'make noise': 'ဆူညံစေ',
  'clamor': 'အော်ဟစ်',
  'clique': 'အုပ်စု',
  'lineage': 'မျိုးရိုး',
  'pedigree': 'မျိုးရိုးစာရင်း',
  'faction': 'အုပ်စုဖွဲ့',
  'straw rope': 'ကောက်ရိုးကြိုး',
  'sway': 'ယိမ်းယိုင်',
  'neighboring': 'အိမ်နီးချင်း',
  'benevolence': 'မေတ္တာကရုဏာ',
  'commanding respect': 'ရိုသေမှုဖြစ်စေ',
  'cryptomeria': 'ဆူဂီပင်',
  'stagnate': 'ရပ်တန့်နေ',
  'be delayed': 'နှောင့်နှေး',
  'overdue': 'သက်တမ်းကျော်',
  'insignificance': 'မသိမသာမှု',
  'temporarily': 'ယာယီအားဖြင့်',
  'loyalty': 'သစ္စာရှိမှု',
  'cellar': 'မြေအောက်ခန်း',
  'lad': 'လူငယ်',
  'boy (ancient)': 'ယောက်ျားလေး (ရှေး)',
  'chutzpah': 'ရဲတင်းမှု',
  'run alongside': 'ဘေးချင်းပြေး',
  'follow along': 'လိုက်လံ',
  'run along': 'အတိုင်းပြေး',
  'lie along': 'အတိုင်းလှဲ',
  'chant': 'ရွတ်ဆို',
  'recite': 'ရွတ်ဆို',
  'call upon': 'လာရောက်လည်',
  'searching': 'ရှာဖွေခြင်း',
  'inquiring': 'မေးမြန်းခြင်း',
  'haiku': 'ဟိုင်ကု',
  'frightened': 'ခြောက်လန့်သော',
  'amazed': 'အံ့ဩသော',
  'numb': 'ထုံကျင်သော',
  'wide expanse': 'ကျယ်ပြန့်သော',
  'vigorous': 'အားကောင်းသော',
  'fall into': 'ကျရောက်',
  'cave in': 'ပြိုကျ',
  'fall (castle)': 'ကျဆုံး (ရဲတိုက်)',
  '8 1/3lbs': '၈ ၁/၃ ပေါင်',
  'brace': 'ထောက်တိုင်',
  'cent': 'ဆင့်',
  'decameron': 'ဆယ်ရက်ကာလ',
  'ten-day period': 'ဆယ်ရက်ကာလ',
  'season (for specific products)': 'ရာသီ (ကုန်ပစ္စည်း)',
  'as is': 'အတိုင်းပင်',
  'hegemony': 'ကြီးစိုးမှု',
  'champion': 'ချန်ပီယံ',
  'touch': 'ထိတွေ့',
  'threaten': 'ခြိမ်းခြောက်',
  'coerce': 'အတင်းအကျပ်',
  'grow thick': 'ထူထပ်ကြီး',
  'banner': 'အလံ',
  'long-distance': 'အကွာအဝေးရှည်',
  'spur': 'နှိုးဆော်',
  'fetlock': 'မြင်းခွာဆံ',
  'gracious': 'ကြင်နာသော',
  'decorate': 'အလှဆင်',
  'adorn': 'အလှဆင်',
  'embellish': 'အလှဆင်',
  'netting': 'ပိုက်ကွန်',
  'luxuriant': 'စိမ်းလန်းစိုပြေ',
  'wing': 'အတောင်',
  'plane': 'လေယာဉ်',
  'flank': 'ဘေးဘက်',
  'lagoon': 'ကမ်းအိုင်',
  'foe': 'ရန်သူ',
  'opponent': 'ပြိုင်ဘက်',
  'bewitch': 'မှော်ဆွဲ',
  'destroy': 'ဖျက်ဆီး',
  'overthrow': 'ဖြုတ်ချ',
  'cornerstone': 'ထောင့်ကျောက်',
  'foundation stone': 'အခြေခံကျောက်',
  'exhaust': 'ကုန်ဆုံး',
  'use up': 'သုံးကုန်',
  'run out of': 'ကုန်သွား',
  'deplete': 'ကုန်ခန်း',
  'me': 'ကျွန်တော်',
  'I (male)': 'ကျွန်တော် (ကျား)',
  'cherry': 'ချယ်ရီ',
  'slippery': 'ချောသော',
  'slip': 'ချော်',
  'fail exam': 'စာမအောင်',
  'inflammation': 'ရောင်ရမ်းခြင်း',
  'indemnify': 'လျော်ကြေးပေး',
  'steel': 'သံမဏိ',
  'makeup': 'မိတ်ကပ်',
  'radiance': 'ရောင်ခြည်',
  'patrol': 'ကင်းလှည့်',
  'blink': 'မျက်တောင်ခတ်',
  'be proud': 'ဂုဏ်ယူသည်',
  'triumphantly': 'အောင်ပွဲခံစွာ',
  'animal sacrifice': 'တိရစ္ဆာန်ယဇ်',
  'offering': 'လှူဖွယ်',
  'tempt': 'သွေးဆောင်',
  'instigate': 'နှိုးဆော်',
  'promote': 'မြှင့်တင်',
  'thwart': 'ဟန့်တား',
  'separate from': 'ခွဲခွာ',
  'bribe': 'လိုက်လံပေး',
  'chrysanthemum': 'ဂျပန်ပန်းပွင့်',
  'strangle': 'လည်ညှစ်',
  'wring': 'ညှစ်',
  'dart': 'မြှားခပ်',
  '-proof': '-ကာကွယ်',
  'enduring': 'ခံနိုင်သော',
  'cram school': 'ကြိုးစားသင်ကျောင်း',
  'private school': 'ပုဂ္ဂလိကကျောင်း',
  'jubilation': 'ဝမ်းသာခြင်း',
  'be happy': 'ပျော်ရွှင်သည်',
  'penal': 'ပြစ်ဒဏ်ဆိုင်ရာ',
  'chastise': 'အပြစ်ပေး',
  'punish': 'ပြစ်ဒဏ်ပေး',
  'discipline': 'စည်းကမ်းသင်',
  'sabre': 'ဓားရှည်',
  'clock hand': 'နာရီလက်တံ',
  'chess piece': 'စစ်တုရင်ရုပ်',
  'shogi': 'ရှိုဂိ',
  'ethics': 'ကျင့်ဝတ်',
  'explain': 'ရှင်းပြ',
  'submerge': 'နစ်မြုပ်',
  'lower (voice)': 'အသံလျှော့',
  'pear tree': 'သစ်တော်ပင်',
  'overcome': 'ကျော်လွှား',
  'kindly': 'ကြင်နာစွာ',
  'skillfully': 'ကျွမ်းကျင်စွာ',
  'seize': 'ဖမ်းဆီး',
  'concerned': 'သက်ဆိုင်သော',
  'become silent': 'ဆိတ်ဆိတ်နေ',
  'stop speaking': 'စကားရပ်',
  'tortoise': 'လိပ်',
  'turtle': 'လိပ်',
  'hearth': 'မီးဖို',
  'reactor': 'ဓာတ်ပေါင်းဖို',
  'breed': 'မွေးမြူ',
  'care for': 'ဂရုစိုက်',
  'shepherd': 'သိုးထိန်း',
  'aperture': 'အပေါက်',
  'slit': 'အက်ကြောင်း',
  'ridicule': 'ပြောင်လှောင်',
  'stork': 'ငှက်ကုလားအုတ်',
  'clap': 'လက်ခုပ်တီး',
  'beat (music)': 'တီးခတ် (ဂီတ)',
  'tolerant': 'သည်းခံသော',
  'leniency': 'သည်းခံမှု',
  'capsize': 'မှောက်',
  'shade': 'အရိပ်',
  'mantle': 'ခြုံထည်',
  'placenta': 'အချင်း',
  'sac': 'အိတ်',
  'sheath': 'အခွံ',
  'lungs': 'အဆုတ်',
  'upright': 'ဖြောင့်မတ်သော',
  'chastity': 'သီလ',
  'constancy': 'တည်ကြည်မှု',
  'righteousness': 'တရားမျှတမှု',
  'peaceful': 'ငြိမ်းချမ်းသော',
  'specimen': 'နမူနာ',
  'take warning from': 'သတိယူ',
  'learn from': 'သင်ယူ',
  'inscription': 'ရေးထွင်းစာ',
  'signature (of artisan)': 'လက်မှတ် (လက်မှု)',
  'ardent': 'ပြင်းထန်သော',
  'furious': 'ဒေါသထွက်သော',
  'inquire': 'မေးမြန်း',
  'fathom': 'တိုင်းတာ',
  'to be (classical)': 'ဖြစ်သည် (ဂန္ထ)',
  'ridgepole': 'အမိုးရိုး',
  'cartoon': 'ကာတွန်း',
  'involuntarily': 'အလိုအလျောက်',
  'unrestrained': 'မထိန်းချုပ်နိုင်',
  'in spite of oneself': 'ကိုယ်မလိုဘဲ',
  'sticky': 'ကပ်သော',
  'glutinous': 'စေးကပ်သော',
  'greasy': 'ဆီချောသော',
  'persevere': 'ဇွဲရှိ',
  'acquire skill': 'ကျွမ်းကျင်လာ',
  'rising sun': 'နေထွက်',
  'morning sun': 'မနက်နေ',
  'pea': 'ပဲစေ့',
  'midget': 'လူပု',
  'consummate': 'ပြည့်စုံသော',
  'commit (suicide)': 'ကိုယ့်ကိုသတ်',
  'lunatic': 'ရူးသွပ်သူ',
  'insane': 'ရူးသွပ်သော',
  'crazy': 'ရူးသော',
  'highness': 'မြင့်မြတ်သော',
  'steps (of throne)': 'နန်းလှေကား',
  'horizontal': 'အလျားလိုက်',
  'woof': 'အလျားချည်',
  'left & right': 'ဘယ်ညာ',
  '(parallels of) latitude': 'လတ္တီတွဒ်',
  'foster': 'မွေးမြူ',
  'wane': 'ယုတ်လျော့',
  'weaken': 'အားနည်း',
  'rowboat': 'လှေငယ်',
  'small boat': 'လှေငယ်',
  'bend': 'ကွေး',
  'flinch': 'နောက်ဆုတ်',
  'submit': 'လက်နက်ချ',
  'pull': 'ဆွဲ',
  'courts': 'တရားရုံးများ',
  'imperial court': 'နန်းတော်',
  'brocade': 'ပိုးထည်',
  'fine dress': 'အဝတ်လှပ',
  'honors': 'ဂုဏ်ထူးများ',
  'besides': 'ထို့အပြင်',
  'gall bladder': 'သည်းခြေအိတ်',
  'fine': 'ကောင်းမွန်သော',
  'thin kimono': 'ပါးလွှာကီမိုနို',
  'void': 'ဗလာ',
  'emptiness': 'အလွတ်',
  'spirits': 'ဝိညာဉ်များ',
  'soul': 'ဝိညာဉ်',
  'repent': 'နောင်တရ',
  'rebuke': 'ဆုံးမ',
  'warn': 'သတိပေး',
  'tyrannize': 'အာဏာရှင်ဆန်',
  'turn over': 'လှန်',
  'flutter': 'လွင့်ပျံ',
  'fall (down)': 'လဲကျ',
  'lay a foundation': 'အခြေခံချ',
  'install': 'တပ်ဆင်',
  'equip': 'တပ်ဆင်',
  'fertile': 'မြေဩဇာကောင်း',
  'load (a vehicle)': 'တင်ဆောင်',
  'ride': 'စီး',
  'rapids': 'ရေစီးမြန်',
  'cascade': 'ရေတံခွန်',
  'hamper': 'ဟန့်တား',
  'grate': 'ပွတ်',
  'scrape': 'ခြစ်',
  'whale': 'ဝေလငါး',
  'inn': 'တည်းခိုခန်း',
  'cottage': 'အိမ်ငယ်',
  'feudal manor': 'ဖူဒယ်လ်ခြံ',
  'lightning bolt': 'လျှပ်စီး',
  'drift': 'မျော',
  'float (on liquid)': 'မျော (အရည်ပေါ်)',
  'plantation': 'စိုက်ခင်း',
  'kidnap': 'ပြန်ပေးဆွဲ',
  'falsify': 'အတုလုပ်',
  'burdensome': 'ဝန်ထုပ်ဝန်ပိုး',
  'pack horse': 'ဝန်မြင်း',
  'horse load': 'မြင်းဝန်',
  'send by horse': 'မြင်းဖြင့်ပို့',
  'diagonal': 'ထောင့်ဖြတ်',
  'slanting': 'စောင်းသော',
  'oblique': 'စောင်းသော',
  'fast learner': 'လျင်မြန်သင်သူ',
  'wandering': 'လှည့်လည်ခြင်း',
  'stage': 'စင်မြင့်',
  'terrace': 'လှေကားခုံ',
  'witch': 'မှော်ဆရာမ',
  'repay': 'ပြန်ဆပ်',
  'purple': 'ခရမ်းရောင်',
  'family crest': 'မိသားစုတံဆိပ်',
  'figures': 'ကိန်းဂဏန်းများ',
  'wholesale': 'လက်ကား',
  'stirred up': 'နှိုးဆွခံရ',
  'be invigorated': 'အားတက်သည်',
  'deviate': 'လွဲသွား',
  'idleness': 'ပျင်းရိမှု',
  'miss the mark': 'ပစ်မှား',
  'prison': 'အကျဉ်းထောင်',
  'jail': 'အကျဉ်းထောင်',
  'carve': 'ထွင်း',
  'engrave': 'ထွင်းထု',
  'chisel': 'ထွင်းတူ',
  'adroit': 'ကျွမ်းကျင်သော',
  'skilled': 'ကျွမ်းကျင်သော',
  'ingenuity': 'ဉာဏ်ပညာ',
  'halberd': 'လှံတံ',
  'festival float': 'ပွဲတော်လှည်း',
  'deceit': 'လှည့်ဖြားမှု',
  'delude': 'လှည့်စား',
  'bush clover': 'ချုံပင်ပန်း',
  'solemn': 'ကြီးကျယ်သော',
  'softly': 'ပျော့ပျောင်းစွာ',
  'chestnut': 'သစ်အယ်သီး',
  'absurdity': 'မိုက်မဲမှု',
  'erect': 'ထောင်',
  'nourishing': 'အာဟာရပေး',
  'more & more': 'ပို၍ပို၍',
  'vow': 'ကတိသစ္စာ',
  'swear': 'ကျမ်းကျိန်',
  'pledge': 'ကတိပြု',
  'faggot': 'ထင်းစည်း',
  'bunch': 'စည်း',
  'counter for bundles': 'စည်းရေတွက်',
  'alienate': 'ခွဲခွာစေ',
  'shun': 'ရှောင်',
  'rapidly': 'လျင်မြန်စွာ',
  'subjugate': 'နှိမ်နင်း',
  'attack the rebellious': 'ပုန်ကန်သူတိုက်',
  'collect taxes': 'အခွန်ကောက်',
  'marry into': 'အိမ်ထောင်ဝင်',
  'self-effacing': 'နှိမ့်ချသော',
  'humble oneself': 'ကိုယ်ကိုနှိမ့်',
  'condescend': 'နှိမ့်ချ',
  'be modest': 'နှိမ့်ချသည်',
  'moan': 'ညည်းညူ',
  'fungus': 'မှို',
  'sickle': 'တံစဉ်',
  'scythe': 'တံစဉ်',
  'hive': 'ပျားအုံ',
  'cobweb': 'ပင့်ကူအိမ်',
  'recur': 'ပြန်ဖြစ်',
  'harp': 'စောင်း',
  'koto': 'ကိုတို',
  'shelf': 'စင်',
  'ledge': 'ကျောက်ဆောင်',
  'rack': 'စင်',
  'cruel': 'ရက်စက်သော',
  'severe': 'ပြင်းထန်သော',
  'atrocious': 'ကြမ်းကြုတ်သော',
  'unjust': 'မတရားသော',
  'sign of the dragon': 'နဂါးရာသီ',
  '7-9AM': 'မနက် ၇-၉',
  'fifth sign of Chinese zodiac': 'တရုတ်ဆယ့်နှစ်ရာသီ ၅',
  'shin dragon radical (no. 161)': 'နဂါးရက်ဒီကယ် (၁၆၁)',
  'be hazy': 'မှုန်ဝါးသည်',
  'grow dim': 'မှေးမှိန်လာ',
  'blurred': 'မှုန်ဝါးသော',
  'prostrated': 'ဦးညွှတ်သော',
  'bend down': 'ကွေးညွှတ်',
  'Go': 'ဂို',
  'black ink': 'မင်နက်',
  'India ink': 'အိန္ဒိယမင်',
  'ink stick': 'မင်တုံး',
  'Mexico': 'မက္ကဆီကို',
  'tranquilize': 'ငြိမ်သက်စေ',
  'ancient peace-preservation centers': 'ရှေးငြိမ်ဝပ်စခန်း',
  'den': 'တွင်း',
  'inferiority': 'နိမ့်ကျမှု',
  'be inferior to': 'နိမ့်သည်',
  'be worse': 'ပိုဆိုးသည်',
  'assault': 'တိုက်ခိုက်',
  'thrash': 'ရိုက်နှက်',
  'with child': 'ကိုယ်ဝန်ရှိ',
  'pigeon': 'ချိုးငှက်',
  'dove': 'ချိုးငှက်',
  'drunk': 'မူးသော',
  'feel sick': 'နေမကောင်းခံစား',
  'poisoned': 'အဆိပ်သင့်',
  'elated': 'ဝမ်းသာသော',
  'be sparing of': 'ခြိုးခြံ',
  'frugal': 'ခြိုးခြံသော',
  'stingy': 'စေးကပ်သော',
  'reap': 'ရိတ်',
  'be watered': 'ရေလောင်းခံရ',
  'profit by': 'အကျိုးခံစား',
  'receive benefits': 'အကျိုးခံရ',
  'grieve over': 'ဝမ်းနည်း',
  'destitution': 'ဆင်းရဲခြင်း',
  'scarce': 'ရှားပါးသော',
  'limited': 'ကန့်သတ်သော',
  'above-stated': 'အထက်ပါ',
  'the said': 'အဆိုပါ',
  'that specific': 'ထိုအတိအကျ',
  'mulberry': 'သပြေပင်',
  'Japanese Judas-tree': 'ဂျပန်ဂျူဒတ်စ်ပင်',
  'cinnamon tree': 'သစ်ကြံပိုးပင်',
  'marrow': 'ရိုးတွင်းခြင်ဆီ',
  'pith': 'အူတိုင်',
  'basin': 'အောက်ခံ',
  'lantern festival': 'မီးပုံးပွဲ',
  'robust': 'ကျန်းမာကြံ့ခိုင်',
  'manhood': 'ယောက်ျားဘဝ',
  'epidemic': 'ကပ်ရောဂါ',
  'accumulate': 'စုဆောင်း',
  'involvement': 'ပါဝင်ပတ်သက်မှု',
  'conveyor': 'သယ်ယူစက်',
  'carry': 'သယ်ဆောင်',
  'healing': 'ကုသခြင်း',
  'quench (thirst)': 'ငတ်ပြေ (ရေ)',
  'wreak': 'အပြစ်ပေး',
  'paulownia': 'ပေါ်လိုနီးယား',
  'quarters': 'နေရာများ',
  'fortification': 'ခံတပ်',
  'red-light district': 'ညဥ့်ဘက်ရပ်ကွက်',
  'vomit': 'အန်',
  'belch': 'လေချဉ်တက်',
  'confess': 'ဝန်ခံ',
  'hawk': 'เหယင်',
  'captive': 'အကျဉ်းသား',
  'low epithet for the enemy': 'ရန်သူအမည်ဆိုး',
  'remorse': 'နောင်တ',
  'be sorry': 'ဝမ်းနည်းသည်',
  'boar': 'ဝက်ရိုင်း',
  'increasingly': 'ပို၍ပို၍',
  'rugged': 'ကြမ်းတမ်းသော',
  'spear': 'လှံ',
  'equestrian': 'မြင်းစီးဆိုင်ရာ',
  'riding on horses': 'မြင်းစီးခြင်း',
  'counter for equestrians': 'မြင်းစီးသူရေတွက်',
  'sequential': 'အစဉ်လိုက်',
  'put up with': 'သည်းခံ',
  'tea pavillion': 'လက်ဖက်ရည်အိမ်',
  'phoenix': 'ဖီးနစ်',
  'stiff': 'တောင့်တင်းသော',
  'be absorbed in': 'စွဲလမ်းနေ',
  'seedling': 'ပျိုးပင်',
  'sapling': 'ပျိုးပင်ငယ်',
  'pathetic': 'သနားစရာ',
  'pathos': 'ဝမ်းနည်းမှု',
  'workman': 'အလုပ်သမား',
  'droop': 'တွဲကျ',
  'slouch': 'ပျော့ညံ့ထိုင်',
  'snake': 'မြွေ',
  'serpent': 'မြွေ',
  'hard drinker': 'အရက်သမား',
  'sew': 'ချုပ်',
  'stitch': 'ချုပ်',
  'embroider': 'ပန်းထိုး',
  'span': 'ကာလ',
  'extend over': 'ကျော်လွှား',
  'beautiful woman': 'အလှမယ်',
  'sewer': 'ရေမြောင်း',
  'drain': 'ရေထုတ်မြောင်း',
  'reverent': 'ရိုသေသော',
  'be in disorder': 'ရောထွေးနေ',
  'bamboo grass': 'ဝါးပင်ငယ်',
  'cereals': 'စပါးဂျုံ',
  'vice': 'ဒုစရိုက်',
  'breakage': 'ပျက်စီးခြင်း',
  'hard up': 'ငွေကြပ်သော',
  'destitute': 'ဆင်းရဲသော',
  'suffer': 'ခံစားရ',
  'perplexed': 'ရှုပ်ထွေးသော',
  'stinking': 'နံသော',
  'ill-smelling': 'နံစော်သော',
  'suspicious looking': 'သံသယဖြစ်ဖွယ်',
  'odor': 'အနံ့',
  'edge': 'အစွန်း',
  'blind': 'မျက်မမြင်',
  'blind man': 'မျက်မမြင်သူ',
  'ignoramus': 'မသိသူ',
  'embarrass': 'ရှက်စေ',
  'humiliate': 'အရှက်ရစေ',
  'bowstring': 'လေးကြိုး',
  'hypotenuse': 'ထောင့်ဖြတ်ဘက်',
  'plug up': 'ပိတ်ဆို့',
  'deluge': 'ရေလွှမ်းမိုး',
  'vicarious': 'အစားထိုးသော',
  'surrogate': 'ကိုယ်စားလှယ်',
  'act in addition to': 'အပိုလုပ်',
  'take in': 'လက်ခံ',
  'sated': 'ဝလုံသော',
  'tired of': 'ငြီးငွေ့သော',
  'bored': 'ပျင်းသော',
  'satiate': 'ဝလုံစေ',
  'superfluous': 'ပိုလျှံသော',
  'peach': 'မက်မွန်',
  'hunt': 'အမဲလိုက်',
  'gather': 'စုဆောင်း',
  'whirlpool': 'ရေဝဲ',
  'eddy': 'ရေဝဲ',
  'vortex': 'ရေဝဲ',
  'sire': 'အဖေမြင်း',
  'good belt': 'ကောင်းသောခါးပတ်',
  'tombstone': 'သင်္ချိုင်းကျောက်',
  'monument': 'အမှတ်တရကျောက်',
  'partially clothed': 'တစ်ဝက်ဝတ်',
  'chunk': 'အတုံး',
  'bow (archery, violin)': 'လေး (လေးပစ်/တယော)',
  'tank': 'တင့်ကား',
  'mercy': 'ကရုဏာ',
  'two-mat area': 'တာတာမိနှစ်ချပ်',
  'approx. thirty-six sq ft': 'ပေသုံးဆယ့်ခြောက်ခန့်',
  'dark blue': 'အပြာရင့်',
  'navy': 'ရေတပ်ပြာ',
  'camellia': 'ကမယ်လီယာ',
  'clapper': 'ခေါက်တံ',
  'thin silk': 'ပိုးပါး',
  'Rome': 'ရောမ',
  'arrange': 'စီစဉ်',
  'gorge': 'ချောက်',
  'ravine': 'ချောက်ကြား',
  'stipend': 'လစာ',
  'rin': 'ရင်',
  '1/10 sen': 'ဆင့် ၁/၁၀',
  '1/10 bu': 'ဘူ ၁/၁၀',
  'condolences': 'နှစ်သိမ့်ခြင်း',
  'nun': 'သီလရှင်',
  'measuring rod': 'တိုင်းတံ',
  'send forth fragrance': 'ရနံ့ထွက်',
  'be scented': 'နံ့သာခံ',
  'smoke (tobacco)': 'ဆေးလိပ်သောက်',
  'sheep': 'သိုး',
  'spy': 'သူလျှို',
  'hoarse': 'အသံကွဲသော',
  'scold': 'ဆူပူဆုံးမ',
  'womb': 'သားအိမ်',
  'uterus': 'သားအိမ်',
  'fermentation': 'အချဉ်ဖောက်ခြင်း',
  'intercept': 'ကြားဖြတ်ဖမ်း',
  'interrupt': 'ကြားဖြတ်',
  'front door': 'ရှေ့တံခါး',
  'title page': 'ခေါင်းစည်းမျက်နှာ',
  'sulphur': 'ဆာလဖာ',
  'bubbles': 'ပူဖောင်းများ',
  'suds': 'ဆပ်ပြာအမြှုပ်',
  'or again': 'သို့မဟုတ်ပြန်',
  'on the other hand': 'တစ်ဖက်တွင်',
  'rue': 'နောင်တရ',
  'be sad': 'ဝမ်းနည်းသည်',
  'bear a grudge': 'ရန်ငြိုးထား',
  'abhor': 'မုန်းတီး',
  'death anniversary': 'နှစ်ပတ်လည်သေနေ့',
  'Big Dipper': 'ကြယ်ခုနစ်ပွင့်',
  'ten sho (vol)': 'ဆို ဆယ် (ထု)',
  'sake dipper': 'ဆာကေးဇွန်း',
  'dots and cross radical (no. 68)': 'အစက်နှင့်လက်ဝါးကပ် (၆၈)',
  'orchid': 'သစ်ခွ',
  'Holland': 'ဟော်လန်',
  'resemblance': 'ဆင်တူမှု',
  'rice tub': 'ထမင်းအိုး',
  'crown': 'သရဖူ',
  'rot': 'ပုပ်',
  'remain in seclusion': 'တစ်ဦးတည်းနေ',
  'nut shell': 'အခွံ',
  'Manchu dynasty': 'မန်ချူးမင်းဆက်',
  'name given to naturalized foreigners': 'နိုင်ငံခြားသားနာမည်',
  'miscanthus reed': 'မြက်ရိုင်း',
  'mediator': 'ကြားဝင်သူ',
  'chicken': 'ကြက်',
  'Zen': 'ဇင်',
  'silent meditation': 'တိတ်ဆိတ်တရားထိုင်',
  'trunk': 'ကိုယ်လုံး',
  'torso': 'ကိုယ်လုံး',
  'hull (ship)': 'သင်္ဘောကိုယ်ထည်',
  'hub of wheel': 'ဘီးဗဟို',
  'alternation': 'အလှည့်အပြောင်း',
  'chinquapin': 'သစ်အယ်မျိုး',
  'mallet': 'တူ',
  'obeisance': 'ဦးညွှတ်ခြင်း',
  'attend on': 'စောင့်ရှောက်',
  'cultural progress': 'ယဉ်ကျေးမှုတိုးတက်',
  'in the event': 'ဖြစ်ခဲ့လျှင်',
  'camphor tree': 'ကမ်ဖာပင်',
  'clarinet': 'ကလာရီနက်',
  'whistle': 'ငှက်သံ',
  'sound of jewels': 'ကျောက်မျက်သံ',
  'guy': 'လူ',
  'fist': 'လက်သီး',
  'soar': 'ပျံတက်',
  'waiter': 'စားပွဲထိုး',
  'wait upon': 'စောင့်ရှောက်',
  'mountain peak': 'တောင်ထိပ်',
  'mountain pass': 'တောင်ကြားလမ်း',
  'climax': 'အထွတ်အထိပ်',
  'crest': 'အမောက်',
  'thirst': 'ရေငတ်',
  'withstand': 'ခံနိုင်',
  'narrate': 'ပြောပြ',
  'describe': 'ဖော်ပြ',
  'versify': 'ကဗျာဆို',
  'singing': 'သီဆိုခြင်း',
  'recital': 'ရွတ်ဆိုခြင်း',
  'sending': 'ပို့ဆောင်ခြင်း',
  'headland': 'ကျွန်းဆောင်',
  'sign of the tiger': 'ကျားရာသီ',
  '3-5AM': 'မနက် ၃-၅',
  'third sign of Chinese zodiac': 'တရုတ်ဆယ့်နှစ်ရာသီ ၃',
  'reef': 'သန္တာကျောက်',
  'sunken rock': 'နစ်မြုပ်ကျောက်',
  'barracks': 'စစ်တန်းလျား',
  'birch': 'ဘုစ်ပင်',
  'dark red': 'နီရင့်သော',
  'matrimony': 'အိမ်ထောင်ရေး',
  'marry': 'အိမ်ထောင်ပြု',
  'mimic': 'တုပ',
  'aim (a gun) at': 'ပစ်မှတ်ချိန်',
  'nominate': 'အမည်တင်သွင်း',
  'harmonious': 'သဟဇာတသော',
  'lowly': 'နိမ့်ကျသော',
  'vile': 'ယုတ်ညံ့သော',
  'vulgar': 'ကြမ်းတမ်းသော',
  'despise': 'မထီမဲ့မြင်',
  'make light of': 'ပေါ့ပေါ့တွက်',
  'casting': 'သွန်းလုပ်ခြင်း',
  'mint': 'ဒင်္ဂါးထု',
  'erase': 'ဖျက်',
  'military officer': 'စစ်အရာရှိ',
  'Zelkova tree': 'ဇဲလ်ကိုဗာပင်',
  'dairy products': 'နို့ထွက်ပစ္စည်း',
  'whey': 'နို့ရည်',
  'broth': 'ဟင်းရည်',
  'fruit juice': 'အသီးရည်',
  'commander': 'တပ်မှူး',
  'leading troops': 'တပ်ဦးဆောင်',
  'governor': 'အုပ်ချုပ်သူ',
  'lightning-bug': 'ပိုးစုန်းကြူး',
  'firefly': 'ပိုးစုန်းကြူး',
  'banana': 'ငှက်ပျော',
  'plantain': 'ငှက်ပျော',
  'precious stone': 'ကျောက်မျက်',
  'diarrhea': 'ဝမ်းလျှော',
  'pit': 'တွင်း',
  'indigo': 'အင်ဒီဂို',
  'burglar': 'အိမ်ဖောက်သူ',
  'rebel': 'ပုန်ကန်သူ',
  'traitor': 'သစ္စာဖောက်',
  'robber': 'ဓားပြ',
  'squeeze': 'ညှစ်',
  'paddy ridge': 'လယ်ကန်သင်း',
  'levee': 'ရေကာ',
  'mandarin orange': 'မန္ဒရင်းသီး',
  'backbone': 'ကျောရိုး',
  'torture': 'နှိပ်စက်',
  'southeast': 'အရှေ့တောင်',
  'mountain stream': 'တောင်ချောင်း',
  'venerable old man': 'ရိုသေအိုသူကြီး',
  'reverently': 'ရိုသေစွာ',
  'humbly': 'နှိမ့်ချစွာ',
  'oven': 'မီးဖို',
  'extol': 'ချီးမွမ်း',
  'measuring box': 'တိုင်းအိုး',
  '1.8 liter': '၁.၈ လီတာ',
  'martyrdom': 'အာဇာနည်ဖြစ်',
  'follow by resigning': 'နုတ်ထွက်လိုက်',
  'comma-design': 'ကော်မာပုံစံ',
  'criminal investigation': 'ရာဇဝတ်စုံစမ်း',
  'degenerate': 'ယိုယွင်း',
  'descend to': 'ဆင်းသက်',
  'lapse into': 'ကျရောက်',
  'tariff': 'အကောက်ခွန်',
  'crop tax': 'သီးနှံအခွန်',
  'scaffold': 'ငြမ်း',
  'cleat': 'သပ်',
  'jetty': 'ဆိပ်ခံတံတား',
  'Yamato': 'ယာမာတို',
  'ancient Japan': 'ရှေးဂျပန်',
  'bridegroom': 'သတို့သား',
  'pining': 'လွမ်းဆွတ်ခြင်း',
  'love dearly': 'ချစ်ခင်နှစ်သက်',
  'captured': 'ဖမ်းဆီးခံရသော',
  'charging ahead of others': 'ရှေ့ဆောင်ချီတက်',
  'ooze': 'ယို',
  'flow': 'စီး',
  'soak in': 'စိမ်',
  'strong and brave': 'ခိုင်မာရဲရင့်',
  'hollyhock': 'ဟော်လီဟော့',
  'seaweed': 'ပင်လယ်ရေညှိ',
  'duckweed': 'ရေညှိ',
  'legitimate wife': 'တရားဝင်ဇနီး',
  'direct descent (non-bastard)': 'တိုက်ရိုက်သားစဉ်',
  'sign of the snake or serpent': 'မြွေရာသီ',
  '9-11AM': 'မနက် ၉-၁၁',
  'sixth sign of Chinese zodiac': 'တရုတ်ဆယ့်နှစ်ရာသီ ၆',
  'convex': 'ခုံးသော',
  'beetle brow': 'နဖူးထွက်',
  'uneven': 'မညီညာသော',
  'rhyme': 'ကာရန်',
  'nitrate': 'နိုက်ထရိတ်',
  'saltpeter': 'ဆားပေါက်',
  'imperial order': 'ဧကရာဇ်အမိန့်',
  'parsley': 'ပင်စိမ်း',
  'apricot': 'ဇီးသီး',
  'coffin': 'ခေါင်းအုံး',
  'casket': 'အုတ်ဂူခေါင်း',
  'Confucian': 'ကွန်ဖြူးရှပ်ဆိုင်ရာ',
  'male mythical bird': 'ဒဏ္ဍာရီငှက်အထီး',
  'be anxious': 'စိုးရိမ်သည်',
  'watchtower': 'စောင့်ကြည့်မျှော်စင်',
  'lookout': 'စောင့်ကြည့်ရာ',
  'high building': 'အဆောက်အအုံမြင့်',
  'firewood': 'ထင်း',
  'kindling': 'မီးစွဲစာ',
  'darning': 'ဖာထေးခြင်း',
  'mend': 'ပြင်ဆင်',
  'plug': 'ပိတ်စ',
  'bung': 'ပိတ်တုံး',
  'freshwater trout': 'ရေချိုငါး',
  'smelt': 'ငွေငါး',
  'hazelnut': 'ဟေဇယ်သီး',
  'filbert': 'ဖီးလ်ဘတ်',
  'concave': 'ခွက်သော',
  'sunken': 'နစ်သော',
  'vine': 'နွယ်ပင်',
  'ivy': 'နွယ်ပင်',
  'falcon': 'လင်းယုန်',
  'strand': 'ကမ်းခြေ',
  'Mt Fuji': 'ဖူဂျီတောင်',
  'imperial edict': 'ဧကရာဇ်အမိန့်စာ',
  'fifth month': 'ပဉ္စမလ',
  'squab': 'ငှက်ကလေး',
  'duckling': 'ဘဲကလေး',
  'blackened eyebrows': 'မျက်ခုံးမည်း',
  'yearn after': 'လွမ်းဆွတ်',
  'aspire to': 'မျှော်မှန်း',
  'admire': 'လေးစားချီးမွမ်း',
  'unnecessarily': 'မလိုအပ်ဘဲ',
  'without authority': 'အာဏာမရှိဘဲ',
  'dried meat': 'အသားခြောက်',
  'bar-tending': 'ဆာကေးလောင်း',
  'serving sake': 'ဆာကေးကျွေး',
  'the host': 'အိမ်ရှင်',
  'draw (water)': 'ရေခပ်',
  'silkworm': 'ပိုးကောင်',
  'limb': 'ကိုယ်အင်္ဂါ',
  'arms & legs': 'လက်ခြေ',
  'sandalwood': 'စန္ဒကူး',
  'victory song': 'အောင်ပွဲသီချင်း',
  'comet': 'ကြယ်တံခွန်',
  'broom': 'တံမြက်စည်း',
  'catalpa tree': 'ကာတာလ်ပါပင်',
  'woodblock printing': 'သစ်သားပုံနှိပ်',
  'sign of the ox or cow': 'နွားရာသီ',
  '1-3AM': 'ည ၁-၃',
  'second sign of Chinese zodiac': 'တရုတ်ဆယ့်နှစ်ရာသီ ၂',
  'brilliant fabric design': 'တောက်ပသောပုံစံ',
  'attending': 'တက်ရောက်ခြင်း',
  'entertainer': 'ဖျော်ဖြေသူ',
  'furrow': 'ထွန်ကြောင်း',
  'thirty tsubo': 'ဆုဘို သုံးဆယ်',
  'rib': 'နံရိုး',
  'lazy': 'ပျင်းရိသော',
  'show symptoms of': 'လက္ခဏာပြ',
  'malt': 'မုယောမှုန့်',
  'one (in documents)': 'တစ် (စာရွက်တွင်)',
  'sow (seeds)': 'မျိုးကြဲ',
  'carp': 'ငါးကြင်း',
  'arc': 'အကွေး',
  'type of morning glory': 'မနက်ခင်းပန်းမျိုး',
  'rose of Sharon': 'ရှာရွန်နှင်းဆီ',
  'althea': 'အယ်လ်သီယာ',
  'sparkle of jewelry': 'ကျောက်မျက်လက်',
  'affixed': 'ကပ်ထားသော',
  'spotted': 'အစက်ပါသော',
  'mottled': 'အစက်အပြောက်',
  'patterned': 'ပုံစံပါသော',
  'small tiger': 'ကျားငယ်',
  'taro': 'တာရို',
  'yam': 'မြစ်ဥ',
  'tuber': 'ဥမြစ်',
  'madder': 'မက်ဒါပင်',
  'red dye': 'အနီဆိုးဆေး',
  'Turkey red': 'တူရကီနီ',
  'keep (rain)out': 'မိုးကာကွယ်',
  'stave off': 'တားဆီး',
  'tide over': 'ကျော်ဖြတ်',
  'sparkling water': 'ပူဖောင်းရေ',
  'old woman': 'အဘွား',
  'grandma': 'အဘွား',
  'wet nurse': 'နို့ထိန်း',
  'scarlet': 'နီရဲသော',
  'cardinal': 'ကာဒီနယ်နီ',
  'sea bream': 'ပင်လယ်ဘရမ်',
  'red snapper': 'နီငါး',
  'peck': 'စုစု',
  'pick up': 'ကောက်ယူ',
  'good crops': 'သီးနှံကောင်း',
  '10**28': '၁၀^၂၈',
  'serving our elders': 'လူကြီးစောင့်ရှောက်',
  'citron': 'သံပုရာ',
  'cocoon': 'ပိုးအိမ်',
  'pongee (a knotted silk cloth)': 'ပွန်ဂျီပိုးထည်',
  'lull': 'ငြိမ်သက်',
  'bookmark': 'စာညှပ်',
  'mountains towering in a row': 'တောင်တန်းဆက်',
  'pig iron': 'သံကြမ်း',
  'dilate': 'ချဲ့',
  'distend': 'ဖောင်း',
  'bulge': 'ဖောင်းကား',
  'fill out': 'ဖြည့်ပြည့်',
  'ode': 'ကဗျာ',
  'prose': 'စကားပြေ',
  'axe': 'ပုဆိန်',
  '1.32 lb': '၁.၃၂ ပေါင်',
  'catty': 'ကတ္တီ',
  'counter for loaves of bread': 'မုန့်တုံးရေတွက်',
  'melting': 'အရည်ပျော်ခြင်း',
  'smelting': 'သတ္တုရည်ကျို',
  'beautiful as a jewel': 'ကျောက်မျက်ကဲ့သို့လှ',
  'sign of the hog': 'ဝက်ရာသီ',
  '9-11PM': 'ည ၉-၁၁',
  'twelfth sign of the Chinese zodiac': 'တရုတ်ဆယ့်နှစ်ရာသီ ၁၂',
  'officer': 'အရာရှိ',
  'an official': 'အရာရှိ',
  'ladle': 'ဇွန်း',
  'one tenth of a go': 'ဂို ၁/၁၀',
  'dip': 'နှိုက်',
  'urge to eat': 'စားရန်တိုက်တွန်း',
  'water route': 'ရေလမ်း',
  'shipping channel': 'သင်္ဘောလမ်းကြောင်း',
  'be aggravated': 'ပိုဆိုးလာ',
  'grow worse': 'ပိုဆိုးလာ',
  'grow bulky': 'ကြီးလာ',
  'monme': 'မွန်မေ',
  '3.75 grams': '၃.၇၅ ဂရမ်',
  'Buddhist surplice': 'ဗုဒ္ဓသင်္ကန်း',
  'descendent': 'သားစဉ်မြေးဆက်',
  'baron': 'ဗဲရုန်',
  'peerage': 'မင်းမျိုးမင်းနွယ်',
  'court rank': 'နန်းတော်အဆင့်',
  'type of deciduous tree': 'ရွက်ကြွေပင်မျိုး',
  'grey starling': 'ကြယ်ငှက်မီးခိုး',
  'ancestral offering receptacle': 'ဘိုးဘေးလှူအိုး',
  'coral': 'သန္တာ',
  'soothe': 'ဖြေသိမ့်',
  'pacify': 'ငြိမ်သက်စေ',
  'a coarse camlet': 'ကြမ်းထည်',
  'maple': 'မေပယ်',
  'ground-breaking': 'မြေဖွင့်ခြင်း',
  'open up farmland': 'လယ်ယာဖွင့်',
  'the Pleiades': 'ပလီယာဒီးစ်',
  'a reed instrument': 'ကျူပင်တူရိယာ',
  'the violet': 'ခရမ်းပန်း',
  'pox': 'ကျောက်ရောဂါ',
  'smallpox': 'ကျောက်ရောဂါ',
  'eggplant': 'ခရမ်းသီး',
  'iris': 'မေမုံ',
  'glassy': 'မှန်ကဲ့သို့',
  'smiling': 'ပြုံးသော',
  'reed used to cover tatami': 'တာတာမိကျူ',
  'Chinese parasol tree': 'တရုတ်ထီးပင်',
  'phoenix tree': 'ဖီးနစ်ပင်',
  'gossamer': 'ပိုးပါး',
  'butterbur': 'ထောပတ်ပင်',
  'bog rhubarb': 'ရွှံ့ရူပါ့',
  'pupil of the eye': 'မျက်ဆန်',
  'eulogy': 'ချီးမွမ်းစာ',
  'coconut tree': 'အုန်းပင်',
  'tinkling of jewelry': 'ကျောက်မျက်မြည်သံ',
  'affix a seal': 'တံဆိပ်နှိပ်',
  'audience (with king)': 'ဘုရင့်ရှေ့ဆက်',
  'straight grain': 'ဖြောင့်စေ့',
  'overflow': 'လျှံ',
  'spread out': 'ဖြန့်',
  'string': 'ကြိုး',
  'samisen music': 'ရှာမိဆင်ဂီတ',
  'holly': 'ဟော်လီ',
  'tolerate': 'သည်းခံ',
  'forgive': 'ခွင့်လွှတ်',
  'third class': 'တတိယတန်း',
  '3rd': 'တတိယ',
  '3rd calendar sign': 'ပြက္ခဒိန်လက္ခဏာ ၃',
  'majestic plural': 'ဘုရင့်ကျွန်ုပ်တို့',
  'imperial we': 'ဘုရင့်ကျွန်ုပ်',
  'tedious': 'ပျင်းရိသော',
  'bonfire': 'မီးပုံ',
  'deep and broad (water)': 'ရေနက်ကျယ်'
};
