module.exports = {
  'historic village': 'သမိုင်းဝင်ရွာ',
  'to employ': 'အလုပ်ခန့်သည်',
  'to hire': 'ငှားရမ်း/ခန့်သည်',
  'language study': 'ဘာသာစကားလေ့လာ',
  'reciprocity': 'အပြန်အလှန်',
  'candidacy': 'ကိုယ်စားလှယ်လောင်းဖြစ်မှု',
  'to be effective': 'ထိရောက်သည်',
  'across the street': 'လမ်းတစ်ဖက်',
  'other side': 'တစ်ဖက်',
  'good luck': 'ကံကောင်းခြင်း',
  'to spread (out)': 'ပြန့်သည်/ဖြန့်သည်',
  'to reach to': 'ရောက်သည်',
  'advertisement': 'ကြော်ငြာ',
  'solid': 'ခိုင်မာ',
  'hard (esp. metal': 'မာကျော (သတ္တု',
  'stone)': 'ကျောက်)',
  'unpolished writing': 'မပြောင်မလှစာ',
  'coin': 'ဒင်္ဂါး',
  'taking into account': 'ထည့်တွက်ခြင်း',
  'flying': 'ပျံသန်းခြင်း',
  'services': 'ဝန်ဆောင်မှုများ',
  'fragrance': 'ရနံ့',
  'high price': 'ဈေးမြင့်',
  'high speed': 'မြန်နှုန်းမြင့်',
  'high gear': 'ဂီယာမြင့်',
  'sum total': 'စုစုပေါင်း',
  'total amount': 'စုစုပေါင်းပမာဏ',
  'National Diet': 'အမျိုးသားလွှတ်တော်',
  'national language': 'နိုင်ငံဘာသာ',
  'cereal': 'စားဂျုံ/စပါးမျိုး',
  'corn': 'ပြောင်းဖူး',
  'blackboard': 'ပျဉ်ချပ်မဲ',
  'hip': 'တင်ပါး',
  'bone fracture': 'အရိုးကျိုး',
  'even now': 'ယခုတိုင်',
  'from now on': 'ယခုမှစ၍',
  'betrothal': 'ထိမ်းမြားကြိုတင်',
  'chaos': 'ရောထွေး',
  'mayhem': 'အကြမ်းဖက်ရုန်းရင်း',
  'discrimination': 'ခွဲခြားဆက်ဆံ',
  'desert': 'သဲကန္တာရ',
  'chain': 'ကြိုးဆက်/ကွင်းဆက်',
  'in the middle of': 'အလယ်တွင်',
  'ingredients': 'ပါဝင်ပစ္စည်း',
  'novelist': 'ဝတ္ထုရေးဆရာ',
  'produce (e.g. agricultural)': 'ထွက်ကုန် (စိုက်ပျိုး)',
  'crops': 'သီးနှံများ',
  'cherry blossom': 'ချယ်ရီပန်း',
  'cherry tree': 'ချယ်ရီပင်',
  '(1) token': '(၁) တိုကင်',
  '(2) ticket': '(၂) လက်မှတ်',
  '(3) charm': '(၃) စုန်းဆေး/အမှတ်တရ',
  'oxygen': 'အောက်ဆီဂျင်',
  'residue': 'အကြွင်းအကျန်',
  'remaining': 'ကျန်ရှိ',
  'left-over': 'ပိုလျှံ/ကျန်',
  'stimulus': 'လှုံ့ဆော်မှု',
  'impetus': 'တွန်းအား',
  '(the) market (as a concept)': 'ဈေးကွက် (သဘော)',
  'memories': 'အမှတ်တရများ',
  'recollections': 'ပြန်အမှတ်ရမှု',
  'reminiscence': 'အတိတ်ပြန်တွေး',
  'unintentional': 'မရည်ရွယ်',
  'spontaneous': 'သဘာဝအလျောက်',
  'guidance': 'လမ်းညွှန်',
  'coaching': 'နည်းပြပေးခြင်း',
  'to choke': 'လည်ချောင်းပိတ်',
  'to be obstructed': 'ပိတ်ဆို့ခံရ',
  'branch store (office)': 'ဌာနခွဲ/ဆိုင်ခွဲ',
  'to cease': 'ရပ်စဲသည်',
  'to abolish': 'ဖျက်သိမ်းသည်',
  'to resign': 'နုတ်ထွက်သည်',
  'verse of poetry': 'ကဗျာပိုဒ်',
  'poet': 'ကဗျာဆရာ',
  'in succession': 'ဆက်တိုက်',
  '(1) order': '(၁) အစဉ်',
  'precedence': 'ဦးစားပေးအစဉ်',
  '(2) circumstances': '(၂) အခြေအနေ',
  '(3) immediate(ly)': '(၃) ချက်ချင်း',
  'suicide': 'ကိုယ့်ကိုယ်ကိုသတ်',
  'by oneself': 'ကိုယ်တိုင်',
  'personally': 'ကိုယ်ရေးကိုယ်တာ',
  'self-motion': 'ကိုယ်တိုင်လှုပ်ရှား',
  'unemployment': 'အလုပ်လက်မဲ့',
  'as a matter of fact': 'တကယ်တော့',
  'implementation': 'အကောင်အထည်ဖော်',
  'realization': 'နားလည်/အကောင်အထည်',
  'practical': 'လက်တွေ့ကျ',
  'actual condition': 'အမှန်တကယ်အခြေအနေ',
  'to be taken off': 'ချွတ်ခံရ/ဖယ်ခံရ',
  'to be removed': 'ဖယ်ရှားခံရ',
  'surgical operation': 'ခွဲစိတ်ကုသ',
  'sleight of hand': 'လက်လှည့်ပညာ',
  'conjuring trick': 'မျက်လှည့်',
  'magic': 'မှော်ပညာ',
  'juggling': 'ဘောလုံးလှည့်ကစား',
  '(1) seed': '(၁) မျိုးစေ့',
  '(2) material': '(၂) ပစ္စည်း',
  '(3) cause': '(၃) အကြောင်းရင်း',
  'capital city': 'မြို့တော်',
  'crop': 'သီးနှံ',
  'ingathering': 'ရိတ်သိမ်းခြင်း',
  'receipts': 'ဝင်ငွေ/ပြေစာ',
  'revenue': 'ဝင်ငွေ',
  'to settle in (place)': 'အခြေချသည်',
  'to take (seat': 'ထိုင်သည် (နေရာ',
  'position)': 'ရာထူး)',
  'to study (under teacher)': 'ဆရာထံသင်သည်',
  'finding employment': 'အလုပ်ရှာ/အလုပ်ရ',
  'sandbank': 'သဲသောင်',
  'repairing': 'ပြုပြင်ခြင်း',
  'focusing the mind': 'စိတ်အာရုံစိုက်',
  'to abide (by the rules)': 'စည်းကမ်းလိုက်နာ',
  'to obey': 'နာခံသည်',
  'cousin (male)': 'ဝမ်းကွဲအစ်ကို/ညီ',
  'congestion (e.g. traffic)': 'ပိတ်ဆို့မှု (ယာဉ်)',
  'importance': 'အရေးကြီးမှု',
  'serious consideration': 'လေးနက်စဉ်းစား',
  'to congratulate': 'ဂုဏ်ပြုသည်',
  'to celebrate': 'ကျင်းပ/ဂုဏ်ပြု',
  'graduate from': 'ဘွဲ့ရသည်',
  'come from': 'မှလာသည်',
  'presence': 'ရှိနေခြင်း',
  'if at all possible': 'ဖြစ်နိုင်လျှင်',
  'to state': 'ဖော်ပြသည်',
  'to mention': 'ဖော်ပြ/ပြောသည်',
  'turn (in line)': 'အလှည့် (တန်း)',
  'order of things': 'အစဉ်အတိုင်း',
  'documents': 'စာရွက်စာတမ်း',
  'official papers': 'တရားဝင်စာရွက်',
  'helper': 'ကူညီသူ',
  'helpmeet': 'အဖော်အကူ',
  'assistant': 'လက်ထောက်',
  'tutor': 'ကျူရှင်ဆရာ',
  'to exclude': 'ချန်လှပ်သည်',
  'to except': 'မှလွဲ၍',
  'scholarship': 'ပညာသင်ဆု',
  'hut': 'တဲ',
  'cabin': 'အိမ်ငယ်/ကက်ဘင်',
  'shed': 'ကုန်လှောင်တဲ',
  '(animal) pen': 'တိရစ္ဆာန်ခြံ',
  'just a minute': 'ခဏနေ',
  'small quantity': 'ပမာဏနည်း',
  'anything of': 'တစ်ခုခုမျှ',
  'not one bit': 'နည်းနည်းမှမ',
  'boys': 'ယောက်ျားလေးများ',
  'juveniles': 'လူငယ်များ',
  'floor': 'ကြမ်းပြင်/ထပ်',
  'admitting': 'ဝန်ခံခြင်း',
  'to arise': 'ပေါ်ပေါက်သည်',
  'to ascend': 'တက်သည်',
  'to go up': 'တက်သွားသည်',
  '(1) pine tree': '(၁) ထင်းရှူးပင်',
  '(2) highest (of a three-tier ranking system)': '(၂) အမြင့်ဆုံး (အဆင့်သုံး)',
  'fire department': 'မီးသတ်ဌာန',
  'to eliminate': 'ဖယ်ရှားသည်',
  'to curtail': 'လျှော့ချသည်',
  'to economize': 'ခြိုးခြံသည်',
  'smiling face': 'ပြုံးမျက်နှာ',
  'collision': 'တိုက်မိခြင်း',
  'conflict': 'ပဋိပက္ခ',
  'elephant': 'ဆင်',
  'award': 'ဆု',
  'obstacle': 'အတားအဆီး',
  'impediment (fault)': 'အနှောင့်အယှက် (ချို့ယွင်း)',
  'outer': 'အပြင်ဘက်',
  'surface': 'မျက်နှာပြင်',
  'proceeding to the capital (Tokyo)': 'မြို့တော်သို့သွား',
  'very good': 'အလွန်ကောင်း',
  'jest': 'ဟာသ/နောက်ပြောင်',
  'common sense': 'ဘုံအသိ',
  'terms': 'စကားလုံး/စည်းကမ်း',
  '(male) (vulg) to eat': 'စားသည် (ယောက်ျား/ကြမ်း)',
  'dining table': 'ထမင်းစားစားပွဲ',
  'commodity': 'ကုန်ပစ္စည်း',
  'foodstuff': 'အစားအသောက်ပစ္စည်း',
  'appetite (for food)': 'အစားစားချင်စိတ်',
  'rations': 'ရိက္ခာ',
  'buttocks': 'တင်ပါး/နောက်ပိုင်း',
  'traffic lights': 'မီးပွိုင့်',
  'semaphore': 'အချက်ပြအလံ',
  'discretion': 'ဆင်ခြင်ဉာဏ်',
  'prudence': 'သတိထားမှု',
  'fresh': 'လတ်ဆတ်',
  'to apply for': 'လျှောက်ထားသည်',
  'to make an application': 'လျှောက်လွှာတင်',
  'flushed (of face)': 'မျက်နှာနီရဲ',
  'seriousness': 'လေးနက်မှု',
  'earnestness': 'စိတ်ရင်းမှန်',
  'mimicry': 'တုပခြင်း',
  'behavior': 'အပြုအမူ',
  'pretense': 'ဟန်ဆောင်',
  'close (e.g. friend)': 'ရင်းနှီး (သူငယ်ချင်း)',
  'relative': 'ဆွေမျိုး',
  'close friend': 'ရင်းနှီးသူငယ်ချင်း',
  'buddy': 'သူငယ်ချင်း',
  'medical examination': 'ဆေးစစ်ခြင်း',
  'height (of body)': 'ကိုယ်အရပ်',
  'stature': 'အရပ်အမောင်း',
  'going on to university': 'တက္ကသိုလ်ဆက်တက်',
  'hand (e.g. clock)': 'လက်တံ (နာရီ)',
  'sign of life': 'အသက်ရှိလက္ခဏာ',
  'manmade': 'လူလုပ်',
  'human work': 'လူ့အလုပ်',
  'human skill': 'လူ့ကျွမ်းကျင်မှု',
  'crowd of people': 'လူအုပ်',
  'race (of people)': 'လူမျိုး',
  '(human) life (i.e. conception to death)': 'လူ့ဘဝ (မွေးမှသေ)',
  'mankind': 'လူသားမျိုးနွယ်',
  'humanity': 'လူသား/လူ့စိတ်',
  'recommendation': 'အကြံပြု/ထောက်ခံ',
  '(1) water level': '(၁) ရေအဆင့်',
  '(2) level': '(၂) အဆင့်',
  'to get drunk': 'မူးသည်',
  'to become intoxicated': 'မူးယစ်သည်',
  'limitation': 'ကန့်သတ်ချက်',
  'grow to adulthood': 'အရွယ်ရောက်သည်',
  '(logical) true': 'မှန် (ယုတ္တိ)',
  'punctuality': 'အချိန်မှန်မှု',
  'exactness': 'တိကျမှု',
  'authenticity': 'စစ်မှန်မှု',
  'integrity': 'သမာဓိ',
  '(1) draft (beer)': '(၁) စည်သွတ်ဘီယာ',
  '(2) raw': '(၂) စိမ်း/မချက်',
  'unprocessed': 'မပြုပြင်ရသေး',
  'raw food': 'စားစရာစိမ်း',
  'helping': 'ဟင်းတစ်ပွဲ',
  'serving': 'တင်ကျွေးခြင်း',
  'at the most': 'အများဆုံး',
  'at best': 'အကောင်းဆုံးအားဖြင့်',
  'to the utmost': 'အတတ်နိုင်ဆုံး',
  'as much (far) as possible': 'ဖြစ်နိုင်သမျှ',
  'manufactured goods': 'ထုတ်ကုန်ပစ္စည်း',
  'finished goods': 'အချောထည်',
  'proactive': 'ကြိုတင်လုပ်ဆောင်',
  'to condemn': 'ရှုတ်ချသည်',
  'to criticize': 'ဝေဖန်သည်',
  '(1) to cut well': '(၁) ကောင်းစွာဖြတ်',
  'to be sharp': 'ထက်သည်',
  '(2) to break (off)': '(၂) ချိုး/ပြတ်သည်',
  'facilities': 'အဆောက်အအုံ/စက်ရုံ',
  'economising': 'ခြိုးခြံခြင်း',
  'saving': 'စုဆောင်းခြင်း',
  'absolute': 'လုံးဝ/အကြွင်းမဲ့',
  'unconditional': 'စည်းကမ်းမဲ့',
  'absoluteness': 'အကြွင်းမဲ့မှု',
  'extinction': 'မျိုးတုန်း/ပျောက်ကွယ်',
  'the other day': 'နေ့က',
  'a few days ago': 'ရက်အနည်းငယ်က',
  '(1) to comprise': '(၁) ပါဝင်သည်',
  'to account for': 'ရာခိုင်နှုန်းရှိ',
  'to make up (of)': 'ဖွဲ့စည်းသည်',
  '(2) to hold': '(၂) ကိုင်/ကျင်းပ',
  'major subject': 'အဓိကဘာသာ',
  'special study': 'အထူးလေ့လာ',
  '(1) player (in game)': '(၁) ကစားသမား',
  '(2) team': '(၂) အသင်း',
  'all members (unanimity)': 'အဖွဲ့သားအားလုံး',
  'all hands': 'လူအားလုံး',
  'the whole crew': 'အမှုထမ်းအားလုံး',
  'country-wide': 'နိုင်ငံအနှံ့',
  'nation-wide': 'တနိုင်ငံလုံး',
  'entirety': 'တစ်ခုလုံး',
  'whatever (is the matter)': 'ဘာပဲဖြစ်ဖြစ်',
  'flaw': 'ချို့ယွင်းချက်',
  'blemish': 'အစွန်းအထင်း',
  'prime': 'အဓိက/အကောင်းဆုံး',
  'to sue (a person)': 'တရားစွဲသည်',
  'to resort to': 'အားကိုး/သုံးသည်',
  'to appeal to': 'တိုင်ကြား/ဆွဲဆောင်',
  '(1) mouse': '(၁) ကြွက်',
  '(2) dark gray': '(၂) မီးခိုးရင့်',
  'twins': 'အမွှာ',
  'a twin': 'အမွှာတစ်ဦး',
  'imagination': 'စိတ်ကူး',
  'sweeping': 'တံမြက်စည်းလှည်း',
  'breeding place': 'မွေးမြူရာနေရာ',
  'beehive': 'ပျားအုံ',
  'succession': 'ဆက်ခံခြင်း',
  'inheritance': 'အမွေ',
  'apparatus': 'ကိရိယာ',
  'noise': 'ဆူညံသံ',
  'handbreadth': 'လက်အနံ',
  'sequel': 'ဆက်လက်အပိုင်း',
  'sleeve': 'လက်စွပ်',
  'reverence': 'ရိုသေမှု',
  'regard': 'လေးစားမှု',
  'other (esp. places and things)': 'အခြား (နေရာ/ပစ္စည်း)',
  'physical education': 'ကိုယ်လက်လေ့ကျင့်',
  'athletics': 'အားကစား',
  'temperature (body)': 'ကိုယ်အပူချိန်',
  'band (e.g. conduction': 'ကြိုး/တီးဝိုင်း (လျှပ်ကူး',
  'valence)': 'တန်ဖိုး)',
  'manner': 'ပုံစံ/အမူအရာ',
  'tedium': 'ငြီးငွေ့မှု',
  'boredom': 'ပျင်းရိမှု',
  'apprehension': 'စိုးရိမ်မှု',
  'representation': 'ကိုယ်စားပြု',
  'agency': 'အေးဂျင်စီ',
  'proxy': 'ကိုယ်စားလှယ်',
  'deputy': 'ဒုတိယ/ကိုယ်စား',
  'rich family': 'ချမ်းသာသောမိသားစု',
  'distinguished family': 'ထင်ရှားမိသားစု',
  'tournament': 'ပြိုင်ပွဲ',
  'mass meeting': 'အစည်းအဝေးကြီး',
  'rally': 'စုဝေးပွဲ',
  'ambassador': 'သံအမတ်',
  'cabinet minister': 'ဝန်ကြီး',
  'great war': 'စစ်ကြီး',
  'great battle': 'တိုက်ပွဲကြီး',
  'president': 'သမ္မတ/ဥက္ကဋ္ဌ',
  'chief executive': 'အမှုဆောင်ချုပ်',
  'most part': 'အများစု',
  'greater part': 'အများစုပိုင်း',
  'continent': 'တိုက်ကြီး',
  'to clap': 'လက်ခုပ်တီး',
  'to dust': 'ဖုန်ခါသည်',
  'to snatch away': 'လုယူသည်',
  'someone': 'တစ်စုံတစ်ဦး',
  'somebody': 'တစ်ယောက်ယောက်',
  '(in) charge': 'တာဝန်ခံ',
  'shot': 'ပစ်ချက်/ရိုက်ချက်',
  'to decline': 'ငြင်းသည်/ကျဆင်း',
  'to dismiss': 'ထုတ်ပယ်သည်',
  'prefectural governor': 'ပြည်နယ်အုပ်ချုပ်ရေးမှူး',
  'brains': 'ဦးနှောက်/ဉာဏ်',
  '(social) position': 'လူမှုရာထူး',
  'status': 'အဆင့်အတန်း',
  'basement': 'မြေအောက်ထပ်',
  'underground': 'မြေအောက်',
  'lateness': 'နောက်ကျမှု',
  'late coming': 'နောက်ကျလာခြင်း',
  'discontinuance': 'ရပ်ဆိုင်းခြင်း',
  'annotation': 'မှတ်ချက်',
  'explanatory note': 'ရှင်းလင်းချက်',
  'tooth decay': 'သွားပိုးစား',
  'decayed tooth': 'ပိုးစားသွား',
  'caries': 'သွားပိုး',
  'parking (e.g. car)': 'ကားရပ်နား',
  '(bank) savings': 'ဘဏ်စုငွေ',
  'to view': 'ကြည့်ရှုသည်',
  'to gaze at': 'စိုက်ကြည့်သည်',
  'long time period': 'ကြာရှည်ကာလ',
  'to feel depressed': 'စိတ်ဓာတ်ကျ',
  'to overtake': 'ကျော်တက်သည်',
  'to catch up (with)': 'လိုက်မီသည်',
  'to chase': 'လိုက်သည်',
  'to run after': 'နောက်လိုက်ပြေး',
  'in accordance with ~': '~အတိုင်း',
  'following ~': '~နောက်လိုက်',
  '~ Street': '~လမ်း',
  '~ Avenue': '~လမ်းမ',
  'passage through': 'ဖြတ်သန်းခြင်း',
  'commuting to school': 'ကျောင်းတက်သွားလာ',
  'bus or tram stop': 'ဘတ်စ်/ထရမ်မှတ်တိုင်',
  'fixed term': 'သတ်မှတ်ကာလ',
  'proposal': 'အဆိုပြုချက်',
  'proposition': 'အဆို/ဝါကျ',
  'filing': 'ဖိုင်တင်ခြင်း',
  'to fit': 'ကိုက်ညီသည်',
  'pertinent': 'သက်ဆိုင်',
  'adequate': 'လုံလောက်',
  'relevance': 'သက်ဆိုင်မှု',
  'applying': 'လျှောက်ထား/အသုံးချ',
  'to be drowned': 'ရေနစ်သည်',
  'to indulge in': 'နှစ်သက်စွဲလမ်း',
  'philosophy': 'ဒဿနိကဗေဒ',
  'thoroughness': 'ပြည့်စုံစေ့စပ်',
  'all night vigil': 'ညလုံးပေါက်စောင့်',
  'sleepless night': 'အိပ်မပျော်ည',
  'railroad': 'ရထားလမ်း',
  'to fall down': 'လဲသည်',
  'to fall over': 'လဲကျသည်',
  'electron': 'အီလက်ထရွန်',
  'rabbit': 'ယုန်',
  'hare': 'တောယုန်',
  'cony': 'ယုန်',
  '(1) to breathe': '(၁) အသက်ရှူ',
  '(2) to tell (lies)': '(၂) လိမ်ပြော',
  '(3) to vomit': '(၃) အန်သည်',
  'mountain-climbing': 'တောင်တက်ခြင်း',
  'just (now': 'ယခုပဲ (အခု',
  'at the moment': 'ဒီအချိန်မှာ',
  'to bring down': 'ချသည်/ချခေါ်',
  'to blow down': 'မှုတ်ချသည်',
  'party (political)': 'ပါတီ (နိုင်ငံရေး)',
  'to be frozen over': 'အေးခဲသည်',
  'voting': 'မဲပေးခြင်း',
  'poll': 'မဲဆန္ဒ',
  'to be hit': 'ထိ/ရသည်',
  'to be successful': 'အောင်မြင်သည်',
  'to be equivalent to': 'ညီမျှသည်',
  'at that time': 'ထိုအချိန်က',
  'in those days': 'ထိုခေတ်က',
  'examination paper': 'စာမေးပွဲစာရွက်',
  'examination script': 'စာမေးအဖြေစာ',
  'peas': 'ပဲစေ့',
  'headache': 'ခေါင်းကိုက်',
  'verb': 'ကြိယာ',
  'simultaneous(ly)': 'တစ်ပြိုင်နက်',
  'same time': 'တစ်ချိန်တည်း',
  'synchronous': 'တစ်ပြိုင်နက်',
  'coworker': 'လုပ်ဖော်ကိုင်ဖက်',
  'colleague': 'လုပ်ဖော်',
  'morals': 'ကျင့်ဝတ်',
  'triumph': 'အောင်ပွဲ',
  'toxicant': 'အဆိပ်ပစ္စည်း',
  'bachelorhood': 'လူပျိုဘဝ',
  'celibate': 'အိမ်ထောင်မရှိ',
  'uniqueness': 'ထူးခြားမှု',
  'independence (e.g. Ind. Day)': 'လွတ်လပ်ရေး',
  'self-support': 'ကိုယ်တိုင်ရပ်တည်',
  'saucepan': 'ဟင်းချက်အိုး',
  'hospitalization': 'ဆေးရုံတက်',
  'entry to school or university': 'ကျောင်း/တက္ကသိုလ်ဝင်',
  'matriculation': 'တက္ကသိုလ်ဝင်ခွင့်',
  'to entrust to another': 'အခြားသူကိုအပ်',
  'to leave to': 'လွှဲအပ်သည်',
  'to appreciate': 'တန်ဖိုးထား/ကျေးဇူးတင်',
  'to admit': 'ဝန်ခံ/ဝင်ခွင့်ပေး',
  'tropics': 'အပူပိုင်း',
  'months and years': 'လနှင့်နှစ်',
  'being skilled in': 'ကျွမ်းကျင်ခြင်း',
  'nicely': 'ကောင်းစွာ',
  'properly': 'မှန်ကန်စွာ',
  'farmer': 'လယ်သမား',
  'farm family': 'လယ်ယာမိသားစု',
  'peasants': 'တောင်သူလယ်သမား',
  '(personal) bankruptcy': 'ကိုယ်ပိုင်ဒေဝါလီ',
  '(1) horse': '(၁) မြင်း',
  '(2) promoted bishop (shogi)': '(၂) မြှင့်ဘုရား (ရှိုးဂိ)',
  'fool': 'လူမိုက်',
  'idiot': 'အရူး',
  'trivial matter': 'အရေးမကြီးကိစ္စ',
  'player': 'ကစားသမား/တူရိယာသမား',
  'performer': 'ဖျော်ဖြေသူ',
  'plum-tree': 'ဇီးပင်',
  'lowest (of a three-tier ranking system)': 'အနိမ့်ဆုံး (အဆင့်သုံး)',
  'rainy season': 'မိုးရာသီ',
  'rain during the rainy season': 'မိုးဦးမိုး',
  'to be sold': 'ရောင်းချခံရ',
  'doctorate': 'ပါရဂူဘွဲ့',
  'PhD': 'ပါရဂူဘွဲ့',
  'museum': 'ပြတိုက်',
  'clapping hands': 'လက်ခုပ်တီး',
  'applause': 'လက်ခုပ်သံ',
  'detonation': 'ပေါက်ကွဲသံ',
  'discovery': 'ရှာဖွေတွေ့ရှိ',
  'detection': 'ဖော်ထုတ်ခြင်း',
  'finding': 'တွေ့ရှိချက်',
  'issue (publications)': 'ထုတ်ဝေခြင်း',
  'departure of a vehicle': 'ယာဉ်ထွက်ခွာ',
  'invention': 'တီထွင်မှု',
  'hair (head)': 'ဆံပင်',
  'to punish': 'ပြစ်ဒဏ်ပေး',
  'to penalize': 'ဒဏ်ပေးသည်',
  'to extract': 'ထုတ်ယူသည်',
  'to draw out': 'ဆွဲထုတ်သည်',
  'plank': 'ပျဉ်ချပ်',
  'offender': 'ပြစ်မှုကျူးလွန်သူ',
  'marketing': 'ဈေးကွက်ရှာဖွေ',
  'repudiation': 'ငြင်းပယ်ခြင်း',
  'they (usually male)': 'သူတို့ (ယောက်ျား)',
  'to be sad': 'ဝမ်းနည်းသည်',
  'to mourn for': 'ငိုကြွေးသည်',
  'to regret': 'နောင်တရသည်',
  'tragedy': 'ကြေကွဲဖွယ်',
  'commentary': 'ရှင်းလင်းချက်/ဝေဖန်',
  'tiredness': 'ပင်ပန်းမှု',
  'to suffer': 'ခံစားရသည်',
  '(1) to avoid (physical contact )': '(၁) ထိတွေ့မှုရှောင်',
  '(2) to ward off': '(၂) ကာကွယ်သည်',
  'to skip over': 'ကျော်သွားသည်',
  'to jump out': 'ခုန်ထွက်သည်',
  'to rush out': 'ပြေးထွက်သည်',
  'to fly out': 'ပျံထွက်သည်',
  'to provide for': 'ပြင်ဆင်/ထောက်ပံ့',
  'subtle': 'သိမ်မွေ့',
  'beautiful person (woman)': 'လှပသောအမျိုးသမီး',
  'knee': 'ဒူး',
  '(not) always': 'အမြဲတမ်း(မ)',
  '(not) necessarily': 'မုချ(မ)',
  '(not) all': 'အားလုံး(မ)',
  '(not) entirely': 'လုံးဝ(မ)',
  'inevitable death': 'မလွှဲမရှောင်သေ',
  'desperation': 'စိတ်ပျက်အားလျှော့',
  'frantic': 'ရူးသွပ်/အသည်းအသန်',
  'inevitable result': 'မလွှဲရလဒ်',
  'writing brush': 'စုတ်တံ',
  '(1) string': '(၁) ကြိုး',
  '(2) pimp': '(၂) ပြည့်တန်ဆာအေးဂျင့်',
  'table (e.g. Tab 1)': 'ဇယား (ဥပမာ ဇယား၁)',
  'expression': 'ဖော်ပြချက်/အမူအရာ',
  'representation (math)': 'ကိုယ်စားပြု (သင်္ချာ)',
  'facial expression': 'မျက်နှာအမူအရာ',
  'valuation': 'တန်ဖိုးသတ်မှတ်',
  'assessment': 'အကဲဖြတ်',
  'evaluation': 'အကဲဖြတ်ခြင်း',
  'second (60th min)': 'စက္ကန့်',
  'un': 'မ-',
  'non': 'မရှိ/မဟုတ်',
  'negative prefix': 'ငြင်းဆိုရှေ့ဆက်',
  'uneasiness': 'မအေးချမ်းမှု',
  'insecurity': 'မလုံခြုံမှု',
  'suspense': 'စိတ်လှုပ်ရှားစောင့်',
  'injustice': 'မတရားမှု',
  'insufficiency': 'မလုံလောက်မှု',
  'shortage': 'ရှားပါးမှု',
  'deficiency': 'ချို့တဲ့မှု',
  'displeasure': 'မကျေနပ်မှု',
  'complaints': 'တိုင်ကြားချက်',
  'disadvantage': 'အားနည်းချက်',
  'handicap': 'မသန်စွမ်း/အားနည်း',
  'unfavorable': 'မကောင်းသော',
  'drawback': 'အားနည်းချက်',
  'socializing': 'ပေါင်းသင်းဆက်ဆံ',
  'fellowship': 'ရင်းနှီးမှု/အသင်းအဖွဲ့',
  'husband and wife': 'ဇနီးမောင်နှံ',
  'to go bad': 'ပျက်စီး/ပုပ်သည်',
  'stage (theatre)': 'စင်မြင့်',
  'garments': 'အဝတ်အစား',
  'merciful person': 'သနားတတ်သူ',
  'Buddhist image': 'ဗုဒ္ဓရုပ်ပွား',
  'sounds': 'အသံများ',
  'prices of commodities': 'ကုန်ဈေးနှုန်း',
  'prices (in general)': 'ဈေးနှုန်းများ',
  'things': 'အရာများ',
  'physics': 'ရူပဗေဒ',
  'phrase': 'စကားစု',
  'equality (a)': 'တန်းတူညီမျှ',
  'impartiality': 'ဘက်မလိုက်မှု',
  'to close (e.g. book': 'ပိတ်သည် (စာအုပ်',
  'eyes)': 'မျက်စိ)',
  'to shut': 'ပိတ်သည်',
  'a habit (often a bad habit)': 'အကျင့် (မကောင်း)',
  '(not) particularly': 'အထူးသဖြင့်(မ)',
  'goblin': 'ဘီလူး',
  'bugbear': 'ကြောက်စရာ',
  'box lunch': 'ဘန်တို',
  'conservation': 'ထိန်းသိမ်းခြင်း',
  'to be caught': 'ဖမ်းဆီးခံရ',
  'to be arrested': 'ဖမ်းဆီးခံရ',
  'footpath': 'ခြေလျင်လမ်း',
  'walkway': 'လမ်းလျှောက်',
  'sidewalk': 'လမ်းဘေးလမ်း',
  'bale': 'ထုပ်/အထုပ်',
  'to hold or carry under or in the arms': 'ရင်ခွင်ပိုက်သည်',
  '(sl) to embrace': 'ပွေ့ဖက်သည် (လူငယ်)',
  'to hug': 'ပွေ့ဖက်သည်',
  'to harbour': 'ခိုလှုံ/ထားရှိ',
  'broadcast': 'ထုတ်လွှင့်',
  'broadcasting': 'ထုတ်လွှင့်ခြင်း',
  'Act (law: the X Act)': 'ဥပဒေ (X ဥပဒေ)',
  'bubble': 'ပူဖောင်း',
  'head on beer': 'ဘီယာအမြှုပ်',
  'plenty': 'ပေါများ',
  'bounty': 'ကြွယ်ဝမှု/ဆုငွေ',
  'to get tired of': 'ငြီးငွေ့သည်',
  'to lose interest in': 'စိတ်ဝင်စားမှုပျောက်',
  'to have enough': 'လုံလောက်ပြီ',
  '(a) hope': 'မျှော်လင့်ချက်',
  'pole': 'တိုင်/ဝင်ရိုး',
  'stick': 'တုတ်',
  'risk': 'အန္တရာယ်',
  'venture': 'စွန့်စားလုပ်',
  'adventure': 'စွန့်စားခန်း',
  'cheek (of face)': 'ပါး',
  'the person himself': 'သူ့ကိုယ်တိုင်',
  'genuine article': 'ပစ္စည်းအစစ်',
  'the end of': 'အဆုံး',
  'by some chance': 'တိုက်ဆိုင်စွာ',
  'by some possibility': 'ဖြစ်နိုင်ချေဖြင့်',
  'if by any chance': 'တကယ်လို့',
  '10E4:1 odds': 'အလောင်းအစား ၁၀၀၀၀:၁',
  'to be full': 'ပြည့်သည်',
  'to rise (tide)': 'တက်သည် (ရေ)',
  'to mature': 'ရင့်ကျက်သည်',
  'to expire': 'သက်တမ်းကုန်',
  'satisfaction': 'ကျေနပ်မှု',
  'future (life': 'အနာဂတ် (ဘဝ',
  'tense)': 'ကာလ)',
  'glamour': 'ဆွဲဆောင်မှု',
  'daze': 'မူးဝေ',
  '(in a) trance': 'စိတ်လွင့်',
  'ecstasy': 'အလွန်ပျော်ရွှင်',
  'delirium': 'အရူးအမူး',
  'disregard': 'လျစ်လျူရှု',
  'ignore': 'ဂရုမစိုက်',
  'lamplight': 'မီးရောင်',
  'light (in general)': 'အလင်းရောင်',
  'to dawn': 'မိုးလင်းသည်',
  'to become daylight': 'နေ့အလင်းရောက်',
  'clarify': 'ရှင်းလင်းသည်',
  'define': 'သတ်မှတ်သည်',
  'lost (stray) child': 'လမ်းပျောက်ကလေး',
  'annoyance': 'စိတ်ရှုပ်/နှောင့်ယှက်',
  'rarely (with neg. verb)': 'ရှားရှားပါးပါး',
  'seldom': 'မကြာခဏမဟုတ်',
  'certificate': 'လက်မှတ်',
  'blanket': 'စောင်',
  'to be silent': 'ဆိတ်ဆိတ်နေ',
  'target': 'ပစ်မှတ်',
  'quite right': 'လုံးဝမှန်',
  'plausible': 'ယုံနိုင်ဖွယ်',
  'natural': 'သဘာဝ',
  'but then': 'ဒါပေမဲ့',
  'midnight': 'သန်းခေါင်',
  'dead of night': 'ညနက်',
  'burden': 'ဝန်ထုပ်',
  'export': 'တင်ပို့',
  'overall victory': 'အလုံးစုံအောင်',
  'championship': 'ချန်ပီယံဆု',
  'valour': 'ရဲစွမ်းသတ္တိ',
  'validity': 'တရားဝင်မှု',
  'availability': 'ရရှိနိုင်မှု',
  'effectiveness': 'ထိရောက်မှု',
  'advantageous': 'အကျိုးရှိ',
  'lucrative': 'အမြတ်များ',
  'postal service': 'စာပို့ဌာန',
  'assume will happen': 'ဖြစ်မည်ဟုယူဆ',
  'budget': 'ဘတ်ဂျက်',
  'precaution': 'ကြိုတင်ကာကွယ်',
  'protection against': 'ကာကွယ်မှု',
  'not very (used as adverb)': 'သိပ်မ…ဘူး',
  'not much': 'များများစားစားမ',
  'to give into custody': 'ထိန်းသိမ်းအပ်',
  'very young': 'အလွန်ငယ်',
  'day of the week': 'ရက်သတ္တပတ်နေ့',
  'element': 'ဒြပ်စင်/အခြေခံ',
  'main point': 'အဓိကအချက်',
  'wings': 'အတောင်များ',
  'for (10 days)': '(၁၀ရက်) ကြာ',
  'next (year)': 'လာမည့် (နှစ်)',
  'to have recourse to': 'အားကိုးသည်',
  'to depend on': 'မှီခိုသည်',
  'profits': 'အမြတ်များ',
  'gains': 'ရရှိမှုများ',
  '(political': '(နိုင်ငံရေး',
  'economic) interest': 'စီးပွားရေး) အကျိုးစီးပွား',
  'ideal': 'စံပြ/အကောင်းဆုံး',
  'to betray': 'သစ္စာဖောက်',
  'to turn traitor to': 'သစ္စာဖောက်သည်',
  'to double-cross': 'လှည့်စားသစ္စာဖောက်',
  'divorce': 'အိမ်ထောင်ကွဲ',
  'six (used in legal documents)': 'ခြောက် (ဥပဒေသုံး)',
  'to stand up': 'ထသည်',
  'to drain': 'ရေထုတ်သည်',
  'to shed (blood': 'ယိုသည် (သွေး',
  'tears)': 'မျက်ရည်)',
  'to fasten': 'ချည်/ပိတ်သည်',
  'to turn off': 'ပိတ်သည်',
  'to detain': 'ချုပ်နှောင်သည်',
  'studying abroad': 'နိုင်ငံခြားပညာသင်',
  'serenity': 'ငြိမ်သက်မှု',
  'train (ordinary)': 'ရထား (ပုံမှန်)',
  'to fall behind': 'နောက်ကျသည်',
  'to be inferior to': 'နိမ့်သည်',
  'lover': 'ချစ်သူ',
  'sweetheart': 'ချစ်သူ',
  'association (of ideas)': 'အတွေးဆက်စပ်',
  'serial': 'ဆက်လက်',
  'consecutive': 'ဆက်တိုက်',
  'continuity': 'ဆက်စပ်မှု',
  'continuing': 'ဆက်လက်ဖြစ်',
  'old person': 'လူကြီး/သက်ကြီး',
  'controversy': 'အငြင်းပွားမှု',
  'to suffer from': 'ခံစားရသည်',
  'basket': 'ခြင်းတောင်း',
  'cage': 'လှောင်အိမ်',
  'to run somebody over (with vehicle)': 'ယာဉ်နှင့်တိုက်နင်း',
  'to knock someone down': 'လူကိုလှဲချ',
  'accent': 'အသံနေအသံထား',
  'yawn': 'ဟောက်ခြင်း',
  'to do for': 'အတွက်လုပ်ပေး',
  'to be applicable': 'သက်ဆိုင်သည်',
  'to come under (a category)': 'အမျိုးအစားဝင်',
  'to become confused': 'ရှုပ်ထွေးသည်',
  'antenna': 'အင်တင်နာ',
  'carelessly': 'ဂရုမစိုက်ဘဲ',
  'thoughtlessly': 'မစဉ်းစားဘဲ',
  'inadvertently': 'မရည်ရွယ်ဘဲ',
  'loiteringly': 'လှည့်လည်ရင်း',
  'aimless wandering': 'ရည်မှန်းမဲ့လှည့်',
  'a great deal': 'အများကြီး',
  'etiquette': 'ယဉ်ကျေးမှုစည်းကမ်း',
  'apron': 'ရှေ့ဆီးပုဆိုး',
  'orchestra': 'တီးဝိုင်းကြီး',
  'rough (not precise)': 'ကြမ်း/မတိကျ',
  'automation': 'အလိုအလျောက်စနစ်',
  '(hon) wife': 'ဇနီး (လေးစား)',
  'your wife': 'သင့်ဇနီး',
  'madam': 'ကတော်/မိန်းမကြီး',
  'Excuse me for disturbing you': 'နှောင့်ယှက်မိ၍တောင်းပန်',
  '(abbr) Good morning': 'မင်္ဂလာနံနက်ခင်း',
  'Please wait a moment': 'ခဏစောင့်ပါ',
  'happy event': 'ဝမ်းသာဖွယ်ကိစ္စ',
  'matter for congratulation': 'ဂုဏ်ပြုဖွယ်ကိစ္စ',
  'auspicious event': 'မင်္ဂလာကိစ္စ',
  '(1) between meal snack': '(၁) အစာကြားမုန့်',
  'shrine visit': 'ဘုရား/နတ်ကွန်းဖူး',
  'maid': 'အိမ်အကူ',
  'second helping': 'ထပ်ထည့်',
  'another cup': 'နောက်တစ်ခွက်',
  '(1) curve': '(၁) ကွေးမျဉ်း',
  '(2) curve ball (baseball)': '(၂) ကွေးဘောလုံး',
  'cassette (tape)': 'ကက်ဆက်',
  'cover (ex. book)': 'အဖုံး (စာအုပ်)',
  'chewing gum': 'ပီကေ',
  '(n) playing cards (pt: carta)': 'ဖဲချပ်',
  'calorie': 'ကယ်လိုရီ',
  'fully': 'ပြည့်ပြည့်ဝဝ',
  'gang': 'ဂိုဏ်း',
  'cooler': 'အေးစက်',
  'air conditioner': 'လေအေးပေးစက်',
  'laundry service': 'အဝတ်လျှော်ဝန်ဆောင်',
  'thus': 'ထို့ကြောင့်',
  'it is I who should say so': 'ကျွန်ုပ်ပြောသင့်သည်',
  '(1) cook (nl:)': '(၁) စားဖိုမှူး',
  '(2) tap': '(၂) ရေပိုက်ခေါင်း',
  'spigot': 'ရေပိုက်ခေါင်း',
  'stealthily': 'လျှို့ဝှက်စွာ',
  'secretly': 'လျှို့ဝှက်စွာ',
  '(1) collection': '(၁) စုစည်းမှု',
  '(2) correction': '(၂) ပြင်ဆင်ခြင်း',
  'contest (fr: concours)': 'ပြိုင်ပွဲ',
  '(1) consent': '(၁) သဘောတူ',
  '(2) concentric': '(၂) ဗဟိုတူ',
  'siren': 'ဆိုင်ရင်/အချက်ပေးသံ',
  'salary man': 'လစာရဝန်ထမ်း',
  'company employee': 'ကုမ္ပဏီဝန်ထမ်း',
  'season (sporting)': 'ရာသီ (အားကစား)',
  'sheet': 'စာရွက်/အိပ်ရာခင်း',
  'insistent': 'ဇွဲရှိ/တောင်းဆို',
  'obstinate': 'ခေါင်းမာ',
  'to go to sleep (i.e.': 'ထုံသည် (ဥပမာ',
  'a limb)': 'ခြေလက်)',
  'journalist': 'သတင်းထောက်',
  'to squat': 'ထိုင်သည်/ပတုံထိုင်',
  'shutter': 'ရှပ်တာ/တံခါးပိတ်',
  '(n) rock-scissors-paper game': 'ကျောက်-ကတ်ကြေး-စက္ကူ',
  'series': 'စီးရီး',
  'stewardess': 'လေယာဉ်မယ်',
  '(1) stage': '(၁) စင်မြင့်',
  '(2) performance': '(၂) ဖျော်ဖြေမှု',
  'stockings': 'ခြေအိတ်ရှည်',
  'speaker': 'စပီကာ/ဟောပြောသူ',
  'stylish': 'စတိုင်ကျ',
  'to put off': 'ရွှေ့ဆိုင်းသည်',
  '(n) seminar': 'ဆွေးနွေးပွဲ',
  'offense': 'တိုက်ခိုက်/ပြစ်မှု',
  'method of attack': 'တိုက်ခိုက်နည်း',
  'cement': 'ဘိလပ်မြေ',
  'centimeter': 'စင်တီမီတာ',
  'centi-': 'စင်တီ-',
  '10^-2': '၁၀^-၂',
  'which reminds me ..': 'ပြောရဦးမယ်…',
  'otherwise': 'မဟုတ်ရင်',
  'diamond': 'စိန်',
  'dial': 'ဒိုင်ယယ်',
  'dumb': 'စကားမပြောနိုင်/မိုက်',
  'a slut': 'မဖွယ်မရာမိန်းမ',
  'to cut up fine': 'သေးသေးလှီး',
  'to pick (fruit)': 'ခူးသည် (သစ်သီး)',
  '(1) gratuity': '(၁) လက်ဖက်ရည်ဖိုး',
  '(2) chip': '(၂) ချစ်ပ်/အပိုင်း',
  'chock': 'တုံး/ပိတ်ဆို့',
  'chalk': 'ခဲဖြူ',
  '(n) theme': 'အကြောင်းအရာ',
  'topic (de: Thema)': 'ခေါင်းစဉ်',
  '(1) irresponsible utterance': '(၁) တာဝန်မဲ့စကား',
  '(2) random': '(၂) ကျပန်း',
  'tempo': 'အရှိန်/စည်းချက်',
  'throb': 'ခုန်နေခြင်း',
  'beat (fast)': 'စည်းချက် (မြန်)',
  'nylon': 'နိုင်လွန်',
  '(a) screw': 'ဝက်အူ',
  'lucidly': 'ရှင်းလင်းစွာ',
  'bucket': 'ပုံး',
  'pail': 'ပုံး',
  'pattern': 'ပုံစံ',
  'spring (e.g. coil': 'စပရိန် (ကွိုင်',
  'leaf)': 'အရွက်)',
  'underpants': 'အတွင်းခံဘောင်းဘီ',
  'band': 'ကြိုး/တီးဝိုင်း',
  'steering wheel': 'စတီယာရင်',
  'glitter': 'တောက်ပခြင်း',
  'pistol': 'ပစ္စတို',
  'vitamin': 'ဗီတာမင်',
  'vinyl': 'ဗီနိုင်း',
  'pink': 'ပန်းရောင်',
  'fastener': 'ချိတ်/ဇစ်ပါ',
  'zipper': 'ဇစ်ပါ',
  'grumbling': 'ညည်းညူခြင်း',
  'complaining in a small voice': 'တိုးတိုးညည်းညူ',
  'fry pan': 'ဒယ်အိုး',
  'frying pan': 'ဒယ်အိုး',
  'blouse': 'ဘလောက်စ်',
  'brushy': 'စုတ်တံ/ချုံထူ',
  'plastic': 'ပလတ်စတစ်',
  'platform': 'ပလက်ဖောင်း',
  'handout': 'လက်ကမ်းစာစောင်',
  'brooch': 'ရင်ထိုး',
  'veteran': 'ကျွမ်းကျင်သူ/စစ်မှုထမ်းဟောင်း',
  'helicopter': 'ရဟတ်ယာဉ်',
  '(abbr) pliers (lit: pinchers)': 'ပလာယာ',
  'so-so': 'သင့်တင့်ရုံ',
  'eyelids': 'မျက်ခွံ',
  'muffler': 'လည်စည်း/အသံတိတ်',
  'marathon': 'မာရသွန်',
  'large apartment': 'တိုက်ခန်းကြီး',
  'apartment house': 'အပါတ်မန့်တိုက်',
  '(arch) sad': 'ဝမ်းနည်း (ရှေး)',
  'wretched': 'ဆင်းရဲ/ညံ့ဖျင်း',
  'sewing machine': 'ချုပ်စက်',
  'meter (clock)': 'မီတာ/တိုင်းကိရိယာ',
  'remarkably': 'ထူးခြားစွာ',
  'motor': 'မော်တာ',
  'monorail': 'မိုနိုရေးလ်',
  '(1) noisy': '(၁) ဆူညံ',
  '(2) strict': '(၂) တင်းကျပ်',
  'fussy': 'ရွေးချယ်တတ်/ဂေါ်',
  'to attack (an enemy)': 'တိုက်ခိုက်သည်',
  'to do away with': 'ဖယ်ရှား/ဖျက်သိမ်း',
  'to finish off': 'အဆုံးသတ်သည်',
  '(1) to send': '(၁) ပို့သည်',
  'to forward': 'လွှဲပို့သည်',
  '(2) to hand over (e.g. money)': '(၂) ပေးအပ်သည်',
  'rush hour': 'ယာဉ်ကြောပြွတ်သိပ်ချိန်',
  'lunch': 'နေ့လယ်စာ',
  '(1) running': '(၁) ပြေးခြင်း',
  '(2) tank top': '(၂) လက်မဲ့အင်္ကျီ',
  'rhythm': 'စည်းချက်',
  'litre': 'လီတာ',
  'ribbon': 'ဖဲကြိုး',
  'raincoat': 'မိုးကာအင်္ကျီ',
  'lens': 'မှန်ဘီလူး',
  'locker': 'လော့ကာ',
  'lobby': 'ဧည့်ခန်း/လိုဘီ',
  'one-piece dress': 'ဝတ်စုံတစ်ထည်',
  'compression': 'ဖိသိပ်ခြင်း',
  'condensation': 'ငွေ့ရည်ဖြစ်ခြင်း',
  'easy-going': 'ပေါ့ပေါ့ပါးပါး',
  'on and after': 'မှစ၍',
  'thereafter': 'ထို့နောက်',
  'to swagger': 'မာန်မာနဖြင့်လျှောက်',
  'malicious': 'ရက်စက်/မကောင်းကြံ',
  'ill-tempered': 'စိတ်ဆိုးတတ်',
  'unkind': 'ကြင်နာမှုမရှိ',
  'to comfort': 'နှစ်သိမ့်သည်',
  'money order': 'ငွေလွှဲစာ',
  'demise': 'ကွယ်လွန်ခြင်း',
  'latitude (nav.)': 'လတ္တီတွဒ်',
  'water well': 'ရေတွင်း',
  'childcare': 'ကလေးပြုစု',
  'upbringing': 'မွေးမြူပြုစု',
  'simultaneous': 'တစ်ပြိုင်နက်',
  'top grade': 'အဆင့်အမြင့်ဆုံး',
  'foremost': 'ရှေ့ဆုံး',
  'top-notch': 'အကောင်းဆုံး',
  'to stray (turn) from subject': 'အကြောင်းလွဲသည်',
  'to get lost': 'လမ်းပျောက်သည်',
  'to go astray': 'လမ်းလွဲသည်',
  'to come from': 'မှလာသည်',
  'to be stuck in': 'ပိတ်မိသည်',
  'to be cheated': 'လှည့်စားခံရ',
  'to turn over': 'လှန်သည်',
  'to knock over': 'လှဲချသည်',
  'to be overturned': 'မှောက်သည်',
  'to be upset': 'စိတ်မသာ/မှောက်',
  'to topple over': 'လဲသည်',
  'to be reversed': 'ပြောင်းပြန်ဖြစ်',
  'to draw back': 'ဆုတ်သည်',
  'to cave in': 'ပြိုကျသည်',
  'moving (dwelling etc.)': 'ပြောင်းရွှေ့ (နေအိမ်)',
  'subtraction': 'နုတ်ခြင်း',
  'to bring back': 'ပြန်ယူလာ',
  'shuttlecock': 'ကြက်တောင်',
  'sliding storm door': 'လျှောမုန်တိုင်းတံခါး',
  'waterway': 'ရေလမ်း',
  'to project': 'ပေါ်ထွက်/ပြသည်',
  'to cast (shadow)': 'အရိပ်ပစ်သည်',
  'to be reflected': 'ထင်ဟပ်သည်',
  'to harmonize with': 'လိုက်ဖက်သည်',
  'to come out (photo)': 'ပေါ်သည် (ဓာတ်ပုံ)',
  'sentence in English': 'အင်္ဂလိပ်ဝါကျ',
  'English-Japanese (e.g. dictionary)': 'အင်္ဂလိပ်-ဂျပန်',
  'horticulture': 'ဥယျာဉ်စိုက်ပျိုး',
  'gardening': 'ဥယျာဉ်လုပ်ငန်း',
  'elongation': 'ရှည်ထွက်ခြင်း',
  'prolongation': 'သက်တမ်းတိုး',
  'lengthening': 'ရှည်စေခြင်း',
  'play (theatrical)': 'ပြဇာတ်',
  'chimney': 'မီးခိုးခေါင်းတိုင်',
  'gloss': 'တောက်ပြောင်မှု',
  'glaze': 'ကြွေရည်',
  'salty (taste)': 'ငန် (အရသာ)',
  '(col) round trip': 'အသွားအပြန်',
  'return ticket': 'အပြန်လက်မှတ်',
  'put to practical use': 'လက်တွေ့သုံး',
  'sliding screen': 'လျှောကန့်လန့်ကာ',
  'outdoors': 'အပြင်ဘက်',
  'to sell wholesale': 'လက်ကားရောင်း',
  'grated (vegetables)': 'ပွတ်ထား (ဟင်းသီး)',
  'greenhouse': 'ဖန်လုံအိမ်',
  'spa': 'ရေပူစမ်းကုသ',
  'hot spring': 'ရေပူစမ်း',
  'onsen': 'အွန်ဆဲန်',
  'temperate zone': 'သမပိုင်းဇုန်',
  'getting off': 'ဆင်းခြင်း',
  'month (last third of)': 'လကုန်ပိုင်း',
  'rough copy': 'မူကြမ်း',
  'draft': 'မူကြမ်း',
  'sewage': 'ရေဆိုး',
  'underline': 'မျဉ်းသား',
  'underscore': 'အောက်မျဉ်း',
  'geta (Japanese footwear)': 'ဂဲတာ (ဂျပန်ဖိနပ်)',
  'wooden clogs': 'သစ်သားဖိနပ်',
  'Shitamachi': 'ရှီတာမချိ',
  'lower parts of town': 'မြို့အောက်ပိုင်း',
  'vulgarity': 'ကြမ်းတမ်းမှု',
  'indecency': 'မဖွယ်မရာ',
  'coarseness': 'ကြမ်းတမ်းမှု',
  'supposition': 'ယူဆချက်',
  'hypothesis': 'ယူဆချက်',
  '(n) alias': 'အမည်ဝှက်',
  'pseudonym': 'ကလောင်အမည်',
  'pen name': 'ကလောင်အမည်',
  'kana orthography': 'ကနာစာလုံးပေါင်း',
  'syllabary spelling': 'အက္ခရာပေါင်း',
  'such and such': 'ဤသို့ဤသို့',
  'What?': 'ဘာလဲ?',
  'what minute?': 'ဘယ်မိနစ်?',
  'how many minutes?': 'ဘယ်နှစ်မိနစ်?',
  'adoption (e.g. motion': 'အတည်ပြု (အဆို',
  'bill)': 'ဥပဒေကြမ်း)',
  'aerial': 'လေထု/အင်တင်နာ',
  'overhead': 'ခေါင်းပေါ်/အထက်',
  'fiction': 'စိတ်ကူးယဉ်ဇာတ်',
  'fanciful': 'စိတ်ကူးယဉ်',
  'a burner': 'မီးဖိုခေါင်း',
  'origin of a fire': 'မီးစတင်ရာ',
  'volcano': 'မီးတောင်',
  'fireworks': 'မီးရှူးမီးပန်း',
  'taxation': 'အခွန်ကောက်',
  'freight': 'ကုန်တင်ပို့',
  'over-': 'အလွန်အကျွံ-',
  'meeting hall': 'အစည်းအဝေးခန်း',
  'assembly hall': 'စုဝေးခန်းမ',
  'breakup': 'ကွဲခြင်း',
  'dissolution': 'ဖျက်သိမ်းခြင်း',
  'liberation': 'လွတ်မြောက်ခြင်း',
  'emancipation': 'လွတ်မြောက်ရေး',
  'number of times': 'အကြိမ်ရေ',
  'book of tickets': 'လက်မှတ်စာအုပ်',
  'turning': 'လှည့်ခြင်း',
  'mass': 'အစုအဝေး/ဒြပ်ထု',
  'cluster': 'အစုအပြုံ',
  'good weather': 'ရာသီဥတုကောင်း',
  'dubious': 'သံသယဖြစ်ဖွယ်',
  'doubtful': 'သံသယရှိ',
  'mortifying': 'ရှက်စရာ/နာကျင်',
  'vexing': 'စိတ်ရှုပ်ဖွယ်',
  'to mourn': 'ဝမ်းနည်းငို',
  'dear': 'ချစ်ရသော',
  'desired': 'လိုချင်သော',
  'missed': 'လွမ်းဆွတ်/လွဲ',
  'examination of tickets': 'လက်မှတ်စစ်',
  '(1) remodeling': '(၁) ပြင်ဆင်မွမ်းမံ',
  '(2) modding (comp)': '(၂) မွမ်းမံ (ကွန်ပျူတာ)',
  'sea bathing': 'ပင်လယ်ရေချိုး',
  'seawater bath': 'ပင်လယ်ရေချိုး',
  'ashen': 'ပြာရောင်',
  'colors': 'အရောင်များ',
  'paints': 'ဆေးသုတ်များ',
  'opening of a meeting': 'အစည်းအဝေးဖွင့်',
  'to be disconnected': 'ပြတ်တောက်သည်',
  'to get out of place': 'နေရာလွဲသည်',
  'to be off': 'ပိတ်/မှားသည်',
  'to be out (e.g. of gear)': 'မကိုက် (ဂီယာ)',
  'surgical department': 'ခွဲစိတ်ဌာန',
  'intro': 'နိဒါန်း',
  'general remarks': 'အထွေထွေမှတ်ချက်',
  'street corner': 'လမ်းထောင့်',
  'hedge': 'ခြံစည်းရိုးချုံ',
  'every place': 'နေရာတိုင်း',
  'various places': 'နေရာအမျိုးမျိုး',
  'escape (ESC)': 'ထွက်ပြေး (ESC)',
  'exceptional': 'ထူးခြား',
  'hull': 'အခွံ/သင်္ဘောကိုယ်',
  'chaff': 'ဖွဲ',
  'probability': 'ဖြစ်နိုင်ခြေ',
  'angle': 'ထောင့်',
  'to be shut out': 'ပိတ်ပင်ခံရ',
  'study subject': 'သင်ကြားဘာသာ',
  'course of study': 'သင်ရိုး',
  'scientific society': 'သိပ္ပံအသင်း',
  'academic meeting': 'ပညာရေးအစည်းအဝေး',
  'year in school': 'ကျောင်းနှစ်',
  'department of a university': 'တက္ကသိုလ်ဌာန',
  'undergraduate': 'ဘွဲ့ကြို',
  'musical instrument': 'တူရိယာ',
  'multiplication': 'မြှောက်ခြင်း',
  'comparitively': 'နှိုင်းယှဉ်လျှင်',
  'parenthesis': 'ကွင်းစကွင်းပိတ်',
  'brackets': 'ကွင်းများ',
  'printing type': 'ပုံနှိပ်စာလုံး',
  'vitality': 'အသက်စွမ်းအား',
  'to be thirsty': 'ရေဆာသည်',
  'iron pot': 'သံအိုး',
  'roof tile': 'အမိုးအုတ်ကြွပ်',
  'to dry (clothes': 'ခြောက်သည် (အဝတ်',
  'to desiccate': 'ခြောက်သွေ့စေ',
  'arid': 'ခြောက်သွေ့',
  'insipid': 'အရသာမရှိ',
  'dehydrated': 'ရေခန်း',
  'dry cell': 'ခြောက်ဘက်ထရီ',
  'toast (drink)': 'ကျန်းမာရေးဆုတောင်းသောက်',
  'frigid zone': 'အအေးပိုင်းဇုန်',
  'wrong guess': 'မှားယွင်းခန့်မှန်း',
  'authorities': 'အာဏာပိုင်များ',
  'inspiration': 'စိတ်ကူးရမှု',
  'impressions': 'ခံစားချက်များ',
  'thoughts': 'အတွေးများ',
  'ventilation': 'လေဝင်လေထွက်',
  'Chinese Character-Japanese (e.g. dictionary)': 'တရုတ်စာ-ဂျပန်',
  'to pamper': 'ချော့မော့သည်',
  'to spoil': 'ပျက်စီး/ချော့မော့',
  'signboard': 'ဆိုင်းဘုတ်',
  'doorplate': 'တံခါးနံပါတ်ပြား',
  'nursing (a patient)': 'လူနာပြုစု',
  'packing (in cans)': 'ဗူးသွပ်ခြင်း',
  'canning': 'ဗူးသွပ်လုပ်ငန်း',
  'canned goods': 'ဗူးသွပ်စားစရာ',
  '(1) idea': '(၁) အတွေးအခေါ်',
  '(2) sense (e.g. of duty)': '(၂) သဘော (တာဝန်)',
  'appreciation': 'တန်ဖိုးထား/ကျေးဇူးတင်',
  'indirection': 'သွယ်ဝိုက်မှု',
  'indirectness': 'သွယ်ဝိုက်မှု',
  'eastern half of Japan': 'ဂျပန်အရှေ့ခြမ်း',
  'including Tokyo': 'တိုကျိုအပါအဝင်',
  'to instruct': 'သင်ကြား/ညွှန်ကြား',
  'to make one understand': 'နားလည်အောင်ရှင်း',
  'utensil': 'ပစ္စည်းကိရိယာ',
  'locomotive': 'ရထားခေါင်း',
  'to pay attention': 'ဂရုစိုက်သည်',
  'to take care': 'ဂရုစိုက်သည်',
  'atmospheric pressure': 'လေထုဖိအား',
  'gas': 'ဓာတ်ငွေ့',
  'getting out of bed': 'အိပ်ရာထခြင်း',
  'to starve': 'ငတ်သည်',
  'famine': 'ငတ်မွတ်ခေါင်းပါး',
  'rite': 'ဓလေ့ထုံးတမ်း',
  'to be packed': 'ပြည့်ကျပ်သည်',
  'parlor': 'ဧည့်ခန်း',
  'guest room': 'ဧည့်အခန်း',
  'guest seating': 'ဧည့်ထိုင်ခုံ',
  'lecture cancelled': 'ဟောပြောပွဲပယ်ဖျက်',
  '(1) to draw (water)': '(၁) ရေခပ်သည်',
  'to dip': 'နှစ်သည်',
  'to pump': 'စုပ်ထုတ်သည်',
  'fishing (industry)': 'ငါးဖမ်းလုပ်ငန်း',
  'fisherman': 'ငါးဖမ်းသမား',
  'horse racing': 'မြင်းပြိုင်',
  'overbearing': 'မာန်မာနကြီး',
  'coercive': 'အတင်းအကျပ်',
  'pushy': 'ဖိအားပေးတတ်',
  'forcible': 'အတင်းအကျပ်',
  'strengthen': 'အားဖြည့်သည်',
  'intensify': 'ပြင်းထန်စေ',
  'reinforce': 'အားဖြည့်သည်',
  'solidify': 'ခိုင်မာစေ',
  'very kind of you': 'ကျေးဇူးအများကြီးတင်',
  'sorry to trouble': 'နှောင့်ယှက်မိ၍တောင်းပန်',
  'to get between': 'ကြားဝင်သည်',
  'to be taught': 'သင်ကြားခံရ',
  'soba (buckwheat noodles)': 'ဆိုဘာ (ခေါက်ဆွဲ)',
  'to resound': 'ပဲ့တင်သည်',
  'Koto (Japanese harp)': 'ကိုတို (ဂျပန်စောင်း)',
  'to bring near': 'နီးကပ်အောင်ယူ',
  'to put close': 'နီးနီးထား',
  'to let come near': 'နီးကပ်ခွင့်ပေး',
  'goldfish': 'ရွှေငါး',
  'punctuation marks': 'ပုဒ်ဖြတ်သင်္ကေတ',
  'limits': 'ကန့်သတ်ချက်များ',
  'domain': 'နယ်ပယ်',
  'daydream': 'နေ့အိပ်မက်',
  'fantasy': 'စိတ်ကူးယဉ်',
  'fancy': 'စိတ်ကူး/နှစ်သက်',
  'comb': 'หวီ',
  'to dig': 'တူးသည်',
  'to excavate': 'တူးဖော်သည်',
  'to concern oneself in': 'ပါဝင်ပတ်သက်',
  'to have to do with': 'သက်ဆိုင်သည်',
  'to influence': 'သြဇာလွှမ်းမိုး',
  'to incline toward': 'ယိမ်းသည်',
  'to slant': 'စောင်းသည်',
  'to lurch': 'ယိမ်းလဲသည်',
  'true adjective': 'နာမဝိသေသနအစစ်',
  'adjectival noun': 'နာမဝိသေသနနာမ်',
  'quasi-adjective': 'နာမဝိသေသနတူ',
  'to be blessed with': 'ကောင်းချီးခံရ',
  'to be rich in': 'ကြွယ်ဝသည်',
  '(n) (a) joy': 'ဝမ်းသာမှု',
  'to show respect': 'ရိုသေသည်',
  'to honour': 'ဂုဏ်ပြုသည်',
  'honorific': 'လေးစားစကား',
  'term of respect': 'ရိုသေစကား',
  'to be tied together': 'ချည်နှောင်ခံရ',
  'to be connected to': 'ချိတ်ဆက်သည်',
  'to be related to': 'ဆက်စပ်သည်',
  'to connect': 'ချိတ်ဆက်သည်',
  'fluorescent lamp': 'ဖလူအိုရက်မီး',
  'person who is slow to react': 'တုံ့ပြန်နှေးသူ',
  'public entertainment': 'အများဖျော်ဖြေ',
  'accomplishments': 'အောင်မြင်မှုများ',
  'attainments': 'ရရှိမှုများ',
  'sudden increase': 'ရုတ်တရက်တိုး',
  'crevice': 'အက်ကြောင်း',
  'opening': 'အပေါက်/ဖွင့်ပွဲ',
  'column': 'ကော်လံ/တိုင်',
  'digit': 'ဂဏန်း',
  'best work': 'အကောင်းဆုံးလက်ရာ',
  'boner': 'အမှားကြီး',
  'blunder': 'အမှားကြီး',
  'blood pressure': 'သွေးပေါင်ချိန်',
  'monthly salary': 'လစဉ်လစာ',
  'end of the month': 'လကုန်',
  'to hold (position)': 'ရာထူးကိုင်',
  'to be unable': 'မနိုင်/မတတ်',
  'hard (esp. wood)': 'မာ (သစ်သား)',
  'steadfast': 'ခိုင်မြဲ',
  'stuffy writing': 'ခက်ခဲစာရေး',
  'to erect': 'တည်ဆောက်/ထောင်',
  'to be erected': 'တည်ဆောက်ခံရ',
  'to be built': 'တည်ဆောက်ခံရ',
  'prefectural office': 'ပြည်နယ်ရုံး',
  'to command a view of': 'မြင်ကွင်းကြည့်နိုင်',
  'to look down on something': 'အောက်ကြည့်/မထီမဲ့မြင်',
  'study by observation': 'လေ့လာကြည့်ရှု',
  'field trip': 'ကွင်းဆင်းလေ့လာ',
  'outward appearance': 'အပြင်ပန်း',
  'to become used to seeing': 'မြင်နေကျဖြစ်',
  'to be familiar with': 'ရင်းနှီးသည်',
  'heading': 'ခေါင်းစဉ်',
  'caption': 'ဓာတ်ပုံစာတန်း',
  'subtitle': 'စာတန်းငယ်',
  '(1) to see off': '(၁) ပို့ဆောင်သည်',
  'to farewell': 'နှုတ်ဆက်သည်',
  '(2) to escort': '(၂) လိုက်ပို့သည်',
  '(3) to let pass': '(၃) လွှတ်ပေးသည်',
  'to look again': 'ပြန်ကြည့်သည်',
  'to get a better opinion of': 'ပိုတန်ဖိုးထား',
  'humble': 'နှိမ့်ချ',
  'sharp eyes': 'ထက်မြက်သောမျက်စိ',
  'microscope': 'အဏုကြည့်မှန်',
  'from the start': 'အစကတည်းက',
  'place of origin': 'မူလနေရာ',
  'habitat': 'နေထိုင်ရာ',
  'fundamental truth': 'အခြေခံအမှန်တရား',
  'to send word': 'သတင်းပို့',
  'to send a message': 'စာပို့/သတင်းပို့',
  'bounds': 'နယ်နိမိတ်',
  'an individual': 'တစ်ဦးချင်း',
  'old book': 'စာအုပ်ဟောင်း',
  'classics': 'ဂန္ထဝင်စာပေ',
  'classic': 'ဂန္ထဝင်',
  'to call out to': 'ခေါ်သည်',
  'to accost': 'ချဉ်းကပ်ပြော',
  'to address (crowd)': 'လူစုကိုပြော',
  'to appeal': 'တိုင်ကြား/ဆွဲဆောင်',
  'to summon': 'ဆင့်ခေါ်သည်',
  'to call (e.g. phone)': 'ခေါ်သည် (ဖုန်း)',
  'firm (not viscous or easily moved)': 'ခိုင်မာ (မပျော့)',
  'to solidify': 'ခိုင်မာသည်',
  'to become firm': 'ခိုင်မာလာ',
  'to become certain': 'သေချာလာ',
  'to die (plant)': 'သေသည် (အပင်)',
  'to be blasted (plant)': 'ပုပ်သိုးသည် (အပင်)',
  'paste': 'ကော်/ငါးပိ',
  'starch': 'ကစီဓာတ်',
  'pepper': 'ငရုတ်ကောင်း',
  'the Japanese syllabary': 'ဂျပန်အက္ခရာစဉ်',
  'junior (at work or school)': 'အငယ် (အလုပ်/ကျောင်း)',
  'font of purifying water placed at entrance of shrine': 'နတ်ကွန်းဝင်ရေဆေးနေရာ',
  'and Company': 'နှင့်ကုမ္ပဏီ',
  'Messrs.': 'လူကြီးမင်းများ',
  'your pardon': 'တောင်းပန်ပါသည်',
  'declining (something)': 'ငြင်းပယ်ခြင်း',
  'Go (board game of capturing territory)': 'ဂို (ဘုတ်ဂိမ်း)',
  'transportation facilities': 'ပို့ဆောင်ရေးအဆောက်အအုံ',
  'alternating current': 'လှည့်စီးဓာတ်အား',
  'intercourse': 'ဆက်ဆံခြင်း',
  '(cultural) exchange': 'ယဉ်ကျေးမှုဖလှယ်',
  'intermingling': 'ရောနှောခြင်း',
  'light ray': 'အလင်းတန်း',
  'public nuisance': 'အများအနှောင့်အယှက်',
  'official announcement': 'တရားဝင်ကြေညာ',
  'official business': 'တရားဝင်ကိစ္စ',
  'public business': 'အများပြည်သူကိစ္စ',
  'meritorious service': 'ဂုဏ်ထူးဝန်ဆောင်',
};
