module.exports = {
  "screwdriver": "ဝက်အူလှည့်",
  "(de:) (n) neurosis (de: Neurose)": "အာရုံကြောရောဂါ",
  "pajamas": "အိပ်ရာဝတ်",
  "pachinko (Japanese pinball)": "ပါချင်ကို",
  "badge": "တံဆိပ်",
  "bat": "တုတ်",
  "to be worn out": "ပင်ပန်းနွမ်း",
  "patrol car": "ရဲကား",
  "hangar": "လေယာဉ်အိမ်",
  "(coat) hanger": "အင်္ကျီချိတ်",
  "1.  (abbr) puncture": "တာယာပေါက်",
  "bursting": "ပေါက်ကွဲ",
  "2.  punk": "ပန့်ခ်",
  "wet through": "စိုရွှဲ",
  "drenched": "ရေစိုလွန်း",
  "possibly": "ဖြစ်နိုင်",
  "last on the list": "စာရင်းအဆုံး",
  "at the bottom": "အောက်ဆုံး",
  "file": "ဖိုင်",
  "fun": "ပျော်စရာ",
  "(camera) filter": "ဖလတာ",
  "boots": "ဘွတ်ဖိနပ်",
  "too big": "ကြီးလွန်း",
  "dangle heavily": "လေးလံတွဲ",
  "sway to and fro": "ယိမ်းယိုင်",
  "aimlessly": "ရည်ရွယ်မဲ့",
  "front": "ရှေ့",
  "plentiful": "ပေါများ",
  "lavish": "စိမ်းကား",
  "pear": "သစ်တော်သီး",
  "bass": "ဘေ့စ်",
  "fawn": "သမင်ငယ်",
  "be very hungry": "အလွန်ဆာ",
  "best-seller": "အရောင်းရဆုံး",
  "boycott": "သပိတ်မှောက်",
  "hose": "ရေပိုက်",
  "pause": "ခဏရပ်",
  "feel relieved": "စိတ်သက်သာ",
  "to grumble": "ညည်းညူ",
  "to complain": "တိုင်တန်း",
  "volt": "ဗို့",
  "pump": "ပန့်",
  "to be confused": "ရှုပ်ထွေး",
  "to be flustered": "စိတ်လှုပ်ရှား",
  "mass communication": "ပြည်သူ့ဆက်သွယ်ရေး",
  "massage": "နှိပ်နယ်",
  "misprint": "ပုံနှိပ်မှား",
  "Mrs.": "မစသည်",
  "maker": "ထုတ်လုပ်သူ",
  "media": "မီဒီယာ",
  "melody": "သီချင်းသံ",
  "motel": "မိုတယ်",
  "(computer) monitor": "မော်နီတာ",
  "to accomplish": "ပြီးမြောက်",
  "race": "ပြိုင်ပွဲ",
  "lace": "ဇာ",
  "lady": "အမျိုးသမီး",
  "lever": "လီဗာ",
  "stove": "မီးဖို",
  "hire car (lit: rent-a-car)": "ငှားရမ်းကား",
  "X-ray (lit: Roentgen)": "ဓာတ်မှန်",
  "romantic": "ရိုမန်တစ်",
  "watt": "ဝပ်",
  "suborder": "အမျိုးခွဲ",
  "subfamily": "မျိုးရင်းခွဲ",
  "auspicious": "မင်္ဂလာရှိ",
  "civility": "ယဉ်ကျေးမှု",
  "compliments": "ချီးမွမ်းစကား",
  "sociability": "လူမှုရေးကျွမ်း",
  "likes and dislikes": "ကြိုက်မကြိုက်",
  "wickedness": "ဆိုးယုတ်မှု",
  "growing worse": "ပိုဆိုးလာ",
  "aggravation": "ပိုဆိုးခြင်း",
  "bad fellow": "လူဆိုး",
  "rascal": "လူလိမ်",
  "ruffian": "လူမိုက်",
  "scoundrel": "လူယုတ်မာ",
  "unlucky day": "ကံဆိုးနေ့",
  "bulrush": "ဗြူးပင်",
  "addressed to": "လိပ်မူထား",
  "cheap-looking": "စျေးပေါပုံ",
  "tawdry": "ညံ့ဖျင်း",
  "insignificant": "အရေးမပါ",
  "assassination": "လုပ်ကြံမှု",
  "mental arithmetic": "စိတ်တွက်",
  "to be anxious": "စိုးရိမ်",
  "to ponder": "စဉ်းစား",
  "sure enough": "အမှန်ပင်",
  "as usual": "ပုံမှန်အတိုင်း",
  "depending on": "အပေါ်မူတည်",
  "accordingly": "ထို့အညီ",
  "because of": "ကြောင့်",
  "dependence": "မှီခိုမှု",
  "dependent": "မှီခိုသော",
  "reliance": "အားကိုးမှု",
  "consign (goods (for sale) to a firm)": "ကုန်အပ်နှံ",
  "entrust (person with something)": "တာဝန်အပ်",
  "commit": "ကျူးလွန်",
  "company officer": "ကုမ္ပဏီအရာရှိ",
  "to be enthusiastic about": "စိတ်အားထက်သန်",
  "dissent": "ကန့်ကွက်မှု",
  "the opposite sex": "ဆန့်ကျင်လိင်",
  "switching over to": "ပြောင်းရွှေ့",
  "emigration": "ပြည်ပထွက်",
  "emigrant": "ပြည်ပထွက်သူ",
  "immigrant": "ပြည်ဝင်သူ",
  "historic ruins (remains  relics)": "သမိုင်းအပျက်အစီး",
  "outside the area": "နယ်ပြင်ပ",
  "unconditionally": "အခြေအနေမဲ့",
  "as a rule": "ပုံမှန်အားဖြင့်",
  "all together": "အားလုံးအတူ",
  "batch": "အုပ်စု",
  "one lump": "တစ်တုံး",
  "one bundle": "တစ်ထုပ်",
  "drink!(said repeatedly as a party cheer)": "သောက်!",
  "at a stroke": "တစ်ချက်တည်း",
  "with a single swoop": "တစ်ချက်တည်း",
  "unfamiliar": "မရင်းနှီး",
  "never before met": "မရင်းဖူး",
  "one mind": "တစ်စိတ်တည်း",
  "wholeheartedness": "စေတနာပြည့်",
  "the whole heart": "စိတ်တစ်ခုလုံး",
  "(ateji) (adv int) (uk) just a minute": "ခဏလေး",
  "a short time": "အချိန်တို",
  "just a little": "နည်းနည်း",
  "a region": "ဒေသ",
  "a zone": "ဇုန်",
  "the whole place": "နေရာအားလုံး",
  "all present": "လာရောက်သူအားလုံး",
  "all concerned": "သက်ဆိုင်သူအားလုံး",
  "all of us": "ကျွန်ုပ်တို့အားလုံး",
  "one defeat": "တစ်ရှုံး",
  "complete change": "လုံးဝပြောင်း",
  "about-face": "ပြန်လှည့်",
  "one side": "တစ်ဖက်",
  "one phase": "တစ်အဆင့်",
  "the other hand": "အခြားတစ်ဖက်",
  "a series": "စဉ်ဆက်",
  "a chain": "ကွင်းဆက်",
  "a ream (of paper)": "စက္ကူတစ်ထုပ်",
  "to turn away": "လှည့်ထွက်",
  "(flash of) lightning": "လျှပ်စီး",
  "to retire to a private place": "တိတ်တိတ်နေရာသို့",
  "to be responsible for": "တာဝန်ရှိ",
  "1.  to hang (something) on (something)": "ချိတ်ထား",
  "to throw on (clothes)": "အဝတ်ပစ်ဝတ်",
  "2.  to hook": "ချိတ်",
  "to catch": "ဖမ်း",
  "retirement": "အငြိမ်းစား",
  "retired person": "အငြိမ်းစားသူ",
  "rain gear": "မိုးကာပစ္စည်း",
  "rainy weather": "မိုးရာသီ",
  "fourth sign of Chinese zodiac (The Hare  5am-7am  east  February)": "ယုန်နှစ်",
  "swirl": "ဝဲဂယက်",
  "liar (sometimes said with not much seriousness)": "လူလိမ်",
  "fibber": "မုသားပြောသူ",
  "and so on": "စသည်ဖြင့်",
  "and so forth": "စသည်ဖြင့်",
  "shipping": "ပို့ဆောင်မှု",
  "freight rates": "ကုန်စည်ခ",
  "shipping expenses": "ပို့ဆောင်ခ",
  "fare": "ယာဉ်ခ",
  "making use of": "အသုံးပြုခြင်း",
  "to carry on (e.g. in ceremony)": "ဆက်လုပ်",
  "to run a business": "လုပ်ငန်းလုပ်",
  "English letter (character)": "အင်္ဂလိပ်စာလုံး",
  "hero": "သူရဲကောင်း",
  "great man": "ကြီးမြတ်သူ",
  "unwillingly": "မလိုလားဘဲ",
  "grudgingly": "ဝန်တိုစွာ",
  "shaking head in refusal (to children)": "ခေါင်းခါငြင်း",
  "disagreeable": "မနှစ်သက်ဖွယ်",
  "garden (esp. man-made)": "ဥယျာဉ်",
  "not only...but also": "သာမက...ပါ",
  "in addition to": "အပြင်",
  "futures": "အနာဂတ်စျေး",
  "credit (buying)": "အကြွေးဝယ်",
  "total": "စုစုပေါင်း",
  "along": "တလျှောက်",
  "to run along": "တလျှောက်ပြေး",
  "along railway line": "ရထားလမ်းတလျှောက်",
  "to perform (a play)": "ပြဇာတ်က",
  "to play (a part)": "အခန်းကဏ္ဍက",
  "to act (a part)": "သရုပ်ဆောင်",
  "to commit (a blunder)": "အမှားလုပ်",
  "to smoke (e.g. fire)": "မီးခိုးထွက်",
  "veranda": "ဗရန်ဒါ",
  "porch": "မုတ်",
  "balcony": "လသာဆောင်",
  "open corridor": "စင်္ကြံ",
  "marriage proposal": "အိမ်ထောင်တောင်း",
  "charming": "ဆွဲဆောင်မှုရှိ",
  "fascinating": "စိတ်ဝင်စားဖွယ်",
  "voluptuous": "ညှို့ယူဖွယ်",
  "to go far off": "အဝေးသို့သွား",
  "roundabout way": "လှည့်ပတ်လမ်း",
  "long way": "ခရီးရှည်",
  "distant place": "အဝေးနေရာ",
  "lead (the metal)": "ခဲဓာတ်",
  "to disgrace": "အရှက်ရစေ",
  "to dishonour": "ဂုဏ်သိက္ခာကျ",
  "uncleanness": "မသန့်ရှင်း",
  "impurity": "အညစ်အကြေး",
  "nephew": "တူ",
  "subscription": "စာရင်းသွင်း",
  "to push aside": "ဖယ်ရှား",
  "to advance on": "ရှေ့တိုး",
  "to push into": "တွန်းသွင်း",
  "to crowd into": "ညှစ်ဝင်",
  "sumo grand champion": "ဆူမိုချန်ပီယံ",
  "timidity": "ကြောက်ရွံ့မှု",
  "I (ego) (boastful first-person pronoun)": "ငါ",
  "mild": "နူးညံ့",
  "tone color": "အသံအရောင်",
  "tone quality": "အသံအရည်အသွေး",
  "timbre": "အသံသွင်",
  "synthesizer patch": "ဆင်းသီဆိုက်ဇာ",
  "low rank": "အဆင့်နိမ့်",
  "subordinate": "လက်အောက်",
  "lower order (e.g. byte)": "အနိမ့်အစဉ်",
  "burning low": "မီးမှေး",
  "waning": "လျော့နည်း",
  "declining": "ဆုတ်ယုတ်",
  "trade in": "လဲလှယ်ရောင်း",
  "part exchange": "တစ်စိတ်လဲ",
  "secret intention": "လျှို့ဝှက်ရည်ရွယ်",
  "going off duty": "တာဝန်ဆင်း",
  "inferior article": "အရည်အသွေးနိမ့်",
  "lower official": "အောက်အရာရှိ",
  "diarrhoea": "ဝမ်းပျက်",
  "to appear in disguise": "ဟန်ဆောင်ပေါ်",
  "to take the form of": "ပုံစံယူ",
  "to change for the worse": "ပိုဆိုးပြောင်း",
  "to change into": "ပြောင်းလဲ",
  "to convert into": "ပြောင်း",
  "to transform": "ပြောင်းလဲ",
  "to be reduced": "လျော့ကျ",
  "chemical combination": "ဓာတုပေါင်းစပ်",
  "fossil": "ရုပ်ကြွင်း",
  "petrifaction": "ကျောက်ဖြစ်",
  "fossilization": "ရုပ်ကြွင်းဖြစ်",
  "synthetic fibres": "ဓာတုမျှင်",
  "tentative": "ယာယီ",
  "provisional": "ယာယီ",
  "which (emphatic)": "ဘယ်ဟာ",
  "how...!": "ဘယ်လို...!",
  "what...!": "ဘာ...!",
  "unconcerned": "စိတ်မဝင်စား",
  "some time or other": "တစ်ချိန်ချိန်",
  "in some respects": "တစ်နည်းအားဖြင့်",
  "beautiful passage of literature": "စာပေအပိုင်းလှ",
  "manufacturing": "ထုတ်လုပ်မှု",
  "becoming a member": "အဖွဲ့ဝင်ဖြစ်",
  "joining": "ပါဝင်ခြင်း",
  "admission": "ဝင်ခွင့်",
  "flavoring": "အရသာဖြည့်",
  "(pt:) (n) playing cards (pt: carta)": "ဖဲချပ်",
  "household economy": "အိမ်စီးပွား",
  "family finances": "မိသားစုငွေ",
  "running away from home": "အိမ်ထွက်ပြေး",
  "leaving home": "အိမ်ထွက်",
  "domestic animals": "မွေးမြူရေးတိရစ္ဆာန်",
  "cattle": "နွား",
  "retainer": "အစေအပါး",
  "retinue": "အစောင့်အရှောက်",
  "rivers": "မြစ်များ",
  "spark": "မီးပွင့်",
  "Mars (planet)": "အင်္ဂါဂြိုဟ်",
  "table with heater": "အပူပေးစားပွဲ",
  "(orig) charcoal brazier in a floor well": "မြေအောက်မီးအိုး",
  "separate": "ခွဲခြား",
  "itemized form": "အချက်ခွဲပုံစံ",
  "itemization": "အချက်ခွဲခြင်း",
  "(flower) petal": "ပန်းပွင့်ရွက်",
  "flower bed": "ပန်းခင်း",
  "pollen": "ပန်းဝတ်မှုန်",
  "load": "ဝန်",
  "baling": "ထုပ်ပိုး",
  "crating": "သေတ္တာထည့်",
  "spectacular": "ထူးခြားကြီးကျယ်",
  "splendor": "တင့်တယ်မှု",
  "gaudiness": "အရောင်တောက်",
  "extracurricular": "သင်ရိုးပြင်ပ",
  "depopulation": "လူဦးရေကျ",
  "superabundance": "ပိုလျှံမှု",
  "overwork": "အလုပ်ပို",
  "strain": "ဖိစီးမှု",
  "to grow hazy": "မြူဖုံး",
  "to be misty": "မြူဆိုင်း",
  "stroke": "လေဖြတ်",
  "epoch-making": "ခေတ်ပြောင်း",
  "artistry": "အနုပညာကျွမ်း",
  "good taste": "အရသာကောင်း",
  "looking after": "ကြည့်ရှုစောင့်",
  "rescinding": "ပယ်ဖျက်",
  "calling off": "ရပ်ဆိုင်း",
  "dissection": "ခွဲစိတ်ကြည့်",
  "autopsy": "ရုပ်အလောင်းစစ်",
  "recovery": "ပြန်လည်ရရှိ",
  "forwarding": "ရှေ့ပို့",
  "circuit (electric)": "ဆားကစ်",
  "monster": "ဘီလူး",
  "to become emotionally attached": "စိတ်ချစ်ခင်",
  "to carry off": "သယ်ယူထွက်",
  "to run away with": "ခိုးပြေး",
  "to kidnap": "ပြန်ပေးဆွဲ",
  "to abduct": "ပြန်ပေးဆွဲ",
  "to be renewed": "ပြန်သစ်",
  "changing for the worse": "ပိုဆိုးပြောင်း",
  "reformation": "ပြုပြင်ပြောင်းလဲ",
  "maritime": "ရေကြောင်း",
  "height above sea level": "ပင်လယ်ရေမျက်နှာပြင်အထက်",
  "ocean current": "သမုဒ္ဒရာရေစီး",
  "sea route": "ပင်လယ်လမ်း",
  "holding a meeting": "အစည်းအဝေးကျင်း",
  "open an exhibition": "ပြပွဲဖွင့်",
  "reclamation (of wasteland)": "မြေယာပြုပြင်",
  "-floor (counter)": "ထပ်ရေတွက်",
  "stories": "ထပ်များ",
  "imported goods": "တင်သွင်းကုန်",
  "foreign money": "နိုင်ငံခြားငွေ",
  "Foreign Minister": "နိုင်ငံခြားရေးဝန်ကြီး",
  "look (or turn) the other way": "အခြားဘက်ကြည့်",
  "outpatient clinic": "ပြင်ပလူနာဌာန",
  "general statement": "အထွေထွေဖော်ပြ",
  "general idea": "အထွေထွေအယူအဆ",
  "concept": "သဘောတရား",
  "~street": "~လမ်း",
  "~quarters": "~ရပ်ကွက်",
  "in the street": "လမ်းပေါ်",
  "corresponding": "သက်ဆိုင်သော",
  "answering to": "တုံ့ပြန်",
  "coming under": "အောက်ကျ",
  "every kind": "အမျိုးမျိုး",
  "all sorts": "မျိုးစုံ",
  "qualitative difference": "အရည်အသွေးကွာ",
  "disparity": "ကွာဟမှု",
  "acquisition": "ရယူမှု",
  "conviction": "ယုံကြည်မှု",
  "confidence": "ယုံကြည်ချက်",
  "ensure": "အာမခံ",
  "maintain": "ထိန်းသိမ်း",
  "insure": "အာမခံထည့်",
  "1.  angle": "ထောင့်",
  "2.  bishop (shogi)": "ဘုန်းကြီး(ရှိဂိ)",
  "to be distant": "အဝေးရှိ",
  "every other week": "တစ်ပတ်ခြား",
  "arts and sciences": "အနုပညာနှင့်သိပ္ပံ",
  "liberal arts": "လစ်ဘရယ်အနုပညာ",
  "university graduate": "တက္ကသိုလ်ဘွဲ့ရ",
  "academic background": "ပညာရေးနောက်ခံ",
  "optimism": "အကောင်းမြင်",
  "score (music)": "သီချင်းမှတ်တမ်း",
  "chin": "မေးစေ့",
  "to cut in": "ဝင်စွက်",
  "to thrust oneself into": "ကိုယ်ထိုးဝင်",
  "to wedge oneself in": "ညှစ်ဝင်",
  "to muscle in on": "အတင်းဝင်",
  "allocation": "ခွဲဝေ",
  "quota": "ခွဲတမ်း",
  "tenths discounted": "ဆယ်ပုံတစ်ပုံလျှော့",
  "to arrange (flowers)": "ပန်းစီ",
  "vigor": "တက်ကြွမှု",
  "glassiness": "မှန်ကဲ့သို့",
  "funny": "ရယ်စရာ",
  "humorous": "ဟာသဆန်",
  "comical": "ဟာသ",
  "laughable": "ရယ်ဖွယ်",
  "to come true (wish)": "ဆန္ဒပြည့်",
  "to grant (request  wish)": "ခွင့်ပြု",
  "stock (company)": "ရှယ်ယာ",
  "to bite off": "ကိုက်ဖြတ်",
  "to gnaw through": "ကိုက်ဖောက်",
  "(rice) gruel": "ဆန်ပြုတ်",
  "solicitation": "တောင်းခံ",
  "canvassing": "မဲဆွယ်",
  "inducement": "ဆွဲဆောင်မှု",
  "flawless": "အပြစ်မရှိ",
  "bureaucracy": "အရာရှိစနစ်",
  "tolerance": "သည်းခံမှု",
  "dried washing (clothes)": "အဝတ်ခြောက်",
  "interference": "ဝင်ရောက်စွက်ဖက်",
  "(tree) trunk": "သစ်ပင်ပင်စည်",
  "main line": "ပင်မလိုင်း",
  "trunk line": "ပင်မလိုင်း",
  "strong feelings": "ခံစားချက်ပြင်း",
  "sense of touch": "အထိအတွေ့",
  "infection": "ကူးစက်မှု",
  "severity (quake)": "ငလျင်ပြင်းအား",
  "deep feeling": "နက်ရှိုင်းခံစား",
  "inexpressible feeling": "ဖော်ပြမရခံစား",
  "filled with emotion": "စိတ်လှုပ်ရှားပြည့်",
  "to accustom": "ကျင့်သားရ",
  "customary practice": "ဓလေ့ထုံးစံ",
  "habit": "အလေ့အထ",
  "traditional event": "ရိုးရာပွဲ",
  "usual (historical) custom": "ပုံမှန်ဓလေ့",
  "dare (to do)": "ရဲစွန့်",
  "challenge (to do)": "စိန်ခေါ်",
  "shout of joy": "ဝမ်းသာအော်",
  "Chinese word": "တရုတ်စကားလုံး",
  "Sino-Japanese word": "တရုတ်-ဂျပန်စကား",
  "to behave like a spoiled child": "ကလေးဆန်ပြုမူ",
  "to fawn on": "အချစ်ပြ",
  "sweet flavour": "ချိုသောအရသာ",
  "mildness": "နူးညံ့မှု",
  "stupidity": "မိုက်မဲမှု",
  "guarding": "စောင့်ကြပ်",
  "surveillance": "စောင့်ကြည့်မှု",
  "(army) nurse": "စစ်သူနာပြု",
  "pole (e.g. for drying laundry)": "ခြောက်တိုင်",
  "easiness": "လွယ်ကူမှု",
  "conciseness": "တိုတောင်းမှု",
  "to slow down": "နှေးအောင်လုပ်",
  "lenient": "သက်ညှာ",
  "spectators": "ကြည့်ရှုသူများ",
  "onlookers": "ကြည့်သူများ",
  "members of the audience": "ပရိသတ်အဖွဲ့ဝင်",
  "viewing": "ကြည့်ရှုခြင်း",
  "return to origins": "မူလသို့ပြန်",
  "60th birthday": "အသက်၆၀မွေးနေ့",
  "relation(ship)": "ဆက်ဆံရေး",
  "taking part in": "ပါဝင်ခြင်း",
  "participating in": "ပါဝင်ဆောင်ရွက်",
  "being concerned in": "ပါဝင်ပတ်သက်",
  "in its entirety": "လုံးဝ",
  "wholly": "အလုံးစုံ",
  "to make round": "လုံးအောင်လုပ်",
  "to round off": "လုံးဝန်းအောင်",
  "to roll up": "လိပ်",
  "to curl up": "ကောက်ရစ်",
  "cancer": "ကင်ဆာ",
  "ophthalmology": "မျက်စိပညာ",
  "stubbornness": "ဇွဲမာန်",
  "obstinacy": "ခေါင်းမာမှု",
  "written application or petition": "လျှောက်လွှာစာ",
  "planning": "စီမံကိန်း",
  "crisis": "အကျပ်အတည်း",
  "comedy": "ဟာသပြဇာတ်",
  "funny show": "ရယ်စရာရှိုး",
  "organ (of body)": "ကိုယ်အင်္ဂါ",
  "settlement date": "ရှင်းတမ်းရက်",
  "end of term": "သက်တမ်းကုန်",
  "abstain from voting": "မဲမပေး",
  "renunciation of a right": "အခွင့်စွန့်",
  "loom": "ရက်ကန်းစင်",
  "returning to Tokyo": "တိုကျိုပြန်",
  "whim": "စိတ်ကူးချက်",
  "caprice": "စိတ်ပြောင်းလွယ်",
  "whimsy": "စိတ်ကူးယဉ်",
  "at ease": "စိတ်အေး",
  "buoyant": "ပျော်ရွှင်",
  "lighthearted": "စိတ်ပေါ့ပါး",
  "hesitance": "တွန့်ဆုတ်မှု",
  "feeling constraint": "အတင်းခံစား",
  "fear of troubling someone": "နှောင့်ယှက်မည်စိုး",
  "affectation": "ဟန်ဆောင်မှု",
  "snobbery": "မာန်မာန",
  "to react to": "တုံ့ပြန်",
  "to be influenced by": "လွှမ်းမိုးခံရ",
  "to go overboard for": "အလွန်အကျွံလုပ်",
  "atmospheric current": "လေစီးကြောင်း",
  "steamship": "ရွှေ့မီးသင်္ဘော",
  "prayer": "ဆုတောင်း",
  "supplication": "တောင်းပန်",
  "quarterly (e.g. magazine)": "သုံးလတစ်ကြိမ်",
  "norm": "စံနှုန်း",
  "to note": "မှတ်သား",
  "mention": "ဖော်ပြ",
  "describing": "ဖော်ပြခြင်း",
  "descriptor": "ဖော်ပြချက်",
  "aristocrat": "မင်းမျိုးမင်းနွယ်",
  "undulation": "လှိုင်းထန်",
  "orbit": "ပတ်လမ်း",
  "railroad track": "ရထားလမ်း",
  "falsification": "အတုလုပ်မှု",
  "fabrication": "ဖန်တီးမှုအတု",
  "counterfeiting": "ငွေအတုလုပ်",
  "legislative bill": "ဥပဒေမူကြမ်း",
  "Diet building": "ပါလီမန်အဆောက်အအုံ",
  "topic of discussion": "ဆွေးနွေးခေါင်းစဉ်",
  "to ladle out": "ဇွန်းနှင့်ထုတ်",
  "tea drinking": "လက်ဖက်ရည်သောက်",
  "tea house": "လက်ဖက်ရည်ဆိုင်",
  "that is to say": "ဆိုလိုသည်မှာ",
  "to rebuke": "ဆူပူ",
  "to tell off": "ဆုံးမ",
  "dramatization (e.g. film)": "ဇာတ်လမ်းပြောင်း",
  "(sudden) change": "ရုတ်တရက်ပြောင်း",
  "reversal": "ပြောင်းပြန်",
  "turn-around": "လှည့်ပြောင်း",
  "coming from behind (baseball)": "နောက်မှလိုက်မီ",
  "handstand": "လက်ထောက်",
  "headstand": "ခေါင်းထောက်",
  "temporary absence from school": "ကျောင်းယာယီပျက်",
  "truce": "အပစ်ရပ်",
  "armistice": "စစ်ရပ်စဲ",
  "bow (and arrow)": "လေးနှင့်မြား",
  "(plant) bulb": "ဥ",
  "ultimate": "အဆုံးစွန်",
  "final": "နောက်ဆုံး",
  "eventual": "နောက်ဆုံးတွင်",
  "school lunch": "ကျောင်းနေ့လည်စာ",
  "providing a meal": "ထမင်းကျွေး",
  "past events": "အတိတ်ဖြစ်ရပ်",
  "bygones": "ပြီးခဲ့သည်များ",
  "old friendship": "ဟောင်းမိတ်သဟာ",
  "veto": "ဗီတို",
  "fishing boat": "ငါးဖမ်းလှေ",
  "fishing village": "ငါးဖမ်းရွာ",
  "enjoyment": "ပျော်ရွှင်မှု",
  "being given": "ပေးခြင်းခံရ",
  "working together": "အတူလုပ်ကိုင်",
  "(husband and wife) earning a living together": "ဇနီးမောင်နှံအတူရှာ",
  "coeducation": "ပူးတွဲပညာရေး",
  "communism": "ကွန်မြူနစ်ဝါဒ",
  "dual income": "ဝင်ငွေနှစ်ခု",
  "resonance": "သံယှဉ်သံ",
  "republicanism": "သမ္မတစနစ်",
  "bad harvest": "သီးနှံပျက်",
  "poor crop": "သီးနှံညံ့",
  "co-operation": "ပူးပေါင်းဆောင်ရွက်",
  "firm (market) tone": "စျေးကွက်ခိုင်",
  "outcry": "အော်ဟစ်မှု",
  "by force": "အတင်းအကျပ်",
  "to force": "အတင်းလုပ်",
  "to compel": "ဖိအားပေး",
  "to get strong": "အားကောင်းလာ",
  "to gain strength": "အားရရှိ",
  "to strengthen": "အားဖြည့်",
  "to emphasize": "အလေးပေး",
  "great": "ကြီးမြတ်",
  "forcing": "အတင်းအကျပ်",
  "compulsion": "ဖိအားပေးမှု",
  "to become frightened": "ကြောက်လန့်",
  "to have a nightmare": "အိပ်မက်ဆိုးမက်",
  "teaching staff": "ဆရာအဖွဲ့",
  "teaching materials": "သင်ကြားပစ္စည်း",
  "teaching certificate": "ဆရာလက်မှတ်",
  "the teaching profession": "ဆရာအလုပ်",
  "bridge building": "တံတားဆောက်",
  "still less (with neg. verb)": "ပို၍မဆို",
  "to say nothing of": "မပြောနှင့်တော့",
  "not to mention": "မပြောနှင့်",
  "to menace": "ခြိမ်းခြောက်",
  "threat": "ခြိမ်းခြောက်မှု",
  "menace": "အန္တရာယ်",
  "terrorism": "အကြမ်းဖက်ဝါဒ",
  "to amuse oneself": "ပျော်ပါး",
  "to make merry": "ပျော်ရွှင်ပြု",
  "industrial enterprise": "စက်မှုလုပ်ငန်း",
  "stimulation": "လှုံ့ဆော်မှု",
  "agitation": "လှုပ်ရှားမှု",
  "arousal": "နှိုးဆွမှု",
  "nostalgia": "အတိတ်လွမ်း",
  "homesickness": "အိမ်လွမ်း",
  "birth-place": "မွေးရပ်မြေ",
  "miracle": "အံ့ဖွယ်",
  "Buddhist karma": "ဗုဒ္ဓကံ",
  "actions committed in a former life": "ရှေးဘဝပြုမှု",
  "localize": "ဒေသခံအောင်လုပ်",
  "piece of music": "ဂီတအပိုင်း",
  "extremity": "အစွန်း",
  "king (shogi)": "ဘုရင်(ရှိဂိ)",
  "paulownia tree": "ပေါလိုးနီးယားပင်",
  "to be fit for": "သင့်လျော်",
  "to be equal to": "ညီမျှ",
  "to function properly": "ကောင်းစွာအလုပ်လုပ်",
  "place of work": "အလုပ်နေရာ",
  "to prohibit": "တားမြစ်",
  "to forbid": "မလုပ်ရ",
  "taboo": "တားမြစ်ချက်",
  "forbidden thing": "မလုပ်ရသောအရာ",
  "nearsightedness": "အနီးမှုန်",
  "myopia": "အနီးမှုန်",
  "to get near": "နီးကပ်လာ",
  "to get acquainted with": "ရင်းနှီးလာ",
  "to get closer": "ပိုနီးလာ",
  "1.  (iron) hammer": "သံတူ",
  "2.  punishment": "ပြစ်ဒဏ်",
  "section (of track  etc)": "လမ်းပိုင်း",
  "to inflict pain": "နာကျင်စေ",
  "(foot) race": "ခြေပြိုင်ပွဲ",
  "to run (race  esp. horse)": "ပြေးပြိုင်",
  "to gallop": "ပြေးခုန်",
  "to canter": "ပြေးသွား",
  "running fast": "မြန်မြန်ပြေး",
  "double time": "နှစ်ဆမြန်",
  "idle complaint": "အချည်းနှီးညည်း",
  "grumble": "ညည်းညူ",
  "blank": "ဗလာ",
  "empty (space)": "နေရာလွတ်",
  "vacancy": "လစ်လပ်နေရာ",
  "room for rent or lease": "ငှားခန်း",
  "bending": "ကွေးခြင်း",
  "indentation": "အထစ်",
  "refraction": "အလင်းယိုင်",
  "monarch": "ဘုရင်",
  "group (math)": "အုပ်စု(သင်္ချာ)",
  "(social) group": "လူမှုအုပ်စု",
  "throng": "လူအုပ်",
  "mob": "လူအုပ်ကြီး",
  "battleship": "စစ်သင်္ဘော",
  "military affairs": "စစ်ရေး",
  "armaments": "လက်နက်များ",
  "military preparations": "စစ်ပြင်ဆင်မှု",
  "military or naval uniform": "စစ်ယူနီဖောင်း",
  "to bless": "ကောင်းချီးပေး",
  "to show mercy to": "သနားညှာ",
  "to publish": "ထုတ်ဝေ",
  "to carry (an article)": "ဆောင်းပါးတင်",
  "to put up": "တင်ထား",
  "appearance (e.g. article in paper)": "ထုတ်ဝေပေါ်",
  "to participate": "ပါဝင်",
  "to take part": "ပါဝင်ဆောင်ရွက်",
  "carrying something": "သယ်ဆောင်ခြင်း",
  "Sincerely yours": "ရိုသေလျက်",
  "1.  details": "အသေးစိတ်",
  "whole story": "အကြောင်းအရာအားလုံး",
  "sequence of events": "ဖြစ်ရပ်အစဉ်",
  "a joint": "အဆစ်",
  "joining point": "ချိတ်ဆက်မှတ်",
  "meter": "မီတာ",
  "gauge": "တိုင်းတာကိရိယာ",
  "warning": "သတိပေး",
  "admonition": "သတိပေးချက်",
  "vigilance": "သတိထားမှု",
  "police inspector": "ရဲအရာရှိ",
  "abatement": "လျှော့ချမှု",
  "disdain": "မထီမဲ့မြင်",
  "hasty": "အလျင်စလို",
  "troupe": "ဇာတ်အဖွဲ့",
  "theatrical company": "ပြဇာတ်ကုမ္ပဏီ",
  "being ashamed": "ရှက်ရွံ့",
  "doing (with resolve)": "ဇွဲဖြင့်လုပ်",
  "carrying out (i.e. a plan)": "အစီအစဉ်ဆောင်ရွက်",
  "balance sheet": "လက်ကျန်ရှင်းတမ်း",
  "settlement of accounts": "စာရင်းရှင်း",
  "decision of a contest": "ပြိုင်ပွဲဆုံးဖြတ်",
  "finals (in sports)": "ဗိုလ်လုပွဲ",
  "to be connected or related": "ဆက်စပ်နေ",
  "to tie on": "ချည်နှောင်",
  "to attach with a knot": "ထုံးနှင့်ချည်",
  "tuberculosis": "အဆုတ်နာ",
  "tubercule": "အဖု",
  "crystallization": "ပုံဆောင်ခဲဖြစ်",
  "blood vessel": "သွေးကြော",
  "monthly tuition fee": "လစဉ်ကျောင်းခ",
  "(the) date": "ရက်စွဲ",
  "monthly installment": "လစဉ်အရစ်ကျ",
  "simultaneously": "တစ်ပြိုင်နက်",
  "side line": "ဘေးအလုပ်",
  "second business": "ဒုတိယလုပ်ငန်း",
  "multi-use": "အသုံးများ",
  "combined use": "ပူးတွဲအသုံး",
  "serving two purposes": "နှစ်မျိုးအသုံး",
  "offering prizes": "ဆုပေးခြင်း",
  "winning": "အနိုင်ရ",
  "verb suffix to indicate reckless abandon to the activity": "မဆင်မခြင်လုပ်နောက်ဆက်",
  "public prosecutor": "အစိုးရရှေ့နေ",
  "authority": "အာဏာ",
  "the right (to do something)": "အခွင့်အရေး",
  "to sharpen": "ထက်အောင်လုပ်",
  "to grind": "ကြိတ်",
  "to scour": "ပွတ်တိုက်",
  "to hone": "ထက်အောင်သွေး",
  "shabby": "ညံ့ဖျင်း",
  "seedy": "ဆင်းရဲပုံ",
  "to show off": "ပြသချင်",
  "to flaunt": "ဝါကြွား",
  "to (happen to) see": "မတော်တဆမြင်",
  "to catch sight of": "မြင်လိုက်",
  "formal marriage interview": "အိမ်ထောင်တွေ့ဆုံ",
  "to exchange glances": "မျက်လွှာလဲ",
  "to postpone": "ရွှေ့ဆိုင်း",
  "to suspend operations": "လုပ်ငန်းရပ်",
  "to refrain from performing an action": "မလုပ်ဘဲနေ",
  "perspective": "ရှုထောင့်",
  "unobstructed view": "အတားအဆီးမဲ့မြင်ကွင်း",
  "to look out over": "အပေါ်ကကြည့်",
  "to survey (scene)": "မြင်ကွင်းစစ်",
  "to take an extensive view of": "ကျယ်ကျယ်ကြည့်",
  "to leave at large": "လွှတ်ထား",
  "viewpoint": "အမြင်",
  "to fail to notice": "မသတိထားမိ",
  "to deprecate oneself and praise the listener": "ကိုယ်နှိမ့်သူချီး",
  "row of houses": "အိမ်တန်း",
  "simple task": "လွယ်ကူအလုပ်",
  "doing": "လုပ်ခြင်း",
  "to carry through": "ဆုံးခန်းတိုင်လုပ်",
  "to achieve": "အောင်မြင်",
  "sovereign": "အချုပ်အခြာ",
  "chemical element": "ဓာတုဒြပ်စင်",
  "first year (of a specific reign)": "နန်းစံပထမနှစ်",
  "logically": "ယုတ္တိရှိစွာ",
  "original form": "မူလပုံစံ",
  "base form": "အခြေခံပုံစံ",
  "original work": "မူရင်းလက်ရာ",
  "original document": "မူရင်းစာရွက်",
  "general rule": "အထွေထွေစည်းမျဉ်း",
  "original (text)": "မူရင်းစာသား",
  "origin (coordinates)": "မူလ(ကိုဩဒိနိတ်)",
  "atomic bomb": "အဏုမြူဗုံး",
  "crude oil": "ရေနံစိမ်း",
  "austere": "တင်းကျပ်",
  "majestic": "ကြီးကျယ်ခမ်းနား",
  "dignified": "ဂုဏ်သိက္ခာရှိ",
  "stately": "တင့်တယ်",
  "subtract": "နုတ်",
  "give a demerit": "အမှတ်လျှော့",
  "expert": "ကျွမ်းကျင်သူ",
  "geisha": "ဂေးရှား",
  "prostitute": "ပြည့်တန်ဆာ",
  "developing (film)": "ဓာတ်ပုံဖော်",
  "actual place": "အစစ်နေရာ",
  "hearsay": "ကြားသိစကား",
  "article counter": "ပစ္စည်းရေတွက်",
  "individuality": "တစ်ဦးချင်းသွင်",
  "personality": "ကိုယ်ရည်ကိုယ်သွေး",
  "idiosyncrasy": "ထူးခြားသွင်ပြင်",
  "particular case": "အထူးကိစ္စ",
  "to call somebody to halt": "ရပ်တန့်ခိုင်း",
  "to fortify": "ခိုင်မာအောင်လုပ်",
  "solid (body)": "အစိုင်အခဲ",
  "fixation": "ပုံသေဖြစ်",
  "peculiar": "ထူးခြား",
  "solitude": "တစ်ကိုယ်တည်း",
  "helplessness": "အကူအညီမဲ့",
  "census": "လူဦးရေစာရင်း",
  "family register": "မိသားစုစာရင်း",
  "closing up": "ပိတ်ခြင်း",
  "fastening the doors": "တံခါးပိတ်",
  "the late (deceased)": "ကွယ်လွန်သူ",
  "the deceased": "သေဆုံးသူ",
  "groin": "ပေါင်ခြံ",
  "crotch": "ပေါင်ကြား",
  "to boast of": "ဝါကြွား",
  "to be proud of": "ဂုဏ်ယူ",
  "exaggeration": "ချဲ့ကားမှု",
  "to extend over or into": "ကျော်လွန်ကူး",
  "employment (long term)": "ရေရှည်အလုပ်",
  "to look back": "နောက်ပြန်ကြည့်",
  "to turn around": "လှည့်ပြန်",
  "to review": "ပြန်လည်သုံးသပ်",
  "putting off": "ရွှေ့ဆိုင်းခြင်း",
  "postponing": "ရွှေ့ဆိုင်း",
  "repentance": "နောင်တ",
  "backspace (BS)": "နောက်ပြန်ဖျက်",
  "go-": "ဂို-",
  "1.  a discount": "လျှော့စျေး",
  "a prize": "ဆု",
  "2.  something additional": "အပိုအရာ",
  "(please) look": "ကြည့်ပါ",
  "(please) try to do": "လုပ်ကြည့်ပါ",
  "Go board": "ဂိုဘုတ်",
  "phrases": "စကားစုများ",
  "word root": "စကားရင်းမြစ်",
  "word derivation": "စကားဆင်းသက်",
  "etymology": "စကားရင်းမြစ်ပညာ",
  "vocabulary": "ဝေါဟာရ",
  "glossary": "အဓိပ္ပာယ်စာရင်း",
  "to falsify": "အတုလုပ်",
  "to misrepresent": "မှားယွင်းဖော်ပြ",
  "guard": "အစောင့်",
  "convoy": "စစ်ကားတန်း",
  "to converse with": "စကားပြော",
  "to cross (swords)": "ဓားရိုက်",
  "to exchange (messages)": "စာလဲလှယ်",
  "to dodge": "ရှောင်",
  "to parry": "ကာကွယ်",
  "delivering": "ပို့ဆောင်ခြင်း",
  "furnishing (with copies)": "မိတ္တူပေး",
  "cost of fuel and light": "မီးမီခ",
  "public performance": "အများပြည်သူဖျော်ဖြေ",
  "presenting to the public": "အများသို့တင်ပြ",
  "public corporation": "အများပိုင်ကော်ပိုရေးရှင်း",
  "official recognition": "တရားဝင်အသိအမှတ်",
  "authorization": "ခွင့်ပြုချက်",
  "accreditation": "အသိအမှတ်ပြု",
  "public appeal": "အများတောင်းဆို",
  "public contribution": "အများလှူဒါန်း",
  "government business": "အစိုးရလုပ်ငန်း",
  "public use": "အများသုံး",
  "public expense": "အများကုန်ကျ",
  "public (institution)": "အများပိုင်",
  "to hum something": "ညှင်း",
  "to sing to oneself": "တစ်ကိုယ်တည်းသီ",
  "verbal statement": "နှုတ်ထွက်ချက်",
  "oral": "ပါးစပ်ဖြင့်",
  "for ~": "~အတွက်",
  "oriented towards ~": "~ဦးတည်",
  "filth": "အညစ်အကြေး",
  "good will": "ကောင်းမွန်စေတနာ",
  "prosperous conditions": "စည်ပင်အခြေအနေ",
  "healthy economy": "ကျန်းမာစီးပွား",
  "in good shape": "အခြေအနေကောင်း",
  "engineering": "အင်ဂျင်နီယာ",
  "to be propagated": "ပျံ့နှံ့",
  "to become confused (disconcerted  disorganized)": "ရှုပ်ထွေးဖြစ်",
  "resistance": "ခုခံမှု",
  "to draw in": "ဆွဲသွင်း",
  "to hold back": "ထိန်းထား",
  "to make notes": "မှတ်စုရေး",
  "to be temperate in": "ထိန်းသိမ်းနေ",
  "subsidy": "ထောက်ပံ့ငွေ",
  "deduction": "နုတ်ယူမှု",
  "10^38": "၁၀^၃၈",
  "hundred undecillion (American)": "ဟန်ဒရက်အန်ဒဆီလျံ",
  "hundred sextillion (British)": "ဟန်ဒရက်ဆက်စတီလျံ",
  "1st in rank": "အဆင့်၁",
  "first sign of the Chinese calendar": "တရုတ်ပြက္ခဒိန်ပထမ",
  "instep": "ခြေကျောက်",
  "Imperial Palace": "ဧကရာဇ်နန်းတော်",
  "archaeology": "ရှေးဟောင်းသုတေသန",
  "voyage": "ခရီးစဉ်",
  "to lay waste": "ဖျက်ဆီး",
  "to devastate": "ပျက်စီးစေ",
  "to damage": "ပျက်စီး",
  "estrangement": "ကွဲကွာမှု",
  "crossing without meeting": "မတွေ့ဘဲဖြတ်",
  "bank clerk": "ဘဏ်ဝန်ထမ်း",
  "march": "ချီတက်ပွဲ",
  "parade": "ပရိတ်သဘင်",
  "subscription (e.g. magazine)": "စာစောင်စာရင်းသွင်း",
  "mining industry": "သတ္တုတွင်းလုပ်ငန်း",
  "mine (ore)": "သတ္တုတွင်း",
  "rainfall": "မိုးရေချိန်",
  "capitulation": "လက်နက်ချ",
  "spices": "ဟင်းခတ်အမွှေး",
  "tableland": "ကုန်းမြင့်",
  "plateau": "ကုန်းပြင်မြင့်",
  "joint together": "ပူးပေါင်း",
  "conference": "ညီလာခံ",
  "singing in a chorus": "အဖွဲ့လိုက်သီ",
  "to inform": "အကြောင်းကြား",
  "diplomatic relations": "သံတမန်ဆက်ဆံရေး",
  "domestic products": "ပြည်တွင်းထုတ်ကုန်",
  "state-sponsored": "နိုင်ငံပံ့ပိုး",
  "realm": "နယ်မြေ",
  "national defence": "အမျိုးသားကာကွယ်ရေး",
  "national ownership": "နိုင်ငံပိုင်",
  "U.N.": "ကုလသမဂ္ဂ",
  "United Nations": "ကုလသမဂ္ဂ",
  "balance (figure) in the black": "အမြတ်လက်ကျန်",
  "curio": "ရှေးဟောင်းပစ္စည်း",
  "to put into": "ထည့်သွင်း",
  "making necessary arrangements": "လိုအပ်စီစဉ်",
  "mixed race": "လူမျိုးရော",
  "mixed parentage": "မိဘရော",
  "merger": "ပေါင်းစည်းမှု",
  "not at all (neg. verb)": "လုံးဝမ",
  "something small or petty": "သေးငယ်သောအရာ",
  "trifle": "အသေးအဖွဲ",
  "(not) much": "များများမ",
  "left-handedness": "ဘယ်သန်မှု",
  "sake drinker": "ဆာကေသောက်သူ",
  "left-hander": "ဘယ်သန်",
  "to deduct": "နုတ်ယူ",
  "to come near to": "နီးကပ်လာ",
  "to interfere": "ဝင်ရောက်စွက်ဖက်",
  "to become impeded": "အတားအဆီးဖြစ်",
  "gravel": "ကျောက်စရစ်",
  "ballast": "အလေးခဲ",
  "pebbles": "ကျောက်ခဲငယ်",
  "fraud": "လိမ်လည်မှု",
  "swindle": "လိမ်လည်",
  "symposium": "ဆွေးနွေးပွဲ",
  "round-table discussion": "စားပွဲဝိုင်းဆွေးနွေး",
  "coordinate(s)": "ကိုဩဒိနိတ်",
  "another meeting": "နောက်ထပ်တွေ့ဆုံ",
  "meeting again": "ပြန်တွေ့",
  "reunion": "ပြန်ဆုံ",
  "rebuilding": "ပြန်တည်ဆောက်",
  "playback": "ပြန်ဖွင့်",
  "regeneration": "ပြန်လည်မွေး",
  "return to life": "အသက်ပြန်ရှင်",
  "the very best": "အကောင်းဆုံး",
  "mining": "သတ္တုတူး",
  "vote": "မဲ",
  "roll call": "အမည်ခေါ်",
  "collecting": "စုဆောင်း",
  "gathering": "စုဝေး",
  "adoption": "မွေးစား",
  "bacillus": "ဘက်တီးရီးယား",
  "bacterium": "ပိုးမွှား",
  "cell (biology)": "ဆဲလ်",
  "stockpile": "သိုလှောင်မှု",
  "riches": "စည်းစိမ်",
  "source of funds": "ငွေရင်းမြစ်",
  "finances": "ဘဏ္ဍာရေး",
  "to be clear": "ရှင်းလင်း",
  "to be serene": "ငြိမ်သက်",
  "to be cold": "အေး",
  "to be skillful": "ကျွမ်းကျင်",
  "make-up": "မိတ်ကပ်",
  "military or naval operations": "စစ်ဆင်ရေး",
  "strategy": "ဗျူဟာ",
  "literary work": "စာပေလက်ရာ",
  "fence": "ခြံစည်းရိုး",
  "paling": "ခြံတိုင်",
  "optical illusion": "မျက်စိအထင်မှား",
  "hallucination": "အမြင်လွဲ",
  "to touch lightly": "ပေါ့ပေါ့ထိ",
  "to take a percentage (from)": "ရာခိုင်နှုန်းယူ",
  "chance encounter": "မတော်တဆတွေ့",
  "murder": "လူသတ်မှု",
  "miscellaneous goods": "အထွေထွေကုန်",
  "general goods": "အထွေထွေပစ္စည်း",
  "sundries": "အသေးစားကုန်",
  "chatting": "စကားပြောခြင်း",
  "idle talk": "အချည်းနှီးစကား",
  "various kinds of small trees": "သစ်ပင်ငယ်မျိုးစုံ",
  "assorted trees": "သစ်ပင်မျိုးစုံ",
  "(num) three": "သုံး",
  "three-stringed Japanese guitar": "ကြိုးသုံးချောင်းဂစ်တာ",
  "shamisen": "ရှာမီဆင်",
  "House of Councillors": "အထက်လွှတ်တော်",
  "calling on": "လည်ပတ်ခြင်း",
  "visiting": "လည်ပတ်",
  "mountains": "တောင်များ",
  "hillside": "တောင်စောင်း",
  "mountainside": "တောင်ခြေ",
  "mountain range": "တောင်တန်း",
  "miserable": "ဆင်းရဲ",
  "to disseminate": "ပျံ့နှံ့စေ",
  "to give money freely": "ငွေလွယ်ကူပေး",
  "maternity leave": "မီးဖွားခွင့်",
  "postpartum": "မီးဖွားပြီး",
  "after childbirth": "မီးဖွားပြီးနောက်",
  "produce": "ထုတ်ကုန်",
  "maternity and gynecology department": "သားဖွားမီးယပ်ဌာန",
  "glorification": "ချီးမွမ်းမှု",
  "acid": "အက်ဆစ်",
  "oxidation": "အောက်ဆီဂျင်ဖြစ်",
  "remaining money": "ကျန်ငွေ",
  "(bank) balance": "ဘဏ်လက်ကျန်",
  "remainder": "ကျန်ရှိ",
  "harshness": "ကြမ်းတမ်းမှု",
  "to work for": "အတွက်အလုပ်လုပ်",
  "gadget": "ကိရိယာငယ်",
  "to commence": "စတင်",
  "to lay (mines)": "မိုင်းထောင်",
  "to set (traps)": "ထောင်ချောက်ထောင်",
  "to wage (war)": "စစ်ဆင်",
  "to finish up": "ပြီးဆုံးအောင်",
  "to partition": "ခွဲခြား",
  "to divide": "ပိုင်းခြား",
  "to mark off": "မှတ်သားခွဲ",
  "to settle accounts": "စာရင်းရှင်း",
  "to lay in stock": "ကုန်သို",
  "to replenish stock": "ကုန်ဖြည့်",
  "to procure": "ရယူ",
  "biting words": "ထက်မြက်စကား",
  "embroidery": "ပန်းထိုး",
  "administration of justice": "တရားစီရင်ရေး",
  "first train": "ပထမရထား",
  "thought": "အတွေး",
  "to point at": "ညွှန်ပြ",
  "mandate": "အမိန့်",
  "pointing out": "ထောက်ပြခြင်း",
  "identification": "ဖော်ထုတ်ခြင်း",
  "orders": "အမိန့်များ",
  "instructions": "ညွှန်ကြားချက်",
  "directive": "ညွှန်ကြား",
  "1.  execution": "ကွပ်မျက်",
  "enforcing": "အတည်ပြုဆောင်ရွက်",
  "to be limited to": "ကန့်သတ်ခံရ",
  "death penalty": "သေဒဏ်",
  "capital punishment": "သေဒဏ်",
  "I (fem)": "ကျွန်မ",
  "private property": "ပုဂ္ဂလိကပိုင်ဆိုင်မှု",
  "personal effects": "ကိုယ်ပိုင်ပစ္စည်း",
  "private ownership": "ပုဂ္ဂလိကပိုင်",
  "private business": "ပုဂ္ဂလိကလုပ်ငန်း",
  "sense of sight": "အမြင်အာရုံ",
  "field of vision": "မြင်ကွင်းနယ်",
  "to consult with": "တိုင်ပင်",
  "qualifications": "အရည်အချင်းများ",
  "requirements": "လိုအပ်ချက်များ",
  "capabilities": "စွမ်းရည်များ",
  "means": "နည်းလမ်း",
  "to grant": "ပေးအပ်",
  "to bestow": "ချီးမြှင့်",
  "female (animal)": "အမ",
  "raising": "မွေးမြူခြင်း",
  "dentistry": "သွားဘက်ဆိုင်ရာ",
  "depending on the circumstances": "အခြေအနေအရ",
  "prior": "ကြိုတင်",
  "to resemble closely": "အလွန်တူ",
  "Samurai": "ဆာမူရိုင်း",
  "section of village": "ရွာပိုင်း",
  "hot topic": "လူပြောများခေါင်းစဉ်",
  "talk of the town": "မြို့ပြောစကား",
  "to be well liked": "လူကြိုက်များ",
  "to make welcome": "ကြိုဆိုစေ",
  "time difference": "အချိန်ကွာခြား",
  "to be at peace": "ငြိမ်းချမ်းနေ",
  "to clamp down": "တင်းကျပ်နှိမ်",
  "to lessen (storm  terror  anger)": "လျော့ပါးစေ",
  "public order": "လူမှုစည်းကမ်း",
  "magnetism": "သံလိုက်ဓာတ်",
  "otolaryngology": "နားနှာခေါင်းလည်ချောင်းပညာ",
  "as a matter of course": "ပုံမှန်အတိုင်း",
  "self-conscious": "ကိုယ်သတိရှိ",
  "pretension": "ဟန်ဆောင်မှု",
  "hubris": "မာန်မာန",
  "freely": "လွတ်လပ်စွာ",
  "at will": "ဆန္ဒအတိုင်း",
  "give oneself up": "ကိုယ်ကိုယ်စွန့်",
  "self-confidence": "ကိုယ့်ယုံကြည်",
  "self-respect": "ကိုယ့်ဂုဏ်သိက္ခာ",
  "intransitive verb (no direct obj)": "အကူးမဲ့ကြိယာ",
  "self-reliance": "ကိုယ့်အားကိုး",
  "ceremonial hall": "အခမ်းအနားခန်း",
  "place of ceremony (e.g. marriage)": "အခမ်းအနားနေရာ",
  "shaft": "ရိုးတံ",
  "axle": "ဝင်ရိုး",
  "drop (of water)": "ရေစက်",
  "adhesion": "ကပ်ငြိမှု",
  "tenacity": "ဇွဲလုံ့လ",
  "disqualification": "အရည်အချင်းပယ်",
  "incapacity (legal)": "ဥပဒေမစွမ်း",
  "lack of harmony": "သဟဇာတမဲ့",
  "jealousy": "မနာလိုမှု",
  "to be moist": "စိုစွတ်",
  "frugality": "ချွေတာမှု",
  "industrialist": "စက်မှုလုပ်ငန်းရှင်",
  "businessman": "စီးပွားရေးသမား",
  "real condition": "အစစ်အခြေအနေ",
  "actual circumstances": "အစစ်အခြေအနေများ",
  "actual state of affairs": "အစစ်အခြေအနေ",
  "actual expense": "အစစ်ကုန်ကျ",
  "cost price": "ကုန်ကျစျေး",
  "sod": "မြက်ခင်း",
  "social life": "လူမှုဘဝ",
  "social intercourse": "လူမှုဆက်ဆံရေး",
  "company owned house": "ကုမ္ပဏီအိမ်",
  "to interrupt": "နှောင့်ယှက်",
  "to intercept": "ကြားဖြတ်",
  "to obstruct": "ပိတ်ဆို့",
  "to be dejected": "စိတ်ဓာတ်ကျ",
  "to be troubled": "စိတ်ပူပန်",
  "to be downcast": "စိတ်ငြိုငြင်",
  "starring": "ဇာတ်ဆောင်အဓိက",
  "playing the leading part": "အဓိကအခန်းကဏ္ဍ",
  "sovereignty": "အချုပ်အခြာအာဏာ",
  "staple food": "အဓိကအစားအစာ",
  "protagonist": "ဇာတ်ဆောင်",
  "main character": "အဓိကဇာတ်ကောင်",
  "hero(ine) (of a story)": "ဇာတ်လမ်းသူရဲကောင်း",
  "head of household": "အိမ်ထောင်ဦးစီး",
  "main leadership": "အဓိကခေါင်းဆောင်မှု",
  "person in charge": "တာဝန်ခံ",
  "responsible official": "တာဝန်ရှိအရာရှိ",
  "knob": "လက်ကိုင်",
  "to deal in": "ရောင်းဝယ်လုပ်",
  "to act as an agent for": "ကိုယ်စားလှယ်လုပ်",
  "to announce (someone)": "မိတ်ဆက်",
  "to convey (a message)": "သတင်းပို့",
  "to set apart": "ခွဲထား",
  "to tackle": "ကိုင်တွယ်",
  "to wrestle with": "နပန်းလုံး",
  "to engage in a bout": "ပြိုင်ပွဲဝင်",
  "to come to grips with": "ရင်ဆိုင်ဖြေရှင်း",
  "swap": "လဲလှယ်",
  "to take back": "ပြန်ယူ",
  "to regain": "ပြန်ရ",
  "to extort": "အတင်းတောင်း",
  "choice of subject": "ဘာသာရပ်ရွေး",
  "collecting data": "ဒေတာစု",
  "security guard": "လုံခြုံရေးအစောင့်",
  "doorkeeper": "တံခါးစောင့်",
  "arrangements": "စီစဉ်မှုများ",
  "handicrafts": "လက်မှုပညာ",
  "on hand": "လက်ထဲရှိ",
  "at hand": "လက်ရောက်",
  "at home": "အိမ်တွင်",
  "protocol": "အစဉ်အလာ",
  "handcuffs": "လက်ထိတ်",
  "manacles": "လက်ထိတ်",
  "number of moves": "လှုပ်ရှားအရေအတွက်",
  "too late": "နောက်ကျလွန်း",
  "belated treatment": "နောက်ကျကုသ",
  "division of labour": "အလုပ်ခွဲဝေ",
  "technique": "နည်းပညာ",
  "to swell (from inflammation)": "ရောင်ရမ်းဖောင်း",
  "to become swollen": "ဖောင်းကား",
  "choker": "လည်ဆွဲ",
  "to pass (examination)": "စာမေးပွဲအောင်",
  "to be accepted": "လက်ခံခံရ",
  "to receive (an application)": "လျှောက်လွှာလက်ခံ",
  "passive voice": "ခံသံကြိယာ",
  "trees and shrubs": "သစ်ပင်ပင်ပေါက်",
  "arbour": "သစ်ပင်အောက်",
  "returns": "ပြန်ရငွေ",
  "gathering up": "စုဆောင်းခြင်း",
  "accumulation": "စုပုံမှု",
  "seating": "ထိုင်ခုံနေရာ",
  "starting work": "အလုပ်စတင်",
  "Masters degree program": "မာစတာဘွဲ့အစီအစဉ်",
  "ornamentation": "အလှဆင်မှု",
  "embellishment": "အလှပြင်မှု",
  "adornment": "အလှဆင်",
  "completion (of a course)": "သင်တန်းပြီးဆုံး",
  "beginning and end": "အစနှင့်အဆုံး",
  "doing a thing from beginning to end": "အစအဆုံးလုပ်",
  "all day": "တစ်နေ့လုံး",
  "Lower House": "အောက်လွှတ်တော်",
  "House of Representatives": "ကိုယ်စားလှယ်လွှတ်တော်",
  "to kick away": "ကန်ထုတ်",
  "to kick off": "ကန်ထုတ်",
  "to kick (someone)": "ကန်",
  "totalization": "စုစုပေါင်းတွက်",
  "aggregate": "စုစုပေါင်း",
  "dwelling": "နေအိမ်",
  "fullness": "ပြည့်ဝမှု",
  "substantiality": "ခိုင်မာမှု",
  "10 minutes": "၁၀မိနစ်",
  "engaging": "ပါဝင်ဆောင်ရွက်",
  "pursuing": "လိုက်လံ",
  "following": "နောက်လိုက်",
  "lithe": "ပျော့ပျောင်း",
  "-fold": "-ဆ",
  "-ply": "-ထပ်",
  "duplication": "ပွားခြင်း",
  "repetition": "ထပ်ကျော့",
  "overlapping": "ထပ်နေ",
  "redundancy": "ပိုလျှံမှု",
  "priceless treasure": "တန်ဖိုးမဖြတ်ရတနာ",
  "usefulness": "အသုံးဝင်မှု",
  "heavy responsibilities": "တာဝန်ကြီးများ",
  "destiny": "ကံကြမ္မာ",
  "predestination": "ကြိုတင်ကံ",
  "celebration": "အခမ်းအနား",
  "to be shortened": "တိုအောင်ဖြစ်",
  "coaching school": "ကျူရှင်ကျောင်း",
  "lessons": "သင်ခန်းစာများ",
  "to happen to meet": "မတော်တဆတွေ့",
  "stage appearance": "စင်ပေါ်ပေါ်",
  "bleeding": "သွေးထွက်",
  "haemorrhage": "သွေးယို",
  "to hold a rendezvous": "ချိန်းတွေ့",
  "(child)birth": "မွေးဖွား",
  "production (of goods)": "ကုန်ထုတ်လုပ်မှု",
  "arrival (in a country  at work  etc.)": "ရောက်ရှိခြင်း",
  "successful career": "အောင်မြင်အလုပ်အကိုင်",
  "eminence": "ထင်ရှားမှု",
  "to be out of": "ကုန်သွား",
  "to have no more at hand": "လက်ထဲမရှိတော့",
  "proposing a question": "မေးခွန်းတင်",
  "irresponsible utterance": "တာဝန်မဲ့စကား",
  "random": "ကျပန်း",
  "touch up": "ပြင်ဆင်",
  "sailing": "ရွက်လွှင့်",
  "marching": "ချီတက်",
  "disbursements": "ထုတ်ငွေများ",
  "able man": "စွမ်းရည်ရှိသူ",
  "tumour": "အကျိတ်",
  "twinkling (of stars)": "ကြယ်လက်",
  "flicker (of light)": "အလင်းတဖျပ်ဖျပ်",
  "to conform": "လိုက်နာ",
  "to apply to": "အကျုံးဝင်",
  "to apply correspondingly": "အညီအကျုံးဝင်",
  "to correspond to": "သက်ဆိုင်",
  "to be proportionate to": "အချိုးကျ",
  "local express (train  slower than an express)": "ဒေသအမြန်ရထား",
  "buckler": "ဒိုင်းငယ်",
  "something heard for the first time": "ပထမဆုံးကြားသိ",
  "first edition": "ပထမအကြိမ်ထုတ်",
  "whereabouts": "ဘယ်မှာရှိ",
  "owning": "ပိုင်ဆိုင်ခြင်း",
  "attached to": "တွဲဖက်",
  "belong to": "ပိုင်ဆိုင်",
  "fixed": "ပုံသေ",
  "prescribed": "သတ်မှတ်ထား",
  "common people": "သာမန်ပြည်သူ",
  "general affairs": "အထွေထွေရေးရာ",
  "to take dictation": "ရွတ်ဆိုမှတ်",
  "to take notes": "မှတ်စုယူ",
  "book review": "စာအုပ်ဝေဖန်",
  "Gentlemen!": "သခင်များ!",
  "Ladies!": "အမျိုးသမီးများ!",
  "postposition": "နောက်ဆက်တွဲ",
  "auxiliary verb": "အကူကြိယာ",
  "Ms.": "မစ",
  "going slowly": "နှေးနှေးသွား",
  "to be hurt": "နာကျင်",
  "to be wounded": "ဒဏ်ရာရ",
  "to get injured": "ဒဏ်ရာရ",
  "to outrival": "သာလွန်",
  "quotient": "ဗျဝဟာရ",
  "to recite": "ရွတ်ဆို",
  "to chant": "သီချင်းဆို",
  "to call upon": "လာရောက်ခေါ်",
  "pediatrics": "ကလေးဆေးပညာ",
  "cheque": "ချက်လက်မှတ်",
  "coins": "ဒင်္ဂါးများ",
  "small change": "ငွေလဲ",
  "retail": "လက်လီ",
  "short (build)": "ကိုယ်လုံးတို"
};
