/** Cursor-agent Myanmar for N3–N1 (part 01) */
module.exports = {
  sign: 'အမှတ်အသား',
  mark: 'အမှတ်',
  fortune: 'ကံကြမ္မာ',
  rough: 'ကြမ်းတမ်း',
  support: 'ထောက်ပံ့မှု',
  respect: 'လေးစားမှု',
  outline: 'အကြမ်းဖျင်း',
  stupid: 'ထုံထိုင်း',
  nursing: 'ပြုစုစောင့်ရှောက်',
  cover: 'အဖုံး',
  'to associate with': 'ပေါင်းသင်းသည်',
  objection: 'ကန့်ကွက်ချက်',
  cord: 'ကြိုး',
  therefore: 'ထို့ကြောင့်',
  impression: 'အထင်အမြင်',
  pipe: 'ပိုက်',
  supply: 'ထောက်ပံ့ရေး',
  limit: 'ကန့်သတ်ချက်',
  treatment: 'ကုသမှု',
  simplicity: 'ရိုးရှင်းမှု',
  prosperity: 'စည်ပင်သာယာမှု',
  skin: 'အရေပြား',
  hide: 'ဖုံးကွယ်',
  'to float': 'မျောသည်',
  excessive: 'အလွန်အကျွံ',
  merit: 'ကောင်းကျိုး',
  rude: 'ယုတ်မာ',
  steam: 'ရေနွေးငွေ့',
  compensation: 'လျော်ကြေး',
  beach: 'ကမ်းခြေ',
  consequently: 'ရလဒ်အနေဖြင့်',
  set: 'အစု',
  tube: 'ပြွန်',
  'to remove': 'ဖယ်ရှားသည်',
  maintenance: 'ထိန်းသိမ်းမှု',
  'one by one': 'တစ်ခုချင်း',
  restraint: 'ထိန်းချုပ်မှု',
  course: 'လမ်းကြောင်း',
  settlement: 'အဖြေရှာမှု',
  damage: 'ပျက်စီးမှု',
  reception: 'ကြိုဆိုမှု',
  rock: 'ကျောက်',
  precious: 'အဖိုးတန်',
  opposite: 'ဆန့်ကျင်ဘက်',
  cooperation: 'ပူးပေါင်းဆောင်ရွက်',
  boundary: 'နယ်နိမိတ်',
  violent: 'ကြမ်းကြုတ်',
  trial: 'စစ်ဆေးမှု',
  judgement: 'စီရင်ချက်',
  consultation: 'တိုင်ပင်မှု',
  loan: 'ချေးငွေ',
  prize: 'ဆု',
  manufacture: 'ထုတ်လုပ်မှု',
  youth: 'လူငယ်',
  shell: 'ခွံ',
  summit: 'ထိပ်သီး',
  presentation: 'တင်ပြမှု',
  'etc.)': 'စသည်',
  'to freeze': 'အေးခဲသည်',
  rope: 'ကြိုး',
  understanding: 'နားလည်မှု',
  actor: 'သရုပ်ဆောင်',
  distribution: 'ဖြန့်ဖြူးမှု',
  criticism: 'ဝေဖန်မှု',
  comparison: 'နှိုင်းယှဉ်မှု',
  estimation: 'ခန့်မှန်းမှု',
  'to join': 'ပူးပေါင်းသည်',
  substance: 'အရာဝတ္ထု',
  wealth: 'စည်းစိမ်',
  trouble: 'ပြဿနာ',
  excellence: 'ထူးချွန်မှု',
  dispute: 'အငြင်းပွားမှု',
  'to overflow': 'လျှံသည်',
  summary: 'အနှစ်ချုပ်',
  absurd: 'မိုက်မဲ',
  rotation: 'လည်ပတ်မှု',
  individual: 'တစ်ဦးချင်း',
  reduction: 'လျှော့ချမှု',
  'government office': 'အစိုးရရုံး',
  'to be mixed': 'ရောနှောသည်',
  'to be blended with': 'ရောစပ်သည်',
  arms: 'လက်နက်',
  volume: 'ထုထည်',
  supplement: 'ဖြည့်စွက်',
  ridge: 'တောင်ကြော',
  seal: 'တံဆိပ်',
  stamp: 'တံဆိပ်ခေါင်း',
  servant: 'အလုပ်သမား',
  reform: 'ပြုပြင်ပြောင်းလဲ',
  sympathy: 'စာနာမှု',
  reward: 'ဆုလာဘ်',
  regret: 'နောင်တ',
  boil: 'ဆူ',
  follow: 'လိုက်',
  conceal: 'ဖုံးကွယ်',
  trick: 'လှည့်စားမှု',
  writer: 'စာရေးဆရာ',
  pity: 'သနားမှု',
  abuse: 'စော်ကားမှု',
  'all the more': 'ပို၍ပင်',
  'to stretch': 'ဆန့်သည်',
  assistance: 'အကူအညီ',
  'to append': 'ပူးတွဲသည်',
  'to unfasten': 'ဖြေသည်',
  resolution: 'ဆုံးဖြတ်ချက်',
  improvement: 'တိုးတက်မှု',
  leather: 'သားရေ',
  energy: 'စွမ်းအင်',
  consideration: 'စဉ်းစားမှု',
  completion: 'ပြီးစီးမှု',
  conclusion: 'နိဂုံး',
  feeling: 'ခံစားချက်',
  observation: 'လေ့လာစောင့်ကြည့်',
  pleasure: 'ပျော်ရွှင်မှု',
  contribution: 'ပံ့ပိုးမှု',
  valuable: 'အဖိုးတန်',
  association: 'အသင်းအဖွဲ့',
  stress: 'ဖိအား',
  guess: 'ခန့်မှန်း',
  wise: 'ပညာရှိ',
  'to abate': 'လျော့နည်းသည်',
  pride: 'မာန်မာန',
  facing: 'မျက်နှာချင်းဆိုင်',
  smell: 'အနံ့',
  moat: 'မြောင်း',
  author: 'စာရေးသူ',
  debt: 'အကြွေး',
  'to follow': 'လိုက်သည်',
  'to accompany': 'လိုက်ပါသည်',
  signature: 'လက်မှတ်',
  merchant: 'ကုန်သည်',
  acceptance: 'လက်ခံမှု',
  'to omit': 'ချန်လှပ်သည်',
  superiority: 'သာလွန်မှု',
  worry: 'စိုးရိမ်မှု',
  excuse: 'ဆင်ခြေ',
  nerve: 'အာရုံကြော',
  restriction: 'ကန့်သတ်ချက်',
  growth: 'ကြီးထွားမှု',
  frankness: 'ရိုးသားမှု',
  theory: 'သီအိုရီ',
  tone: 'သံ',
  continuation: 'ဆက်လက်မှု',
  attitude: 'သဘောထား',
  arrest: 'ဖမ်းဆီးမှု',
  capture: 'ဖမ်းယူမှု',
  'to beat': 'ရိုက်သည်',
  horizon: 'မိုးကုပ်စက်ဝိုင်း',
  suspension: 'ရပ်ဆိုင်းမှု',
  peak: 'ထိပ်',
  characteristic: 'ထူးခြားချက်',
  single: 'တစ်ခုတည်း',
  pot: 'အိုး',
  rather: 'ထက်',
  wave: 'လှိုင်း',
  'to tear': 'ဆုတ်ဖြဲသည်',
  'to surpass': 'ကျော်လွန်သည်',
  comment: 'မှတ်ချက်',
  delicate: 'နူးညံ့',
  complaint: 'တိုင်ကြားချက်',
  'to attach': 'ကပ်သည်',
  handle: 'လက်ကိုင်',
  vicinity: 'အနီးအနား',
  dawn: 'မိုးသောက်',
  forecast: 'ခန့်မှန်းချက်',
  excess: 'ပိုလျှံ',
  calm: 'ငြိမ်သက်',
  bay: 'ပင်လယ်အော်',
  inlet: 'ဝင်ပေါက်',
  ambiguous: 'မရှင်းလင်း',
  interview: 'တွေ့ဆုံမေးမြန်း',
  pregnancy: 'ကိုယ်ဝန်',
  worship: 'ကိုးကွယ်မှု',
  repeatedly: 'ထပ်ခါထပ်ခါ',
  feast: 'ပွဲခံ',
  'to spill': 'ဖိတ်သည်',
  careless: 'မေ့လျော့',
  'to deceive': 'လှည့်စားသည်',
  loose: 'လျှော့',
  nonsense: 'အဓိပ္ပာယ်မရှိ',
  naturally: 'သဘာဝအလျောက်',
  print: 'ပုံနှိပ်',
  scrap: 'အပိုင်းအစ',
  unreasonable: 'မတရား',
  recreation: 'အပန်းဖြေ',
  leisure: 'အားလပ်ချိန်',
  pressure: 'ဖိအား',
  transfer: 'လွှဲပြောင်း',
  circumference: 'ပတ်လည်',
  princess: 'မင်းသမီး',
  burn: 'လောင်',
  dry: 'ခြောက်သွေ့',
  service: 'ဝန်ဆောင်မှု',
  shame: 'ရှက်စရာ',
  inspection: 'စစ်ဆေးမှု',
  bow: 'ဦးညွှတ်',
  proclamation: 'ကြေညာချက်',
  'to expand': 'ချဲ့သည်',
  perfume: 'ရေမွှေး',
  square: 'စတုရန်း',
  efficiency: 'ထိရောက်မှု',
  force: 'အင်အား',
  uncle: 'ဦးလေး',
  abbreviation: 'အတိုကောက်',
  raid: 'ဝင်ရောက်တိုက်ခိုက်',
  surname: 'မျိုးရိုးအမည်',
  'family name': 'မျိုးရိုးအမည်',
  conceit: 'မာန်မာန',
  storehouse: 'ဂိုဒေါင်',
  appointment: 'ချိန်းဆိုမှု',
  contrast: 'ဆန့်ကျင်ဘက်',
  check: 'စစ်ဆေး',
  'to flourish': 'စည်ပင်သည်',
  companion: 'အဖော်',
  catch: 'ဖမ်း',
  strike: 'ရိုက်',
  ferry: 'ဖယ်ရီ',
  swing: 'လွှဲ',
  gentle: 'နူးညံ့သိမ်မွေ့',
  possession: 'ပိုင်ဆိုင်မှု',
  noble: 'မြင့်မြတ်',
  refusal: 'ငြင်းပယ်မှု',
  rejection: 'ပယ်ချမှု',
  outlook: 'အမြင်',
  declaration: 'ကြေညာချက်',
  flood: 'ရေကြီးမှု',
  germ: 'ပိုးမွှား',
  praise: 'ချီးမွမ်း',
  'to weaken': 'အားနည်းသည်',
  dominion: 'အုပ်ချုပ်နယ်',
  defense: 'ကာကွယ်ရေး',
  accommodation: 'တည်းခိုနေရာ',
  promotion: 'ရာထူးတိုး',
  pure: 'သန့်ရှင်း',
  neglect: 'လစ်လျူရှု',
  rebellion: 'ပုန်ကန်မှု',
  escape: 'ထွက်ပြေး',
  abandon: 'စွန့်ပစ်',
  depression: 'စိတ်ဓာတ်ကျ',
  protection: 'ကာကွယ်မှု',
  imitate: 'တုပ',
  lotus: 'ကြာပန်း',
  frame: 'ဘောင်',
  shine: 'တောက်ပ',
  pluck: 'ဆွတ်',
  obstruct: 'ပိတ်ဆို့',
  lament: 'ညည်းတွား',
  '(kokuji)': 'ကိုကူဂျိ',
  tracks: 'ခြေရာ',
  welcome: 'ကြိုဆို',
  'so to speak': 'ပြောရလျှင်',
  gargle: 'ပလုတ်ကျင်း',
  'rinse mouth': 'ပါးစပ်ဆေး',
  luck: 'ကံ',
  engine: 'အင်ဂျင်',
  mutual: 'အပြန်အလှန်',
  reciprocal: 'အပြန်အလှန်',
  grand: 'ကြီးကျယ်',
  sisters: 'ညီအစ်မများ',
  namely: 'ဆိုလိုသည်မှာ',
  bottom: 'အောက်ခြေ',
  sole: 'တစ်ခုတည်း',
  nevertheless: 'သို့သော်လည်း',
  'in brief': 'အတိုချုပ်',
  date: 'ရက်စွဲ',
  'no matter what': 'ဘာပဲဖြစ်ဖြစ်',
  somewhere: 'တစ်နေရာရာ',
  'by the way': 'စကားမစပ်',
  top: 'ထိပ်',
  unexpected: 'မမျှော်လင့်',
  nothing: 'ဘာမှမရှိ',
  'be surprised': 'အံ့ဩသည်',
  'be frightened': 'ကြောက်သည်',
  approximately: 'ခန့်မှန်းခြေ',
  grief: 'ဝမ်းနည်းမှု',
  insult: 'စော်ကားမှု',
  slander: 'အသရေဖျက်',
  demon: 'နတ်ဆိုး',
  preservation: 'ထိန်းသိမ်းမှု',
  each: 'တစ်ခုချင်း',
  'to hide': 'ဖုံးကွယ်သည်',
  interior: 'အတွင်းပိုင်း',
  bride: 'သတို့သမီး',
  curriculum: 'သင်ရိုးညွှန်းတမ်း',
  patience: 'သည်းခံမှု',
  sprout: 'အညှောက်',
  rehabilitation: 'ပြန်လည်ထူထောင်',
  restoration: 'ပြန်လည်တည်ဆောက်',
  pleasant: 'သာယာ',
  agreeable: 'နှစ်သက်ဖွယ်',
  comfortable: 'သက်သောင့်သက်သာ',
  injury: 'ဒဏ်ရာ',
  harm: 'ထိခိုက်မှု',
  enlargement: 'ချဲ့ထွင်မှု',
  affirmation: 'အတည်ပြုချက်',
  resignation: 'နုတ်ထွက်မှု',
  'practical use': 'လက်တွေ့အသုံး',
  stock: 'စတော့',
  intuition: 'အလိုအလျောက်သိ',
  perfection: 'ပြည့်စုံမှု',
  completeness: 'ပြီးပြည့်စုံမှု',
  sensation: 'ခံစားမှု',
  'deep emotion': 'နက်ရှိုင်းသောခံစား',
  audience: 'ပရိသတ်',
  'to be based on': 'အခြေခံသည်',
  period: 'ကာလ',
  term: 'သက်တမ်း',
  organ: 'အင်္ဂါ',
  entry: 'ဝင်ရောက်မှု',
  reverse: 'ပြောင်းပြန်',
  huge: 'ကြီးမား',
  enormous: 'အလွန်ကြီးမား',
  permission: 'ခွင့်ပြုချက်',
  border: 'နယ်စပ်',
  robbery: 'လုယက်မှု',
  instruction: 'ညွှန်ကြားချက်',
  ban: 'ပိတ်ပင်မှု',
  classification: 'ခွဲခြားမှု',
  material: 'ပစ္စည်း',
  accidentally: 'မတော်တဆ',
  trend: 'လမ်းကြောင်း',
  notice: 'သတိပေးချက်',
  vehement: 'ပြင်းထန်',
  hole: 'အပေါက်',
  farewell: 'နှုတ်ဆက်',
  aim: 'ရည်မှန်းချက်',
  materialization: 'ပုံပေါ်လာမှု',
  misunderstanding: 'နားလည်မှုလွဲ',
  exchange: 'လဲလှယ်မှု',
  'to extend': 'တိုးချဲ့သည်',
  scent: 'ရနံ့',
  grain: 'စပါး',
  'before long': 'မကြာမီ',
  confusion: 'ရှုပ်ထွေးမှု',
  leadership: 'ဦးဆောင်မှု',
  payment: 'ငွေပေးချေမှု',
  allowance: 'ထောက်ပံ့ကြေး',
  poem: 'ကဗျာ',
  ceremony: 'အခမ်းအနား',
  lawn: 'မြက်ခင်း',
  mainly: 'အဓိကအားဖြင့်',
  harvest: 'ရိတ်သိမ်း',
  inauguration: 'ဖွင့်ပွဲ',
  stagnation: 'ရပ်တန့်မှု',
  'to come across': 'ကြုံတွေ့သည်',
  attendance: 'တက်ရောက်မှု',
  publication: 'ထုတ်ဝေမှု',
  'dealing with': 'ကိုင်တွယ်မှု',
  actress: 'မင်းသမီး',
  trader: 'ကုန်သည်',
  consent: 'သဘောတူမှု',
  invitation: 'ဖိတ်ကြားချက်',
  consumption: 'စားသုံးမှု',
  care: 'ဂရုစိုက်မှု',
  imitation: 'တုပမှု',
  dust: 'ဖုန်မှုန့်',
  standard: 'စံ',
  regular: 'ပုံမှန်',
  accurate: 'တိကျ',
  honesty: 'ရိုးသားမှု',
  production: 'ထုတ်လုပ်မှု',
  'to pile up': 'ပုံသည်',
  equipment: 'ပစ္စည်းကိရိယာ',
  destruction: 'ဖျက်ဆီးမှု',
  selection: 'ရွေးချယ်မှု',
  national: 'အမျိုးသား',
  'to put together': 'ပေါင်းစည်းသည်',
  cleaning: 'သန့်ရှင်းရေး',
  uproar: 'ဆူညံမှု',
  existence: 'တည်ရှိမှု',
  pair: 'အတွဲ',
  majority: 'အများစု',
  'to strike': 'ရိုက်သည်',
  valley: 'ချိုင့်ဝှမ်း',
  intelligence: 'ဉာဏ်ရည်',
  stoppage: 'ရပ်တန့်မှု',
  interruption: 'နှောင့်ယှက်မှု',
  'to sink': 'နစ်သည်',
  passage: 'လမ်းကြောင်း',
  suggestion: 'အကြံပြုချက်',
  enemy: 'ရန်သူ',
  moderate: 'အလယ်အလတ်',
  tradition: 'ဓလေ့ထုံးတမ်း',
  'to congeal': 'ခဲသည်',
  tower: 'မျှော်စင်',
  arrival: 'ရောက်ရှိမှု',
  concurrent: 'တစ်ပြိုင်နက်',
  alone: 'တစ်ယောက်တည်း',
  unmarried: 'အိမ်ထောင်မရှိ',
  reading: 'ဖတ်ရှုခြင်း',
  hemp: 'ပိုက်ဆံပင်',
  better: 'ပိုကောင်း',
  instead: 'အစား',
  'the aged': 'သက်ကြီးရွယ်အို',
  agriculture: 'စိုက်ပျိုးရေး',
  'to violate': 'ချိုးဖောက်သည်',
  'to smash': 'ထုခွဲသည်',
  plum: 'ဇီးသီး',
  explosion: 'ပေါက်ကွဲမှု',
  eruption: 'ပေါက်ကွဲထွက်',
  board: 'ဘုတ်',
  criminal: 'ရာဇဝတ်သား',
  sale: 'ရောင်းချမှု',
  negation: 'ငြင်းပယ်မှု',
  denial: 'ငြင်းဆိုမှု',
  'to equip': 'တပ်ဆင်သည်',
  'to install': 'တပ်ဆင်သည်',
  lap: 'ပေါင်',
  discontent: 'မကျေနပ်မှု',
  dissatisfaction: 'မကျေနပ်မှု',
  'to add': 'ပေါင်းသည်',
  scenery: 'ရှုခင်း',
  separation: 'ခွဲခွာမှု',
  ghost: 'ဘူတ',
  apparition: 'အရိပ်အငွေ့',
  nearby: 'အနီးအနား',
  tomb: 'သင်္ချိုင်း',
  gem: 'ကျောက်မျက်',
  jewel: 'ရတနာ',
  abundance: 'ကြွယ်ဝမှု',
  wish: 'ဆန္ဒ',
  desire: 'လိုချင်မှု',
  brightness: 'တောက်ပမှု',
  permit: 'ခွင့်ပြုချက်',
  daybreak: 'မိုးသောက်',
  'to excel': 'ထူးချွန်သည်',
  courage: 'ရဲစွမ်းသတ္တိ',
  bravery: 'ရဲရင့်မှု',
  prediction: 'ခန့်မှန်းချက်',
  surplus: 'ပိုလျှံ',
  gist: 'အနှစ်သာရ',
  naked: 'အချည်းနှီး',
  thunder: 'မိုးကြိုး',
  storm: 'မုန်တိုင်း',
  tear: 'မျက်ရည်',
  composure: 'တည်ငြိမ်မှု',
  coolness: 'အေးချမ်းမှု',
  gulf: 'ပင်လယ်အော်',
  vague: 'မရှင်းလင်း',
  separately: 'သီးခြား',
  'to threaten': 'ခြိမ်းခြောက်သည်',
  'to coerce': 'အတင်းအကျပ်သည်',
  tightly: 'တင်းတင်း',
  earnestly: 'စိတ်ရင်းဖြင့်',
  'to wither': 'ညှိုးနွမ်းသည်',
  'to wilt': 'ညှိုးသည်',
  carpet: 'ကော်ဇော',
  impudent: 'ရဲတင်း',
  shameless: 'ရှက်မဲ့',
  schedule: 'အချိန်ဇယား',
  slide: 'ချော်',
  'to disagree': 'သဘောမတူသည်',
  furthermore: 'ထို့အပြင်',
  tire: 'တာယာ',
  tip: 'အစွန်',
  'somehow or other': 'ဘယ်လိုပဲဖြစ်ဖြစ်',
  necklace: 'လည်ဆွဲ',
  sparkle: 'တောက်ပ',
  encyclopedia: 'စွယ်စုံကျမ်း',
  'to joke': 'ဟာသလုပ်သည်',
  'to run into': 'တိုက်မိသည်',
  poster: 'ပိုစတာ',
  confused: 'ရှုပ်ထွေး',
  'to straddle': 'ခွဲထိုင်သည်',
  dazzling: 'မျက်စိလည်',
  'to lean against': 'မှီသည်',
  'to lean on': 'မှီခိုသည်',
  'to recline on': 'မှီလဲသည်',
  recklessly: 'မဆင်မခြင်',
  comparatively: 'နှိုင်းယှဉ်လျှင်',
  'to take over': 'လွှဲယူသည်',
  canal: 'တူးမြောင်း',
  'to reflect': 'ရောင်ပြန်ဟပ်သည်',
  liquid: 'အရည်',
  fluid: 'အရည်',
  application: 'လျှောက်လွှာ',
  grace: 'ကျေးဇူးတော်',
  blessing: 'ကောင်းချီး',
  ditch: 'မြောင်း',
  acceleration: 'အရှိန်မြှင့်မှု',
  landlord: 'အိမ်ရှင်',
  frequency: 'ကြိမ်နှုန်း',
  revolution: 'တော်လှန်ရေး',
  shellfish: 'ခရုကမာ',
  cap: 'ဦးထုပ်',
  discount: 'လျှော့ဈေး',
  base: 'အခြေခံ',
  vapour: 'ငွေ့',
  indication: 'ညွှန်ပြချက်',
  symbol: 'သင်္ကေတ',
  rising: 'တက်လာခြင်း',
  'upside down': 'မှောက်မှား',
  'to approach': 'ချဉ်းကပ်သည်',
  'to overlook': 'လျစ်လျူရှုသည်',
  modesty: 'နှိမ့်ချမှု',
  humility: 'နှိမ့်ချမှု',
  'by nature': 'သဘာဝအားဖြင့်',
  principle: 'မူဝါဒ',
  cross: 'လက်ဝါးကပ်တိုင်',
  achievements: 'အောင်မြင်မှုများ',
  worker: 'အလုပ်သမား',
  'to press': 'နှိပ်သည်',
  wild: 'ရိုင်း',
  resentment: 'မကျေနပ်မှု',
  'to mix': 'ရောသည်',
  mixing: 'ရောနှောမှု',
  misfortune: 'ကံဆိုးမှု',
  elimination: 'ဖယ်ရှားမှု',
  'to scatter': 'ကြဲသည်',
  repair: 'ပြုပြင်မှု',
  'middle-aged gentleman': 'လူလတ်ပိုင်းအမျိုးသား',
  'to shrink': 'ကျုံ့သည်',
  circulation: 'လည်ပတ်မှု',
  cycle: 'စက်ဝန်း',
  decoration: 'အလှဆင်',
  pyjamas: 'အိပ်ရာဝတ်',
  shortsightedness: 'အမြော်အမြင်မဲ့',
  adjustment: 'ညှိနှိုင်းမှု',
  ancestor: 'ဘိုးဘေး',
  combination: 'ပေါင်းစပ်မှု',
  warehouse: 'ဂိုဒေါင်',
  hateful: 'မုန်းစရာ',
  detestable: 'ရွံရှာဖွယ်',
  'to arrange': 'စီစဉ်သည်',
  contents: 'အကြောင်းအရာ',
  regulation: 'စည်းမျဉ်း',
  'to put in order': 'စနစ်တကျထားသည်',
  route: 'လမ်းကြောင်း',
  reckless: 'မဆင်မခြင်',
  'to twist': 'လိမ်သည်',
  showy: 'ပြောင်ပြောင်တောက်',
  gay: 'ရွှင်လန်း',
  'to peel off': 'အခွံခွာသည်',
  'to rip off': 'ဆုတ်ဖြဲသည်',
  fate: 'ကံကြမ္မာ',
  'tie-up': 'ချိတ်ဆက်မှု',
  affiliated: 'ဆက်နွယ်',
  warrior: 'စစ်သည်',
  samurai: 'ဆာမူရိုင်း',
  'to split': 'ခွဲသည်',
  villa: 'ဗီလာ',
  monk: 'ရဟန်း',
  'to disturb': 'နှောင့်ယှက်သည်',
  tray: 'ဗန်း',
  'to bury': 'မြှုပ်သည်',
  negligence: 'ပေါ့ဆမှု',
  container: 'ဘူး',
  promising: 'အလားအလာကောင်း',
  bowl: 'ပန်းကန်လုံး',
  flattery: 'ချော့မော့',
  career: 'အလုပ်အကိုင်',
  '#NAME?': 'အမည်',
  scenario: 'ဇာတ်ညွှန်း',
  shock: 'တုန်လှုပ်မှု',
  slender: 'ပိန်လှီ',
  fan: 'ပန်ကာ',
  evil: 'မကောင်းမှု',
  coercion: 'အတင်းအကျပ်',
  'old man': 'လူကြီး',
  gloom: 'မှောင်မိုက်',
  melancholy: 'စိတ်ညစ်ညူး',
  investment: 'ရင်းနှီးမြှုပ်နှံ',
  'to prosper': 'စည်ပင်သည်',
  harmony: 'ညီညွတ်မှု',
  motive: 'ရည်ရွယ်ချက်',
  brilliant: 'ထူးချွန်',
  collection: 'စုစည်းမှု',
  cultivation: 'စိုက်ပျိုးမှု',
  nucleus: 'ဗဟို',
  pardon: 'ခွင့်လွှတ်',
  'starting point': 'အစမှတ်',
  conciliation: 'ပြေလည်မှု',
  foolish: 'မိုက်မဲ',
  stalk: 'ပင်စည်',
  encouragement: 'အားပေးမှု',
  view: 'အမြင်',
  isolation: 'သီးခြားခွဲထား',
  satisfactory: 'ကျေနပ်ဖွယ်',
  sail: 'ရွက်',
  ruin: 'ပျက်စီးမှု',
  yield: 'အထွက်',
  spine: 'ကျောရိုး',
  son: 'သား',
  beforehand: 'ကြိုတင်',
  'in advance': 'ကြိုတင်',
  porcelain: 'ကြွေထည်',
  independence: 'လွတ်လပ်မှု',
  stem: 'ပင်စည်',
  essence: 'အနှစ်သာရ',
  borrowing: 'ချေးယူမှု',
  supremacy: 'အထွတ်အထိပ်',
  living: 'အသက်ရှင်ခြင်း',
  exhibit: 'ပြသမှု',
  shield: 'ဒိုင်း',
  emotion: 'စိတ်ခံစားမှု',
  compassion: 'ကရုဏာ',
  compromise: 'အလျှော့အတင်း',
  sincerity: 'စစ်မှန်မှု',
  gentleman: 'လူကောင်း',
  advance: 'တိုးတက်မှု',
  'to run out': 'ကုန်သွားသည်',
  trim: 'ညှိ',
  strife: 'ရန်ပွဲ',
  confrontation: 'ထိပ်တိုက်တွေ့',
  moment: 'ခဏ',
  'to escape from': 'လွတ်မြောက်သည်',
  dullness: 'မှိုင်းမှု',
  sigh: 'ညည်းတွားသံ',
  bowels: 'အူ',
  intestines: 'အူလမ်းကြောင်း',
  silence: 'ငြိမ်သက်မှု',
  genius: 'ဉာဏ်ကြီးရှင်',
  fellow: 'သူငယ်ချင်း',
  lead: 'ခဲ',
  viscera: 'အတွင်းအင်္ဂါ',
  insurrection: 'ပုန်ကန်မှု',
  grasp: 'ဆုပ်ကိုင်',
  revolt: 'ပုန်ကန်',
  seashore: 'ကမ်းခြေ',
  split: 'ခွဲ',
  reparation: 'လျော်ကြေး',
  deposit: 'အပ်ငွေ',
  emulate: 'တုပ',
  collapse: 'ပြိုကျမှု',
  manservant: 'အိမ်အလုပ်သမား',
  honor: 'ဂုဏ်',
  predominance: 'လွှမ်းမိုးမှု',
  territory: 'နယ်မြေ',
  bud: 'အညွန့်',
  bear: 'ဝက်ဝံ',
  discard: 'စွန့်ပစ်',
  chase: 'လိုက်ဖမ်း',
  pierce: 'ထိုးဖောက်',
  thick: 'ထူ',
  fly: 'ပျံ',
  rejoice: 'ဝမ်းသာ',
  'look for': 'ရှာဖွေ',
  shake: 'လှုပ်',
  compare: 'နှိုင်းယှဉ်',
  revere: 'ရိုသေ',
  parch: 'လှော်',
  paint: 'ဆေးသုတ်',
  adore: 'မြတ်နိုး',
  spit: 'ထွေး',
  urge: 'တိုက်တွန်း',
  resist: 'ခုခံ',
  withdraw: 'ဆုတ်ခွာ',
  reject: 'ပယ်ချ',
  mourning: 'ငိုကြွေး',
  penetrate: 'ထိုးဖောက်',
  fragrant: 'မွှေးကြိုင်',
  laziness: 'ပျင်းရိမှု',
  shore: 'ကမ်း',
  barbarian: 'ရိုင်းစိုင်းသူ',
  endure: 'သည်းခံ',
  'lapis lazuli': 'နီလာကျောက်',
  'Ah!': 'အာ!',
  'Oh!': 'အို!',
  '(1) trace': 'ခြေရာ',
  tease: 'နှောင့်ယှက်',
  prank: 'နောက်ပြောင်မှု',
  'practical joke': 'နောက်ပြောင်ဟာသ',
  'expression of gratitude before meals': 'အစားမစားမီကျေးဇူးတင်',
  sometime: 'တစ်ချိန်ချိန်',
  someday: 'တစ်နေ့နေ့',
  'one day': 'တစ်နေ့',
  forever: 'ထာဝရ',
  'for good': 'အပြီးတိုင်',
  eternally: 'ထာဝရ',
  'as long as one likes': 'ကြိုက်သမျှ',
  'getting nervous': 'စိတ်လှုပ်ရှား',
  irritation: 'စိတ်အနှောင့်အယှက်',
  'the so-called': 'ခေါ်ဝေါ်သော',
  'to groan': 'ညည်းသည်',
  'to moan': 'ညည်းတွားသည်',
  'an auspicious occasion!': 'မင်္ဂလာအခါ!',
  precisely: 'တိတိကျကျ',
  camp: 'စခန်း',
  stinginess: 'ကပ်စေးနဲမှု',
  miser: 'ကပ်စေးနဲသူ',
  miserliness: 'ကပ်စေးနဲမှု',
  coach: 'နည်းပြ',
  code: 'ကုဒ်',
  chord: 'ကြိုးသံ',
  'I beg your pardon': 'ခွင့်လွှတ်ပါ',
  'excuse me': 'ခွင့်ပြုပါ',
  these: 'ဤတို့',
  roughly: 'အကြမ်းဖျင်း',
  'in accordance with': 'အညီ',
  'Damn it!': 'ရှက်စရာ!',
  juice: 'ဖျော်ရည်',
  throughout: 'တစ်လျှောက်လုံး',
  'that is': 'ဆိုလိုသည်မှာ',
  'i.e.': 'ဆိုလိုသည်မှာ',
  eventually: 'နောက်ဆုံးတွင်',
  'sooner or later': 'မကြာမီ',
  'of the previously mentioned': 'အထက်ပါ',
  'without change': 'မပြောင်းလဲဘဲ',
  'as it is (i.e. now)': 'အရှိအတိုင်း',
  'but (still)': 'သို့သော်',
  'and yet': 'သို့သော်လည်း',
  'even so': 'ထိုသို့ပင်',
  '(hand) towel': 'လက်သုတ်ပုဝါ',
  intolerable: 'သည်းမခံနိုင်',
  unbearable: 'သည်းမခံနိုင်',
  unendurable: 'သည်းမခံနိုင်',
  'in short': 'အတိုချုပ်',
  'in other words': 'အခြားစကားဖြင့်',
  demonstration: 'ဆန္ဒပြမှု',
  'by all means': 'မုချ',
  anywhere: 'ဘယ်နေရာမဆို',
  'even if': 'ဖြစ်လျှင်တောင်',
  driving: 'ကားမောင်းခြင်း',
  dress: 'ဝတ်စုံ',
  ton: 'တန်',
  carefree: 'ပူပန်မှုမရှိ',
  scissors: 'ကတ်ကြေး',
  plump: 'ဝဖြိုး',
  'be amazed': 'အံ့ဩသည်',
  astonishment: 'အံ့ဩမှု',
  pin: 'ပင်',
  professional: 'ပညာရှင်',
  selfishness: 'ကိုယ်ကျိုးရှာမှု',
  egoism: 'ကိုယ်ကျိုးရှာမှု',
  wilfulness: 'ခေါင်းမာမှု',
  disobedience: 'မနာခံမှု',
  'on purpose': 'ရည်ရွယ်ချက်ဖြင့်',
  helpless: 'အကူအညီမဲ့',
  sorrow: 'ဝမ်းနည်းမှု',
  'evil speaking': 'အသရေဖျက်စကား',
  devil: 'နတ်ဆိုး',
  'evil spirit': 'ဘူတ',
  'to handle': 'ကိုင်တွယ်သည်',
  'to treat': 'ဆက်ဆံသည်',
  'a certain...': 'တစ်ဦးတစ်ယောက်...',
  'some...': 'အချို့...',
  equilibrium: 'မျှခြေ',
  greatness: 'ကြီးမြတ်မှု',
  disorder: 'ရှုပ်ထွေးမှု',
  removal: 'ဖယ်ရှားမှု',
  migration: 'ရွှေ့ပြောင်းမှု',
  movement: 'လှုပ်ရှားမှု',
  'medical care': 'ဆေးကုသမှု',
  'medical treatment': 'ဆေးကုသမှု',
  'single word': 'စကားလုံးတစ်လုံး',
  'still more': 'ပို၍ပင်',
  'all at once': 'တစ်ပြိုင်နက်',
  quotation: 'ကိုးကားချက်',
  citation: 'ကိုးကားချက်',
  motion: 'အဆို',
  feed: 'အစာ',
  nourishment: 'အာဟာရ',
  eternity: 'ထာဝရ',
  perpetuity: 'ထာဝရတည်မြဲ',
  immortality: 'မသေနိုင်မှု',
  aid: 'အကူအညီ',
  performance: 'ဖျော်ဖြေမှု',
  flame: 'မီးလျှံ',
  smoke: 'မီးခိုး',
  monkey: 'မျောက်',
  diffidence: 'ယုံကြည်မှုမရှိ',
  reserve: 'ကြိုတင်ထား',
  pollution: 'ညစ်ညမ်းမှု',
  'to satisfy': 'ကျေနပ်စေသည်',
  'to comply with': 'လိုက်နာသည်',
  'open sea': 'ပွင့်လင်းပင်လယ်',
  obligation: 'တာဝန်',
  warmth: 'နွေးထွေးမှု',
  'to confer': 'ပေးအပ်သည်',
  everything: 'အားလုံး',
  endurance: 'သည်းခံမှု',
  perseverance: 'ဇွဲ',
  artist: 'အနုပညာရှင်',
  'counter for occurrences': 'ကြိမ်ရေရေတွက်',
  hurt: 'နာကျင်',
  foreign: 'နိုင်ငံခြား',
  'going out': 'အပြင်ထွက်',
  magnification: 'ချဲ့မှု',
  scholar: 'ပညာရှင်',
  action: 'လုပ်ရပ်',
  activity: 'လှုပ်ရှားမှု',
  'to harvest': 'ရိတ်သိမ်းသည်',
  perception: 'အာရုံခံမှု',
  calculation: 'တွက်ချက်မှု',
  'to encourage': 'အားပေးသည်',
  sense: 'အာရုံ',
  admiration: 'ချီးမွမ်းမှု',
  excitement: 'စိတ်လှုပ်ရှားမှု',
  sweat: 'ချွေး',
  survey: 'စစ်တမ်း',
  'to bear in mind': 'စိတ်ထဲထားသည်',
  crag: 'ကျောက်ဆောင်',
  '(a) delight': 'ပျော်ရွှင်မှု',
  rapture: 'အလွန်ပျော်ရွှင်',
  donation: 'လှူဒါန်းမှု',
  flag: 'အလံ',
  mechanism: 'ယန္တရား',
  'to suit': 'လိုက်ဖက်သည်',
  pitiful: 'သနားစရာ',
  climate: 'ရာသီဥတု',
  'to notice': 'သတိထားသည်',
  'to recognize': 'အသိအမှတ်ပြုသည်',
  '-like': 'ကဲ့သို့',
  engineer: 'အင်ဂျင်နီယာ',
  congress: 'ကွန်ဂရက်',
  parliament: 'လွှတ်တော်',
  'to shorten': 'တိုသည်',
  'to go against': 'ဆန့်ကျင်သည်',
  'to oppose': 'ဆန့်ကျင်သည်',
  'to disobey': 'မနာခံသည်',
  salary: 'လစာ',
  wages: 'လုပ်ခ',
  'to approve': 'အတည်ပြုသည်',
  approval: 'အတည်ပြုချက်',
  collaboration: 'ပူးပေါင်းဆောင်ရွက်',
  emphasis: 'အလေးပေးမှု',
  terrible: 'ကြောက်မက်ဖွယ်',
  dreadful: 'ကြောက်စရာ',
  prohibition: 'တားမြစ်မှု',
  distinction: 'ခွဲခြားမှု',
  differentiation: 'ခွဲခြားသတ်မှတ်',
  troubles: 'ပြဿနာများ',
  hardships: 'ဒုက္ခများ',
  concrete: 'ကွန်ကရစ်/တိကျ',
  unexpectedly: 'မမျှော်လင့်ဘဲ',
  'to repeat': 'ထပ်လုပ်သည်',
  tendency: 'သဘောထား',
  honour: 'ဂုဏ်',
  constitution: 'ဖွဲ့စည်းပုံအခြေခံဥပဒေ',
  prefecture: 'ခရိုင်',
  shoulder: 'ပခုံး',
  escort: 'လိုက်ပါကာကွယ်',
  estimate: 'ခန့်မှန်း',
  smart: 'ထက်မြက်',
  eaves: 'အိမ်အမိုးစွန်း',
  'to decrease (in size or number)': 'လျော့နည်းသည်',
  'to diminish': 'လျော့သည်',
  embodiment: 'ပုံသဏ္ဍာန်',
  reality: 'အမှန်တရား',
  phenomenon: 'ဖြစ်ရပ်',
  'status quo': 'လက်ရှိအခြေအနေ',
  bound: 'ချည်နှောင်',
  breath: 'အသက်ရှူ',
  'home town': 'ဇာတိမြို့',
  birthplace: 'မွေးရပ်',
  tiger: 'ကျား',
  honourable: 'ဂုဏ်သိက္ခာရှိ',
  interchange: 'လဲလှယ်မှု',
  aviation: 'လေကြောင်း',
  aroma: 'ရနံ့',
  signal: 'အချက်ပြ',
  subjugation: 'သိမ်းပိုက်မှု',
  conquest: 'အောင်နိုင်မှု',
  'national or state border': 'နိုင်ငံနယ်စပ်',
  hereafter: 'ဤနောက်',
  difficulty: 'အခက်အခဲ',
  distress: 'ဒုက္ခ',
  engagement: 'စေ့စပ်မှု',
  root: 'အမြစ်',
  congestion: 'ပိတ်ဆို့မှု',
  'to be finished': 'ပြီးသည်',
  property: 'ပိုင်ဆိုင်မှု',
  assets: 'ပိုင်ဆိုင်မှုများ',
  label: 'တံဆိပ်',
  participation: 'ပါဝင်မှု',
  reference: 'ကိုးကား',
  remnant: 'အကြွင်းအကျန်',
  incentive: 'မက်လုံး',
  'to be blocked': 'ပိတ်သည်',
  expenditure: 'အသုံးစရိတ်',
  expenses: 'ကုန်ကျစရိတ်',
  'to give up': 'စွန့်လွှတ်သည်',
  resources: 'အရင်းအမြစ်များ',
  automatic: 'အလိုအလျောက်',
  boast: 'ကြွား',
  equation: 'ညီမျှခြင်း',
  formula: 'ဖော်မြူလာ',
  'to scold': 'ဆူသည်',
  experiment: 'စမ်းသပ်မှု',
  liabilities: 'တာဝန်ဝတ္တရား',
  primarily: 'အဓိကအားဖြင့်',
  'to come off': 'ကွာသည်',
  source: 'ရင်းမြစ်',
  'Prime Minister': 'ဝန်ကြီးချုပ်',
  income: 'ဝင်ငွေ',
  mending: 'ပြုပြင်မှု',
  odour: 'အနံ့',
  stench: 'အနံ့ဆိုး',
  concentration: 'စူးစိုက်မှု',
  resident: 'နေထိုင်သူ',
  housing: 'အိမ်ရာ',
  delay: 'နှောင့်နှေးမှု',
  'to meet by chance': 'မတော်တဆတွေ့သည်',
  'to happen to encounter': 'ကြုံတွေ့သည်',
  'to express': 'ဖော်ပြသည်',
  processing: 'လုပ်ငန်းစဉ်',
  disposition: 'သဘောထား',
  books: 'စာအုပ်များ',
  queen: 'မိဖုရား',
  shopkeeper: 'ဆိုင်ရှင်',
  wheat: 'ဂျုံ',
  parcel: 'ပါဆယ်',
  package: 'ထုပ်ပိုး',
  assent: 'သဘောတူမှု',
  'fire fighting': 'မီးသတ်',
  upper: 'အပေါ်',
  'first class': 'ပထမတန်း',
  'to place on (something)': 'တင်သည်',
  'to take on board': 'တင်ဆောင်သည်',
  'to give a ride': 'စီးခိုင်းသည်',
  passenger: 'ခရီးသည်',
  joke: 'ဟာသ',
  castle: 'ရဲတိုက်',
  conditions: 'အခြေအနေများ',
  employment: 'အလုပ်အကိုင်',
  provisions: 'စားနပ်ရိက္ခာ',
  'to lengthen': 'ရှည်သည်',
  'to reach out': 'လက်ဆန့်သည်',
  'to grow (beard)': 'ပေါက်သည်',
  refereeing: 'ဒိုင်လူကြီးလုပ်',
  umpire: 'ဒိုင်လူကြီး',
  concern: 'စိုးရိမ်မှု',
  anxiety: 'စိုးရိမ်ပူပန်',
  mentality: 'စိတ်ဓာတ်',
  apology: 'တောင်းပန်ချက်',
  'deep red': 'နီရင့်',
  sensitivity: 'ထိခိုက်လွယ်မှု',
  intimate: 'ရင်းနှီး',
  'to advance': 'ရှေ့တိုးသည်',
  'to promote': 'မြှင့်တင်သည်',
  'to hasten': 'အလျင်အမြန်သည်',
  needle: 'အပ်',
  artificial: 'အတု',
  dirt: 'အညစ်အကြေး',
  sex: 'လိင်',
  gender: 'ကျား/မ',
  'young man': 'လူငယ်',
  coal: 'ကျောက်မီးသွေး',
  positive: 'အပြုသဘော',
  active: 'တက်ကြွ',
  'to blame': 'အပြစ်တင်သည်',
  device: 'ကိရိယာ',
  installation: 'တပ်ဆင်မှု',
  tongue: 'လျှာ',
  choice: 'ရွေးချယ်မှု',
  'whole country': 'နိုင်ငံလုံး',
  whole: 'အားလုံး',
  defect: 'ချို့ယွင်းချက်',
  'weak point': 'အားနည်းချက်',
  rat: 'ကြွက်',
  'slate color': 'မီးခိုးရောင်',
  nest: 'အသိုက်',
  rookery: 'ငှက်အသိုက်စု',
  frost: 'နှင်းခဲ',
  disturbance: 'နှောင့်ယှက်မှု',
  bundle: 'ထုပ်',
  being: 'သတ္တဝါ',
  grandchild: 'မြေး',
  esteem: 'လေးစားမှု',
  'another person': 'အခြားသူ',
  'unrelated person': 'မဆိုင်သူ',
  outsider: 'ပြင်ပလူ',
  stranger: 'သူစိမ်း',
  gymnastics: 'ကိုယ်လက်လေ့ကျင့်',
  couple: 'စုံတွဲ',
  'to be idle': 'ပျင်းရိသည်',
  'to neglect': 'လစ်လျူရှုသည်',
  lending: 'ချေးငှားမှု',
  convention: 'အစည်းအဝေး',
  bullet: 'ကျည်ဆံ',
  'to refuse': 'ငြင်းသည်',
  cavity: 'အပေါက်',
  passing: 'ဖြတ်သန်းခြင်း',
  submission: 'တင်သွင်းမှု',
  'to abandon': 'စွန့်ပစ်သည်',
  mud: 'ရွှံ့',
  rival: 'ပြိုင်ဘက်',
  flute: 'ပုလွေ',
  appropriate: 'သင့်လျော်',
  'all night': 'ညလုံးပတ်လည်',
  'to disgorge': 'အန်သည်',
  'to throw down': 'ပစ်ချသည်',
  pagoda: 'စေတီ',
  beans: 'ပဲ',
  associate: 'လုပ်ဖော်ကိုင်ဖက်',
  feature: 'ထူးခြားချက်',
  poison: 'အဆိပ်',
  peculiarity: 'ထူးခြားချက်',
  riddle: 'ပဟေဠိ',
  puzzle: 'ပဟေဠိ',
  enigma: 'နက်နဲသောအရာ',
  sunlight: 'နေရောင်',
  dating: 'ရက်စွဲသတ်မှတ်',
  'old people': 'သက်ကြီးရွယ်အို',
  farmers: 'တောင်သူများ',
  'to defeat': 'အနိုင်ယူသည်',
  folly: 'မိုက်မဲမှု',
  delivery: 'ပို့ဆောင်မှု',
  vast: 'ကျယ်ပြန့်',
  announcement: 'ကြေညာချက်',
  selling: 'ရောင်းချခြင်း',
  review: 'သုံးသပ်ချက်',
  fatigue: 'ပင်ပန်းမှု',
  fur: 'သားမွေး',
  secret: 'လျှို့ဝှက်',
  secrecy: 'လျှို့ဝှက်မှု',
  'to avert': 'ရှောင်သည်',
  'to furnish': 'ပံ့ပိုးသည်',
  ice: 'ရေခဲ',
  hail: 'မိုးသီး',
  chart: 'ဇယား',
  list: 'စာရင်း',
  bottle: 'ပုလင်း',
  unfairness: 'မတရားမှု',
  lack: 'မရှိခြင်း',
  'married couple': 'အိမ်ထောင်ဖက်',
  'to rot': 'ပုပ်သည်',
  Buddha: 'ဗုဒ္ဓ',
  'the dead': 'သေသူများ',
  analysis: 'ခွဲခြမ်းစိတ်ဖြာ',
  evenness: 'ညီမျှမှု',
  grip: 'ဆုပ်ကိုင်',
  parting: 'ခွဲခွာမှု',
  storage: 'သိုလှောင်မှု',
  grave: 'သင်္ချိုင်း',
  treasure: 'ရတနာ',
  'to entertain': 'ဧည့်ခံသည်',
  foam: 'အမြှုပ်',
  froth: 'အမြှုပ်',
  call: 'ခေါ်ဆိုမှု',
  visit: 'လည်ပတ်မှု',
  rod: 'တံ',
  powder: 'မှုန့်',
  charm: 'ဆွဲဆောင်မှု',
  fascination: 'စွဲလမ်းမှု',
  futility: 'အချည်းနှီး',
  uselessness: 'အသုံးမကျမှု',
  fog: 'မြူ',
  mist: 'မြူဆိုင်း',
  'clear up': 'ရှင်းလင်း',
  bother: 'အနှောင့်အယှက်',
  license: 'လိုင်စင်',
  licence: 'လိုင်စင်',
  objective: 'ရည်မှန်းချက်',
  'to outstrip': 'ကျော်လွန်သည်',
  profitable: 'အမြတ်ရှိ',
  mail: 'စာပို့',
  expectation: 'မျှော်လင့်ချက်',
  prevention: 'ကာကွယ်မှု',
  extra: 'အပို',
  'to entrust': 'အပ်နှံသည်',
  'to deposit': 'အပ်သည်',
  childish: 'ကလေးဆန်',
  nude: 'အချည်းနှီး',
  'to rely on': 'အားကိုးသည်',
  tempest: 'မုန်တိုင်း',
  comprehension: 'နားလည်မှု',
  fashionable: 'ခေတ်စား',
  fad: 'ခေတ်စားမှု',
  'in vogue': 'ခေတ်စားနေ',
  prevailing: 'လွှမ်းမိုးနေ',
  luxury: 'ဇိမ်ခံ',
  extravagance: 'အလွန်အကျွံ',
  'to be amazed': 'အံ့ဩသည်',
  'to be shocked': 'တုန်လှုပ်သည်',
  'to fulfill': 'ပြည့်စုံသည်',
  'to apply': 'လျှောက်သည်',
  'to adapt': 'လိုက်လျောညီထွေသည်',
  'to scorch': 'လောင်သည်',
  'to flood': 'ရေလျှံသည်',
  'to brim over': 'လျှံသည်',
  'one thing or another': 'တစ်ခုမဟုတ်တစ်ခု',
  'this and that': 'ဒီဟာနဲ့ဟိုဟာ',
  'this or that': 'ဒီဟာ သို့မဟုတ် ဟိုဟာ',
  'before one knows': 'မသိလိုက်ခင်',
  unnoticed: 'မသိမသာ',
  unawares: 'မသိလိုက်ဘဲ',
  wool: 'သိုးမွေး',
  waitress: 'စားပွဲထိုးမ',
  'noodles (Japanese)': 'ဂျပန်ခေါက်ဆွဲ',
  'very much': 'အလွန်',
  broad: 'ကျယ်ပြန့်',
  sketchy: 'အကြမ်းဖျင်း',
  'Thanks to god': 'ဘုရားကျေးဇူးကြောင့်',
  'thanks to you': 'သင့်ကျေးဇူးကြောင့်',
  'side dish': 'ဟင်းလျာ',
  'accompaniment for rice dishes': 'ထမင်းနှင့်တွဲဖက်',
  'smartly dressed': 'လှပစွာဝတ်',
  'someone smartly dressed': 'လှပစွာဝတ်သူ',
  'fashion-conscious': 'ဖက်ရှင်သိ',
  'Take care of yourself': 'ကိုယ့်ကိုယ်ကိုဂရုစိုက်',
  'Sorry to have kept you waiting': 'စောင့်ခိုင်းမိလို့တောင်းပန်',
  'afternoon refreshment': 'နေ့လယ်စာစား',
  'certainly!': 'မုချ!',
  itchy: 'ယားယံ',
  itching: 'ယားခြင်း',
  campus: 'ကျောင်းဝင်း',
  sneeze: 'နှာချေ',
  'good-for-nothing': 'အသုံးမကျ',
  trivial: 'သေးငယ်',
  worthless: 'တန်ဖိုးမရှိ',
  'to adhere to': 'ကပ်သည်',
  'to keep close to': 'နီးကပ်စွာနေသည်',
  verbose: 'စကားများ',
  importunate: 'အတင်းတောင်း',
  'heavy (taste)': 'အရသာပြင်း',
  'dry cleaning': 'ခြောက်သွေ့ဆေးကြော',
  'to be engulfed in': 'ဝိုင်းရံသည်',
  'to be enveloped by': 'ဖုံးအုပ်သည်',
  'to wrap up': 'ထုပ်ပိုးသည်',
  sincerely: 'စစ်မှန်စွာ',
  chorus: 'သံစုံသီချင်း',
  'Thank you very much for your....': 'ကျေးဇူးတင်ပါသည်....',
  faucet: 'ရေပိုက်ခေါင်း',
  'May I come in?': 'ဝင်လို့ရပါသလား?',
  'good evening': 'မင်္ဂလာညနေခင်း',
  'two days before yesterday': 'မနေ့မတိုင်မီနှစ်ရက်',
  quickly: 'မြန်မြန်',
  'good-bye': 'ဂွတ်ဘိုင်',
  sample: 'နမူနာ',
  'two days after tomorrow': 'နက်ဖြန်နှစ်ရက်ကြာ',
  'silent (as the grave)': 'သင်္ချိုင်းလိုတိတ်ဆိတ်',
  '(deathly) quiet': 'အလွန်တိတ်ဆိတ်',
  'tail (animal)': 'အမြီး',
  'to become numb': 'ထုံသည်',
  'to fade (away)': 'မှေးမှိန်သည်',
  'to shrivel': 'တွန့်သည်',
  keenly: 'ပြင်းပြင်း',
  deeply: 'နက်နက်',
  heartily: 'စိတ်ရင်းဖြင့်',
  hiccough: 'ဟစ်',
  hiccup: 'ဟစ်',
  scarf: 'လည်စည်း',
  'at least': 'အနည်းဆုံး',
  slim: 'ပိန်လှီ',
  'sorry (phrase)': 'တောင်းပန်ပါတယ်',
  'to delay': 'နှောင့်နှေးသည်',
  'to pass by one another': 'လွဲချော်သည်',
  'by all means (with sense of not taking no for an answer)': 'မုချလိုအပ်',
  thoughtless: 'မစဉ်းစား',
  'in addition': 'ထို့အပြင်',
  hence: 'ထို့ကြောင့်',
  'for that reason': 'ထိုအကြောင်းကြောင့်',
  tyre: 'တာယာ',
  diagram: 'ပုံကြမ်း',
  'to trick': 'လှည့်စားသည်',
  'to cheat': 'လိမ်သည်',
  'to hesitate': 'တွန့်ဆုတ်သည်',
  slovenly: 'ညစ်ပတ်',
  'chest of drawers': 'အံဆွဲဗီရို',
  project: 'စီမံကိန်း',
  nonsensical: 'အဓိပ္ပာယ်မရှိ',
  'pleased to meet you': 'တွေ့ရတာဝမ်းသာပါတယ်',
  'to shout': 'အော်သည်',
  'to yell': 'အော်ဟစ်သည်',
  'for some reason or another': 'တစ်ခုခုကြောင့်',
  saw: 'လွှ',
  'How do you do?': 'မင်္ဂလာပါ?',
  'I am glad to meet you': 'တွေ့ရတာဝမ်းသာပါတယ်',
  'by itself': 'သူ့အလိုလို',
  automatically: 'အလိုအလျောက်',
  'to romp': 'ကစားသည်',
  'to gambol': 'ခုန်ပေါက်သည်',
  'to frolic': 'ကစားခုန်သည်',
  'to collide with': 'တိုက်မိသည်',
  'to knock': 'ခေါက်သည်',
  'to nail on': 'သံမှိုရိုက်သည်',
  'to strike hard': 'ပြင်းပြင်းရိုက်သည်',
  brush: 'စုတ်တံ',
  program: 'အစီအစဉ်',
  navel: 'ချက်',
  'belly-button': 'ချက်',
  bonus: 'ဆုကြေး',
  rag: 'အဝတ်စုတ်',
  'tattered clothes': 'စုတ်ပြတ်အဝတ်',
  'fault (esp. in a pretense)': 'ချို့ယွင်းချက်',
  minus: 'နှုတ်',
  mask: 'မျက်နှာဖုံး',
  radiant: 'တောက်ပ',
  shameful: 'ရှက်စရာ',
  indecent: 'ယုတ်ညံ့',
  'milli-': 'မီလီ-',
  '10^-3': '၁၀^-၃',
  'messed up': 'ရှုပ်ထွေး',
  menu: 'မီနူး',
  dizziness: 'မူးဝေမှု',
  giddiness: 'မူးမော်မှု',
  'to lie heavy (on the stomach)': 'ဗိုက်လေးသည်',
  'too good': 'ကောင်းလွန်း',
  'more than one deserves': 'မထိုက်တန်အောင်',
  wasteful: 'အလဟဿ',
  sacrilegious: 'သာသနာဆန့်ကျင်',
  randomly: 'ကျပန်း',
  blindly: 'မျက်စိမှိတ်',
  'cannot be helped': 'မတတ်နိုင်',
  unavoidable: 'ရှောင်လွှဲမရ',
  launch: 'စတင်ထုတ်',
  romanization: 'ရိုမန်စာလုံးရေး',
  'Roman letters': 'ရိုမန်စာလုံးများ',
  'to be proud': 'ဂုဏ်ယူသည်',
};
