/** Cursor-agent Myanmar glosses for missing N4 kanji */
module.exports = {
  oneself: 'မိမိ',
  departure: 'ထွက်ခွာ',
  discharge: 'ထုတ်လွှတ်',
  publish: 'ထုတ်ဝေ',
  emit: 'ထုတ်လွှတ်',
  traffic: 'ယာဉ်ကြော',
  'pass through': 'ဖြတ်သန်း',
  avenue: 'လမ်းမ',
  commute: 'သွားလာ',
  'rice field': 'စပါးခင်း',
  'rice paddy': 'လယ်ကွင်း',
  lord: 'သခင်',
  chief: 'အကြီးအကဲ',
  master: 'ဆရာ/သခင်',
  'main thing': 'အဓိကအရာ',
  consider: 'စဉ်းစား',
  'think over': 'တွေးတော',
  goods: 'ကုန်ပစ္စည်း',
  refinement: 'ယဉ်ကျေးမှု',
  dignity: 'ဂုဏ်သိက္ခာ',
  article: 'ပစ္စည်း/ဆောင်းပါး',
  pedestal: 'ခံစင်',
  'a stand': 'စင်/ခုံ',
  'counter for machines and vehicles': 'ယာဉ်/စက်ရေတွက်',
  fee: 'ကြေး',
  materials: 'ပစ္စည်းများ',
  craft: 'လက်မှု',
  construction: 'ဆောက်လုပ်ရေး',
  'katakana e radical (no. 48)': 'ရက်ဒီကယ်',
  hurry: 'အလျင်အမြန်',
  emergency: 'အရေးပေါ်',
  sudden: 'ရုတ်တရက်',
  steep: 'မတ်စောက်',
  polish: 'ပွတ်တိုက်/သုတေသန',
  'study of': 'လေ့လာမှု',
  sharpen: 'ထက်အောင်လုပ်',
  rouse: 'နှိုးဆော်',
  'wake up': 'နိုး',
  'get up': 'ထ',
  reflect: 'ရောင်ပြန်ဟပ်',
  reflection: 'ရောင်ပြန်',
  projection: 'ပုံဖော်ပြသ',
  verification: 'စစ်ဆေးအတည်ပြု',
  effect: 'အကျိုးသက်ရောက်',
  testing: 'စမ်းသပ်ခြင်း',
  pour: 'လောင်း',
  irrigate: 'ရေသွင်း',
  'shed (tears)': 'မျက်ရည်ကျ',
  'flow into': 'စီးဝင်',
  homecoming: 'အိမ်ပြန်',
  'arrive at': 'ရောက်ရှိ',
  'lead to': 'ဦးတည်',
  'result in': 'ဖြစ်ပေါ်စေ',
  springtime: 'နွေဦးကာလ',
  'spring (season)': 'နွေဦး',
  building: 'အဆောက်အအုံ',
  mansion: 'အိမ်ကြီး',
  'large building': 'အဆောက်အအုံကြီး',
  palace: 'နန်းတော်',
  clothing: 'အဝတ်အစား',
  admit: 'ဝန်ခံ',
  obey: 'နာခံ',
  borrow: 'ငှား',
  rent: 'ငှားရမ်း',
  weekday: 'တနင်္ဂနွေမှလွဲသောနေ့',
  lend: 'ချေးပေး',
  'public chamber': 'ခန်းမ',
  hall: 'ခန်းမ',
  meal: 'အစားအသောက်',
  'boiled rice': 'ထမင်း',
  exertion: 'ကြိုးစားအားထုတ်',
  endeavour: 'ကြိုးပမ်း',
  encourage: 'အားပေး',
  strive: 'ကြိုးစား',
  'younger brother': 'ညီ',
  'faithful service to elders': 'လူကြီးကိုနာခံ',
  'elder brother': 'အစ်ကို',
  'big brother': 'အစ်ကို',
  'younger sister': 'ညီမ',
  'elder sister': 'အစ်မ',
  'Sino-': 'တရုတ်-',
  China: 'တရုတ်',
};
