/** Cursor-agent Myanmar glosses for N4 vocabulary */
module.exports = {
  Ah: 'အာ',
  'like that': 'အဲဒီလို',
  'to greet': 'နှုတ်ဆက်သည်',
  infant: 'ကလေးငယ်',
  accessory: 'အသုံးအဆောင်',
  announcer: 'ကြေညာသူ',
  Africa: 'အာဖရိက',
  'part-time job': 'အချိန်ပိုင်းအလုပ်',
  such: 'ဒီလို',
  'to tease': 'နှောင့်ယှက်သည်',
  '(humble) to receive': 'လက်ခံသည် (နှိမ့်ချ)',
  '(respectful) to be': 'ရှိသည် (လေးစား)',
  'to come or to go': 'လာ/သွားသည်',
  within: 'အတွင်း',
  glad: 'ဝမ်းသာ',
  '(informal) yes': 'ဟုတ် (ရင်းနှီး)',
  escalator: 'လှုပ်လှေကား',
  motorcycle: 'ဆိုင်ကယ်',
  'owing to': 'ကြောင့်',
  'strange or funny': 'ထူးဆန်း/ရယ်စရာ',
  '(respectful) to say': 'ပြောသည် (လေးစား)',
  toy: 'ကစားစရာ',
  'rich man': 'ချမ်းသာသူ',
  'calling on someone who is ill': 'နာမကျန်းလူ့ကိုလည်',
  enquiry: 'မေးမြန်းမှု',
  festival: 'ပွဲတော်',
  congratulation: 'ဂုဏ်ပြုခြင်း',
  'young lady': 'လူပျိုမ',
  '(polite) your house': 'သင့်အိမ်',
  souvenir: 'အမှတ်တရပစ္စည်း',
  'expression of gratitude': 'ကျေးဇူးတင်စကား',
  curtain: 'ကုလားကာ',
  petrol: 'ဓာတ်ဆီ',
  'petrol station': 'ဓာတ်ဆီဆိုင်',
  'a glass pane': 'မှန်ချပ်',
  surely: 'သေချာပေါက်',
  '(respectful) to give': 'ပေးသည် (လေးစား)',
  cake: 'ကိတ်မုန့်',
  'to injure': 'ဒဏ်ရာရစေသည်',
  'to quarrel': 'ရန်ဖြစ်သည်',
  'this way': 'ဒီဘက်/ဒီလို',
  'a feast': 'ပွဲခံ',
  'these days': 'ဒီရက်ပိုင်း',
  nowadays: 'ယနေ့ခေတ်',
  rubbish: 'အမှိုက်',
  '(respectful) to see': 'ကြည့်သည် (လေးစား)',
  'after this': 'ဒီနောက်',
  concert: 'တေးဂီတပွဲ',
  knowing: 'သိကျွမ်းမှု',
  acquaintance: 'သိကျွမ်းသူ',
  'some time ago': 'မကြာမီက',
  salad: 'သုပ်',
  sandal: 'ဖိနပ်ပွင့်',
  sandwich: 'စန္ဒဝစ်',
  'the month after next': 'နှစ်လကြာမှ',
  'the week after next': 'နှစ်ပတ်ကြာမှ',
  'a particular': 'အထူးတစ်ခု',
  firmly: 'ခိုင်ခိုင်',
  steadily: 'တည်ငြိမ်စွာ',
  'little while': 'ခဏ',
  hindrance: 'အနှောင့်အယှက်',
  intrusion: 'ဝင်ရောက်နှောင့်ယှက်',
  jam: 'ယာဉ်ကြောပိတ်/ယို',
  extremely: 'အလွန်',
  suit: 'စွတ်ကျူ',
  suitcase: 'ခရီးဆောင်သေတ္တာ',
  'to become empty': 'ဗလာဖြစ်သည်',
  screen: 'မျက်နှာပြင်/ကန့်လန့်ကာ',
  straight: 'တည့်တည့်',
  'all of a sudden': 'ရုတ်တရက်',
  steak: 'အသားကင်',
  stereo: 'စတီရီယို',
  wonderful: 'အံ့ဩဖွယ်',
  pickpocket: 'အိတ်ကပ်ခိုးသူ',
  then: 'ပြီးရင်',
  'without fail': 'မုချ',
  'not entirely (used in a negative sentence)': 'လုံးဝမဟုတ်',
  really: 'တကယ်',
  'because of that': 'အဲဒါကြောင့်',
  moreover: 'ထို့အပြင်',
  'to that extent': 'အဲဒီလောက်',
  'that sort of': 'အဲဒီလိုမျိုး',
  'so much': 'အဲဒီလောက်',
  occasionally: 'တစ်ခါတစ်ရံ',
  'no good': 'မရဘူး',
  'to check': 'စစ်ဆေးသည်',
  'not at all (used with a negative verb)': 'လုံးဝမ…',
  'suffix for familiar female person': 'မိန်းမခေါ်နောက်ဆက်',
  text: 'စာသား',
  'text book': 'သင်ရိုးစာအုပ်',
  'as much as possible': 'တတ်နိုင်သမျှ',
  tennis: 'တင်းနစ်',
  finally: 'နောက်ဆုံးမှာ',
  'after all': 'အဆုံးမှာ',
  barber: 'ဆံပင်ညှပ်ဆရာ',
  'more and more': 'ပို၍ပို၍',
  '(respectful) to do': 'လုပ်သည် (လေးစား)',
  'now I understand': 'အခုနားလည်ပြီ',
  'a smell': 'အနံ့',
  'to get wet': 'စိုသည်',
  enthusiasm: 'စိတ်အားထက်သန်မှု',
  throat: 'လည်ချောင်း',
  'part time': 'အချိန်ပိုင်း',
  'it should be so': 'ဟုတ်ရမည်',
  'personal computer': 'ပုဂ္ဂိုလ်ရေးကွန်ပျူတာ',
  clearly: 'ရှင်းလင်းစွာ',
  handbag: 'လက်ကိုင်အိတ်',
  piano: 'စန္ဒရား',
  beard: 'မုတ်ဆိတ်',
  'to be surprised': 'အံ့ဩသည်',
  awful: 'ဆိုးရွား',
  'building or bill': 'အဆောက်အအုံ/ဘေလ်',
  fax: 'ဖက်စ်',
  grapes: 'စပျစ်သီး',
  bell: 'ခေါင်းလောင်း',
  extent: 'အတိုင်းအတာ',
  mostly: 'အများအားဖြင့်',
  'to praise': 'ချီးမွမ်းသည်',
  'first of all': 'ပထမဦးဆုံး',
  'at last': 'နောက်ဆုံးမှာ',
  'as I thought': 'ထင်ထားသလို',
  absolutely: 'လုံးဝ',
  '(respectful) OK': 'ရပါပြီ (လေးစား)',
  'all right': 'အဆင်ပြေ',
  register: 'မှတ်ပုံတင်',
  'word processor': 'စာရေးစက်',
  'to guide': 'လမ်းညွှန်သည်',
  'less than': 'ထက်နည်း',
  'with the exception of': 'မှလွဲ၍',
  'more than': 'ထက်ပို',
  'this is all': 'ဒါပဲ',
  'in order to': 'ရန်အတွက်',
  'to move house or transfer': 'အိမ်ပြောင်း/ပြောင်းရွှေ့',
  'medical science': 'ဆေးပညာ',
  'to rear': 'မွေးမြူသည်',
  'to bring up': 'ပြုစုပျိုးထောင်',
  'with utmost effort': 'အပြင်းအထန်',
  once: 'တစ်ကြိမ်',
  drawer: 'ဆွဲထုတ်ခုံ',
  'drawing out': 'ဆွဲထုတ်ခြင်း',
  'to withdraw': 'ထုတ်ယူသည်',
  'to move house': 'အိမ်ပြောင်းသည်',
  'to transport': 'သယ်ယူပို့ဆောင်',
  driver: 'ယာဉ်မောင်း',
  'to exercise': 'လေ့ကျင့်ခန်းလုပ်',
  'way of swimming': 'ရေကူးနည်း',
  distant: 'ဝေး',
  'to be reserved': 'ရှက်ရွံ့/ထိန်းထား',
  'to be restrained': 'ထိန်းချုပ်ထား',
  'to get dirty': 'ညစ်သည်',
  closet: 'ဗီရို',
  'one hundred million': 'သိန်းတစ်ထောင်',
  rooftop: 'ခေါင်မိုးပေါ်',
  'to get off': 'ဆင်းသည်',
  lodging: 'တည်းခယ်',
  underwear: 'အောက်ခံအဝတ်',
  housewife: 'အိမ်ရှင်မ',
  'cherry-blossom viewing': 'ချယ်ရီပန်းကြည့်',
  'section manager': 'ဌာနမှူး',
  'to exceed': 'ကျော်လွန်သည်',
  'meeting room': 'အစည်းအဝေးခန်း',
  'assembly hall or meeting place': 'အစည်းအဝေးခန်းမ',
  conversation: 'စကားပြောဆိုမှု',
  'to go around': 'ပတ်လည်သွား',
  'to be broken': 'ပျက်သည်',
  coast: 'ကမ်းခြေ',
  everybody: 'လူတိုင်း',
  'to open an event': 'ပွဲဖွင့်သည်',
  definite: 'သေချာသော',
  joy: 'ဝမ်းသာမှု',
  'to enjoy oneself': 'ပျော်ရွှင်သည်',
  'to hang something': 'ချိတ်သည်',
  rate: 'နှုန်း',
  ratio: 'အချိုး',
  percentage: 'ရာခိုင်နှုန်း',
  'to slide': 'ချောသည်',
  'to slip': 'ချော်သည်',
  'to bite': 'ကိုက်သည်',
  'to chew': 'ဝါးသည်',
  'to get dry': 'ခြောက်သည်',
  'to grow accustomed to': 'ရင်းနှီးသည်',
  'female nurse': 'သူနာပြုမ',
  'to be in time for': 'အချိန်မီသည်',
  'to make a mistake': 'မှားသည်',
  'to be delighted': 'ဝမ်းသာသည်',
  'steam train': 'ရေနွေးငွေ့ရထား',
  'to pray': 'ဆုတောင်းသည်',
  season: 'ရာသီ',
  regulations: 'စည်းမျဉ်းများ',
  'to wake': 'နှိုးသည်',
  guest: 'ဧည့်သည်',
  customer: 'ဖောက်သည်',
  'after a long time': 'ကြာမြင့်စွာပြီး',
  urgent: 'အရေးတကြီး',
  steep: 'မတ်စောက်',
  'to hurry': 'အလျင်အမြန်လုပ်',
  speedy: 'မြန်ဆန်',
  express: 'အမြန်ရထား',
  'to weep': 'ငိုသည်',
  competition: 'ပြိုင်ပွဲ',
  church: 'ဘုရားကျောင်း',
  mirror: 'မှန်',
  neighbourhood: 'ရပ်ကွက်',
  corner: 'ထောင့်',
  nook: 'ထောင့်စွန်း',
  '(informal) You (used by men towards women)': 'နင် (ယောက်ျားသုံး)',
  scene: 'မြင်ကွင်း',
  landscape: 'ရှုခင်း',
  'to go out to meet': 'ကြိုဆိုသည်',
  'to be decided': 'ဆုံးဖြတ်ပြီး',
  'study room': 'စာကျက်ခန်း',
  laboratory: 'ဓာတ်ခွဲခန်း',
  silk: 'ပိုးသား',
  'to be in sight': 'မြင်ရသည်',
  'to be discovered': 'တွေ့ရှိသည်',
  sightseeing: 'လည်ပတ်ကြည့်ရှု',
  strict: 'တင်းကြပ်',
  'to break-down': 'ပျက်စီးသည်',
  lake: 'ကန်',
  '(honorable) your husband': 'ခင်ပွန်း',
  traffic: 'ယာဉ်ကြော',
  transportation: 'သယ်ယူပို့ဆောင်ရေး',
  'to shine': 'တောက်ပသည်',
  'to glitter': 'လက်သည်',
  'government worker': 'အစိုးရဝန်ထမ်း',
  'the manufacturing industry': 'ကုန်ထုတ်လုပ်ငန်း',
  headmaster: 'ကျောင်းအုပ်',
  harbour: 'ဆိပ်ကမ်း',
  'to consider': 'စဉ်းစားသည်',
  lecture: 'ဟောပြောပို့ချ',
  auditorium: 'ဟောပြောခန်းမ',
  outskirts: 'မြို့စွန်',
  'to start to rain': 'မိုးစရွာသည်',
  'high school': 'အထက်တန်းကျောင်း',
  'high school student': 'အထက်တန်းကျောင်းသား',
  'to match': 'ကိုက်ညီသည်',
  international: 'နိုင်ငံတကာ',
  'to be crowded': 'စည်ကားသည်',
  '(polite) to give': 'ပေးသည် (ယဉ်ကျေး)',
  sand: 'သဲ',
  latest: 'နောက်ဆုံးပေါ်',
  '(humble) wife': 'ဇနီး (နှိမ့်ချ)',
  slope: 'စောင်း',
  hill: 'တောင်ကုန်း',
  industry: 'စက်မှုလုပ်ငန်း',
  disappointment: 'စိတ်ပျက်မှု',
  citizen: 'နိုင်ငံသား',
  finger: 'လက်ချောင်း',
  'finger ring': 'လက်စွပ်',
  branch: 'ဌာနခွဲ/အကိုင်း',
  twig: 'အကိုင်းငယ်',
  'to stop something': 'ရပ်စေသည်',
  thread: 'ချည်မျှင်',
  dentist: 'သွားဆရာဝန်',
  'to be similar': 'ဆင်တူသည်',
  era: 'ခေတ်',
  'to be cured': 'ပျောက်ကင်းသည်',
  'to heal': 'ကုသသည်',
  freedom: 'လွတ်လပ်မှု',
  dictionary: 'အဘိဓာန်',
  'to copy or photograph': 'မိတ္တူ/ဓာတ်ပုံရိုက်',
  'to throw away': 'ပစ်သည်',
  'company president': 'ကုမ္ပဏီဥက္ကဋ္ဌ',
  lonely: 'အထီးကျန်',
  'to exchange': 'လဲလှယ်သည်',
  glove: 'လက်အိတ်',
  'to assist': 'ကူညီသည်',
  hobby: 'ဝါသနာ',
  neck: 'လည်ပင်း',
  'to take a lesson or test': 'စာမေး/သင်တန်းတက်',
  surroundings: 'ပတ်ဝန်းကျင်',
  'to pick up': 'ကောက်ယူသည်',
  'to gather': 'စုရုံးသည်',
  custom: 'ဓလေ့',
  manners: 'ယဉ်ကျေးမှု',
  'to collect something': 'စုဆောင်းသည်',
  judo: 'ဂျူဒို',
  'to attend': 'တက်ရောက်သည်',
  '(polite) to eat': 'စားသည် (ယဉ်ကျေး)',
  'elementary school': 'မူလတန်းကျောင်း',
  novel: 'ဝတ္ထု',
  'small bird': 'ငှက်ငယ်',
  'to consent': 'သဘောတူသည်',
  eraser: 'ခဲဖျက်',
  'to bake': 'ဖုတ်သည်',
  'to grill': 'ကင်သည်',
  'to burn': 'မီးရှို့သည်',
  'to be roasted': 'ကင်ခံရသည်',
  introduction: 'မိတ်ဆက်',
  'to change between buses or trains': 'ယာဉ်ပြောင်းစီး',
  vehicle: 'ယာဉ်',
  location: 'တည်နေရာ',
  'Japanese straw mat': 'တာတာမိ',
  'to decorate': 'အလှဆင်သည်',
  'to touch': 'ထိသည်',
  'to have a meal': 'ထမင်းစားသည်',
  groceries: 'နေ့စဉ်ကုန်',
  'sleeping in late': 'နောက်ကျအိပ်',
  'newspaper company': 'သတင်းစာတိုက်',
  'Shinto shrine': 'ရှင်တိုဘုရားကျောင်း',
  parents: 'မိဘ',
  kindness: 'ကြင်နာမှု',
  'to make progress': 'တိုးတက်သည်',
  population: 'လူဦးရေ',
  swimming: 'ရေကူး',
  'water supply': 'ရေပေးဝေရေး',
  mathematics: 'သင်္ချာ',
  arithmetic: 'ဂဏန်းသင်္ချာ',
  'to look after': 'ကြည့်ရှုပြုစု',
  terrific: 'အံ့ဩဖွယ်ကောင်း',
  'to produce': 'ထုတ်လုပ်သည်',
  popularity: 'လူကြိုက်များမှု',
  prosperous: 'စည်ပင်',
  'western countries': 'အနောက်နိုင်ငံများ',
  seat: 'ထိုင်ခုံ',
  'to break or to fold': 'ချိုး/ခေါက်',
  'to break or be folded': 'ကျိုး/ခေါက်ခံရ',
  explanation: 'ရှင်းလင်းချက်',
  shallow: 'တိမ်',
  superficial: 'အပေါ်ယံ',
  grandfather: 'အဖိုး',
  grandmother: 'အဖွား',
  'to become thin': 'ပိန်သည်',
  'to discuss': 'ဆွေးနွေးသည်',
  'to make noise': 'ဆူညံသည်',
  'to be excited': 'စိတ်လှုပ်ရှား',
  gift: 'လက်ဆောင်',
  '(humble) son': 'သား (နှိမ့်ချ)',
  'to add a number': 'ပေါင်းသည်',
  'to be enough': 'လုံလောက်သည်',
  'to be continued': 'ဆက်လက်ရှိ',
  graduation: 'ဘွဲ့ရခြင်း',
  'to become fat': 'ဝသည်',
  'to hit': 'ရိုက်သည်',
  'to leave hospital': 'ဆေးရုံဆင်း',
  substitute: 'အစားထိုး',
  alternate: 'အလှည့်ကျ',
  typhoon: 'တိုင်ဖွန်း',
  'university student': 'တက္ကသိုလ်ကျောင်းသား',
  generally: 'ယေဘုယျအားဖြင့်',
  greatly: 'အလွန်',
  shelves: 'စင်များ',
  'to look for': 'ရှာသည်',
  heating: 'အပူပေးခြင်း',
  'to notify': 'အကြောင်းကြား',
  earthquake: 'ငလျင်',
  geography: 'ပထဝီဝင်',
  embarrassed: 'ရှက်ရွံ့',
  '(humble) to do': 'လုပ်သည် (နှိမ့်ချ)',
  'to be late': 'နောက်ကျသည်',
  kimono: 'ကီမိုနို',
  considerably: 'အတော်အတန်',
  'junior high school': 'အလယ်တန်းကျောင်း',
  'middle school': 'အလယ်တန်း',
  daytime: 'နေ့ခင်း',
  'during the day': 'နေ့အတွင်း',
  'noon break': 'နေ့လည်နားချိန်',
  caution: 'သတိပေးချက်',
  injection: 'ထိုးဆေး',
  'parking lot': 'ကားရပ်နားရာ',
  polite: 'ယဉ်ကျေး',
  'to investigate': 'စုံစမ်းသည်',
  'to be fixed': 'ပြင်ပြီး',
  'to be repaired': 'ပြုပြင်ပြီး',
  'to commute': 'သွားလာအလုပ်လုပ်',
  'to go through': 'ဖြတ်သန်းသည်',
  'to soak': 'စိမ်သည်',
  'to pickle': 'အချဉ်လုပ်',
  thief: 'ခိုးသူ',
  suitability: 'သင့်လျော်မှု',
  'weather forecast': 'မိုးလေဝသခန့်မှန်း',
  exhibition: 'ပြပွဲ',
  'shop assistant': 'ဆိုင်ဝန်ထမ်း',
  countryside: 'ကျေးလက်',
  'electric light': 'လျှပ်စစ်မီး',
  telegram: 'ကြေးနန်း',
  'to paint': 'ဆေးသုတ်သည်',
  'to plaster': 'အင်္ဂတေသုတ်',
  'on the way': 'လမ်းမှာ',
  metropolitan: 'မြို့တော်ဆိုင်ရာ',
  'to get angry': 'ဒေါသထွက်',
  'to be angry': 'ဒေါသဖြစ်',
  'to break down': 'ပျက်စီးသည်',
  'to throw or cast away': 'ပစ်ပယ်သည်',
  'to steal': 'ခိုးသည်',
  'hot water': 'ရေနွေး',
  response: 'တုံ့ပြန်မှု',
  'to step on': 'နင်းသည်',
  'to escape': 'ထွက်ပြေးသည်',
  zoo: 'တိရစ္ဆာန်ဥယျာဉ်',
  particularly: 'အထူးသဖြင့်',
  especially: 'အထူးသဖြင့်',
  'limited express train (faster than an express train)': 'အထူးအမြန်ရထား',
  'to reach': 'ရောက်သည်',
  'two storied': 'နှစ်ထပ်',
  journal: 'ဂျာနယ်/မှတ်တမ်း',
  'to hospitalise': 'ဆေးရုံတင်',
  'to enter school or university': 'ကျောင်းဝင်',
  fever: 'အဖျား',
  '(humble) to look at': 'ကြည့်သည် (နှိမ့်ချ)',
  'back of the body': 'ကျော',
  double: 'နှစ်ဆ',
  'place where things are sold': 'ရောင်းရာနေရာ',
  'to lodge at': 'တည်းခိုသည်',
  pronunciation: 'အသံထွက်',
  opposition: 'ဆန့်ကျင်မှု',
  'television or radio program': 'အစီအစဉ်',
  'art gallery': 'အနုပညာပြခန်း',
  certainly: 'သေချာပေါက်',
  necessarily: 'မုချ',
  'the front': 'ရှေ့',
  goods: 'ကုန်ပစ္စည်း',
  inconvenience: 'အဆင်မပြေ',
  'to be attached': 'ကပ်တွဲရှိ',
  'Japanese bedding': 'ဂျပန်အိပ်ရာ',
  futon: 'ဖူတွန်',
  frightening: 'ကြောက်စရာ',
  'head of a section': 'ဌာနမှူး',
  revision: 'ပြန်လည်သုံးသပ်',
  complexity: 'ရှုပ်ထွေးမှု',
  complication: 'ရှုပ်ထွေးမှု',
  grammar: 'သဒ္ဒါ',
  'to be heard': 'ကြားရသည်',
  'uncooked rice': 'ဆန်',
  wall: 'နံရံ',
  'to separate': 'ခွဲသည်',
  'to tidy up': 'ရှင်းလင်းသည်',
  reply: 'အကြောင်းပြန်',
  'to seize': 'ဖမ်းယူသည်',
  'to get dark': 'မှောင်သည်',
  'to come to an end': 'ပြီးဆုံးသည်',
  'to wrap': 'ထုပ်သည်',
  'to broadcast': 'ထုတ်လွှင့်သည်',
  'lost article': 'ပျောက်ပစ္စည်း',
  trade: 'ကုန်သွယ်ရေး',
  'I (used by males)': 'ဘိုကူ (ယောက်ျား)',
  translation: 'ဘာသာပြန်',
  comic: 'ကာတွန်း',
  flavour: 'အရသာ',
  'bean paste': 'ပဲငံပြာရည်ခဲ',
  sleepy: 'အိပ်ချင်',
  '(humble) daughter': 'သမီး (နှိမ့်ချ)',
  'hair or fur': 'ဆံပင်/အမွေး',
  cotton: 'ဝါဂွမ်း',
  'to turn back': 'ပြန်လှည့်',
  'to be helpful': 'အကူအညီဖြစ်',
  'to export': 'တင်ပို့သည်',
  'to import': 'တင်သွင်းသည်',
  'preparation for a lesson': 'စာပြင်ဆင်မှု',
  reservation: 'ကြိုတင်စာရင်း',
  'to shake': 'လှုပ်သည်',
  'to sway': 'ယိမ်းသည်',
  'things to do': 'လုပ်စရာများ',
  leaf: 'ရွက်',
  'to fall or drop': 'ကျသည်',
  utilization: 'အသုံးချမှု',
  'reverse side': 'နောက်ဘက်',
  'to stand something up': 'မတ်တတ်ထား',
  absence: 'မရှိခြင်း',
  'Japanese hotel': 'ရယိုကန်',
  'both sides': 'နှစ်ဘက်စလုံး',
  woods: 'တောအုပ်',
  forester: 'တောစောင့်',
  'for example': 'ဥပမာအားဖြင့်',
  'to grow cold': 'အေးလာသည်',
  'air conditioning': 'လေအေးပေးစက်',
  'to lead': 'ဦးဆောင်သည်',
  contact: 'ဆက်သွယ်မှု',
  arm: 'လက်မောင်း',
};
