/** Cursor-agent Myanmar glosses for N5 vocabulary (EN → MY) */
module.exports = {
  'over there': 'ဟိုဘက်မှာ',
  'that over there': 'ဟိုဟာ',
  apartment: 'အပါတ်မန့်',
  'to bathe': 'ရေချိုးသည်',
  'to shower': 'ရေချိုးသည်',
  'not very': 'သိပ်မ…ဘူး',
  'how many?': 'ဘယ်နှစ်ခု',
  'how old?': 'အသက်ဘယ်လောက်',
  'how much?': 'ဘယ်လောက်',
  various: 'အမျိုးမျိုး',
  elevator: 'ဓာတ်လှေကား',
  stomach: 'ဗိုက်',
  grandmother: 'အဖွား',
  'female senior-citizen': 'အဘွားကြီး',
  'friendly term for policeman': 'ရဲသား (ခေါ်စကား)',
  interesting: 'စိတ်ဝင်စားဖွယ်',
  sweets: 'မုန့်ချို',
  candy: 'သကြားလုံး',
  '(honorable) older brother': 'အစ်ကို',
  plate: 'ပန်းကန်',
  dish: 'ပန်းကန်/ဟင်း',
  '(honorable) older sister': 'အစ်မ',
  bathroom: 'ရေချိုးခန်း/သန့်စင်ခန်း',
  'green tea': 'လက်ဖက်ရည်စိမ်း',
  '(honorable) father': 'အဖေ',
  'boxed lunch': 'ဘန်တို',
  '(honorable) mother': 'အမေ',
  'to take time or money': 'ကြာသည်/ကုန်သည်',
  'to call by phone': 'ဖုန်းဆက်သည်',
  cup: 'ခွက်',
  camera: 'ကင်မရာ',
  curry: 'ဟင်းချက်/ကာရီ',
  calendar: 'ပြက္ခဒိန်',
  guitar: 'ဂစ်တာ',
  kilogram: 'ကီလိုဂရမ်',
  kilometre: 'ကီလိုမီတာ',
  gram: 'ဂရမ်',
  coat: 'ကုတ်အင်္ကျီ',
  'tennis court': 'တင်းနစ်ကွင်း',
  'this person or way': 'ဒီလူ/ဒီဘက်',
  such: 'ဒီလို',
  'well…': 'အင်း…',
  'year after next': 'နှစ်နှစ်ကြာမှ',
  'well then…': 'ကောင်းပြီ…',
  shirt: 'ရှပ်အင်္ကျီ',
  shower: 'ရေပက်ကိရိယာ',
  'soy sauce': 'ပဲငံပြာရည်',
  skirt: 'စကတ်',
  instantly: 'ချက်ချင်း',
  heater: 'အပူပေးစက်',
  spoon: 'ဇွန်း',
  trousers: 'ဘောင်းဘီ',
  slippers: 'ဖိနပ်ပေါ့',
  sweater: 'ဆွယ်တာ',
  jumper: 'ဂျမ်ပါ',
  'that place': 'ဟိုနေရာ',
  'after that': 'အဲဒီနောက်',
  'in that situation': 'အဲဒီအခြေအနေမှာ',
  tobacco: 'ဆေးလိပ်',
  cigarettes: 'စigareတ်',
  gradually: 'တဖြည်းဖြည်း',
  'rice bowl': 'ထမင်းပန်းကန်',
  exactly: 'အတိအကျ',
  somewhat: 'နည်းနည်း',
  'to turn on': 'ဖွင့်သည်',
  boring: 'ပျင်းစရာ',
  tape: 'တိပ်',
  'tape recorder': 'တိပ်ရီကော်ဒါ',
  'to be able to': 'တတ်နိုင်သည်',
  'with that...': 'အဲဒီနဲ့…',
  'department store': 'ဒီပါတ်မန့်စတိုး',
  'Western style door': 'အနောက်တံခါး',
  'for what reason': 'ဘာကြောင့်',
  'which of two': 'ဘယ်ဟာ (နှစ်ခုထဲ)',
  'chicken meat': 'ကြက်သား',
  'which (of three or more)': 'ဘယ်ဟာ',
  'et cetera': 'စသည်',
  tie: 'နက်ကတိုင်',
  necktie: 'နက်ကတိုင်',
  notebook: 'မှတ်စုစာအုပ်',
  'exercise book': 'လေ့ကျင့်စာအုပ်',
  chopsticks: 'တူ',
  butter: 'ထောပတ်',
  handkerchief: 'လက်ကိုင်ပုဝါ',
  'roll of film': 'ဖလင်လိပ်',
  'swimming pool': 'ရေကူးကန်',
  fork: 'ခက်ရင်း',
  page: 'စာမျက်နှာ',
  pet: 'အိမ်မွေးတိရစ္ဆာန်',
  'ball-point pen': 'ဘောပင်',
  pocket: 'အိတ်ကပ်',
  post: 'စာတိုက်/တိုင်',
  button: 'ခလုတ်/ခလုပ်',
  unpleasant: 'မနှစ်မြို့ဖွယ်',
  'straight ahead': 'တည့်တည့်',
  direct: 'တိုက်ရိုက်',
  match: 'ပွဲ/မီးခြစ်',
  everyone: 'လူတိုင်း',
  metre: 'မီတာ',
  slowly: 'ဖြည်းဖြည်း',
  'Used for comparison.': 'နှိုင်းယှဉ်ရာတွင်သုံး',
  radio: 'ရေဒီယို',
  'radio cassette player': 'ရေဒီယိုကက်ဆက်',
  splendid: 'ထူးချွန်/လှပ',
  record: 'မှတ်တမ်း/စကျင်',
  'business shirt': 'အလုပ်ရှပ်',
  gloomy: 'မှောင်မိုက်/စိတ်ညစ်',
  'to differ': 'ကွဲပြားသည်',
  'medical doctor': 'ဆရာဝန်',
  'one month': 'တစ်လ',
  'day before yesterday': 'တစ်နေ့က',
  'year before last': 'ယမန်နှစ်',
  together: 'အတူတူ',
  'one person': 'တစ်ယောက်',
  '(1) one day': 'တစ်ရက်',
  '(2) first of month': 'လဆန်းတစ်ရက်',
  'to pull': 'ဆွဲသည်',
  'a drink': 'အချိုရည်/သောက်စရာ',
  'right side': 'ညာဘက်',
  cinema: 'ရုပ်ရှင်ရုံ',
  'English language': 'အင်္ဂလိပ်စာ',
  pencil: 'ခဲတံ',
  '(honorable) wife': 'ဇနီး',
  'to push': 'တွန်းသည်',
  'to stamp something': 'တံဆိပ်နှိပ်သည်',
  'luke warm': 'နွေးနွေး',
  unskillful: 'မကျွမ်းကျင်',
  'summer holiday': 'နွေရာသီအားလပ်ရက်',
  household: 'အိမ်ထောင်စု',
  'free time': 'အားလပ်ချိန်',
  'a vase': 'ပန်းအိုး',
  luggage: 'ခရီးဆောင်အိတ်',
  ashtray: 'ပြာခံခွက်',
  stairs: 'လှေကား',
  'foreign country': 'နိုင်ငံခြား',
  foreigner: 'နိုင်ငံခြားသား',
  'a corner': 'ထောင့်',
  enjoyable: 'ပျော်ရွှင်ဖွယ်',
  'Chinese character': 'ခန်းဂျိ',
  glasses: 'မျက်မှန်',
  desk: 'စာရေးစားပွဲ',
  'to go back': 'ပြန်သွားသည်',
  'coffee lounge': 'ကော်ဖီဆိုင်',
  'to smoke': 'ဆေးလိပ်သောက်သည်',
  'to suck': 'စုပ်သည်',
  beef: 'အမဲသား',
  'last year': 'မနှစ်က',
  powerful: 'အားကြီး',
  classroom: 'စာသင်ခန်း',
  'to turn': 'လှည့်သည်',
  'to bend': 'ကွေးသည်',
  'to work for someone': 'အလုပ်လုပ်ပေးသည်',
  'nine days': 'ကိုးရက်',
  'ninth day': 'ကိုးရက်မြောက်',
  shoes: 'ဖိနပ်',
  socks: 'ခြေအိတ်',
  '(humble) older brother': 'အစ်ကို',
  '(humble) siblings': 'ညီအစ်ကိုမောင်နှမ',
  policeman: 'ရဲသား',
  building: 'အဆောက်အအုံ',
  'entry hall': 'ဝင်ပေါက်ခန်း',
  'old (not used for people)': 'ဟောင်း',
  'Japanese style door': 'ဂျပန်တံခါး',
  'five days': 'ငါးရက်',
  'fifth day': 'ငါးရက်မြောက်',
  afterwards: 'နောက်မှ',
  'cooked rice': 'ထမင်း',
  meal: 'စာစားပွဲ/အစားအသောက်',
  intersection: 'လမ်းဆုံ',
  'police box': 'ရဲကင်း',
  likeable: 'ကြိုက်နှစ်သက်ဖွယ်',
  'black tea': 'လက်ဖက်ရည်မည်း',
  'this month': 'ဒီလ',
  'this week': 'ဒီအပတ်',
  'this year': 'ဒီနှစ်',
  'this evening': 'ဒီညနေ',
  'to be worried': 'စိုးရိမ်သည်',
  'left hand side': 'ဘယ်ဘက်',
  'to stretch out hands': 'လက်ဆန့်သည်',
  'to raise an umbrella': 'ထီးထောင်သည်',
  thin: 'ပါး/ပိန်',
  wallet: 'ပိုက်ဆံအိတ်',
  'to bloom': 'ပွင့်သည်',
  composition: 'စာစီစာကုံး',
  writing: 'ရေးသားချက်',
  'last night': 'မနေ့ည',
  'to take a photo or record a film': 'ဓာတ်ပုံရိုက်သည်',
  'three days': 'သုံးရက်',
  'third day of the month': 'လဆန်းသုံးရက်',
  umbrella: 'ထီး',
  'to stroll': 'လှည့်လည်သည်',
  'four days': 'လေးရက်',
  'fouth day of the month': 'လဆန်းလေးရက်',
  '(humble) older sister': 'အစ်မ',
  'to come to a halt': 'ရပ်တန့်သည်',
  '(humble) I': 'ကျွန်တော်/ကျွန်မ',
  myself: 'ကိုယ်တိုင်',
  tooth: 'သွား',
  dictionary: 'အဘိဓာန်',
  watch: 'နာရီ',
  clock: 'နာရီ',
  automobile: 'ကား',
  oneself: 'မိမိ',
  'seven days': 'ခုနစ်ရက်',
  'the seventh day': 'ခုနစ်ရက်မြောက်',
  photograph: 'ဓာတ်ပုံ',
  'to take something': 'ယူသည်',
  'to live in': 'နေထိုင်သည်',
  'ten days': 'ဆယ်ရက်',
  'the tenth day': 'ဆယ်ရက်မြောက်',
  homework: 'အိမ်စာ',
  'for the first time': 'ပထမဆုံးအကြိမ်',
  'to erase': 'ဖျက်သည်',
  'to turn off power': 'မီးပိတ်သည်',
  'on top of': 'အပေါ်မှာ',
  skillful: 'ကျွမ်းကျင်',
  jacket: 'ဂျာကင်',
  colour: 'အရောင်',
  'dining hall': 'ထမင်းစားခန်း',
  'to blow': 'မှုတ်သည်',
  'clear weather': 'ကောင်းကင်သာ',
  'to be sunny': 'နေသာသည်',
  'to be born': 'မွေးဖွားသည်',
  pupil: 'ကျောင်းသား',
  quiet: 'တိတ်ဆိတ်',
  'postage stamp': 'စာပို့တံဆိပ်',
  'last month': 'ပြီးခဲ့သောလ',
  'last week': 'ပြီးခဲ့သောအပတ်',
  washing: 'ရေဆေးခြင်း',
  quick: 'မြန်',
  fat: 'ဆီ/ဝ',
  'to be very likeable': 'အလွန်ကြိုက်သည်',
  embassy: 'သံရုံး',
  'all right': 'ရပါပြီ/အဆင်ပြေ',
  adult: 'လူကြီး',
  'great number of people': 'လူအများ',
  'to take off clothes': 'အဝတ်ချွတ်သည်',
  'to play an instrument with strings': 'ကြိုးတူရိယာတီးသည်',
  'including piano': 'စန္ဒရားအပါအဝင်',
  'underground train': 'မြေအောက်ရထား',
  pond: 'ကန်',
  brown: 'အညို',
  'to arrive at': 'ရောက်ရှိသည်',
  'to put on from the shoulders down': 'ဝတ်သည် (အပေါ်ဝတ်)',
  'midday meal': 'နေ့လည်စာ',
  breakfast: 'မနက်စာ',
  painful: 'နာကျင်',
  'younger brother': 'ညီ',
  'to tie': 'ချည်သည်',
  'to stick': 'ကပ်သည်',
  'electric train': 'လျှပ်စစ်ရထား',
  'to hand over': 'ပေးအပ်သည်',
  'to go across': 'ဖြတ်ကူးသည်',
  'to climb': 'တက်သည်',
  pork: 'ဝက်သား',
  'cloudy weather': 'တိမ်ထူ',
  'to become cloudy': 'တိမ်ဖုံးသည်',
  'to become dim': 'မှောင်သည်',
  '20 years old': 'အသက်နှစ်ဆယ်',
  '20th year': 'နှစ်ဆယ်နှစ်မြောက်',
  'twenty days': 'နှစ်ဆယ်ရက်',
  twentieth: 'နှစ်ဆယ်မြောက်',
  'two people': 'နှစ်ယောက်',
  'two days': 'နှစ်ရက်',
  'second day of the month': 'လဆန်းနှစ်ရက်',
  'to put in': 'ထည့်သည်',
  entrance: 'ဝင်ပေါက်',
  'hot to the touch': 'ပူ (ထိရ)',
  'business suit': 'စွတ်ကျူ',
  shopping: 'ဈေးဝယ်ခြင်း',
  grandfather: 'အဖိုး',
  'male senior citizen': 'အဘိုးကြီး',
  aunt: 'အဒေါ်',
  'eight days': 'ရှစ်ရက်',
  'eighth day of the month': 'လဆန်းရှစ်ရက်',
  greengrocer: 'ဟင်းသီးဟင်းရွက်ဆိုင်',
  'half minute': 'တစ်မိနစ်ခွဲ',
  noisy: 'ဆူညံ',
  annoying: 'စိတ်အနှောင့်အယှက်',
  'evening meal': 'ညစာ',
  'to get tired': 'ပင်ပန်းသည်',
  aeroplane: 'လေယာဉ်',
  envelope: 'စာအိတ်',
  'to be understood': 'နားလည်သည်',
  'to line up': 'တန်းစီသည်',
  'to stand in a line': 'တန်းစီရပ်သည်',
  'to set up': 'တည်ဆောက်/စီစဉ်သည်',
  'to close something': 'ပိတ်သည်',
  'to return something': 'ပြန်ပေးသည်',
  useful: 'အသုံးဝင်',
  convenient: 'အဆင်ပြေ',
  hat: 'ဦးထုပ်',
  bookshelves: 'စာအုပ်စင်',
  'to brush teeth': 'သွားတိုက်သည်',
  'to polish': 'ပွတ်တိုက်သည်',
  '(humble) younger sister': 'ညီမ',
  'every month': 'လတိုင်း',
  'every week': 'အပတ်တိုင်း',
  'every morning': 'မနက်တိုင်း',
  'every day': 'နေ့တိုင်း',
  'every year': 'နှစ်တိုင်း',
  'every night': 'ညတိုင်း',
  'fountain pen': 'မင်ဘောပင်',
  'to lose something': 'ပျောက်သည်',
  bright: 'လင်း/ဉာဏ်ကောင်း',
  'animal noise. to chirp': 'မြည်သည်',
  'roar or croak etc.': 'ဟစ်အော်/မြည်သည်',
  gate: 'ဂိတ်/တံခါးကြီး',
  dinner: 'ညစာ',
  'western-style clothes': 'အနောက်တိုင်းဝတ်စုံ',
  postcard: 'ပို့စကတ်',
  'next month': 'နောက်လ',
  'next week': 'နောက်အပတ်',
  'next year': 'နှစ်သစ်/လာမည့်နှစ်',
  'overseas student': 'နိုင်ငံခြားသားကျောင်းသား',
  'both parents': 'မိဘနှစ်ပါး',
  cuisine: 'ဟင်းလျာ',
  refreshing: 'သက်သာ/လန်းဆန်း',
  'next door to': 'ဘေးအိမ်/ကပ်လျက်',
  'cold to the touch': 'အေး (ထိရ)',
  refrigerator: 'ရေခဲသေတ္တာ',
  corridor: 'စင်္ကြံ',
  'six days': 'ခြောက်ရက်',
  'sixth day of the month': 'လဆန်းခြောက်ရက်',
};
